;;; Deep recursion on a small stack cache (the test makes it small): the
;;; frames past it copied into the heap as a chain, and restored as they
;;; return. Values the flushed frames hold, through collections; an abort
;;; to a prompt flushed; a mark read through flushed frames; and a
;;; composable continuation of flushed frames, taken and run twice.
(define* sum-cons (subr (maxeff (alloc @l) (read @l) spin) (int (listof int @l)) int)
  (lambda (n xs) (if (= n 0) 0 (+ (car xs) (sum-cons (- n 1) (cons n xs))))))
(sum-cons 100000 (the (listof int @l) (cons 0 nil)))
(define-effect downward (maxeff (read (globals t raise down)) spin))
(define t (prompt-tag int int downward @z) (make-continuation-prompt-tag))
(define-effect aborting (maxeff (goto @z) downward))
(define* raise (subr (maxeff (goto @z) (read (globals t))) (int) void)
  (lambda (n) (abort-current-continuation t n)))
(define* down (subr aborting (int int) int)
  (lambda (d n) (if (= d 0) (raise n) (+ 1 (down (- d 1) n)))))
(define* under (subr aborting (int) int) (lambda (d) (prompt t (down d 7) (lambda (v) (+ v 1000)))))
(under 50000)
(define key (mark-key int @m) (make-continuation-mark-key))
(define* deep-mark (subr (maxeff (read @m) (read (globals key)) spin) (int) int)
  (lambda (d) (if (= d 0) (first-mark key 0) (+ 1 (deep-mark (- d 1))))))
(define* marked (subr (maxeff (read @m) (write @m) (read (globals key deep-mark)) spin) (int) int)
  (lambda (d) (with-mark key 5 (lambda () (deep-mark d)))))
(marked 50000)
(define-effect grabbing (maxeff (goto @p) (comefrom @p) (read (globals u grab climb)) spin))
(define u (prompt-tag int int grabbing @p) (make-continuation-prompt-tag))
(define* grab (subr grabbing () int)
  (lambda () (call-with-composable-continuation (lambda (k) (k (k 1))) u)))
(define* climb (subr grabbing (int) int)
  (lambda (d) (if (= d 0) (grab) (+ 1 (climb (- d 1))))))
(define* twice (subr grabbing (int) int) (lambda (d) (prompt u (climb d) (lambda (v) v))))
(twice 20000)
(define-effect marking (maxeff (read @m) (write @m) (alloc @m)))
(define-effect levels (maxeff marking (read (globals key level spin-down count)) spin))
(define* count (subr (maxeff (read @m) spin) ((listof int @m) int) int)
  (lambda (xs n) (if (null? xs) n (count (cdr xs) (+ n 1)))))
(define* spin-down (subr spin (int) int) (lambda (n) (if (= n 0) 0 (spin-down (- n 1)))))
(define* level (subr levels (int) int)
  (lambda (d)
    (if (= d 0)
        (count (current-marks key) 0)
        (with-mark key 1
          (lambda ()
            (begin (spin-down 2) (with-mark key 2 (lambda () (+ 1 (level (- d 1)))))))))))
(level 30000)
