;;; More values than registers (8): past the seventh, a list in the last
;;; register (Larceny's convention). Parameters, arguments, calls of itself,
;;; a closure's free values, a call-out's operands (a bloblet of 10 fields),
;;; and calls between native and cellular code (`stay-cellular`) both ways.
(define* ten (subr pure (int int int int int int int int int int) int)
  (lambda (a b c d e f g h i j) (- (+ a (+ b (+ c (+ d (+ e (+ f (+ g (+ h i)))))))) (* 2 j))))
(ten 1 2 3 4 5 6 7 8 9 10)
(define* spin10 (subr spin (int int int int int int int int int int) int)
  (lambda (n a b c d e f g h i)
    (if (= n 0) (+ a (* 10 i)) (+ 1 (spin10 (- n 1) b c d e f g h i a)))))
(spin10 1000 1 2 3 4 5 6 7 8 9)
(define* cell10 (subr (maxeff (read @globals) spin) (int int int int int int int int int int) int)
  ;; (Recursive, so not inlined into its caller, which then stays native.)
  (lambda (a b c d e f g h i j)
    (if (< a 0)
        (cell10 (- 0 a) b c d e f g h i j)
        (begin (stay-cellular #u) (ten j i h g f e d c b a)))))
(define* to-cell (subr (maxeff (read @globals) spin) (int) int)
  (lambda (x) (+ 1 (cell10 x 1 2 3 4 5 6 7 8 9))))
(to-cell -100)
(define* from-cell (subr (maxeff (read @globals) spin) (int) int)
  (lambda (x) (begin (stay-cellular #u) (+ 1 (ten x 1 2 3 4 5 6 7 8 9)))))
(from-cell 100)
(define-type adder (subr (read @globals) (int) int))
(define* over10 (subr (alloc @heap) (int int int int int int int int int int) adder)
  (lambda (a b c d e f g h i j) (lambda (x) (+ x (ten a b c d e f g h i j)))))
((over10 1 2 3 4 5 6 7 8 9 10) 1000)
(define* fields10 (subr (maxeff (alloc @heap) (read @heap)) (int) int)
  (lambda (x)
    (let ((b (make-bloblet 0 x (+ x 1) (+ x 2) (+ x 3) (+ x 4)
                           (+ x 5) (+ x 6) (+ x 7) (+ x 8) (+ x 9))))
      (+ (bloblet-ref b 0) (* 100 (bloblet-ref b 9))))))
(fields10 1)
