(define saved #f)
(define log '())
(define entries 0)
(define (run)
  (let loop ((i 0))
    (if (< i 3)
        (begin
          (if (= i 1) (call/cc (lambda (k) (set! saved k))))
          (set! log (cons i log))
          (loop (+ i 1)))
        'end)))
(run)
(set! entries (+ entries 1))
(if (< entries 2) (saved 'reentry))
(list entries (reverse log))
