(define (make-walker tree)
  (define return #f)
  (define (walk t)
    (cond ((null? t) 'skip)
          ((pair? t) (walk (car t)) (walk (cdr t)))
          (else (call/cc (lambda (resume)
                  (set! walk-state resume)
                  (return t))))))
  (define walk-state #f)
  (lambda ()
    (call/cc (lambda (caller)
      (set! return caller)
      (if walk-state
          (walk-state 'again)
          (begin (walk tree) (return 'done)))))))
(define (same-fringe? a b)
  (let ((wa (make-walker a)) (wb (make-walker b)))
    (let loop ()
      (let ((x (wa)) (y (wb)))
        (cond ((and (eq? x 'done) (eq? y 'done)) #t)
              ((or (eq? x 'done) (eq? y 'done)) #f)
              ((eqv? x y) (loop))
              (else #f))))))
(list (same-fringe? '(1 (2 3)) '((1 2) 3))
      (same-fringe? '(1 (2 3)) '((1 2) 4))
      (same-fringe? '(1 2 3) '(1 2)))
