//! Reading and comparing conformance goldens.
//!
//! The goldens are generated by driving the recovered original implementations
//! under Racket (see `reference/`), so comparison is textual — which means the
//! run-dependent parts have to be canonicalised on both sides first. There are
//! two, and they come from two *independent* counters in the original:
//!
//! * `*UNIF*-591` — a unification variable, numbered by `*alpha-counter*`.
//! * `t-2675`, `letrec-2036`, `fail-1806` — a gensym from `new-identifier`,
//!   numbered by its own `*gensym*`.
//!
//! Because the counters are independent, `t-5` and `*UNIF*-5` can coexist and
//! mean unrelated things, so they are renumbered in separate namespaces.
//! Renumbering is by order of first appearance *within a record*, which
//! preserves sharing: two occurrences of one variable stay equal, and two
//! distinct variables stay distinct. So a normalised comparison still fails if
//! the structure differs, which is the whole point.
//!
//! There is a third, subtler case. A unification variable that generalisation
//! turns into a `poly` binder keeps its *bare* alpha number as its name, so a
//! type can read `(poly ((|687| effect)) (-> |687| …))`. That number is the
//! allocation counter at one moment during checking, so it shifts if anything
//! upstream allocates one more or one fewer variable — and under
//! alpha-renaming the name carries no meaning at all. It is therefore
//! normalised too.
//!
//! But *not* everywhere: a `productof` field label is also a bare numeric
//! symbol, and there the number is the field's position — structural, and a
//! real distinction to preserve. So the rule is scoped by the enclosing form,
//! which is why this needs a paren-tracking scan rather than a regular
//! expression.

use std::collections::HashMap;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Outcome {
    /// Typechecked: the unparsed type and effect.
    Typed { ty: String, effect: String },
    /// The reference rejected it.
    StaticError { message: String },
}

#[derive(Clone, Debug)]
pub struct Case {
    pub number: u32,
    pub src: String,
    pub outcome: Outcome,
    /// What the unmodified reference evaluates it to, when it evaluates.
    pub value: Option<String>,
    /// The error, when it does not.
    pub value_error: Option<String>,
    /// The value once the reference's own missing primitives are supplied —
    /// present only where it differs from `value_error`. See
    /// `docs/divergences.md`.
    pub value_augmented: Option<String>,
}

impl Case {
    /// The value `fixpt` should produce: the augmented one where the reference
    /// has a gap we deliberately fix, otherwise the plain one.
    pub fn expected_value(&self) -> Option<&str> {
        self.value_augmented.as_deref().or(self.value.as_deref())
    }
}

#[derive(Debug)]
pub struct ParseError {
    pub line: usize,
    pub message: String,
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "golden file line {}: {}", self.line, self.message)
    }
}

/// Parse a `.expected` file.
pub fn parse_goldens(text: &str) -> Result<Vec<Case>, ParseError> {
    let mut cases = Vec::new();
    let mut current: Option<Partial> = None;
    for (i, line) in text.lines().enumerate() {
        let lineno = i + 1;
        if line.starts_with(";;;") || line.trim().is_empty() {
            continue;
        }
        let (tag, rest) = match line.split_once(' ') {
            Some((t, r)) => (t, r),
            None => (line, ""),
        };
        match tag {
            "#case" => {
                let number = rest.trim().parse().map_err(|_| ParseError {
                    line: lineno,
                    message: format!("bad case number {rest:?}"),
                })?;
                current = Some(Partial::new(number));
            }
            "#end" => {
                let p = current.take().ok_or(ParseError {
                    line: lineno,
                    message: "`#end` outside a case".into(),
                })?;
                cases.push(p.finish(lineno)?);
            }
            _ => {
                let p = current.as_mut().ok_or(ParseError {
                    line: lineno,
                    message: format!("{tag} outside a case"),
                })?;
                match tag {
                    "#src" => p.src = Some(rest.to_string()),
                    "#type" => p.ty = Some(rest.to_string()),
                    "#effect" => p.effect = Some(rest.to_string()),
                    "#static-error" => p.static_error = Some(unquote(rest)),
                    "#value" => p.value = Some(unquote(rest)),
                    "#value-error" => p.value_error = Some(unquote(rest)),
                    "#value-aug" => p.value_augmented = Some(unquote(rest)),
                    "#value-aug-error" => p.value_error = Some(unquote(rest)),
                    other => {
                        return Err(ParseError {
                            line: lineno,
                            message: format!("unknown tag {other}"),
                        });
                    }
                }
            }
        }
    }
    Ok(cases)
}

struct Partial {
    number: u32,
    src: Option<String>,
    ty: Option<String>,
    effect: Option<String>,
    static_error: Option<String>,
    value: Option<String>,
    value_error: Option<String>,
    value_augmented: Option<String>,
}

impl Partial {
    fn new(number: u32) -> Partial {
        Partial {
            number,
            src: None,
            ty: None,
            effect: None,
            static_error: None,
            value: None,
            value_error: None,
            value_augmented: None,
        }
    }

    fn finish(self, line: usize) -> Result<Case, ParseError> {
        let src = self.src.ok_or(ParseError { line, message: "case has no `#src`".into() })?;
        let outcome = match (self.ty, self.effect, self.static_error) {
            (Some(ty), Some(effect), None) => Outcome::Typed { ty, effect },
            (None, None, Some(message)) => Outcome::StaticError { message },
            _ => {
                return Err(ParseError {
                    line,
                    message: "case needs either `#type`+`#effect` or `#static-error`".into(),
                });
            }
        };
        Ok(Case {
            number: self.number,
            src,
            outcome,
            value: self.value,
            value_error: self.value_error,
            value_augmented: self.value_augmented,
        })
    }
}

/// Racket writes these fields with `~s`, so they arrive as quoted strings.
fn unquote(s: &str) -> String {
    let s = s.trim();
    if !(s.starts_with('"') && s.len() >= 2) {
        return s.to_string();
    }
    let mut out = String::new();
    let mut chars = s[1..s.len() - 1].chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('\\') => out.push('\\'),
            Some('"') => out.push('"'),
            Some(other) => out.push(other),
            None => break,
        }
    }
    out
}

/// Canonicalise the run-dependent identifier numbering. See the module docs.
pub fn normalize(text: &str) -> String {
    let mut unif: HashMap<u32, u32> = HashMap::new();
    let mut gensym: HashMap<u32, u32> = HashMap::new();
    let mut bare: HashMap<u32, u32> = HashMap::new();
    // The head word of each currently-open list, so a `productof` label can be
    // told apart from a generalised binder that happens to be numeric.
    let mut heads: Vec<Option<String>> = Vec::new();
    let mut out = String::with_capacity(text.len());
    let bytes: Vec<char> = text.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        if c == '(' || c == '[' {
            heads.push(None);
            out.push(c);
            i += 1;
            continue;
        }
        if c == ')' || c == ']' {
            heads.pop();
            out.push(c);
            i += 1;
            continue;
        }
        if !is_symbol_char(c) {
            out.push(c);
            i += 1;
            continue;
        }
        let start = i;
        while i < bytes.len() && is_symbol_char(bytes[i]) {
            i += 1;
        }
        let token: String = bytes[start..i].iter().collect();
        let first_in_list = heads.last().is_some_and(|h| h.is_none());
        if first_in_list
            && let Some(slot) = heads.last_mut()
        {
            *slot = Some(token.clone());
        }
        // `productof` and `sumof` tags are positions and names, not counters.
        let structural = heads
            .iter()
            .rev()
            .take(2)
            .any(|h| matches!(h.as_deref(), Some("productof") | Some("sumof")));
        out.push_str(&rename(&token, &mut unif, &mut gensym, &mut bare, structural));
    }
    out
}

fn is_symbol_char(c: char) -> bool {
    !matches!(c, '(' | ')' | '[' | ']' | ' ' | '\t' | '\n' | '\r' | '"' | '\'' | '`' | ',')
}

fn rename(
    token: &str,
    unif: &mut HashMap<u32, u32>,
    gensym: &mut HashMap<u32, u32>,
    bare: &mut HashMap<u32, u32>,
    structural: bool,
) -> String {
    // A bare number, written `|687|` by `write`: a generalised binder's alpha
    // name, unless we are inside a form where numbers mean positions.
    if let Some(inner) = token.strip_prefix('|').and_then(|t| t.strip_suffix('|'))
        && !inner.is_empty()
        && inner.bytes().all(|b| b.is_ascii_digit())
    {
        if structural {
            return token.to_string();
        }
        if let Ok(n) = inner.parse::<u32>() {
            let next = bare.len() as u32;
            let id = *bare.entry(n).or_insert(next);
            return format!("|#b{id}|");
        }
    }
    let Some(dash) = token.rfind('-') else { return token.to_string() };
    let (prefix, digits) = token.split_at(dash);
    let digits = &digits[1..];
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return token.to_string();
    }
    let Ok(n) = digits.parse::<u32>() else { return token.to_string() };
    // The two counters are independent, so a number means different things in
    // each namespace and they must be renumbered apart.
    let table = if prefix == "*UNIF*" { unif } else { gensym };
    let next = table.len() as u32;
    let id = *table.entry(n).or_insert(next);
    format!("{prefix}-#{id}")
}

/// A single case's result, for the progress report.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Verdict {
    Match,
    /// Reached the right stage but disagreed.
    Mismatch { expected: String, got: String },
    /// Not implemented far enough to say. Counted separately, so partial
    /// progress reads as progress rather than as failure.
    Unsupported { reason: String },
    /// Errored where the reference did not, or vice versa.
    Error { message: String },
}

/// Tally across a corpus, formatted for a test's output.
#[derive(Default)]
pub struct Report {
    pub matched: Vec<u32>,
    pub mismatched: Vec<(u32, String, String, String)>,
    pub unsupported: Vec<(u32, String)>,
    pub errors: Vec<(u32, String, String)>,
}

impl Report {
    pub fn record(&mut self, case: &Case, verdict: Verdict) {
        match verdict {
            Verdict::Match => self.matched.push(case.number),
            Verdict::Mismatch { expected, got } => {
                self.mismatched.push((case.number, case.src.clone(), expected, got))
            }
            Verdict::Unsupported { reason } => self.unsupported.push((case.number, reason)),
            Verdict::Error { message } => {
                self.errors.push((case.number, case.src.clone(), message))
            }
        }
    }

    pub fn total(&self) -> usize {
        self.matched.len() + self.mismatched.len() + self.unsupported.len() + self.errors.len()
    }

    pub fn summary(&self, label: &str) -> String {
        format!(
            "{label}: {}/{} match, {} mismatch, {} unsupported, {} error",
            self.matched.len(),
            self.total(),
            self.mismatched.len(),
            self.unsupported.len(),
            self.errors.len()
        )
    }

    /// The first `n` problems, in case order, with enough detail to act on.
    pub fn detail(&self, n: usize) -> String {
        let mut out = String::new();
        for (num, src, expected, got) in self.mismatched.iter().take(n) {
            out.push_str(&format!(
                "\n  case {num} MISMATCH\n    src:      {src}\n    expected: {expected}\n    got:      {got}\n"
            ));
        }
        for (num, src, message) in self.errors.iter().take(n) {
            out.push_str(&format!("\n  case {num} ERROR\n    src: {src}\n    {message}\n"));
        }
        let mut reasons: HashMap<&str, usize> = HashMap::new();
        for (_, reason) in &self.unsupported {
            *reasons.entry(reason.as_str()).or_insert(0) += 1;
        }
        if !reasons.is_empty() {
            let mut counted: Vec<_> = reasons.into_iter().collect();
            counted.sort_by_key(|(_, c)| std::cmp::Reverse(*c));
            out.push_str("\n  unsupported, by reason:\n");
            for (reason, count) in counted.iter().take(15) {
                out.push_str(&format!("    {count:4}  {reason}\n"));
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renumbering_preserves_structure_and_separates_namespaces() {
        // Same variable twice stays the same; distinct variables stay distinct.
        assert_eq!(normalize("(-> *UNIF*-591 (*UNIF*-591) *UNIF*-592)"),
                   "(-> *UNIF*-#0 (*UNIF*-#0) *UNIF*-#1)");
        // Renumbering is relative, so a run with different absolute numbers
        // normalises to the same thing.
        assert_eq!(normalize("(-> *UNIF*-7 (*UNIF*-7) *UNIF*-9)"),
                   normalize("(-> *UNIF*-591 (*UNIF*-591) *UNIF*-592)"));
        // …but a genuinely different structure still differs.
        assert_ne!(normalize("(-> *UNIF*-1 (*UNIF*-1) *UNIF*-2)"),
                   normalize("(-> *UNIF*-1 (*UNIF*-2) *UNIF*-2)"));
        // The two counters are independent: t-5 and *UNIF*-5 are unrelated.
        assert_eq!(normalize("(t-5 *UNIF*-5)"), "(t-#0 *UNIF*-#0)");
    }

    #[test]
    fn generalised_binders_normalise_but_field_labels_do_not() {
        // A binder's alpha number is an allocation artifact.
        assert_eq!(
            normalize("(poly ((|687| effect)) (-> |687| () int))"),
            normalize("(poly ((|686| effect)) (-> |686| () int))")
        );
        // …but a productof label is the field's position.
        assert_eq!(
            normalize("(productof (|1| int) (|2| bool))"),
            "(productof (|1| int) (|2| bool))"
        );
        assert_ne!(
            normalize("(productof (|1| int) (|2| bool))"),
            normalize("(productof (|2| int) (|1| bool))")
        );
    }

    #[test]
    fn ordinary_symbols_are_left_alone() {
        for s in ["(-> (maxeff) ((x bool)) bool)", "int", "list->sexp~", "set-car!", "\\1"] {
            assert_eq!(normalize(s), s);
        }
    }

    #[test]
    fn reads_a_record() {
        let text = "\
;;; header
#case 3
#src (with (module (define f 3)) f)
#type int
#effect (maxeff)
#value \"3\"
#end
#case 4
#src (bad)
#static-error \"unbound value variable f\"
#end
";
        let cases = parse_goldens(text).unwrap();
        assert_eq!(cases.len(), 2);
        assert_eq!(cases[0].number, 3);
        assert_eq!(cases[0].outcome,
                   Outcome::Typed { ty: "int".into(), effect: "(maxeff)".into() });
        assert_eq!(cases[0].expected_value(), Some("3"));
        assert!(matches!(cases[1].outcome, Outcome::StaticError { .. }));
    }
}
