(define log '())
(define (note x) (set! log (cons x log)))
(define k #f)
(define n 0)
(dynamic-wind (lambda () (note 'in))
              (lambda () (call/cc (lambda (c) (set! k c))) (set! n (+ n 1)))
              (lambda () (note 'out)))
(if (< n 2) (k 'again))
(list n (reverse log))
