;;; FX-87 standard environment -- GENERATED, do not edit.
;;; regenerate with: reference/regenerate.sh
;;; source: GiffordHistory fx-lang/fx87/private/impl.rkt
;;;   *standard-initial-t-env*  value bindings, each (name type region)
;;;   *standard-initial-k-env*  description bindings, each (name kind)
;;;   *standard-initial-dstore* description values, each (name desc)

(k-env
 (bool type)
 (unit type)
 (ref (dfunc (type region) type))
 (void type)
 (char type)
 (int type)
 (float type)
 (symbol type)
 (null type)
 (string (dfunc (region) type))
 (uniqueof (dfunc (type) type))
 (pairof (dfunc (type type region) type))
 (listof (dfunc (type region) type))
 (vsubr (dfunc (effect type type) type))
 (promise (dfunc (effect type) type))
 (vectorof (dfunc (type region) type))
 (input-port type)
 (output-port type)
 (sexp type)
 (default-region region)
)

(d-store
 (bool bool)
 (unit unit)
 (ref ref)
 (default-region @=)
 (void void)
 (char char)
 (int int)
 (float float)
 (symbol symbol)
 (null null)
 (string string)
 (uniqueof uniqueof)
 (pairof pairof)
 (listof (dlambda ((t type) (r region)) (dletrec ((list (pairof t list r))) list)))
 (vsubr vsubr)
 (promise promise)
 (vectorof vectorof)
 (input-port input-port)
 (output-port output-port)
 (sexp (dletrec ((sexp (oneof ((s-unit unit) (s-bool bool) (s-int int) (s-float float) (s-char char) (s-symbol symbol) (s-string (string @=)) (s-vectorof (vectorof sexp @=)) (s-null null) (s-pairof (pairof sexp sexp @=))) @=))) sexp))
)

(t-env
 (equiv? (subr pure (bool bool) bool) @=)
 (and? (subr pure (bool bool) bool) @=)
 (or? (subr pure (bool bool) bool) @=)
 (not? (subr pure (bool) bool) @=)
 (new (poly ((r region)) (poly ((t type)) (subr (alloc r) (t) (ref t r)))) @=)
 (get (poly ((r region)) (poly ((t type)) (subr (read r) ((ref t r)) t))) @=)
 (set (poly ((r region)) (poly ((t type)) (subr (write r) ((ref t r) t) unit))) @=)
 (error (poly ((r region)) (subr pure ((string r)) void)) @=)
 (char=? (subr pure (char char) bool) @=)
 (char<? (subr pure (char char) bool) @=)
 (char>? (subr pure (char char) bool) @=)
 (char<=? (subr pure (char char) bool) @=)
 (char>=? (subr pure (char char) bool) @=)
 (char-ci=? (subr pure (char char) bool) @=)
 (char-ci<? (subr pure (char char) bool) @=)
 (char-ci>? (subr pure (char char) bool) @=)
 (char-ci<=? (subr pure (char char) bool) @=)
 (char-ci>=? (subr pure (char char) bool) @=)
 (char-alphabetic? (subr pure (char) bool) @=)
 (char-numeric? (subr pure (char) bool) @=)
 (char-whitespace? (subr pure (char) bool) @=)
 (char-lower-case? (subr pure (char) bool) @=)
 (char-upper-case? (subr pure (char) bool) @=)
 (char-upcase (subr pure (char) char) @=)
 (char-downcase (subr pure (char) char) @=)
 (char->int (subr pure (char) int) @=)
 (int->char (subr pure (int) char) @=)
 (= (subr pure (int int) bool) @=)
 (< (subr pure (int int) bool) @=)
 (> (subr pure (int int) bool) @=)
 (<= (subr pure (int int) bool) @=)
 (>= (subr pure (int int) bool) @=)
 (+ (subr pure (int int) int) @=)
 (- (subr pure (int int) int) @=)
 (* (subr pure (int int) int) @=)
 (/ (subr pure (int int) int) @=)
 (abs (subr pure (int) int) @=)
 (expt (subr pure (int int) int) @=)
 (modulo (subr pure (int int) int) @=)
 (remainder (subr pure (int int) int) @=)
 (fl= (subr pure (float float) bool) @=)
 (fl< (subr pure (float float) bool) @=)
 (fl> (subr pure (float float) bool) @=)
 (fl<= (subr pure (float float) bool) @=)
 (fl>= (subr pure (float float) bool) @=)
 (fl+ (subr pure (float float) float) @=)
 (fl- (subr pure (float float) float) @=)
 (fl* (subr pure (float float) float) @=)
 (fl/ (subr pure (float float) float) @=)
 (flabs (subr pure (float) float) @=)
 (exp (subr pure (float) float) @=)
 (log (subr pure (float) float) @=)
 (sin (subr pure (float) float) @=)
 (cos (subr pure (float) float) @=)
 (tan (subr pure (float) float) @=)
 (asin (subr pure (float) float) @=)
 (acos (subr pure (float) float) @=)
 (atan (subr pure (float) float) @=)
 (sqrt (subr pure (float) float) @=)
 (floor (subr pure (float) int) @=)
 (ceiling (subr pure (float) int) @=)
 (truncate (subr pure (float) int) @=)
 (round (subr pure (float) int) @=)
 (int->float (subr pure (int) float) @=)
 (string->symbol (poly ((r region)) (subr (read r) ((string r)) symbol)) @=)
 (symbol->string (poly ((r region)) (subr (alloc r) (symbol) (string r))) @=)
 (symbol=? (subr pure (symbol symbol) bool) @=)
 (hash (subr pure (symbol) int) @=)
 (() null @=)
 (make-string (poly ((r region)) (subr (alloc r) (int char) (string r))) @=)
 (string-length (poly ((r region)) (subr pure ((string r)) int)) @=)
 (string-ref (poly ((r region)) (subr (read r) ((string r) int) char)) @=)
 (string-set! (poly ((r region)) (subr (write r) ((string r) int char) unit)) @=)
 (string-fill! (poly ((r region)) (subr (write r) ((string r) char) unit)) @=)
 (substring-fill! (poly ((r region)) (subr (write r) ((string r) int int char) unit)) @=)
 (string=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string<? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string>? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string<=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string>=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string-ci=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string-ci<? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string-ci>? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string-ci<=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (string-ci>=? (poly ((r region)) (subr (read r) ((string r) (string r)) bool)) @=)
 (substring (poly ((r1 region)) (subr (read r1) ((string r1) int int) (poly ((r2 region)) (subr (alloc r2) () (string r2))))) @=)
 (string-append (poly ((r1 region)) (subr (read r1) ((string r1) (string r1)) (poly ((r2 region)) (subr (alloc r2) () (string r2))))) @=)
 (string-copy (poly ((r1 region)) (subr (read r1) ((string r1)) (poly ((r2 region)) (subr (alloc r2) () (string r2))))) @=)
 (unique (poly ((t type)) (subr (alloc @uniqueof) (t) (uniqueof t))) @=)
 (value (poly ((t type)) (subr pure ((uniqueof t)) t)) @=)
 (eq? (poly ((t1 type) (t2 type)) (subr pure ((uniqueof t1) (uniqueof t2)) bool)) @=)
 (null? (poly ((r region)) (poly ((t1 type) (t2 type)) (subr pure ((pairof t1 t2 r)) bool))) @=)
 (cons (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (alloc r) (t1 t2) (pairof t1 t2 r)))) @=)
 (car (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (read r) ((pairof t1 t2 r)) t1))) @=)
 (cdr (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (read r) ((pairof t1 t2 r)) t2))) @=)
 (caar (poly ((r region)) (poly ((t type) (t1 type) (t2 type)) (subr (read r) ((pairof (pairof t t1 r) t2 r)) t))) @=)
 (cdar (poly ((r region)) (poly ((t type) (t1 type) (t2 type)) (subr (read r) ((pairof (pairof t1 t r) t2 r)) t))) @=)
 (cadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type)) (subr (read r) ((pairof t1 (pairof t t2 r) r)) t))) @=)
 (cddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type)) (subr (read r) ((pairof t1 (pairof t2 t r) r)) t))) @=)
 (caaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof (pairof (pairof t t1 r) t2 r) t3 r)) t))) @=)
 (cdaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof (pairof (pairof t1 t r) t2 r) t3 r)) t))) @=)
 (cadar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof (pairof t1 (pairof t t2 r) r) t3 r)) t))) @=)
 (cddar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof (pairof t1 (pairof t2 t r) r) t3 r)) t))) @=)
 (caadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof t1 (pairof (pairof t t2 r) t3 r) r)) t))) @=)
 (cdadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof t1 (pairof (pairof t2 t r) t3 r) r)) t))) @=)
 (caddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof t t3 r) r) r)) t))) @=)
 (cdddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof t3 t r) r) r)) t))) @=)
 (caaaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof (pairof (pairof t t1 r) t2 r) t3 r) t4 r)) t))) @=)
 (cdaaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof (pairof (pairof t1 t r) t2 r) t3 r) t4 r)) t))) @=)
 (cadaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof (pairof t1 (pairof t t2 r) r) t3 r) t4 r)) t))) @=)
 (cddaar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof (pairof t1 (pairof t2 t r) r) t3 r) t4 r)) t))) @=)
 (caadar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof t1 (pairof (pairof t t2 r) t3 r) r) t4 r)) t))) @=)
 (cdadar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof t1 (pairof (pairof t2 t r) t3 r) r) t4 r)) t))) @=)
 (caddar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof t1 (pairof t2 (pairof t t3 r) r) r) t4 r)) t))) @=)
 (cdddar (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof (pairof t1 (pairof t2 (pairof t3 t r) r) r) t4 r)) t))) @=)
 (caaadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof (pairof (pairof t t2 r) t3 r) t4 r) r)) t))) @=)
 (cdaadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof (pairof (pairof t2 t r) t3 r) t4 r) r)) t))) @=)
 (cadadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof (pairof t2 (pairof t t3 r) r) t4 r) r)) t))) @=)
 (cddadr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof (pairof t2 (pairof t3 t r) r) t4 r) r)) t))) @=)
 (caaddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof (pairof t t3 r) t4 r) r) r)) t))) @=)
 (cdaddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof (pairof t3 t r) t4 r) r) r)) t))) @=)
 (cadddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof t3 (pairof t t4 r) r) r) r)) t))) @=)
 (cddddr (poly ((r region)) (poly ((t type) (t1 type) (t2 type) (t3 type) (t4 type)) (subr (read r) ((pairof t1 (pairof t2 (pairof t3 (pairof t4 t r) r) r) r)) t))) @=)
 (set-car! (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (write r) ((pairof t1 t2 r) t1) unit))) @=)
 (set-cdr! (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (write r) ((pairof t1 t2 r) t2) unit))) @=)
 (list (poly ((r region)) (poly ((t type)) (vsubr (alloc r) t (listof t r)))) @=)
 (length (poly ((r region)) (poly ((t type)) (subr (read r) ((listof t r)) int))) @=)
 (append (poly ((r region)) (poly ((t type)) (subr (maxeff (read r) (alloc r)) ((listof t r) (listof t r)) (listof t r)))) @=)
 (reverse (poly ((r1 region)) (poly ((t type)) (subr (read r1) ((listof t r1)) (poly ((r2 region)) (subr (alloc r2) () (listof t r2)))))) @=)
 (list-tail (poly ((r region)) (poly ((t type)) (subr (read r) ((listof t r) int) (listof t r)))) @=)
 (list-ref (poly ((r region)) (poly ((t type)) (subr (read r) ((listof t r) int) t))) @=)
 (memq (poly ((r region)) (poly ((t type)) (subr (read r) ((uniqueof t) (listof (uniqueof t) r)) (listof (uniqueof t) r)))) @=)
 (assq (poly ((r region)) (poly ((t1 type) (t2 type)) (subr (read r) ((uniqueof t1) (listof (pairof (uniqueof t1) t2 r) r)) (pairof (uniqueof t1) t2 r)))) @=)
 (member (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff e (read r)) ((subr e (t t) bool) t (listof t r)) (listof t r)))) @=)
 (assoc (poly ((r1 region)) (poly ((t1 type) (t2 type) (e effect)) (subr (maxeff e (read r)) ((subr e (t1 t2) bool) t1 (listof (pairof t1 t2 r) r)) (pairof t1 t2 r)))) @=)
 (string->list (poly ((r region)) (subr (maxeff (read r) (alloc r)) ((string r)) (listof char r))) @=)
 (list->string (poly ((r region)) (subr (maxeff (read r) (alloc r)) ((listof char r)) (string r))) @=)
 (apply (poly ((r region)) (poly ((t1 type) (t2 type) (e effect)) (subr (maxeff e (read r)) ((vsubr e t1 t2) (listof t1 r)) t2))) @=)
 (map (poly ((r region)) (poly ((t1 type) (t2 type) (e effect)) (subr (maxeff e (read r) (alloc r)) ((subr e (t1) t2) (listof t1 r)) (listof t2 r)))) @=)
 (reduce (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff e (read r)) ((subr e (t t) t) (listof t r) t) t))) @=)
 (for-each (poly ((r region)) (poly ((t1 type) (t2 type) (e effect)) (subr (maxeff e (read r)) ((subr e (t1) t2) (listof t1 r)) unit))) @=)
 (force (poly ((e effect) (t type) (r region)) (subr e ((promise e t)) t)) @=)
 (make-vector (poly ((r region)) (poly ((t type)) (subr (alloc r) (int t) (vectorof t r)))) @=)
 (vector (poly ((r region)) (poly ((t type)) (vsubr (alloc r) t (vectorof t r)))) @=)
 (vector-length (poly ((r region)) (poly ((t type)) (subr pure ((vectorof t r)) int))) @=)
 (vector-ref (poly ((r region)) (poly ((t type)) (subr (read r) ((vectorof t r) int) t))) @=)
 (vector-set! (poly ((r region)) (poly ((t type)) (subr (write r) ((vectorof t r) int t) unit))) @=)
 (vector-fill! (poly ((r region)) (poly ((t type)) (subr (write r) ((vectorof t r) t) unit))) @=)
 (vector->list (poly ((r region)) (poly ((t type)) (subr (maxeff (read r) (alloc r)) ((vectorof t r)) (listof t r)))) @=)
 (list->vector (poly ((r region)) (poly ((t type)) (subr (maxeff (read r) (alloc r)) ((listof t r)) (vectorof t r)))) @=)
 (call-with-input-file (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff e (alloc @io) (read r)) ((string r) (subr e (input-port) t)) t))) @=)
 (call-with-output-file (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff e (alloc @io) (read r)) ((string r) (subr e (output-port) t)) t))) @=)
 (current-input-port (subr (maxeff (read @io) (write @io)) () input-port) @=)
 (current-output-port (subr (maxeff (read @io) (write @io)) () output-port) @=)
 (with-input-from-file (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff (write @io) (read @io) (alloc @io) e (read r)) ((string r) (subr e () t)) t))) @=)
 (with-output-to-file (poly ((r region)) (poly ((t type) (e effect)) (subr (maxeff (write @io) (read @io) (alloc @io) e (read r)) ((string r) (subr e () t)) t))) @=)
 (open-input-file (poly ((r region)) (subr (maxeff (alloc @io) (read @io) (write @io) (read r)) ((string r)) input-port)) @=)
 (open-output-file (poly ((r region)) (subr (maxeff (alloc @io) (read @io) (write @io) (read r)) ((string r)) output-port)) @=)
 (close-input-port (subr (maxeff (write @io) (read @io)) (input-port) unit) @=)
 (close-output-port (subr (maxeff (write @io) (read @io)) (output-port) unit) @=)
 (char-ready? (vsubr (maxeff (write @io) (read @io)) input-port bool) @=)
 (read-bool (subr (maxeff (write @io) (read @io)) () bool) @=)
 (read-char (subr (maxeff (write @io) (read @io)) () char) @=)
 (read-int (subr (maxeff (write @io) (read @io)) () int) @=)
 (read-float (subr (maxeff (write @io) (read @io)) () float) @=)
 (read-string (subr (maxeff (write @io) (read @io)) () (string @=)) @=)
 (read-symbol (subr (maxeff (write @io) (read @io)) () symbol) @=)
 (read-bool-from-port (subr (maxeff (write @io) (read @io)) (input-port) bool) @=)
 (read-char-from-port (subr (maxeff (write @io) (read @io)) (input-port) char) @=)
 (read-int-from-port (subr (maxeff (write @io) (read @io)) (input-port) int) @=)
 (read-float-from-port (subr (maxeff (write @io) (read @io)) (input-port) float) @=)
 (read-string-from-port (subr (maxeff (write @io) (read @io)) (input-port) (string @=)) @=)
 (read-symbol-from-port (subr (maxeff (write @io) (read @io)) (input-port) symbol) @=)
 (eof? (vsubr (maxeff (write @io) (read @io)) input-port bool) @=)
 (write-bool (subr (maxeff (write @io) (read @io)) (bool) unit) @=)
 (write-char (subr (maxeff (write @io) (read @io)) (char) unit) @=)
 (write-int (subr (maxeff (write @io) (read @io)) (int) unit) @=)
 (write-float (subr (maxeff (write @io) (read @io)) (float) unit) @=)
 (write-string (poly ((r region)) (subr (maxeff (write @io) (read @io)) ((string r)) unit)) @=)
 (write-symbol (subr (maxeff (write @io) (read @io)) (symbol) unit) @=)
 (write-bool-to-port (subr (maxeff (write @io) (read @io)) (bool output-port) unit) @=)
 (write-char-to-port (subr (maxeff (write @io) (read @io)) (char output-port) unit) @=)
 (write-int-to-port (subr (maxeff (write @io) (read @io)) (int output-port) unit) @=)
 (write-float-to-port (subr (maxeff (write @io) (read @io)) (float output-port) unit) @=)
 (write-string-to-port (poly ((r region)) (subr (maxeff (write @io) (read @io)) ((string r) output-port) unit)) @=)
 (write-symbol-to-port (subr (maxeff (write @io) (read @io)) (symbol output-port) unit) @=)
 (read-sexp (subr (maxeff (read @io) (write @io)) () sexp) @=)
 (read-sexp-from-port (subr (maxeff (read @io) (write @io)) (input-port) sexp) @=)
 (write-sexp (subr (maxeff (read @io) (write @io)) (sexp) unit) @=)
 (write-sexp-to-port (subr (maxeff (read @io) (write @io)) (sexp output-port) unit) @=)
)
