//! The FX-91 abstract syntax — descriptions and expressions in one arena.
//!
//! This follows `abstract.scm`'s structure closely, including the decision that
//! looks odd at first: **descriptions and expressions share one node type.**
//! They have to. A `select` description holds an *expression* (the module being
//! selected from), a `subr` type binds *value* variables, and `moduleof`
//! carries both. Splitting them into two arenas would mean every one of those
//! edges crossing a type boundary for no benefit.
//!
//! # Unification by forwarding
//!
//! `unify.scm` unifies by mutating a node into a forwarding pointer at the one
//! slot every node shares, so every existing reference to it silently follows.
//! [`Fx::Forward`] plus [`Arena::resolve`] is the same thing with an explicit
//! union-find, and it is why an arena is the right shape here rather than a
//! tree: a tree would have to be rebuilt on every substitution.
//!
//! # The info cache
//!
//! `abstract.scm` stores five cached facts per node, and reuses the same five
//! slots for two different meanings — `desc-infos` for descriptions (kind,
//! inferability, normal form, free description variables, free value
//! variables) and `val-infos` for expressions (type, effect, free variables,
//! free description variables, literal value). The aliasing is load-bearing for
//! it because both live in vector slot 1. Here they are separate fields: a few
//! words more per node, and no chance of reading one as the other.
//!
//! Note which of the two resolves forwarding. `desc-infos` goes through
//! `forward-vector-ref`, so a description's cache lives on the *resolved* node;
//! `val-infos` does not, because expressions are never unified.

use fixpt_read::{Span, Sym, Syntax};

#[derive(Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
pub struct FxId(pub u32);

impl FxId {
    #[inline]
    pub const fn index(self) -> usize {
        self.0 as usize
    }
}

// ------------------------------------------------------------------- kinds

#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Kind {
    Type,
    Effect,
    /// `(dfunc k…)`, written `(->> k…)` when unparsed.
    DFunc(Vec<Kind>),
}

// --------------------------------------------------------------- variables

/// Alpha-renaming does not distinguish description from value variables, so
/// the domain has to be carried on the variable and checked at every
/// environment lookup. `utils.scm` is explicit about why: think of
/// `(lambda ((x t)) t)`, where `x` and `t` can share a name.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Domain {
    Value,
    Description,
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum VarClass {
    /// Written by the user, or generated by desugaring.
    Identifier,
    /// Introduced by inference. Not user-accessible.
    Unification,
}

/// Three-valued, for the ACUI solver's valuations: an effect constant is known
/// to be absent, known to be present, or not yet determined.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Tri {
    Unknown,
    False,
    True,
}

#[derive(Clone, Debug)]
pub struct VarData {
    pub class: VarClass,
    pub user_name: Sym,
    /// The alpha-renamed identity. Two variables are the same iff this and the
    /// domain agree.
    pub name: u32,
    pub domain: Domain,
    /// Unification variables only: whether this stands for an inferable effect.
    pub weak: bool,
    /// Unification variables only.
    pub kind: Option<Kind>,
    /// Unification variables only: the ACUI solver's per-constant valuation,
    /// keyed by the constant's alpha name.
    pub valuation: Vec<(u32, Tri)>,
}

impl VarData {
    pub fn same(&self, other: &VarData) -> bool {
        self.name == other.name && self.domain == other.domain
    }
    pub fn is_unification(&self) -> bool {
        self.class == VarClass::Unification
    }
    pub fn is_identifier(&self) -> bool {
        self.class == VarClass::Identifier
    }
}

// ------------------------------------------------------------------- nodes

#[derive(Clone, Debug)]
pub enum Fx {
    /// Set by unification; every reference follows it. See [`Arena::resolve`].
    Forward(FxId),

    Variable(VarData),

    /// `with` and `extend` bodies, held unparsed.
    ///
    /// `abstract.scm` explains why: alpha-renaming the body depends on the
    /// *type* of the module expression, which is not known until kind- and
    /// type-checking. So the body keeps its syntax and its alpha environment
    /// and is parsed later.
    Unparsed { alpha: AlphaId, syntax: Syntax },

    // ------------------------------------------------------- descriptions
    DLambda { ids: Vec<FxId>, kinds: Vec<Kind>, body: FxId },
    DApp { rator: FxId, rands: Vec<FxId> },
    Select { module: FxId, id: Sym },
    MaxEff(Vec<FxId>),
    /// `(subr effect ((id type)…) body)`, unparsed as `->`.
    Subr { effect: FxId, ids: Vec<FxId>, types: Vec<FxId>, body: FxId },
    Poly { ids: Vec<FxId>, kinds: Vec<Kind>, body: FxId },
    /// A type scheme. Lives in the type environment and is not user-writable;
    /// `unparse-poly~` produces `(~ …)`, which is deliberately not readable
    /// syntax, so seeing one in output means something went wrong.
    PolyTilde { ids: Vec<FxId>, kinds: Vec<Kind>, body: FxId, constraints: Vec<Constraint> },
    ModuleOf {
        abs_ids: Vec<FxId>,
        abs_kinds: Vec<Kind>,
        desc_ids: Vec<FxId>,
        desc_descs: Vec<FxId>,
        val_ids: Vec<FxId>,
        val_types: Vec<FxId>,
    },
    SumOf { tags: Vec<Sym>, types: Vec<FxId> },
    ProductOf { tags: Vec<Sym>, types: Vec<FxId> },

    // -------------------------------------------------------- expressions
    Lambda {
        ids: Vec<FxId>,
        types: Vec<FxId>,
        /// Whether each parameter's type was written by the user, as opposed to
        /// being a fresh unification variable. Drives inference.
        user_types: Vec<bool>,
        body: FxId,
    },
    Let { ids: Vec<FxId>, exps: Vec<FxId>, body: FxId },
    App { rator: FxId, rands: Vec<FxId> },
    PLambda { ids: Vec<FxId>, kinds: Vec<Kind>, body: FxId },
    Proj { exp: FxId, descs: Vec<FxId> },
    Module {
        /// `define-abstraction` names, and the `up-`/`down-` coercions they
        /// implicitly define.
        abs_ids: Vec<FxId>,
        up_ids: Vec<FxId>,
        down_ids: Vec<FxId>,
        abs_kinds: Vec<Kind>,
        abs_descs: Vec<FxId>,
        desc_ids: Vec<FxId>,
        desc_descs: Vec<FxId>,
        define_ids: Vec<FxId>,
        define_exps: Vec<FxId>,
        typed_ids: Vec<FxId>,
        typed_types: Vec<FxId>,
        typed_exps: Vec<FxId>,
        /// The original source, kept for error messages.
        text: Syntax,
    },
    With { module: FxId, body: FxId, text: Syntax },
    Extend { module: FxId, body: FxId, text: Syntax },
    If { test: FxId, then: FxId, els: FxId },
    Open(FxId),
    Close(FxId),
    Begin(Vec<FxId>),
    /// `(load "file")` — a REPL-era textual inclusion, read and parsed on
    /// demand. Not in the report's reserved words, but real in this
    /// implementation and used by its own test suite.
    Load { path: String, alpha: AlphaId, parsed: Option<FxId> },
    The { ty: FxId, exp: FxId },
    Does { effect: FxId, exp: FxId },
    Sum { ty: FxId, tag: Sym, exp: FxId },
    Product { ty: FxId, exps: Vec<FxId> },
    TagCase { ty: FxId, exp: FxId, tag: Sym, success: FxId, failure: FxId },
    Extract { ty: FxId, exp: FxId, tag: Sym },
}

/// An effect constraint: two effect expressions that must denote the same set.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct Constraint {
    pub lhs: FxId,
    pub rhs: FxId,
}

/// What a literal's value is, for the code generator.
///
/// `standard.scm` caches a literal's value on its node and `code-of-variable`
/// splices it straight into the generated code. Most literals cache themselves;
/// `sexp` is the exception, caching a *quoted, converted* form, so the two
/// cases are distinguished here rather than discovered later.
#[derive(Clone, Debug)]
pub enum LiteralValue {
    /// The datum evaluates to itself.
    SelfEvaluating(Syntax),
    /// A quoted s-expression, converted to `sexp`'s sum representation.
    Sexp(Syntax),
}

#[derive(Clone, Debug, Default)]
pub struct Info {
    // -- as a description --------------------------------------------------
    pub kind: Option<Kind>,
    pub inferable: Option<bool>,
    /// Normal form after description evaluation.
    pub norm: Option<FxId>,
    pub free_dvars: Option<Vec<FxId>>,
    pub free_vars: Option<Vec<FxId>>,
    // -- as an expression --------------------------------------------------
    pub ty: Option<FxId>,
    pub effect: Option<FxId>,
    pub exp_free_vars: Option<Vec<FxId>>,
    pub exp_free_dvars: Option<Vec<FxId>>,
    pub literal: Option<LiteralValue>,
}

#[derive(Clone, Debug)]
pub struct Node {
    pub fx: Fx,
    pub info: Info,
    pub span: Span,
}

// ----------------------------------------------------- alpha environments

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct AlphaId(pub u32);

/// `token.scm`'s alpha environment is an alist extended by `append`ing new
/// bindings onto the front, so extension shares the tail. A chain of frames is
/// the same structure with the sharing made explicit, which matters because
/// every `with` body holds onto one until it is parsed.
#[derive(Clone, Debug)]
pub struct AlphaFrame {
    pub bindings: Vec<(Sym, u32)>,
    pub parent: Option<AlphaId>,
}

// ------------------------------------------------------------------ arena

pub struct Arena {
    nodes: Vec<Node>,
    alpha: Vec<AlphaFrame>,
    /// `*alpha-counter*`: hands out variable identities.
    pub alpha_counter: u32,
    /// `new-identifier`'s own counter, deliberately separate from the one
    /// above. The conformance normaliser depends on them staying separate.
    pub gensym_counter: u32,
}

impl Default for Arena {
    fn default() -> Arena {
        Arena::new()
    }
}

impl Arena {
    pub fn new() -> Arena {
        Arena { nodes: Vec::new(), alpha: Vec::new(), alpha_counter: 0, gensym_counter: 0 }
    }

    pub fn len(&self) -> usize {
        self.nodes.len()
    }
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    pub fn add(&mut self, span: Span, fx: Fx) -> FxId {
        self.nodes.push(Node { fx, info: Info::default(), span });
        FxId(self.nodes.len() as u32 - 1)
    }

    /// Follow forwarding pointers to the node a reference now denotes,
    /// compressing the path so repeated resolution stays cheap.
    pub fn resolve(&mut self, id: FxId) -> FxId {
        let mut root = id;
        while let Fx::Forward(next) = self.nodes[root.index()].fx {
            root = next;
        }
        let mut cursor = id;
        while let Fx::Forward(next) = self.nodes[cursor.index()].fx {
            self.nodes[cursor.index()].fx = Fx::Forward(root);
            cursor = next;
        }
        root
    }

    /// Resolution without path compression, for the many read-only walks.
    pub fn find(&self, id: FxId) -> FxId {
        let mut root = id;
        while let Fx::Forward(next) = self.nodes[root.index()].fx {
            root = next;
        }
        root
    }

    #[inline]
    pub fn get(&self, id: FxId) -> &Fx {
        &self.nodes[self.find(id).index()].fx
    }
    #[inline]
    pub fn raw(&self, id: FxId) -> &Fx {
        &self.nodes[id.index()].fx
    }
    #[inline]
    pub fn span(&self, id: FxId) -> Span {
        self.nodes[id.index()].span
    }

    /// Description-side cache: lives on the resolved node, matching
    /// `desc-infos`'s use of `forward-vector-ref`.
    #[inline]
    pub fn info(&self, id: FxId) -> &Info {
        &self.nodes[self.find(id).index()].info
    }
    #[inline]
    pub fn info_mut(&mut self, id: FxId) -> &mut Info {
        let r = self.find(id);
        &mut self.nodes[r.index()].info
    }

    /// Expression-side cache: on the node itself, matching `val-infos`.
    /// Expressions are never unified, so the two agree in practice; keeping
    /// them distinct documents which is which.
    #[inline]
    pub fn exp_info(&self, id: FxId) -> &Info {
        &self.nodes[id.index()].info
    }
    #[inline]
    pub fn exp_info_mut(&mut self, id: FxId) -> &mut Info {
        &mut self.nodes[id.index()].info
    }

    /// Point `from` at `to`. Returns false if that would be a no-op.
    pub fn forward(&mut self, from: FxId, to: FxId) -> bool {
        let a = self.resolve(from);
        let b = self.resolve(to);
        if a == b {
            return true;
        }
        self.nodes[a.index()].fx = Fx::Forward(b);
        true
    }

    // ------------------------------------------------------------ variables
    pub fn fresh_name(&mut self) -> u32 {
        let n = self.alpha_counter;
        self.alpha_counter += 1;
        n
    }

    pub fn identifier_variable(
        &mut self,
        span: Span,
        user_name: Sym,
        name: u32,
        domain: Domain,
    ) -> FxId {
        self.add(
            span,
            Fx::Variable(VarData {
                class: VarClass::Identifier,
                user_name,
                name,
                domain,
                weak: false,
                kind: None,
                valuation: Vec::new(),
            }),
        )
    }

    /// A unification variable. `weak` marks one that stands only for an
    /// inferable effect.
    pub fn unification_variable(
        &mut self,
        span: Span,
        user_name: Sym,
        weak: bool,
        kind: Kind,
    ) -> FxId {
        let name = self.fresh_name();
        self.add(
            span,
            Fx::Variable(VarData {
                class: VarClass::Unification,
                user_name,
                name,
                domain: Domain::Description,
                weak,
                kind: Some(kind),
                valuation: Vec::new(),
            }),
        )
    }

    pub fn var(&self, id: FxId) -> Option<&VarData> {
        match self.get(id) {
            Fx::Variable(v) => Some(v),
            _ => None,
        }
    }
    pub fn var_mut(&mut self, id: FxId) -> Option<&mut VarData> {
        let r = self.find(id);
        match &mut self.nodes[r.index()].fx {
            Fx::Variable(v) => Some(v),
            _ => None,
        }
    }
    pub fn is_variable(&self, id: FxId) -> bool {
        matches!(self.get(id), Fx::Variable(_))
    }
    /// `variable=?`: same alpha name and same domain.
    pub fn same_variable(&self, a: FxId, b: FxId) -> bool {
        match (self.var(a), self.var(b)) {
            (Some(x), Some(y)) => x.same(y),
            _ => false,
        }
    }
    /// `pure?`: an empty `maxeff`.
    pub fn is_pure(&self, id: FxId) -> bool {
        matches!(self.get(id), Fx::MaxEff(e) if e.is_empty())
    }

    /// `effect-list`: a `maxeff`'s members, or the effect itself.
    pub fn effect_list(&self, id: FxId) -> Vec<FxId> {
        match self.get(id) {
            Fx::MaxEff(e) => e.clone(),
            _ => vec![id],
        }
    }

    // ------------------------------------------------- alpha environments
    pub fn empty_alpha(&mut self) -> AlphaId {
        self.alpha.push(AlphaFrame { bindings: Vec::new(), parent: None });
        AlphaId(self.alpha.len() as u32 - 1)
    }

    pub fn extend_alpha(&mut self, parent: AlphaId, bindings: Vec<(Sym, u32)>) -> AlphaId {
        self.alpha.push(AlphaFrame { bindings, parent: Some(parent) });
        AlphaId(self.alpha.len() as u32 - 1)
    }

    /// Look a name up, or hand out a fresh identity for it.
    ///
    /// `get-alpha-env` invents a name for anything unbound rather than
    /// reporting an error, which is how a reference to an undefined variable
    /// survives parsing and is caught later by the type checker with a better
    /// message.
    pub fn alpha_lookup(&mut self, env: AlphaId, name: Sym) -> u32 {
        let mut cursor = Some(env);
        while let Some(id) = cursor {
            let frame = &self.alpha[id.0 as usize];
            if let Some((_, n)) = frame.bindings.iter().rev().find(|(s, _)| *s == name) {
                return *n;
            }
            cursor = frame.parent;
        }
        self.fresh_name()
    }

    pub fn alpha_bindings(&self, env: AlphaId) -> &[(Sym, u32)] {
        &self.alpha[env.0 as usize].bindings
    }
}
