[package]
name = "fixpt-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "fixpt"
path = "src/main.rs"

[dependencies]
fixpt-heap = { path = "../fixpt-heap" }
fixpt-read = { path = "../fixpt-read" }
fixpt-core = { path = "../fixpt-core" }
fixpt-runtime = { path = "../fixpt-runtime" }
fixpt-engine = { path = "../fixpt-engine" }
fixpt-scheme = { path = "../fixpt-scheme" }
fixpt-fx91 = { path = "../fixpt-fx91" }
fixpt-fx87 = { path = "../fixpt-fx87" }

[lints]
workspace = true
