;;; Closures: made and called, through a higher-order map.
(define-effect conses (maxeff (read @l) (alloc @l) spin))
(define* map-add (subr conses ((subr pure (int) int) (listof int @l)) (listof int @l))
  (lambda (f xs) (if (null? xs) nil (cons (f (car xs)) (map-add f (cdr xs))))))
(define* total (subr (maxeff (read @l) spin) ((listof int @l) int) int)
  (lambda (xs acc) (if (null? xs) acc (total (cdr xs) (+ acc (car xs))))))
(define* upto (subr (maxeff (alloc @l) spin) (int (listof int @l)) (listof int @l))
  (lambda (n acc) (if (= n 0) acc (upto (- n 1) (cons n acc)))))
(define* go (subr conses (int int (listof int @l)) int)
  (lambda (k acc xs)
    (if (= k 0) acc (go (- k 1) (+ acc (total (map-add (lambda ((x int)) (+ x k)) xs) 0)) xs))))
(define* main (subr conses (int) int) (lambda (k) (go k 0 (upto 1000 nil))))
(main 3000)
