(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(define (sum-to n) (let loop ((i 0) (acc 0)) (if (> i n) acc (loop (+ i 1) (+ acc i)))))
(define greeting "shipped")
(define (main args)
  (display greeting)
  (display " ")
  (display (fact 15))
  (display " ")
  (display (sum-to 1000))
  (display " ")
  (write args)
  (newline)
  0)
