(define (make-seq) (cons 0 (make-vector 8 0)))
(define (seq-add! s x)
  (let ((next (car s)) (v (cdr s)))
    (if (= next (vector-length v))
        (let ((w (make-vector (* (vector-length v) 2) 0)))
          (do ((i 0 (+ i 1))) ((= i (vector-length v)))
            (vector-set! w i (vector-ref v i)))
          (set-cdr! s w)
          (seq-add! s x))
        (begin (vector-set! v next x)
               (set-car! s (+ next 1))))))
(define (build n)
  (let ((s (make-seq)))
    (do ((i 0 (+ i 1))) ((= i n) (car s))
      (seq-add! s i))))
(define (run reps n)
  (do ((i 0 (+ i 1))) ((= i reps) 'done)
    (build n)))
