(define (less? a b)
  (cond ((null? a) #f)
        ((null? b) #f)
        ((< (car a) (car b)) #t)
        ((> (car a) (car b)) #f)
        (else (less? (cdr a) (cdr b)))))
(define (merge! a b)
  (cond ((null? a) b)
        ((null? b) a)
        ((less? (car b) (car a))
         (set-cdr! b (merge! a (cdr b))) b)
        (else (set-cdr! a (merge! (cdr a) b)) a)))
(define (halve l)
  (let loop ((slow l) (fast (cdr l)))
    (if (or (null? fast) (null? (cdr fast)))
        (let ((rest (cdr slow))) (set-cdr! slow '()) rest)
        (loop (cdr slow) (cddr fast)))))
(define (sort! l)
  (if (or (null? l) (null? (cdr l)))
      l
      (let ((back (halve l))) (merge! (sort! l) (sort! back)))))
(define (sorted? l)
  (cond ((null? l) #t)
        ((null? (cdr l)) #t)
        ((less? (cadr l) (car l)) #f)
        (else (sorted? (cdr l)))))
