//! Printing [`Syntax`] back out.
//!
//! Symbol escaping deliberately matches what Racket's `write` produces, because
//! the FX conformance goldens were generated by Racket and are compared
//! textually: FX-87's boolean symbols come back as `|#t|`, not `#t`, and a
//! reader-visible difference there would show up as 155 spurious failures.

use crate::datum::{Datum, Num, Syntax};
use crate::intern::Interner;
use std::fmt::Write as _;

/// `write`-style: strings quoted, characters named, symbols escaped as needed.
pub fn write_syntax(s: &Syntax, interner: &Interner) -> String {
    let mut out = String::new();
    put(&mut out, s, interner, true);
    out
}

/// `display`-style: strings and characters rendered as their contents.
pub fn display_syntax(s: &Syntax, interner: &Interner) -> String {
    let mut out = String::new();
    put(&mut out, s, interner, false);
    out
}

fn put(out: &mut String, s: &Syntax, interner: &Interner, write: bool) {
    match &s.datum {
        Datum::Bool(true) => out.push_str("#t"),
        Datum::Bool(false) => out.push_str("#f"),
        Datum::Nil => out.push_str("()"),
        Datum::Number(n) => put_num(out, n),
        Datum::Char(c) => {
            if write {
                put_char(out, *c)
            } else {
                out.push(*c)
            }
        }
        Datum::Str(text) => {
            if write {
                put_string(out, text)
            } else {
                out.push_str(text)
            }
        }
        Datum::Symbol(sym) => put_symbol(out, interner.name(*sym)),
        Datum::List { items, tail } => {
            out.push('(');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(' ');
                }
                put(out, item, interner, write);
            }
            if let Some(t) = tail {
                out.push_str(" . ");
                put(out, t, interner, write);
            }
            out.push(')');
        }
        Datum::Vector(items) => {
            out.push_str("#(");
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(' ');
                }
                put(out, item, interner, write);
            }
            out.push(')');
        }
        Datum::Bytevector(bytes) => {
            out.push_str("#u8(");
            for (i, b) in bytes.iter().enumerate() {
                if i > 0 {
                    out.push(' ');
                }
                let _ = write!(out, "{b}");
            }
            out.push(')');
        }
    }
}

fn put_num(out: &mut String, n: &Num) {
    match n {
        Num::Int(i) => {
            let _ = write!(out, "{i}");
        }
        Num::Big { negative, digits, radix } => {
            if *negative {
                out.push('-');
            }
            match radix {
                2 => out.push_str("#b"),
                8 => out.push_str("#o"),
                16 => out.push_str("#x"),
                _ => {}
            }
            out.push_str(digits);
        }
        Num::Ratio(a, b) => {
            put_num(out, a);
            out.push('/');
            put_num(out, b);
        }
        Num::Real(x) => {
            if x.is_nan() {
                out.push_str("+nan.0");
            } else if x.is_infinite() {
                out.push_str(if *x > 0.0 { "+inf.0" } else { "-inf.0" });
            } else if *x == x.trunc() && x.abs() < 1e21 {
                // R7RS requires a decimal point on an inexact integer, so that
                // reading the output back gives an inexact number again.
                let _ = write!(out, "{x:.1}");
            } else {
                let _ = write!(out, "{x}");
            }
        }
    }
}

fn put_char(out: &mut String, c: char) {
    out.push_str("#\\");
    match c {
        ' ' => out.push_str("space"),
        '\n' => out.push_str("newline"),
        '\t' => out.push_str("tab"),
        '\r' => out.push_str("return"),
        '\0' => out.push_str("null"),
        '\u{7}' => out.push_str("alarm"),
        '\u{8}' => out.push_str("backspace"),
        '\u{7f}' => out.push_str("delete"),
        '\u{1b}' => out.push_str("escape"),
        c if (c as u32) < 0x20 => {
            let _ = write!(out, "x{:x}", c as u32);
        }
        c => out.push(c),
    }
}

fn put_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\x{:x};", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

/// Render a symbol name the way `write` does, adding `|…|` when the bare text
/// would not read back as the same symbol.
///
/// Exposed because the FX front ends print symbols through their own
/// unparsers, and their goldens were produced by Racket's `write`: a `productof`
/// label is the symbol `1`, which must print as `|1|`.
pub fn escape_symbol(name: &str) -> String {
    let mut out = String::new();
    put_symbol(&mut out, name);
    out
}

/// Whether `name` would read back as the same symbol, or needs `|…|`.
fn symbol_needs_bars(name: &str) -> bool {
    if name.is_empty() {
        return true;
    }
    if name.chars().any(|c| {
        c.is_whitespace() || matches!(c, '(' | ')' | '[' | ']' | '"' | ';' | '\'' | '`' | ',' | '|' | '\\')
    }) {
        return true;
    }
    if name.starts_with('#') {
        return true;
    }
    // A lone `.` is the dotted-pair marker, and anything that would read back
    // as a number must be escaped, or `write` then `read` would not round-trip.
    name == "." || crate::reader::parse_number(name, 10, None).is_some()
}

fn put_symbol(out: &mut String, name: &str) {
    if !symbol_needs_bars(name) {
        out.push_str(name);
        return;
    }
    out.push('|');
    for c in name.chars() {
        if c == '|' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('|');
}
