;; A list walked without `spin`: first by a fuel of 1024 steps, and only
;; past that, by the length a cycle-checking pass finds for the rest.
(define-type ints (listof int @l))
(define* total (subr (read @l) (ints) int)
  (lambda (xs0)
    (letrec ((rest (subr (read @l) (ints nat int) int)
                   (lambda (xs n acc)
                     (cond ((= n 0) acc)
                           ((null? xs) acc)
                           (else (rest (cdr xs) (- n 1) (+ acc (car xs)))))))
             (fuel (subr (read @l) (ints nat int) int)
                   (lambda (xs k acc)
                     (cond ((null? xs) acc)
                           ((= k 0) (rest xs (list-length xs) acc))
                           (else (fuel (cdr xs) (- k 1) (+ acc (car xs))))))))
      (fuel xs0 1024 0))))
(define* iota (subr (maxeff (alloc @l) spin) (int ints) ints)
  (lambda (n acc) (if (= n 0) acc (iota (- n 1) (cons n acc)))))
(list (total (iota 10 nil)) (total (iota 5000 nil)))
