;;; A thousand string keys, through several doublings of the buckets.
(define t (table string int @t) (make-table string-hash string=?))
(define digit (subr pure (int) string) (lambda (d) (char->string (integer->char (+ 48 d)))))
(define* digit-at (subr pure (int int) string)
  (lambda (i place) (digit (modulo (quotient i place) 10))))
(define* key (subr pure (int) string)
  (lambda (i)
    (let ((tens-and-ones (string-append (digit-at i 10) (digit-at i 1))))
      (string-append "k" (string-append (digit-at i 100) tens-and-ones)))))
(define* fill (subr (maxeff (read @t) (write @t) (alloc @t) spin) (int) unit)
  (lambda (i) (if (= i 1000) #u (begin (table-set! t (key i) i) (fill (+ i 1))))))
(define* sum-back (subr (maxeff (read @t) spin) (int int) int)
  (lambda (i acc) (if (= i 1000) acc (sum-back (+ i 1) (+ acc (table-ref t (key i) -1))))))
(fill 0)
(let ((nope (if (table-has? t "nope") 1 0)))
  (list (table-count t) (sum-back 0 0) nope))
