//! Compiles the stencils (`stencils/threaded.rs`) with the installed nightly,
//! once per optimisation level, reads the objects, and writes their machine
//! code out as tables for `src/stencil.rs`.
//!
//! What it insists on, so that a stencil placed by copying runs correctly:
//! no relocations at all, and no branch that leaves the stencil. Anything
//! else fails the build, with the offending stencil named.
//!
//! No nightly, no stencils: the build carries on without them, and says so.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

use fixpt_engine::threaded::Trap;
use fixpt_heap::layout::threaded::{KIND, PRIMITIVES, ROUTINES, WORD_CELL0, WORD_ENTRY};
use fixpt_heap::Value;
use fixpt_heap::value::{TAG_BLOBLET, TAG_MASK, TAG_PAIR, TAG_TRAILER};

/// The optimisation levels the stencils are compiled at.
const OPT_LEVELS: &[&str] = &["0", "1", "2", "3", "s"];

/// A routine's name as a Rust identifier.
fn ident(name: &str) -> String {
    match name {
        "+" => "add".into(),
        "-" => "sub".into(),
        "<" => "less".into(),
        "field@" => "field_ref".into(),
        "field!" => "field_set".into(),
        "0branch" => "zbranch".into(),
        // `local!` and the like: a Rust identifier has no `!`.
        n => n.replace('!', "_set"),
    }
}

fn consts() -> String {
    let mut s = String::from("// Generated by build.rs from the layout table.\n");
    let mut c = |name: &str, v: u64| writeln!(s, "pub const {name}: u64 = {v:#x};").unwrap();
    c("TAG_MASK", TAG_MASK);
    c("TAG_PAIR", TAG_PAIR);
    c("TAG_BLOBLET", TAG_BLOBLET);
    c("TAG_TRAILER", TAG_TRAILER);
    c("FALSE", Value::FALSE.raw());
    c("TRUE", Value::TRUE.raw());
    c("PROMPT_MARK", fixpt_engine::threaded::PROMPT_MARK.raw());
    c("MARK_MARK", fixpt_engine::threaded::MARK_MARK.raw());
    c("WORD_KIND", KIND as u64);
    c("CLOSURE_KIND", fixpt_heap::layout::kind("threaded-closure") as u64);
    c("CLOSURE_WORD", fixpt_heap::layout::threaded::CLOSURE_WORD as u64);
    c("CLOSURE_FREE0", fixpt_heap::layout::threaded::CLOSURE_FREE0 as u64);
    c("WORD_ENTRY", WORD_ENTRY as u64);
    c("WORD_CELL0", WORD_CELL0 as u64);
    c("PRIMITIVES", PRIMITIVES as u64);
    for (i, (name, _)) in ROUTINES.iter().enumerate() {
        c(&format!("R_{}", ident(name).to_uppercase()), i as u64);
    }
    let r = "+";
    for (name, t) in [
        ("TYPE", Trap::Type { routine: r }),
        ("OVERFLOW", Trap::Overflow { routine: r }),
        ("UNDERFLOW", Trap::Underflow { routine: r }),
        ("FIELD", Trap::Field { routine: r }),
        ("NO_ROUTINE", Trap::NoRoutine(0)),
        ("NOT_A_WORD", Trap::NotAWord),
        ("OUT_OF_FUEL", Trap::OutOfFuel),
        ("STACK_OVERFLOW", Trap::StackOverflow),
        ("TOO_DEEP", Trap::TooDeep),
    ] {
        c(&format!("TRAP_{name}"), t.code().0);
    }
    s
}

fn main() {
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    println!("cargo:rerun-if-changed=stencils/threaded.rs");
    println!("cargo:rerun-if-changed=src/state.rs");
    fs::copy("stencils/threaded.rs", out.join("threaded.rs")).unwrap();
    fs::copy("src/state.rs", out.join("state.rs")).unwrap();
    fs::write(out.join("consts.rs"), consts()).unwrap();

    let mut table = String::from("// Generated by build.rs: the stencils' machine code.\npub static STENCIL_SETS: &[StencilSet] = &[\n");
    let mut listing = String::new();
    for opt in OPT_LEVELS {
        let obj = out.join(format!("threaded-O{opt}.o"));
        match compile(&out, opt, &obj) {
            Ok(()) => {}
            // No nightly at all: build without stencils, and say so.
            Err(Compile::NoNightly(e)) => {
                println!("cargo:warning=no stencils: {e}");
                table = String::from("pub static STENCIL_SETS: &[StencilSet] = &[\n");
                break;
            }
            // A nightly that rejects the stencils: a bug here, not a missing
            // tool, so the build stops and says what.
            Err(Compile::Failed(e)) => panic!("the stencils do not compile at -O{opt}:\n{e}"),
        }
        let bytes = fs::read(&obj).unwrap();
        let stencils = read_stencils(&bytes).unwrap_or_else(|e| panic!("stencils at -O{opt}: {e}"));
        writeln!(table, "  StencilSet {{ opt: {opt:?}, stencils: &[").unwrap();
        writeln!(listing, "-C opt-level={opt}").unwrap();
        for (name, code) in &stencils {
            writeln!(table, "    ({name:?}, &{code:?}),").unwrap();
            writeln!(listing, "  {name:<16} {:>4} bytes", code.len()).unwrap();
        }
        writeln!(table, "  ]}},").unwrap();
    }
    table.push_str("];\n");
    fs::write(out.join("stencils.rs"), table).unwrap();
    fs::write(out.join("stencils.txt"), listing).unwrap();
}

enum Compile {
    NoNightly(String),
    Failed(String),
}

fn compile(dir: &Path, opt: &str, obj: &Path) -> Result<(), Compile> {
    let out = Command::new("rustup")
        .args(["run", "nightly", "rustc", "--edition", "2024", "--crate-type", "lib", "--emit", "obj"])
        .args(["--target", "aarch64-apple-darwin", "-C", &format!("opt-level={opt}")])
        .args(["-C", "panic=abort", "-C", "debuginfo=0", "-C", "llvm-args=-enable-machine-outliner=never"])
        // Only the optimisation level varies: the checks a debug build adds
        // (overflow, and null and alignment on every dereference) call into
        // `core`, which a stencil cannot reach, so they are off at every level.
        .args(["-C", "debug-assertions=off", "-C", "overflow-checks=off"])
        .arg("-o")
        .arg(obj)
        .arg(dir.join("threaded.rs"))
        .output()
        .map_err(|e| Compile::NoNightly(format!("cannot run `rustup run nightly rustc`: {e}")))?;
    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr).into_owned();
        // rustup's own complaint, when no nightly is installed.
        if err.contains("toolchain 'nightly") && err.contains("not installed") {
            return Err(Compile::NoNightly(err));
        }
        return Err(Compile::Failed(err));
    }
    Ok(())
}

// ----------------------------------------------------- a small Mach-O reader

fn u32le(b: &[u8], o: usize) -> u32 {
    u32::from_le_bytes(b[o..o + 4].try_into().unwrap())
}
fn u64le(b: &[u8], o: usize) -> u64 {
    u64::from_le_bytes(b[o..o + 8].try_into().unwrap())
}
fn cstr(b: &[u8], o: usize) -> String {
    let e = b[o..].iter().position(|&c| c == 0).unwrap();
    String::from_utf8_lossy(&b[o..o + e]).into_owned()
}
fn fixed(b: &[u8]) -> String {
    let e = b.iter().position(|&c| c == 0).unwrap_or(b.len());
    String::from_utf8_lossy(&b[..e]).into_owned()
}

struct Sect {
    name: String,
    addr: u64,
    size: u64,
    off: u32,
    nreloc: u32,
}

/// Every `st_` function in `__text`, as `(name, code)`, checked.
fn read_stencils(b: &[u8]) -> Result<Vec<(String, Vec<u8>)>, String> {
    if u32le(b, 0) != 0xfeed_facf || u32le(b, 4) != 0x0100_000c || u32le(b, 12) != 1 {
        return Err("not an arm64 Mach-O object".into());
    }
    let ncmds = u32le(b, 16) as usize;
    let mut p = 32;
    let mut sects = Vec::new();
    let mut syms = Vec::new();
    for _ in 0..ncmds {
        let (cmd, size) = (u32le(b, p), u32le(b, p + 4) as usize);
        match cmd {
            0x19 => {
                for i in 0..u32le(b, p + 64) as usize {
                    let s = p + 72 + i * 80;
                    sects.push(Sect {
                        name: format!("{},{}", fixed(&b[s + 16..s + 32]), fixed(&b[s..s + 16])),
                        addr: u64le(b, s + 32),
                        size: u64le(b, s + 40),
                        off: u32le(b, s + 48),
                        nreloc: u32le(b, s + 60),
                    });
                }
            }
            0x2 => {
                let (symoff, nsyms, stroff) = (u32le(b, p + 8) as usize, u32le(b, p + 12) as usize, u32le(b, p + 16) as usize);
                for i in 0..nsyms {
                    let e = symoff + i * 16;
                    syms.push((cstr(b, stroff + u32le(b, e) as usize), b[e + 5], u64le(b, e + 8)));
                }
            }
            _ => {}
        }
        p += size;
    }
    let ti = sects.iter().position(|s| s.name == "__TEXT,__text").ok_or("no __text")?;
    let text = &sects[ti];
    if text.nreloc != 0 {
        return Err(format!("__text has {} relocations; a stencil must have none", text.nreloc));
    }
    for s in &sects {
        if s.name != "__TEXT,__text" && s.nreloc != 0 {
            return Err(format!("{} has relocations", s.name));
        }
    }
    let mut starts: Vec<(u64, &str)> =
        syms.iter().filter(|s| s.1 as usize == ti + 1).map(|s| (s.2, s.0.as_str())).collect();
    starts.sort();
    let mut out = Vec::new();
    for (i, &(start, name)) in starts.iter().enumerate() {
        let end = starts.get(i + 1).map(|x| x.0).unwrap_or(text.addr + text.size);
        // Anything else (the panic handler) is unreachable from a stencil:
        // there are no relocations, and every stencil's branches stay in it.
        let Some(name) = name.strip_prefix("_st_") else {
            continue;
        };
        let code = b[text.off as usize + start as usize..text.off as usize + end as usize].to_vec();
        check_branches(name, &code)?;
        out.push((name.to_string(), code));
    }
    Ok(out)
}

/// Every direct branch in a stencil must land inside it.
fn check_branches(name: &str, code: &[u8]) -> Result<(), String> {
    let n = code.len() as i64 / 4;
    for i in 0..n {
        let w = u32le(code, 4 * i as usize);
        let sext = |v: u32, bits: u32| ((v << (32 - bits)) as i32 >> (32 - bits)) as i64;
        let target = if w & 0x7C00_0000 == 0x1400_0000 {
            Some(sext(w & 0x03FF_FFFF, 26)) // b, bl
        } else if w & 0xFF00_0010 == 0x5400_0000 || w & 0x7E00_0000 == 0x3400_0000 {
            Some(sext((w >> 5) & 0x7FFFF, 19)) // b.cond, cbz, cbnz
        } else if w & 0x7E00_0000 == 0x3600_0000 {
            Some(sext((w >> 5) & 0x3FFF, 14)) // tbz, tbnz
        } else {
            None
        };
        if let Some(d) = target
            && !(0..n).contains(&(i + d))
        {
            return Err(format!("st_{name}: the branch at +{:#x} leaves the stencil", 4 * i));
        }
    }
    Ok(())
}
