;;; The checker, in FX-26: first-class modules' descriptions, read
;;; (`docs/research/first-class-modules.md`, stage M2): `moduleof` and
;;; `select`, and a `module`'s items, in one recursive group with the
;;; expression walk (`check-resolve.fx`'s), as a module is an expression
;;; and its items hold them. Before `check-modules.fx`.

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
;; Its types (`check-modules-types.fx`, its file's after it), loaded before the
;; module so that they are not among its values; the module names what it
;; uses of them.
(let* ((check-modules-types (load-module "fx26:check-modules-types.fx"))
       (check-types-types (load-module "fx26:check-types-types.fx"))
       (check-synth-types (load-module "fx26:check-synth-types.fx"))
       (parser-types ((proj (load-module "fx26:parser-types.fx") @s @e @m @c @p)))
       (check-resolve-types (load-module "fx26:check-resolve-types.fx"))
       (check-read-types (load-module "fx26:check-read-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-syntax-types (load-module "fx26:check-syntax-types.fx"))
       (check-read-descs-types (load-module "fx26:check-read-descs-types.fx"))
       (check-subst-types (load-module "fx26:check-subst-types.fx"))
       (reader-types (load-module "fx26:reader-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-resolve (select check-resolve-types check-resolve-sig))
           (check-syntax (select check-syntax-types check-syntax-sig))
           (check-read (select check-read-types check-read-sig))
           (check-env (select check-env-types check-env-sig))
           (check-read-descs (select check-read-descs-types check-read-descs-sig))
           (check-subst (select check-subst-types check-subst-sig))
           (parser (select reader-types parser-sig)))
    (module
(define-type k-rec-read (select check-modules-types k-rec-read))
(define-type k-thunk-unit (select check-modules-types k-thunk-unit))
;; The types it uses of the files before it.
(define-effect checks (select check-types-types checks))
(define ds-eff (with check-types-types ds-eff))
(define ds-fun (with check-types-types ds-fun))
(define ds-var (with check-types-types ds-var))
(define dt (with check-types-types dt))
(define-type k-binders (select check-types-types k-binders))
(define k-done (with check-types-types k-done))
(define k-err (with check-types-types k-err))
(define-type k-ids (select check-types-types k-ids))
(define-type k-item (select check-types-types k-item))
(define-type k-names (select check-types-types k-names))
(define-type k-te (select check-types-types k-te))
(define-effect kreads (select check-types-types kreads))
(define-effect kstate (select check-types-types kstate))
(define-type kx (select check-types-types kx))
(define-type kxs (select check-types-types kxs))
(define r-heap (with check-types-types r-heap))
(define ty-lam (with check-types-types ty-lam))
(define x-app (with check-types-types x-app))
(define x-begin (with check-types-types x-begin))
(define x-bloblet (with check-types-types x-bloblet))
(define x-const (with check-types-types x-const))
(define x-convention (with check-types-types x-convention))
(define x-extract (with check-types-types x-extract))
(define x-if (with check-types-types x-if))
(define x-lambda (with check-types-types x-lambda))
(define x-let (with check-types-types x-let))
(define x-letrec (with check-types-types x-letrec))
(define x-letregion (with check-types-types x-letregion))
(define x-module (with check-types-types x-module))
(define x-plambda (with check-types-types x-plambda))
(define x-product (with check-types-types x-product))
(define x-proj (with check-types-types x-proj))
(define x-prompt (with check-types-types x-prompt))
(define x-rlambda (with check-types-types x-rlambda))
(define x-sum (with check-types-types x-sum))
(define x-tagcase (with check-types-types x-tagcase))
(define x-the (with check-types-types x-the))
(define x-var (with check-types-types x-var))
(define x-with (with check-types-types x-with))
(define-type k-items (select check-types-types k-items))
(define-type k-done (select check-synth-types k-done))
(define e-app (with parser-types e-app))
(define e-begin (with parser-types e-begin))
(define e-bloblet (with parser-types e-bloblet))
(define e-bool (with parser-types e-bool))
(define e-char (with parser-types e-char))
(define e-convention (with parser-types e-convention))
(define e-extract (with parser-types e-extract))
(define e-float (with parser-types e-float))
(define e-if (with parser-types e-if))
(define e-int (with parser-types e-int))
(define e-lambda (with parser-types e-lambda))
(define e-let (with parser-types e-let))
(define e-letrec (with parser-types e-letrec))
(define e-letregion (with parser-types e-letregion))
(define e-module (with parser-types e-module))
(define e-plambda (with parser-types e-plambda))
(define e-product (with parser-types e-product))
(define e-proj (with parser-types e-proj))
(define e-prompt (with parser-types e-prompt))
(define e-rlambda (with parser-types e-rlambda))
(define e-str (with parser-types e-str))
(define e-sum (with parser-types e-sum))
(define e-sym (with parser-types e-sym))
(define e-tagcase (with parser-types e-tagcase))
(define e-the (with parser-types e-the))
(define e-unit (with parser-types e-unit))
(define e-var (with parser-types e-var))
(define e-with (with parser-types e-with))
(define-type exp (select parser-types exp))
(define-type exp-list (select parser-types exp-list))
(define-type mod-item (select parser-types mod-item))
(define-type mod-items (select parser-types mod-items))
(define-type names (select parser-types names))
(define-type syns-a (select parser-types syns-a))
(define-type exp-arms (select check-resolve-types exp-arms))
(define-type exp-let-bs (select check-resolve-types exp-let-bs))
(define-type exp-letrec-bs (select check-resolve-types exp-letrec-bs))
(define-type k-arms (select check-resolve-types k-arms))
(define-type k-let-bs (select check-resolve-types k-let-bs))
(define-type k-letrec-bs (select check-resolve-types k-letrec-bs))
(define-type k-syns (select check-read-types k-syns))
(define-type k-scope (select check-env-types k-scope))
;; What it uses of the modules it is given.
(define k-abstract-funs (with check-types k-abstract-funs))
(define k-arrow (with check-types k-arrow))
(define k-binder-kinds (with check-types k-binder-kinds))
(define k-dvar-name (with check-types k-dvar-name))
(define k-fail (with check-types k-fail))
(define k-has-name? (with check-types k-has-name?))
(define k-lifetimes (with check-types k-lifetimes))
(define k-new-dvar-of (with check-types k-new-dvar-of))
(define k-quote (with check-types k-quote))
(define k-set-outer (with check-types k-set-outer))
(define k-tag (with check-types k-tag))
(define k-te (with check-types k-te))
(define k-ty-new (with check-types k-ty-new))
(define exp-end (with check-resolve exp-end))
(define exp-start (with check-resolve exp-start))
(define k-copy-names (with check-resolve k-copy-names))
(define k-freeze-into (with check-resolve k-freeze-into))
(define k-names-onto (with check-resolve k-names-onto))
(define k-order-binders (with check-resolve k-order-binders))
(define k-place-lives (with check-resolve k-place-lives))
(define k-resolve-descs (with check-resolve k-resolve-descs))
(define k-resolve-params (with check-resolve k-resolve-params))
(define k-resolve-place (with check-resolve k-resolve-place))
(define k-ahead-declare (with check-syntax k-ahead-declare))
(define k-ahead-filled (with check-syntax k-ahead-filled))
(define k-ahead-names (with check-syntax k-ahead-names))
(define k-filled-reversed (with check-syntax k-filled-reversed))
(define k-ground-filled (with check-syntax k-ground-filled))
(define k-list-head (with check-syntax k-list-head))
(define k-parse-conv (with check-syntax k-parse-conv))
(define k-binders-each (with check-read k-binders-each))
(define k-effect-desc (with check-read k-effect-desc))
(define k-items (with check-read k-items))
(define k-parse-binders (with check-read k-parse-binders))
(define k-bool (with check-env k-bool))
(define k-char (with check-env k-char))
(define k-dscope (with check-env k-dscope))
(define k-f64 (with check-env k-f64))
(define k-int (with check-env k-int))
(define k-push-desc (with check-env k-push-desc))
(define k-std-dscope (with check-env k-std-dscope))
(define k-string (with check-env k-string))
(define k-symbol (with check-env k-symbol))
(define k-unit (with check-env k-unit))
(define k-define-type (with check-read-descs k-define-type))
(define k-parse-effect (with check-read-descs k-parse-effect))
(define k-parse-fun (with check-read-descs k-parse-fun))
(define k-parse-type (with check-read-descs k-parse-type))
(define k-parse-types (with check-read-descs k-parse-types))
(define k-note-closed-filled (with check-subst k-note-closed-filled))
(define in-loaded (with parser in-loaded))
(define load-base (with parser load-base))
(define loaded (with parser loaded))
(define syn-end (with parser syn-end))
(define syn-start (with parser syn-start))

;; A module item as `x-module` has it.
(define k-item-of (subr (maxeff (read @globals) (alloc @t)) (int names int k-ids kxs) k-item)
  (lambda (k ns v ts xs) (product (1 k) (2 (k-copy-names ns)) (3 v) (4 ts) (5 xs))))
(define k-push-binders (subr kstate (k-binders) unit)
  (lambda (bs)
    (if (null? bs)
        #u
        (let ((v (extract (car bs) 1)))
          (begin (k-push-desc (k-dvar-name v) (ds-var v (extract (car bs) 2)))
                 (k-push-binders (cdr bs)))))))
;; The names a module's items give type abbreviations: each `define-type`
;; of a name, but of a `dlambda` or an effect.
(define k-module-type-names (subr (maxeff (read @globals) (read @s) (alloc @t)) (mod-items) k-names)
  (lambda (items)
    (if (null? items)
        nil
        (let* ((it (car items)) (ts (extract it 3)) (rest (k-module-type-names (cdr items))))
          (if (and (= (extract it 1) 1) (null? (cdr ts))
                   (not (string=? (k-list-head (car ts)) "dlambda")))
              (the k-names (cons (car (extract it 2)) rest))
              rest)))))
(define k-in-loaded (subr (maxeff checks spin) (k-thunk-unit int int int) unit)
  (lambda (f base a b)
    (let ((r (prompt k-tag (begin (f) (k-done (k-te 0 nil))) (lambda (r) r))))
      (tagcase r
        (k-err (m ea eb)
          (if (and (>= ea base) (< ea (+ base load-base)))
              (k-fail (in-loaded (get loaded) base m ea) a b)
              (k-fail m ea eb)))
        (else y #u)))))
;; What a module's first item says of where it was read: from its file, at
;; a base (> 3); not, and why (-1); or not from a file (0 to 3).
(define k-items-kind (subr pure (mod-items) int)
  (lambda (items) (if (null? items) 0 (extract (car items) 1))))
;; The names a module's item defines as descriptions (`types`), or as values:
;; a generative type's name is one, its two conversions values; as the Rust
;; checker's `defined_twice` counts them.
(define k-item-names (subr (maxeff (read @globals) (alloc @t)) (mod-item bool) k-names)
  (lambda (it types)
    (let ((k (extract it 1)))
      (case k ((0)
               (let* ((n (car (extract it 2))) (s (symbol->string n)))
                 (if types
                     (the k-names (list n))
                     (the k-names (list (string->symbol (string-append "up-" s))
                                        (string->symbol (string-append "down-" s)))))))
              ((1) (if types (extract it 2) (the k-names nil)))
              (else (if types (the k-names nil) (extract it 2)))))))
;; The first name of `items`, in order, that one before it defines too, as a
;; description (`seen`) or as a value (`vseen`): a module defining a name
;; twice has no type (`moduleof` refuses it), and which definition a use got
;; would depend on the path that ran it. A value may have a type's name.
(define k-defined-twice (subr (maxeff kreads (alloc @t)) (mod-items k-names k-names) k-names)
  (lambda (items seen vseen)
    (letrec ((first (subr (maxeff (read @globals) (read @t)) (k-names k-names) k-names)
               (lambda (ns seen)
                 (cond ((null? ns) nil)
                       ((k-has-name? seen (car ns)) (the k-names (list (car ns))))
                       (else (first (cdr ns) seen))))))
      (if (null? items)
          nil
          (let* ((ts (k-item-names (car items) #t)) (vs (k-item-names (car items) #f))
                 (twice (first ts seen)) (vtwice (first vs vseen)))
            (cond ((not (null? twice)) twice)
                  ((not (null? vtwice)) vtwice)
                  (else (k-defined-twice (cdr items) (k-names-onto ts seen)
                                         (k-names-onto vs vseen)))))))))
;; How many of `xs` there are.
(define k-syns-count (subr (read @globals) (k-syns) int)
  (lambda (xs) (if (null? xs) 0 (+ 1 (k-syns-count (cdr xs))))))
;; The newest `n` of scope `s` onto `onto`: a module's file's parameters,
;; bound by the `plambda` around it, which it sees.
(define k-scope-newest (subr (maxeff (read @globals) (alloc @t)) (int k-scope k-scope) k-scope)
  (lambda (n s onto)
    (if (or (<= n 0) (null? s)) onto (cons (car s) (k-scope-newest (- n 1) (cdr s) onto)))))
;; Reading expressions (`check-resolve.fx`'s walk) and modules' items, one
;; recursive group: a module is an expression, and its items hold them.
(define-rec
  (k-resolve-all (subr (maxeff checks spin) ((listof exp acyclic)) kxs)
    (lambda (es)
      (if (null? es)
          nil
          (let* ((x (k-resolve-exp (car es))) (rest (k-resolve-all (cdr es))))
            (cons x rest)))))
  (k-resolve-exp (subr (maxeff checks spin) (exp) kx)
    (lambda (e)
      (tagcase e
        (e-var (s a b) (x-var s a b))
        (e-int (n a b) (x-const k-int n a b))
        (e-bool (v a b) (x-const k-bool (if v 1 0) a b))
        (e-str (v a b) (x-const k-string 0 a b))
        (e-char (v a b) (x-const k-char 0 a b))
        (e-float (v a b) (x-const k-f64 0 a b))
        (e-sym (v a b) (x-const k-symbol 0 a b))
        (e-unit (a b) (x-const k-unit 0 a b))
        (e-lambda (ps body a b)
          (let* ((params (k-resolve-params ps)) (x (k-resolve-exp body))) (x-lambda params x a b)))
        (e-app (f args a b)
          (let* ((fx (k-resolve-exp f)) (xs (k-resolve-all args))) (x-app fx xs a b)))
        (e-plambda (binders body a b)
          (let* ((saved (get k-dscope))
                 (lives (get k-lifetimes))
                 (bs (k-parse-binders binders))
                 ;; A procedure's regions and places outlive whatever its
                 ;; body binds.
                 (ordered (k-order-binders bs lives))
                 (x (k-resolve-exp body)))
            (begin (set k-dscope saved) (set k-lifetimes lives) (x-plambda bs x a b))))
        (e-rlambda (r l a b)
          (let* ((rx (k-resolve-exp r)) (lx (k-resolve-exp l))) (x-rlambda rx lx a b)))
        (e-letregion (k name into body a b)
          (let* ((saved (get k-dscope))
                 ;; `letrena` and `letreap` make a place (which is also a
                 ;; region), `letregion` a region only.
                 (kind (if (or (= k 0) (= k 3)) 0 3))
                 (place (if (= k 3) (k-resolve-place into a b) (r-heap)))
                 (v (k-new-dvar-of name kind))
                 (lives (get k-lifetimes))
                 ;; A `letfreeze`'s data leaves in the place it freezes into,
                 ;; so it may be allocated only in that place or one outliving
                 ;; it: those are all it won't outlive.
                 (ordered (begin
                            (k-set-outer v (if (= k 3) (k-place-lives place) lives))
                            (set k-lifetimes (cons v lives))))
                 (pushed (k-push-desc name (ds-var v kind)))
                 (x (k-resolve-exp body)))
            (begin (set k-dscope saved) (set k-lifetimes lives)
                   (x-letregion k v (k-freeze-into place) x a b))))
        (e-proj (body ds a b)
          (let* ((x (k-resolve-exp body)) (descs (k-resolve-descs ds))) (x-proj x descs a b)))
        (e-if (p c d a b)
          (let* ((px (k-resolve-exp p)) (cx (k-resolve-exp c)) (dx (k-resolve-exp d)))
            (x-if px cx dx a b)))
        (e-letrec (bs body a b)
          (let* ((rbs (k-resolve-letrec bs)) (x (k-resolve-exp body))) (x-letrec rbs x a b)))
        (e-let (bs body a b)
          (let* ((rbs (k-resolve-let bs)) (x (k-resolve-exp body))) (x-let rbs x a b)))
        (e-begin (es a b) (x-begin (k-resolve-all es) a b))
        (e-prompt (t body h a b)
          (let* ((tx (k-resolve-exp t)) (bx (k-resolve-exp body)) (hx (k-resolve-exp h)))
            (x-prompt tx bx hx a b)))
        (e-the (ty body a b)
          (let* ((t (k-parse-type ty)) (x (k-resolve-exp body))) (x-the t x a b)))
        (e-convention (c body a b)
          (let* ((cv (k-parse-conv c)) (x (k-resolve-exp body))) (x-convention cv x a b)))
        (e-bloblet (op i args a b) (x-bloblet op i (k-resolve-all args) a b))
        (e-product (fs a b) (x-product (k-resolve-fields fs nil a b) a b))
        (e-extract (body l a b) (x-extract (k-resolve-exp body) l a b))
        (e-sum (l body a b) (x-sum l (k-resolve-exp body) a b))
        (e-tagcase (s arms els a b)
          ;; The `else` arm, if any, is resolved as a `let` binding is.
          (let* ((sx (k-resolve-exp s))
                 (rarms (k-resolve-arms arms nil))
                 (rels (k-resolve-let els)))
            (x-tagcase sx rarms rels a b)))
        (e-module (items a b) (k-resolve-module-items items a b))
        (e-with (m body a b) (x-with m (k-resolve-exp body) a b)))))
  (k-resolve-letrec (subr (maxeff checks spin) (exp-letrec-bs) k-letrec-bs)
    (lambda (bs)
      (if (null? bs)
          nil
          (let* ((t (k-parse-type (extract (car bs) 2)))
                 (x (k-resolve-exp (extract (car bs) 3)))
                 (rest (k-resolve-letrec (cdr bs))))
            (cons (product (1 (extract (car bs) 1)) (2 t) (3 x)) rest)))))
  (k-resolve-let (subr (maxeff checks spin) (exp-let-bs) k-let-bs)
    (lambda (bs)
      (if (null? bs)
          nil
          (let* ((x (k-resolve-exp (extract (car bs) 2))) (rest (k-resolve-let (cdr bs))))
            (cons (product (1 (extract (car bs) 1)) (2 x)) rest)))))
  (k-resolve-fields (subr (maxeff checks spin) (exp-let-bs k-names int int) k-let-bs)
    (lambda (fs seen a b)
      (if (null? fs)
          nil
          (let ((l (extract (car fs) 1)))
            (if (k-has-name? seen l)
                (k-fail (string-append (k-quote (symbol->string l)) " appears twice") a b)
                (let* ((x (k-resolve-exp (extract (car fs) 2)))
                       (rest (k-resolve-fields (cdr fs) (cons l seen) a b)))
                  (cons (product (1 l) (2 x)) rest)))))))
  (k-resolve-arms (subr (maxeff checks spin) (exp-arms k-names) k-arms)
    (lambda (arms seen)
      (if (null? arms)
          nil
          (let* ((arm (car arms)) (tag (extract arm 1)))
            (if (k-has-name? seen tag)
                (k-fail (string-append (k-quote (symbol->string tag)) " has two arms")
                        (exp-start (extract arm 4)) (exp-end (extract arm 4)))
                (let* ((x (k-resolve-exp (extract arm 4)))
                       (rest (k-resolve-arms (cdr arms) (cons tag seen)))
                       (names (k-copy-names (extract arm 3))))
                  (cons (product (1 tag) (2 (extract arm 2)) (3 names) (4 x)) rest)))))))
  (k-resolve-rec-items (subr (maxeff checks spin) (syns-a exp-list) k-rec-read)
    (lambda (ts xs)
      (if (null? ts)
          (product (1 (the k-ids nil)) (2 (the kxs nil)))
          (let* ((t (k-parse-type (car ts)))
                 (x (k-resolve-exp (car xs)))
                 (rest (k-resolve-rec-items (cdr ts) (cdr xs))))
            (product (1 (the k-ids (cons t (extract rest 1))))
                     (2 (the kxs (cons x (extract rest 2)))))))))
  ;; A module's `define-generative`: an abstract type, a type variable in scope
  ;; from here, its representation read in that scope; or, with parameters
  ;; (its head after its representation in `ts`), a type constructor: its
  ;; parameters read, then it, a variable of an arrow kind, and its
  ;; representation a `dlambda` of them (`check-kinds.fx`).
  (k-resolve-abstract (subr (maxeff checks spin) (k-names syns-a exp-list) k-item)
    (lambda (ns ts xs)
      (if (null? (cdr ts))
          (let* ((v (k-new-dvar-of (car ns) 2))
                 (pushed (k-push-desc (car ns) (ds-var v 2)))
                 (rep (k-parse-type (car ts))))
            (k-item-of 0 ns v (the k-ids (cons rep nil)) (k-resolve-all xs)))
          (let* ((ps (cdr (k-items (car (cdr ts)) "a module's definition")))
                 (saved (get k-dscope))
                 (bs (k-binders-each ps))
                 (restored (set k-dscope saved))
                 (kind (k-arrow (k-binder-kinds bs) 2))
                 (v (k-new-dvar-of (car ns) kind))
                 (noted (set k-abstract-funs (cons v (get k-abstract-funs))))
                 (pushed (k-push-desc (car ns) (ds-var v kind)))
                 (inner (get k-dscope))
                 (bound (k-push-binders bs))
                 (rep (k-parse-type (car ts)))
                 (back (set k-dscope inner))
                 (lam (k-ty-new (ty-lam bs (dt rep)))))
            (k-item-of 0 ns v (the k-ids (cons lam nil)) (k-resolve-all xs))))))
  ;; One item: an abstract type a type variable in scope from here (with
  ;; its representation read in that scope), and a transparent one an alias.
  (k-resolve-item (subr (maxeff checks spin) (mod-item) k-item)
    (lambda (it)
      (let ((k (extract it 1)) (ns (extract it 2)) (ts (extract it 3)) (xs (extract it 4)))
        (cond ((or (< k 0) (> k 3)) (k-item-of k ns -1 nil nil))
              ((= k 0) (k-resolve-abstract ns ts xs))
              ;; `(define-effect e E)`: its types the effect and a mark.
              ((and (= k 1) (not (null? (cdr ts))))
               (let ((e (k-parse-effect (car ts))))
                 (begin (k-push-desc (car ns) (ds-eff e))
                        (k-item-of k ns -1 (the k-ids (cons (k-effect-desc e) nil)) nil))))
              ((and (= k 1) (string=? (k-list-head (car ts)) "dlambda"))
               (let ((f (k-parse-fun (car ts) -1)))
                 (begin (k-push-desc (car ns) (ds-fun f))
                        (k-item-of k ns -1 (the k-ids (cons f nil)) nil))))
              ;; As a program's: declared ahead, or a knot of its own.
              ((= k 1)
               (let ((t (k-define-type (car ns) (car ts) (syn-start (car ts)) (syn-end (car ts)))))
                 (k-item-of k ns -1 (the k-ids (cons t nil)) nil)))
              ;; A `define*`'s types its type and a mark: its variable -2.
              ((and (= k 2) (not (null? ts)) (not (null? (cdr ts))))
               (let* ((t (k-parse-types (the syns-a (cons (car ts) nil)))) (x (k-resolve-all xs)))
                 (k-item-of k ns -2 t x)))
              ((= k 2)
               (let* ((t (if (null? ts) (the k-ids nil) (k-parse-types ts))) (x (k-resolve-all xs)))
                 (k-item-of k ns -1 t x)))
              (else
               (let ((r (k-resolve-rec-items ts xs)))
                 (k-item-of k ns -1 (extract r 1) (extract r 2))))))))
  (k-resolve-items (subr (maxeff checks spin) (mod-items) k-items)
    (lambda (items)
      (if (null? items)
          nil
          (let* ((x (k-resolve-item (car items))) (rest (k-resolve-items (cdr items))))
            (cons x rest)))))
  ;; A module's items, its type abbreviations declared ahead, as a program's
  ;; are (`k-ahead`): each defined once, by name, in scope before any is
  ;; read, so that they may name each other, and themselves, in any order;
  ;; each checked grounded once all are.
  (k-resolve-items-ahead (subr (maxeff checks spin) (mod-items) k-items)
    (lambda (items)
      (let* ((outer-names (get k-ahead-names)) (outer-filled (get k-ahead-filled))
             (names (k-module-type-names items))
             (cleared (begin (set k-ahead-names nil) (set k-ahead-filled nil)))
             (declared (k-ahead-declare names names))
             (got (the (ref k-items @t) (new nil)))
             ;; What is wrong in the items, kept until the state outside is back.
             (r (prompt k-tag (begin (set got (k-resolve-items items)) (k-done (k-te 0 nil)))
                        (lambda (r) r)))
             (filled (get k-ahead-filled)))
        (begin (set k-ahead-names outer-names)
               (set k-ahead-filled outer-filled)
               (tagcase r
                 (k-err (m a b) (k-fail m a b))
                 (else y (begin (k-ground-filled (k-filled-reversed filled nil))
                                (k-note-closed-filled filled))))
               (get got)))))
  ;; `(module item …)`: each item read in the scope of the descriptions
  ;; before it; read from a file, of the standard ones only, and its
  ;; parameters (`(module-parameters …)`), the `plambda` around it binds.
  (k-resolve-module-items (subr (maxeff checks spin) (mod-items int int) kx)
    (lambda (items a b)
      (let ((k (k-items-kind items)) (saved (get k-dscope)))
        (cond
          ((< k 0) (k-fail (symbol->string (car (extract (car items) 2))) a b))
          ((not (null? (k-defined-twice items nil nil)))
           (k-fail (string-append (k-quote (symbol->string (car (k-defined-twice items nil nil))))
                                  " is defined twice in this module")
                   a b))
          ((> k 3)
           (let ((got (the (ref k-items @t) (new nil)))
                 (ps (k-syns-count (extract (car items) 3))))
             (begin (set k-dscope (k-scope-newest ps saved (get k-std-dscope)))
                    (k-in-loaded (lambda () (set got (k-resolve-items-ahead items))) k a b)
                    (set k-dscope saved)
                    (x-module (get got) a b))))
          (else
           (let ((xs (k-resolve-items-ahead items)))
             (begin (set k-dscope saved) (x-module xs a b))))))))))))
