;;; The checker, in FX-26: the rules, each expression's type and effect.
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

;; The error that a `tagcase`, `x`, has no arm for the variants `rest`.
(define k-fail-no-arm (subr (maxeff checks spin) (k-parts kx) void)
  (lambda (rest x)
    (let ((names (k-join (k-part-names rest) ", ")))
      (k-fail-at (string-append "this `tagcase` has no arm for " names) x))))
;; Whether `t` is a list at `acyclic`: a pair's type, its region frozen and
;; never written.
(define k-acyclic-list? (subr (maxeff kreads spin) (int) bool)
  (lambda (t)
    (tagcase (k-get t)
      (ty-pair (a d r) (tagcase r (r-frozen (p finite) finite) (else y #f)))
      (else y #f))))
;; Note, for the compilers, that the call `x` of `f` (on parameters
;; `params`) is `apply` of a list at `acyclic`, which it need not copy: the
;; fact -500 (`c-fill-facts`). Every other `apply` copies its list, so that
;; the variadic procedure's is one nothing else can write.
(define k-note-apply-shares (subr (maxeff checks spin) (kx kx k-ids) unit)
  (lambda (x f params)
    (let ((apply? (tagcase f
                    (x-var (op a b) (and (k-std? op) (string=? (symbol->string op) "apply")))
                    (else y #f))))
      (if (and apply? (and (= (k-length params) 2) (k-acyclic-list? (car (cdr params)))))
          (set k-extracts (cons (product (1 (k-start x)) (2 (k-end x)) (3 -500)) (get k-extracts)))
          #u))))
;; Types, and the effect of all.
(define-type k-types-eff (productof (1 k-ids) (2 k-eff)))
;; What a call's arguments were found to be before they are checked: types (or -1), effects.
(define-type k-done (productof (1 (arrayof int @t)) (2 (arrayof k-eff @t))))
;; Type `t` and effect `e` of `x`, or `r`, both, with what `x` masks masked.
(define k-te-masked (subr (maxeff kstate spin) (kx int k-eff) k-te)
  (lambda (x t e) (k-te t (k-mask x e t))))
(define k-masked (subr (maxeff kstate spin) (kx k-te) k-te)
  (lambda (x r) (k-te-masked x (extract r 1) (extract r 2))))
;; `r`'s type onto `rest`'s types, and the effects of both.
(define k-te-onto (subr (maxeff kreads (alloc @t) spin) (k-te k-types-eff) k-types-eff)
  (lambda (r rest)
    (let ((ts (the k-ids (cons (extract r 1) (extract rest 1)))))
      (product (1 ts) (2 (k-union (extract r 2) (extract rest 2)))))))
;; The effect `r` says `x` has, once the type it says is found one `expected` takes.
(define k-as-expected (subr (maxeff checks spin) (kx k-te int) k-eff)
  (lambda (x r expected) (begin (k-expect x (extract r 1) expected) (extract r 2))))
;; A new `subr` type, of the default convention.
(define k-new-subr (subr (maxeff kstate spin) (k-eff k-ids int) int)
  (lambda (e ps res) (k-ty-new (ty-subr e ps res (get k-conv-default)))))
;; A `(nlist e k R)`, `R` the region `rg` made finite, and effect `eff`.
(define k-nlist-te (subr (maxeff kstate spin) (int k-size k-region k-eff) k-te)
  (lambda (e k rg eff) (k-te (k-ty-new (ty-nlist e k (k-fin-region rg))) eff)))
;; A fresh trail, for `k-unify`.
(define k-new-trail (subr (alloc @t) () k-trail) (lambda () (the k-trail (new nil))))
;; The region `r` names, bound as a variable of type `(place r)`.
(define k-bind-place (subr (maxeff kstate spin) (int) unit)
  (lambda (r) (k-bind (k-dvar-name r) (k-ty-new (ty-place (r-var r))))))
;; The form a `letregion` of kind `k` is written as.
(define k-region-form (subr pure (int) string)
  (lambda (k)
    (cond ((= k 0) "letregion") ((= k 1) "letrena") ((= k 2) "letreap") (else "letfreeze"))))
;; Note, for the compiler, that the `extract` at `a`..`b` takes part `i`.
(define k-note-extract (subr kstate (int int int) unit)
  (lambda (a b i) (set k-extracts (cons (product (1 a) (2 b) (3 i)) (get k-extracts)))))
;; `inner`, under binders `bs`, with `m` for them, each within its bound and finite if need be.
(define k-subst-checked (subr (maxeff checks spin) (k-binders k-map int int int) int)
  (lambda (bs m inner a b)
    (begin (k-check-bounds bs m a b) (k-check-finite-sizes bs m inner a b) (k-subst inner m))))
;; `inner`, under binders `bs`, projected with `ds`: an error where they do not fit, or knot.
(define k-projected (subr (maxeff checks spin) (k-binders (listof k-desc acyclic) int int int) int)
  (lambda (bs ds inner a b)
    (let ((inst (k-subst-checked bs (k-proj-map bs ds a b) inner a b)))
      (begin (k-no-knot inst a b) inst))))
;; An `if`'s type, its branches a `tc` and a `td`: the greater; an error if neither is.
(define k-join-branches (subr (maxeff checks spin) (int int int int) int)
  (lambda (tc td a b)
    (cond ((k-subtype tc td) td)
          ((k-subtype td tc) tc)
          ;; Naturals of sizes not shown equal: a `nat`.
          ((and (k-nat-ty? tc) (k-nat-ty? td)) (k-ty-new (ty-nat (sz-finite))))
          (else
           (k-fail (k-cat4 "the branches are a " (k-show-ty tc) " and a " (k-show-ty td)) a b)))))
;; If `p` is `(name v)`, `name` standard, the variable, as the binding it is
;; (none or one).
(define k-certifying-test (subr (maxeff kreads (alloc @t) spin) (kx string) k-named)
  (lambda (p name)
    (tagcase p
      (x-app (f args a b)
        (tagcase (k-under f)
          (x-var (op fa fb)
            (if (and (string=? (symbol->string op) name) (k-std? op) (k-sc-one-arg? args))
                (tagcase (car args)
                  (x-var (v va vb) (the k-named (cons (cons v (k-binding-depth v)) nil)))
                  (else y nil))
                nil))
          (else y nil)))
      (else y nil))))
;; If `p` is `(acyclic? v)`, the variable, as the binding it is (none or one).
(define k-acyclic-test (subr (maxeff kreads (alloc @t) spin) (kx) k-named)
  (lambda (p) (k-certifying-test p "acyclic?")))
;; If `p` is `(nat? v)`, the variable, as the binding it is (none or one).
(define k-nat-test (subr (maxeff kreads (alloc @t) spin) (kx) k-named)
  (lambda (p) (k-certifying-test p "nat?")))
;; What is certified so far: variables acyclic, of lengths, and natural.
(define-type k-certs (productof (1 k-named) (2 k-cert-lens) (3 k-named)))
(define k-certs-now (subr kreads () k-certs)
  (lambda ()
    (product (1 (get k-certified)) (2 (get k-certified-lengths)) (3 (get k-certified-nats)))))
;; Note what test `p` certifies, if anything: a variable acyclic, of a length, or natural.
(define k-push-certified (subr (maxeff kstate spin) (kx) unit)
  (lambda (p)
    (let ((cert (k-acyclic-test p)) (lens (k-length-test p)) (nats (k-nat-test p)))
      (begin
        (if (null? cert) #u (set k-certified (cons (car cert) (get k-certified))))
        (if (null? lens) #u (set k-certified-lengths (cons (car lens) (get k-certified-lengths))))
        (if (null? nats) #u (set k-certified-nats (cons (car nats) (get k-certified-nats))))))))
;; What checking an `if`'s branches puts back as it goes: what was certified, and the size
;; facts, before; and what its test shows when it holds, and when not.
(define-type k-tested (productof (1 k-certs) (2 k-fact-list) (3 k-branch-facts)))
;; Before the branch where `p` holds: what it certifies, and the facts it shows, in force.
(define k-enter-then (subr (maxeff kstate spin) (kx) k-tested)
  (lambda (p)
    (let* ((certs (k-certs-now))
           (pushed (k-push-certified p))
           (facts (k-test-facts p))
           (fsaved (get k-size-facts))
           (fyes (set k-size-facts (k-with-facts (car facts) fsaved))))
      (product (1 certs) (2 fsaved) (3 facts)))))
;; After it, before the branch where `p` does not: nothing certified, and what `p` shows so.
(define k-enter-else (subr kstate (k-tested) unit)
  (lambda (tested)
    (let ((certs (extract tested 1)) (fsaved (extract tested 2)))
      (begin
        (set k-certified (extract certs 1))
        (set k-certified-lengths (extract certs 2))
        (set k-certified-nats (extract certs 3))
        (set k-size-facts (k-with-facts (cdr (extract tested 3)) fsaved))))))
;; After both: the facts as they were.
(define k-leave-test (subr kstate (k-tested) unit) (lambda (t) (set k-size-facts (extract t 2))))
;; Whether `args` are one variable, as the binding it is, among `cs`.
(define k-certified-arg? (subr (maxeff kreads spin) (k-named kxs) bool)
  (lambda (cs args)
    (and (k-sc-one-arg? args)
         (tagcase (car args)
           (x-var (v va vb) (k-certified-has? cs v (k-binding-depth v)))
           (else y #f)))))
;; Whether `x` is a `lambda` of no parameters.
(define k-thunk-lambda? (subr (read @globals) (kx) bool)
  (lambda (x) (tagcase x (x-lambda (ps body a b) (null? ps)) (else y #f))))
;; Note argument `i` found to be a `t`, of effect `e`.
(define k-arg-found (subr kstate (k-done int int k-eff) unit)
  (lambda (done i t e) (begin (array-set! (extract done 1) i t) (array-set! (extract done 2) i e))))
;; Note argument `i` found to be what `r` says, and what that solves of its parameter's type `p`.
(define k-arg-unified (subr (maxeff kstate spin) (int k-binders k-solved k-done int k-te) unit)
  (lambda (p kinds solved done i r)
    (begin (k-unify p (extract r 1) kinds solved (k-new-trail))
           (k-arg-found done i (extract r 1) (extract r 2)))))
;; Variable `s`, of polymorphic type `t`, at `a`..`b`: `t` instantiated at
;; `p`, and the effect of naming `s`.
(define k-poly-instance (subr (maxeff checks spin) (symbol int int int int) k-te)
  (lambda (s t p a b) (k-te (k-instantiate-against t p a b) (k-naming-effect s t))))
;; `x`, if a variable of a polymorphic type (a standard `list`): its type
;; instantiated at `p`, and the effect of naming it; else none.
(define k-poly-var-at (subr (maxeff checks spin) (kx int) (listof k-te @t))
  (lambda (x p)
    (tagcase x
      (x-var (s a b)
        (let ((t (k-lookup s)))
          (if (and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #t) (else y #f)))
              (the (listof k-te @t) (cons (k-poly-instance s t p a b) nil))
              (the (listof k-te @t) nil))))
      (else y (the (listof k-te @t) nil)))))
;; Whether `et` is a `(nat z)` that natural literal `k` is one of.
(define k-literal-within? (subr kreads (k-ty int) bool)
  (lambda (et k) (tagcase et (ty-nat (z) (k-size-le? (k-size-lit k) z)) (else w #f))))
;; Whether `et` is a `nlist` of no elements, or of any number.
(define k-may-be-empty? (subr kreads (k-ty) bool)
  (lambda (et)
    (tagcase et
      (ty-nlist (e z r) (or (k-size-any? z) (k-size-eq? z (k-size-lit 0))))
      (else w #f))))
;; A `tagcase`'s type, its arms of `types`: `expected` if given (≥ 0), or the least they all are.
(define k-arms-type (subr (maxeff checks spin) (kx k-ids int) int)
  (lambda (x types expected)
    (if (>= expected 0)
        expected
        (let ((found (k-upper-bound types types)))
          (if (< found 0)
              (k-fail-at (string-append "the arms are " (k-join (k-show-list types nil) ", ")) x)
              found)))))
;; The region a place of type `t` is at; an error at `a`..`b` if `t` is not a place.
(define k-place-region (subr (maxeff checks spin) (int int int) k-region)
  (lambda (t a b)
    (tagcase (k-get t)
      (ty-place (r) r)
      (else y (k-fail-ty "a region is expected here, and this is a " t a b)))))
;; A type, or none: none or one.
(define-type k-maybe-ty (listof k-ty acyclic))
;; What a `make-bloblet` of `fields`, checked against `expected` (≥ 0), is told: that type, if a
;; bloblet not frozen, of as many fields, at the region `given` (if any).
(define k-bloblet-want (subr (maxeff kreads (alloc @t) spin) (int kxs k-regions) k-maybe-ty)
  (lambda (expected fields given)
    (if (< expected 0)
        nil
        (tagcase (k-get expected)
          (ty-bloblet (fs z r)
            (if (and (not z) (= (k-length fs) (k-length fields))
                     (or (null? given) (k-region=? r (car given))))
                (cons (k-get expected) nil)
                nil))
          (else y nil)))))
;; Field `i`'s type, of a bloblet of type `bt` whose fields are `fields`; an error if none.
(define k-bloblet-field (subr (maxeff checks spin) (int k-ids int int int) int)
  (lambda (bt fields i a b)
    (if (< i (k-length fields))
        (k-nth fields i)
        (let ((last (- (k-length fields) 1)))
          (k-fail (k-cat5 "a " (k-show-ty bt) " has no field " (int->string i)
                          (string-append ": its fields are 0 to " (int->string last))) a b)))))
;; Type `t` and effect `e`, with `region` read, or written.
(define k-te-reading (subr (maxeff kreads (alloc @t) spin) (int k-region k-eff) k-te)
  (lambda (t region e) (k-te t (k-insert (a-read region) e))))
(define k-te-writing (subr (maxeff kreads (alloc @t) spin) (int k-region k-eff) k-te)
  (lambda (t region e) (k-te t (k-insert (a-write region) e))))
;; Whether a handler that is a `c` takes a `payload` to an `answer`.
(define k-handles? (subr (maxeff kstate spin) (k-callable int int) bool)
  (lambda (c payload answer)
    (let ((ps (extract c 2)))
      (and (= (k-length ps) 1) (k-subtype payload (car ps)) (k-subtype (extract c 3) answer)))))
;; What a handler of type `ht` is called as, taking a `payload` to an `answer`; or an error.
(define k-handler-callable (subr (maxeff checks spin) (kx int int int) k-callable)
  (lambda (handler ht payload answer)
    (let ((c (k-as-subr ht)))
      (cond ((null? c) (k-fail-ty-at "a handler is a subroutine, not a " ht handler))
            ((k-handles? (car c) payload answer) (car c))
            (else
             (let ((wants (k-handler-wants payload answer)))
               (k-fail-at (k-cat4 wants "; it is a " (k-show-ty ht) "") handler)))))))

;; `module` and `with`, `check-module-rules.fx`'s, which sets this.
(define k-module-rules (ref (subr (maxeff checks spin) (kx) k-te) @t)
  (new (lambda (x) (k-fail-at "a module" x))))
;;; ------------------------------------------------------------ the rules
(define-rec
  (k-synth (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (let* ((r (k-synth-node x)) (e (k-frozen x (extract r 2))))
        (begin (k-note-effect x e) (k-te (extract r 1) e)))))
  (k-synth-node (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (tagcase x
        (x-var (s a b)
          (let ((t (k-lookup s)))
            (if (< t 0) (k-fail (k-unbound s) a b) (k-te t (k-naming-effect s t)))))
        (x-const (t v a b) (k-te t nil))
        (x-lambda (ps body a b) (k-synth-lambda-as x nil -1))
        (x-app (f args a b) (k-synth-app x f args -1))
        (x-the (t0 e a b) (let ((t (k-resolve-selects t0 a b))) (k-te t (k-check e t))))
        (x-convention (c e a b)
          (let* ((r (k-synth e)) (t (k-resolve (extract r 1))))
            (tagcase (k-get t)
              (ty-subr (fe ps res from)
                (begin (if (k-conv=? from c) #u (k-convert-at x t c))
                       (k-te (k-ty-new (ty-subr fe ps res c)) (extract r 2))))
              (else y (k-fail-ty "`convention` takes a procedure, and this is a " t a b)))))
        (x-plambda (bs body a b)
          (let ((r (k-synth body)))
            (if (k-generalizable? body (extract r 2))
                (k-te (k-ty-new (ty-poly bs (extract r 1))) (extract r 2))
                (k-fail-impure-plambda (extract r 2) a b))))
        (x-rlambda (r l a b) (k-synth-rlambda x r l -1))
        (x-proj (body ds a b)
          (let* ((r (k-synth body)) (t (extract r 1)))
            (tagcase (k-get t)
              (ty-poly (bs inner)
                (if (not (= (k-length bs) (k-length ds)))
                    (k-fail (k-proj-count-error bs ds) a b)
                    (let ((result (k-projected bs ds inner a b)))
                      (k-te-masked x result (extract r 2)))))
              (else y (k-fail-ty "`proj` needs a polymorphic value, not a " t a b)))))
        (x-if (p c d a b)
          (let ((rp (k-synth p)))
            (if (not (k-subtype (extract rp 1) k-bool))
                (k-fail "an `if` test must be a bool" (k-start p) (k-end p))
                (let* ((tested (k-enter-then p))
                       (rc (k-synth c))
                       (between (k-enter-else tested))
                       (rd (k-synth d))
                       (left (k-leave-test tested))
                       (t (k-join-branches (extract rc 1) (extract rd 1) a b))
                       (e (k-union (extract rp 2) (k-union (extract rc 2) (extract rd 2)))))
                  (k-te-masked x t e)))))
        (x-letrec (bs0 body a b)
          (let ((saved (k-mark)) (rsaved (get k-recursive)) (bs (k-letrec-selected bs0 a b)))
            (begin
              ;; A group whose every run ends needs no `spin`.
              (k-bind-group bs)
              ;; The body's calls of the group are not recursion.
              (let* ((ie (k-letrec-checked bs saved rsaved k-check k-check-letrec))
                     (restored (set k-recursive rsaved))
                     (rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (k-te-masked x (extract rb 1) (k-union ie (extract rb 2))))))))
        (x-let (bs body a b)
          (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
            (begin
              (k-bind-named (extract inits 1))
              (k-note-let-lambdas bs)
              (let ((rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (let ((t (k-forget-nats named (extract rb 1) a b)))
                    (k-te-masked x t (k-union (extract inits 2) (extract rb 2)))))))))
        (x-prompt (t body h a b) (k-synth-prompt x t body h))
        ;; The region's name is a variable too, of type `(place r)`, when
        ;; the form makes a place.
        (x-letregion (k r i body a b)
          (let* ((saved (k-mark))
                 (bound (if (or (= k 0) (= k 3)) #u (k-bind-place r)))
                 (freezing (get k-freezing))
                 (pushed (if (= k 3) (set k-freezing (cons r freezing)) #u))
                 (rb (k-synth body))
                 (rt (extract rb 1))
                 (written (k-has-id? (get k-written) r))
                 (popped (set k-freezing freezing)))
            (begin
              (k-unbind-to saved)
              (let ((t (if (= k 3) (k-frozen-result r i written rt a b) rt)))
                (k-close-region x (k-region-form k) r t (extract rb 2) a b)))))
        (x-bloblet (op i args a b) (k-synth-bloblet x op i args -1))
        (x-product (fs a b)
          (let* ((r (k-synth-fields fs)) (t (k-ty-new (ty-product (extract r 1)))))
            (k-te-masked x t (extract r 2))))
        (x-extract (e l a b)
          (let* ((r (k-synth e)) (pt (extract r 1)))
            (tagcase (k-get pt)
              (ty-product (fs)
                (let ((t (k-part-find fs l)))
                  (if (< t 0)
                      (k-fail-no-part pt " has no " l a b)
                      (begin (k-note-extract a b (k-part-index fs l 0))
                             (k-te-masked x t (extract r 2))))))
              (else y (k-fail-ty-at "a product is expected here, and this is a " pt e)))))
        (x-sum (l e a b)
          (let* ((r (k-synth e))
                 (t (k-ty-new (ty-sum (cons (product (1 l) (2 (extract r 1))) nil)))))
            (k-te-masked x t (extract r 2))))
        (x-tagcase (s arms els a b) (k-synth-tagcase x s arms els -1))
        (x-begin (xs a b) (k-masked x (k-synth-seq xs k-unit nil)))
        (x-module (items a b) ((get k-module-rules) x))
        (x-with (m body a b) ((get k-module-rules) x)))))
  (k-synth-seq (subr (maxeff checks spin) (kxs int k-eff) k-te)
    (lambda (xs last e)
      (if (null? xs)
          (k-te last e)
          (let ((r (k-synth (car xs))))
            (k-synth-seq (cdr xs) (extract r 1) (k-union e (extract r 2)))))))
  (k-synth-fields (subr (maxeff checks spin) (k-let-bs) (productof (1 k-parts) (2 k-eff)))
    (lambda (fs)
      (if (null? fs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car fs) 2))) (rest (k-synth-fields (cdr fs)))
                 (part (product (1 (extract (car fs) 1)) (2 (extract r 1)))))
            (product (1 (cons part (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-synth-lets (subr (maxeff checks spin) (k-let-bs) (productof (1 k-bindings) (2 k-eff)))
    (lambda (bs)
      (if (null? bs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car bs) 2))) (rest (k-synth-lets (cdr bs))))
            (product (1 (cons (cons (extract (car bs) 1) (extract r 1)) (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-check-letrec (subr (maxeff checks spin) (k-letrec-bs) k-eff)
    (lambda (bs)
      (if (null? bs)
          nil
          (let* ((n (extract (car bs) 1)) (t (extract (car bs) 2)) (init (extract (car bs) 3))
                 ;; Only lambdas: then nothing runs before every binding
                 ;; exists, and no one sees the knot tied.
                 (e (if (k-lambda? init) (k-check-declared n t init) (k-fail-not-lambda n init)))
                 (rest (k-check-letrec (cdr bs))))
            (k-union e rest)))))
  ;; Check `init` against `t`, the type `n` is declared; an error at `init`
  ;; itself says so.
  (k-check-declared (subr (maxeff checks spin) (symbol int kx) k-eff)
    (lambda (n t init)
      (let ((r (k-declaring (lambda () (k-te t (k-check init t))) (k-start init) (k-end init) n t)))
        (extract r 2))))
  ;;; ------------------------------------------------------------ lambda

  ;; A `lambda`'s type. `hint` supplies the types of parameters the program
  ;; left out; `result`, when not -1, is what the body is checked against.
  (k-synth-lambda-as (subr (maxeff checks spin) (kx k-ids int) k-te)
    (lambda (x hint result)
      (tagcase x
        (x-lambda (ps body a b)
          (let* ((given (k-param-types ps hint a b))
                 (saved (k-mark))
                 (named (get k-skolems))
                 ;; Bound in order, a dependent procedure's (`check-modules.fx`).
                 (dep (k-bind-params given a b))
                 (typed (extract dep 1))
                 (want (if (>= result 0) (k-instantiate-params result (extract dep 2)) -1)))
            (let* ((r (if (>= want 0)
                          (k-te-masked body want (k-check body want))
                          (k-masked body (k-synth body)))))
              (begin
                (k-unbind-to saved)
                (set k-last-latent (extract r 2))
                (let ((res (k-forget-nats named (k-result-back (extract r 1) (extract dep 3)) a b)))
                  (k-te (k-new-subr (extract r 2) (k-binding-types typed) res) nil))))))
        (else y (k-fail-at "a lambda" x)))))
  ;; An `rlambda`'s type: its `lambda`'s, told `expected`'s parameter and
  ;; result types if it is a subroutine's, with `(read R)` in its latent
  ;; effect, since calling it reads the closure; making it allocates in `R`,
  ;; the region `r` names.
  (k-synth-rlambda (subr (maxeff checks spin) (kx kx kx int) k-te)
    (lambda (x r l expected)
      (let* ((rr (k-synth r))
             (rt (extract rr 1))
             (g (k-place-region rt (k-start r) (k-end r)))
             (c (if (< expected 0) (the (listof k-callable acyclic) nil) (k-as-subr expected)))
             (n (tagcase l (x-lambda (ps body a b) (k-length ps)) (else y 0)))
             (lt (cond
                   ((null? c) (k-synth-lambda-as l nil -1))
                   ((not (= (k-length (extract (car c) 2)) n))
                    (k-fail-arity (k-length (extract (car c) 2)) "rlambda" n (k-start x) (k-end x)))
                   (else (k-synth-lambda-as l (extract (car c) 2) (extract (car c) 3)))))
             (t (tagcase (k-get (extract lt 1))
                  (ty-subr (e ps res cv) (k-ty-new (ty-subr (k-insert (a-read g) e) ps res cv)))
                  (else y (k-fail-at "a lambda" x))))
             (e (k-insert (a-alloc g) (extract rr 2))))
        (k-te-masked x t e))))
  ;;; ------------------------------------------------------------ application
  (k-synth-app (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let ((op (tagcase f
                  (x-var (op fa fb) (if (k-std? op) (symbol->string op) ""))
                  (else y ""))))
        (cond ((string=? op "certify-acyclic") (k-certify x args))
              ((string=? op "certify-length") (k-certify-length x args))
              ((string=? op "certify-nat") (k-certify-nat x args))
              ((and (k-op-either? op "+" "-") (k-sc-two? args)) (k-nat-arith x op args))
              ((string=? op "cons")
               (let ((r (k-nlist-cons x args expected)))
                 (if (null? r) (k-synth-app-plain x f args expected) (car r))))
              (else (k-synth-app-plain x f args expected))))))
  ;; `+` and `-` of naturals: a natural, of a size when both are known. Only
  ;; what has a type of its own is asked for it; anything else is told it
  ;; is an int, as for any call.
  (k-nat-arith (subr (maxeff checks spin) (kx string kxs) k-te)
    (lambda (x op args)
      (let* ((ra (k-nat-operand (car args)))
             (rb (k-nat-operand (car (cdr args))))
             (za (extract ra 2)) (zb (extract rb 2))
             (sz (k-nat-arith-size op za zb))
             (t (if (null? sz) k-int (k-ty-new (ty-nat (car sz))))))
        (k-te t (k-union (extract ra 1) (extract rb 1))))))
  (k-nat-operand (subr (maxeff checks spin) (kx) (productof (1 k-eff) (2 k-maybe-size)))
    (lambda (x)
      (if (not (k-natural-by-itself? x))
          (product (1 (k-check x k-int)) (2 (the k-maybe-size nil)))
          (let* ((r (k-synth x)) (t (extract r 1)))
            (begin (k-expect x t k-int) (product (1 (extract r 2)) (2 (k-operand-size x t))))))))
  ;; `(certify-length v k)`: `v`'s value as a `(nlist T k)`, where `length-is?`
  ;; has just found it so; nowhere else.
  (k-certify-length (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (let* ((none (the k-cert-lens nil))
             (found (if (k-sc-two? args) (k-length-arg (car args) (car (cdr args))) none))
             (ok (and (not (null? found)) (k-cert-len-has? (get k-certified-lengths) (car found)))))
        (if (not ok)
            (k-fail-at (string-append "`certify-length` takes only a variable and a length "
                                      "`length-is?` has just confirmed")
                       x)
            (let* ((r (k-synth (car args))) (t (k-resolve (extract r 1)))
                   (k (extract (car found) 3)))
              (tagcase (k-get t)
                (ty-pair (e tail rg)
                  (if (and (= (k-resolve tail) t) (tagcase rg (r-frozen (p f) #t) (else y #f)))
                      (k-nlist-te e k rg (extract r 2))
                      (k-fail-not-frozen t x)))
                (ty-nlist (e z rg) (k-nlist-te e k rg (extract r 2)))
                (else y (k-fail-not-frozen t x))))))))
  ;; `cons` onto a `nlist`: one more element. Where a `nlist` is expected, the
  ;; tail is checked as one shorter; otherwise, a tail that is a variable of
  ;; `nlist` type gives a `nlist` one longer. None if neither.
  (k-nlist-cons (subr (maxeff checks spin) (kx kxs int) (listof k-te acyclic))
    (lambda (x args expected)
      (if (not (k-sc-two? args))
          nil
          (let ((hd (car args)) (tl (car (cdr args))))
            (let ((want (if (< expected 0) (ty-void) (k-get expected))))
              (tagcase want
                (ty-nlist (e z r)
                  (if (not (or (k-size-any? z) (k-size-nonneg? (k-size-plus z -1))))
                      (k-nlist-cons-tail hd tl)
                      (let* ((tail-ty (k-ty-new (ty-nlist e (k-size-plus z -1) r)))
                             (xe (k-check hd e))
                             (te (k-check tl tail-ty)))
                        (the (listof k-te acyclic) (cons (k-te expected (k-union xe te)) nil)))))
                (else y (k-nlist-cons-tail hd tl))))))))
  (k-nlist-cons-tail (subr (maxeff checks spin) (kx kx) (listof k-te acyclic))
    (lambda (hd tl)
      (tagcase tl
        (x-var (v va vb)
          (let ((t (k-lookup v)))
            (if (< t 0)
                nil
                (tagcase (k-get t)
                  (ty-nlist (e z r)
                    (let* ((xe (k-check hd e)) (rt (k-synth tl))
                           (longer (k-ty-new (ty-nlist e (k-size-plus z 1) r)))
                           (e (k-union xe (extract rt 2))))
                      (the (listof k-te acyclic) (cons (k-te longer e) nil))))
                  (else y nil)))))
        (else y nil))))
  ;; `(certify-nat v)`: `v`'s value as a `nat`, where `nat?` has just found
  ;; `v` no less than 0; nowhere else.
  (k-certify-nat (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (if (not (k-certified-arg? (get k-certified-nats) args))
          (k-fail-at "`certify-nat` takes only a variable `nat?` has just found no less than 0" x)
          (let ((r (k-synth (car args))))
            (begin (k-expect (car args) (extract r 1) k-int)
                   (k-te (k-ty-new (ty-nat (sz-finite))) (extract r 2)))))))
  ;; `(certify-acyclic v)`: `v`'s value at `acyclic`, where `acyclic?` has
  ;; just found `v` acyclic; nowhere else.
  (k-certify (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (if (not (k-certified-arg? (get k-certified) args))
          (k-fail-at "`certify-acyclic` takes only a variable `acyclic?` has just found acyclic" x)
          (let* ((r (k-synth (car args))) (t (extract r 1)))
            (if (k-is-data? t) (k-te (k-finitized t) (extract r 2)) (k-fail-not-data t x))))))
  (k-synth-app-plain (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let* ((a (k-start x)) (b (k-end x))
             (rf (k-synth f))
             (n (k-length args))
             (done (product (1 (the (arrayof int @t) (make-array n -1)))
                            (2 (the (arrayof k-eff @t) (make-array n nil)))))
             (ft (tagcase (k-get (extract rf 1))
                   (ty-poly (bs body)
                     (let ((inst (k-instantiate (extract rf 1) args expected a b done)))
                       (begin (k-no-knot inst a b) inst)))
                   (else y (extract rf 1))))
             (callee (k-dependent-callee (k-as-subr ft) args a b))
             (variadic (k-vsubr-parts ft)))
        (cond
          ;; Any number of arguments, each of the element type.
          ((not (null? variadic))
           (let ((v (car variadic)))
             (k-app-result x f ft args (k-vapp-args args (extract v 2) 0 (extract rf 2))
                           (extract v 1) (extract v 3))))
          ((null? callee) (k-fail-ty "not a subroutine: " ft a b))
          ((not (= (k-length (extract (car callee) 2)) n))
           (k-fail-arg-count (k-length (extract (car callee) 2)) n a b))
          (else
           (let* ((c (car callee))
                  (e (k-app-args args (extract c 2) 0 done (extract rf 2))))
             (begin
               (k-note-apply-shares x f (extract c 2))
               (k-app-result x f ft args e (extract c 1) (extract c 3)))))))))
  ;; A call's type and effect, once its arguments have effect `e`: its
  ;; callee's latent effect too, `spin` where the call may loop, and what
  ;; the call masks; its result, of type `result`.
  (k-app-result (subr (maxeff checks spin) (kx kx int kxs k-eff k-eff int) k-te)
    (lambda (x f ft args e latent result)
      (let* ((e (k-union e latent))
             (e (if (k-may-spin? f ft args) (k-insert (a-spin) e) e)))
        (k-te-masked x result e))))
  (k-app-args (subr (maxeff checks spin) (kxs k-ids int k-done k-eff) k-eff)
    (lambda (args params i done e)
      (if (null? args)
          e
          (let* ((t (array-ref (extract done 1) i))
                 (ae (k-app-arg (car args) (car params) i t (array-ref (extract done 2) i))))
            (k-app-args (cdr args) (cdr params) (+ i 1) done (k-union e ae))))))
  ;; Argument `i`, `arg`, for a parameter of type `p`: its effect. Where it was found a `t` (≥ 0)
  ;; of effect `e`, that, converted if need be; checked against `p` where not.
  (k-app-arg (subr (maxeff checks spin) (kx int int int k-eff) k-eff)
    (lambda (arg p i t e)
      (cond ((< t 0) (k-check-argument arg p i))
            ((k-subtype t p) e)
            (else
             (let ((c (k-conversion t p)))
               (if (null? c)
                   (k-fail-at (k-argument-error i (k-show-ty t) (k-show-ty p)) arg)
                   (begin (k-convert-at arg t (car c)) e)))))))
  ;; A `vsubr` call's arguments, each checked as its element type `t`.
  (k-vapp-args (subr (maxeff checks spin) (kxs int int k-eff) k-eff)
    (lambda (args t i e)
      (if (null? args)
          e
          (k-vapp-args (cdr args) t (+ i 1) (k-union e (k-check-argument (car args) t i))))))
  ;; An argument that failed to check is reported as that argument.
  (k-check-argument (subr (maxeff checks spin) (kx int int) k-eff)
    (lambda (arg p i)
      (let ((r (k-rewriting (lambda () (k-te p (k-check arg p))) (k-start arg) (k-end arg)
                            (lambda (m want got) (k-argument-error i got want)))))
        (extract r 2))))
  (k-instantiate (subr (maxeff checks spin) (int kxs int int int k-done) int)
    (lambda (ft args expected a b done)
      (let* ((bo (k-binders-of ft)) (kinds (extract bo 1)) (inner (extract bo 2))
             (callee (k-callee-of inner (k-length args))))
        (if (null? callee)
            (k-fail-ty "not a subroutine, even once projected: " ft a b)
            (let ((params (extract (car callee) 2)) (result (extract (car callee) 3))
                  (solved (the k-solved (new nil))))
              (if (not (= (k-length params) (k-length args)))
                  (k-fail-arg-count (k-length params) (k-length args) a b)
                  (begin
                    (if (>= expected 0) (k-unify result expected kinds solved (k-new-trail)) #u)
                    (k-inst-asked args params 0 kinds solved done)
                    ;; A shape conflict is the error to report, before any
                    ;; binder is found unsolved (`TODO.md` §20).
                    (k-result-shape expected result kinds solved a b)
                    (k-inst-shapes args params 0 kinds solved (extract done 1))
                    (k-inst-told args params 0 kinds solved done)
                    (k-inst-shapes args params 0 kinds solved (extract done 1))
                    (k-default-regions kinds solved)
                    (k-subst-checked kinds (k-finish kinds solved a b ft) inner a b))))))))
  ;; What the arguments are, except the ones that need to be told.
  (k-inst-asked (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved k-done) unit)
    (lambda (args params i kinds solved done)
      (if (null? args)
          #u
          (begin
            (if (k-needs-telling? (car args))
                #u
                (let ((p (k-subst (car params) (get solved))))
                  (if (not (k-mentions-any-unknown? p kinds solved))
                      (k-arg-found done i p (k-check (car args) p))
                      (let ((r (k-synth (car args))))
                        (tagcase (k-get (extract r 1))
                          (ty-poly (bs body) #u)
                          (else y (k-arg-unified (car params) kinds solved done i r)))))))
            (k-inst-asked (cdr args) (cdr params) (+ i 1) kinds solved done)))))
  ;; The arguments that needed telling: each is checked against its parameter
  ;; as solved so far, and what it turns out to be solves more.
  (k-inst-told (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved k-done) unit)
    (lambda (args params i kinds solved done)
      (if (null? args)
          #u
          (begin
            (if (>= (array-ref (extract done 1) i) 0)
                #u
                (let* ((arg (car args))
                       (defaulted (k-default-regions kinds solved))
                       (p (k-subst (car params) (get solved))))
                  (cond
                    ;; A thunk has no parameters to be told: told nothing, it
                    ;; says what it is, as any argument does.
                    ((and (k-needs-telling? arg) (null? (k-as-subr p)) (k-thunk-lambda? arg))
                     (k-arg-unified (car params) kinds solved done i (k-synth arg)))
                    ((k-needs-telling? arg)
                     (let ((c (k-as-subr p)))
                       (if (or (null? c) (k-any-unknown-type? (extract (car c) 2) kinds solved))
                           (k-fail-not-known arg i p)
                           (let* ((res (extract (car c) 3))
                                  (known (if (k-mentions-unknown-type? res kinds solved) -1 res))
                                  (r (k-synth-lambda-as arg (extract (car c) 2) known)))
                             (k-arg-unified (car params) kinds solved done i r)))))
                    ((k-mentions-unknown-type? p kinds solved) (k-fail-not-known arg i p))
                    ;; A variable of a polymorphic type: instantiated at the
                    ;; parameter, and what it turns out to be solves more
                    ;; (`(apply list xs)`: `apply`'s effect).
                    (else
                     (let ((pv (k-poly-var-at arg p)))
                       (if (null? pv)
                           (k-arg-found done i p (k-check arg p))
                           (k-arg-unified (car params) kinds solved done i (car pv))))))))
            (k-inst-told (cdr args) (cdr params) (+ i 1) kinds solved done)))))
  ;;; ------------------------------------------------------------ check mode
  (k-check (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let ((e (k-frozen x (k-check-mode x expected))))
        (begin (k-note-effect x e) e))))
  (k-check-mode (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let* ((et (k-get expected))
             (poly? (tagcase et (ty-poly (bs body) #t) (else y #f)))
             (plambda? (tagcase x (x-plambda (bs body a b) #t) (else y #f)))
             ;; A `let` passes a `poly` to its body, and must then be pure.
             (let? (tagcase x (x-let (bs body a b) #t) (else y #f))))
        (cond
          ((and poly? let?)
           (let ((e (k-check-node x expected et)))
             (if (k-generalizable? x e)
                 e
                 (k-fail-effect "a polymorphic value must be pure, and this has " e
                                (k-start x) (k-end x)))))
          ((and poly? (not plambda?))
           (tagcase et
             (ty-poly (bs body)
               (let ((e (k-check x body)))
                 (if (k-generalizable? x e)
                     e
                     (k-fail-effect "a polymorphic value must be pure, and this has " e
                                    (k-start x) (k-end x)))))
             (else y nil)))
          ((and poly? plambda? (k-plambda-matches? x et))
           (tagcase x
             (x-plambda (binders body a b)
               (tagcase et
                 (ty-poly (bs want)
                   (let* ((want (k-subst want (k-rename bs binders))) (e (k-check body want)))
                     (if (k-generalizable? body e) e (k-fail-impure-plambda e a b))))
                 (else y nil)))
             (else y nil)))
          (else (k-check-node x expected et))))))
  (k-check-node (subr (maxeff checks spin) (kx int k-ty) k-eff)
    (lambda (x expected et)
      (letrec ((otherwise (subr (maxeff (read @globals) checks spin) () k-eff)
                           (lambda () (k-as-expected x (k-synth x) expected))))
       (the k-eff (let ((a (k-start x)) (b (k-end x)))
        (tagcase x
          (x-lambda (ps body xa xb)
            (let ((c (k-as-subr expected)))
              (cond
                ((not (null? c))
                 (let ((want (extract (car c) 2)))
                   (if (not (= (k-length want) (k-length ps)))
                       (k-fail-arity (k-length want) "lambda" (k-length ps) a b)
                       (k-as-expected x (k-synth-lambda-as x want (extract (car c) 3)) expected))))
                ((k-some-untyped? ps) (k-fail-ty "a `lambda` cannot be a " expected a b))
                (else (otherwise)))))
          (x-rlambda (r l xa xb)
            (if (null? (k-as-subr expected))
                (otherwise)
                (k-as-expected x (k-synth-rlambda x r l expected) expected)))
          (x-app (f args xa xb) (k-as-expected x (k-synth-app x f args expected) expected))
          (x-bloblet (op i args xa xb)
            (k-as-expected x (k-synth-bloblet x op i args expected) expected))
          (x-tagcase (s arms els xa xb) (extract (k-synth-tagcase x s arms els expected) 2))
          (x-product (fs xa xb)
            (tagcase et
              (ty-product (want)
                (if (k-same-labels? fs want)
                    (k-mask x (k-check-fields fs want) expected)
                    (otherwise)))
              (else y (otherwise))))
          (x-sum (l e xa xb)
            (tagcase et
              (ty-sum (vs)
                (let ((t (k-part-find vs l)))
                  (if (>= t 0) (k-mask x (k-check e t) expected) (otherwise))))
              (else y (otherwise))))
          ;; A natural literal is a `nat`, and a `(nat k)`.
          (x-const (ty k xa xb)
            (if (and (= ty k-int) (>= k 0) (k-literal-within? et k))
                nil
                (otherwise)))
          (x-var (s xa xb)
            (let ((t (k-lookup s)))
              (cond
               ;; `nil` is a `nlist` of no elements, or of some.
               ((and (string=? (symbol->string s) "nil") (>= t 0) (k-named-has? (get k-std) s t)
                     (k-may-be-empty? et))
                nil)
               ((and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #t) (else y #f)))
                (let ((inst (k-instantiate-against t expected a b)))
                  (begin (k-expect x inst expected) (k-naming-effect s t))))
               (else (otherwise)))))
          (x-if (p c d xa xb)
            (let* ((pe (k-check p k-bool))
                   (tested (k-enter-then p))
                   (ce (k-check c expected))
                   (between (k-enter-else tested))
                   (de (k-check d expected))
                   (left (k-leave-test tested)))
              (k-mask x (k-union pe (k-union ce de)) expected)))
          (x-begin (xs xa xb)
            (let ((e (k-check-seq xs expected nil)))
              (k-mask x e expected)))
          ;; A `letrec`'s body, as a `let`'s, against what is expected.
          (x-letrec (bs0 body xa xb)
            (let ((saved (k-mark)) (rsaved (get k-recursive)) (bs (k-letrec-selected bs0 a b)))
              (begin
                (k-bind-group bs)
                (let* ((ie (k-letrec-checked bs saved rsaved k-check k-check-letrec))
                       (restored (set k-recursive rsaved))
                       (e (k-check body expected)))
                  (begin (k-unbind-to saved) (k-mask x (k-union ie e) expected))))))
          (x-let (bs body xa xb)
            (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
              (begin
                (k-bind-named (extract inits 1))
                (k-note-let-lambdas bs)
                (let ((e (k-check body expected)))
                  (begin (k-unbind-to saved)
                         (set k-skolems named)
                         (k-mask x (k-union (extract inits 2) e) expected))))))
          (else y (otherwise))))))))
  (k-check-seq (subr (maxeff checks spin) (kxs int k-eff) k-eff)
    (lambda (xs expected e)
      (if (null? (cdr xs))
          (k-union e (k-check (car xs) expected))
          (let ((r (k-synth (car xs))))
            (k-check-seq (cdr xs) expected (k-union e (extract r 2)))))))
  (k-check-fields (subr (maxeff checks spin) (k-let-bs k-parts) k-eff)
    (lambda (fs ps)
      (if (null? fs)
          nil
          (let* ((e (k-check (extract (car fs) 2) (extract (car ps) 2)))
                 (rest (k-check-fields (cdr fs) (cdr ps))))
            (k-union e rest)))))
  ;; `body`'s type and effect: checked against `expected` if that is given (≥ 0), found if not.
  (k-synth-as (subr (maxeff checks spin) (kx int) k-te)
    (lambda (body expected)
      (if (>= expected 0) (k-te expected (k-check body expected)) (k-synth body))))
  (k-synth-tagcase (subr (maxeff checks spin) (kx kx k-arms k-let-bs int) k-te)
    (lambda (x s arms els expected)
      (let* ((rs (k-synth s)) (st (extract rs 1)))
        (tagcase (k-get st)
          (ty-sum (variants)
            (let* ((arm-results (k-tagcase-arms arms variants st expected))
                   (rest (k-variants-not-named variants arms))
                   (e (k-union (extract rs 2) (extract arm-results 2)))
                   (armed (product (1 (extract arm-results 1)) (2 e)))
                   (both (k-tagcase-else x armed rest els expected))
                   (t (k-arms-type x (extract both 1) expected)))
              (k-te-masked x t (extract both 2))))
          (else y (k-fail-ty-at "a sum is expected here, and this is a " st s))))))
  ;; A `tagcase`'s arms' types and effect, `armed`, with its `else`, `els`, if any, for the
  ;; variants `rest` not named; an error at `x` if it has none, and some are not named.
  (k-tagcase-else (subr (maxeff checks spin) (kx k-types-eff k-parts k-let-bs int) k-types-eff)
    (lambda (x armed rest els expected)
      (if (null? els)
          (if (null? rest) armed (k-fail-no-arm rest x))
          (let* ((y (extract (car els) 1)) (body (extract (car els) 2))
                 (rest-ty (k-ty-new (ty-sum rest)))
                 (r (k-in-scope-check y rest-ty body expected)))
            (product (1 (k-push-ids (extract armed 1) (cons (extract r 1) nil)))
                     (2 (k-union (extract armed 2) (extract r 2))))))))
  ;; Each arm: its type and the effects of all.
  (k-tagcase-arms (subr (maxeff checks spin) (k-arms k-parts int int) k-types-eff)
    (lambda (arms variants st expected)
      (if (null? arms)
          (product (1 nil) (2 nil))
          (let* ((arm (car arms)) (tag (extract arm 1)) (body (extract arm 4))
                 (t (k-part-find variants tag)))
            (if (< t 0)
                (k-fail-no-part st " has no tag " tag (k-start body) (k-end body))
                (let* ((bound (if (extract arm 2)
                                  (tagcase (k-get t)
                                    (ty-product (fs)
                                      (if (= (k-length fs) (k-length (extract arm 3)))
                                          (k-zip-fields (extract arm 3) fs)
                                          (k-cannot-take-apart tag t (extract arm 3) body)))
                                    (else y (k-cannot-take-apart tag t (extract arm 3) body)))
                                  (the k-bindings (cons (cons (car (extract arm 3)) t) nil))))
                       (saved (k-mark))
                       (r (begin
                            (k-bind-all bound)
                            (k-synth-as body expected)))
                       (restored (k-unbind-to saved))
                       (rest (k-tagcase-arms (cdr arms) variants st expected)))
                  (k-te-onto r rest)))))))
  (k-in-scope-check (subr (maxeff checks spin) (symbol int kx int) k-te)
    (lambda (y t body expected)
      (let ((saved (k-mark)))
        (begin
          (k-bind y t)
          (let ((r (k-synth-as body expected)))
            (begin (k-unbind-to saved) r))))))
  ;;; ------------------------------------------------------------ bloblets
  (k-synth-bloblet (subr (maxeff checks spin) (kx symbol int kxs int) k-te)
    (lambda (x op i args expected)
      (let ((name (symbol->string op)))
        (if (k-op-either? name "make-bloblet" "rmake-bloblet")
            ;; `rmake-bloblet`'s region is its first operand's; `make-bloblet`'s
            ;; the type it is checked against, or a fresh one.
            (k-make-bloblet x (string=? name "rmake-bloblet") args expected)
            (k-bloblet-op x name i args)))))
  ;; `(make-bloblet n f …)`, or, if `rm`, `(rmake-bloblet r n f …)`.
  (k-make-bloblet (subr (maxeff checks spin) (kx bool kxs int) k-te)
    (lambda (x rm args expected)
      (let* ((a (k-start x)) (b (k-end x))
             (gr (if rm (k-synth (car args)) (k-te k-unit (the k-eff nil))))
             (given (the k-regions (if rm (cons (k-place-region (extract gr 1) a b) nil) nil)))
             (args (if rm (cdr args) args))
             (e (k-union (extract gr 2) (k-check (car args) k-int)))
             (fields (cdr args))
             (want (k-bloblet-want expected fields given))
             (made (if (null? want)
                       (let ((r (k-synth-each fields)))
                         (product (1 (extract r 1)) (2 (extract r 2))
                                  (3 (if (null? given) (k-fresh-region "bloblet") (car given)))))
                       (tagcase (car want)
                         (ty-bloblet (fs z r) (product (1 fs) (2 (k-check-each fields fs)) (3 r)))
                         (else y (k-fail "a bloblet" a b)))))
             (region (extract made 3))
             (e (k-insert (a-alloc region) (k-union e (extract made 2))))
             (t (k-ty-new (ty-bloblet (extract made 1) #f region)))
             (unknotted (k-no-knot t a b)))
        (k-te-masked x t e))))
  ;; `(name bx i rest …)`: a bloblet's field `i` read or written, it frozen, or a byte of it.
  (k-bloblet-op (subr (maxeff checks spin) (kx string int kxs) k-te)
    (lambda (x name i args)
      (let* ((a (k-start x)) (b (k-end x))
             (bx (car args)) (rest (cdr args)) (rb (k-synth bx)) (bt (extract rb 1)))
        (tagcase (k-get bt)
          (ty-bloblet (fields frozen region)
            (let* ((e (extract rb 2))
                   (te
                    (cond
                      ((string=? name "bloblet-ref")
                       (let ((t (k-bloblet-field bt fields i a b)))
                         (if frozen (k-te t e) (k-te-reading t region e))))
                      ((string=? name "bloblet-set!")
                       (let ((t (k-bloblet-field bt fields i a b)))
                         (if frozen
                             (k-fail-frozen bt a b)
                             (k-te-writing k-unit region (k-union e (k-check (car rest) t))))))
                      ((string=? name "bloblet-freeze")
                       (k-te-writing (k-ty-new (ty-bloblet fields #t region)) region e))
                      ((string=? name "bloblet-byte")
                       (k-te-reading k-int region (k-union e (k-check (car rest) k-int))))
                      ((string=? name "bloblet-set-byte!")
                       (let* ((e1 (k-check (car rest) k-int)) (e2 (k-check (car (cdr rest)) k-int)))
                         (k-te-writing k-unit region (k-union e (k-union e1 e2)))))
                      (else (k-te k-int e)))))
              (k-masked x te)))
          (else y (k-fail-ty-at "a bloblet is expected here, and this is a " bt bx))))))
  (k-synth-each (subr (maxeff checks spin) (kxs) k-types-eff)
    (lambda (xs)
      (if (null? xs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (car xs))) (rest (k-synth-each (cdr xs))))
            (k-te-onto r rest)))))
  (k-check-each (subr (maxeff checks spin) (kxs k-ids) k-eff)
    (lambda (xs ts)
      (if (null? xs)
          nil
          (let* ((e (k-check (car xs) (car ts))) (rest (k-check-each (cdr xs) (cdr ts))))
            (k-union e rest)))))
  ;;; ------------------------------------------------------------ prompts
  ;;; The tag's type fixes what crosses the prompt, and the body's effect must
  ;;; be within the tag's bound apart from control on its region. Then the
  ;;; prompt delimits: that control is removed, if the body can reach no other
  ;;; tag in the region.
  (k-synth-prompt (subr (maxeff checks spin) (kx kx kx kx) k-te)
    (lambda (x tag body handler)
      (let* ((rt (k-synth tag)) (tt (extract rt 1)))
        (tagcase (k-get tt)
          (ty-tag (answer payload bound region)
            (let* ((be (k-prompt-body body answer))
                   (own (k-insert (a-goto region) (k-one (a-comefrom region))))
                   (beyond (k-beyond be bound own)))
              (if (not (null? beyond))
                  (k-fail-beyond body bound beyond)
                  (let* ((rh (k-synth-handler handler payload answer))
                         (c (k-handler-callable handler (extract rh 1) payload answer))
                         (only (k-reaches-only? body tag region))
                         (delimited (if only (k-beyond be nil own) be))
                         (e (k-union (extract rh 2) (k-union (extract c 1) delimited))))
                    (k-te-masked x answer (k-union (extract rt 2) e))))))
          (else y (k-fail-ty-at "a prompt needs a prompt tag, not a " tt tag))))))
  ;; A prompt's body's effect, checked as an `answer`, the type the tag's prompts deliver.
  (k-prompt-body (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (body answer)
      (let ((r (k-rewriting (lambda () (k-te answer (k-check body answer)))
                            (k-start body) (k-end body)
                            (lambda (m want got) (k-prompt-body-error want got)))))
        (extract r 2))))
  ;; A handler written as a `lambda` of one parameter is told what it takes
  ;; and gives.
  (k-synth-handler (subr (maxeff checks spin) (kx int int) k-te)
    (lambda (h payload answer)
      (tagcase h
        (x-lambda (ps hbody a b)
          (if (= (k-length ps) 1)
              (k-rewriting (lambda () (k-synth-lambda-as h (cons payload nil) answer))
                           (k-start hbody) (k-end hbody)
                           (lambda (m want got) (k-handler-gives payload answer got)))
              (k-synth h)))
        (else y (k-synth h))))))
