;;; The signature of `check-errors.fx`, its `check-errors-module`,
;;; as its clients use it (`TODO.md` §68): a module file of no state.

;;; ------------------------------------------------------------ signatures

;; What its clients use of it (`check-program.fx`).
;; The types it names, from the files that define them.
(define check-types-types (load-module "fx26:check-types-types.fx"))
(define-type kx (select check-types-types kx))
;; The types it names, from the files that define them.
(define-type k-binders (select check-types-types k-binders))
(define-type k-desc (select check-types-types k-desc))
(define-type k-eff (select check-types-types k-eff))
(define-type check-errors-sig
  (moduleof (val k-fail-at
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t))
                       (string kx)
                       void))
            (val k-fail-ty
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (string int int int)
                       void))
            (val k-fail-ty-at
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (string int kx)
                       void))
            (val k-fail-effect
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (string k-eff int int)
                       void))
            (val k-fail-impure-plambda
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (k-eff int int)
                       void))
            (val k-fail-no-part
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (int string symbol int int)
                       void))
            (val k-fail-arity
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t))
                       (int string int int int)
                       void))
            (val k-fail-arg-count
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t))
                       (int int int int)
                       void))
            (val k-argument-error (subr (read @globals) (int string string) string))
            (val k-fail-not-known
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (kx int int)
                       void))
            (val k-fail-not-frozen
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (int kx)
                       void))
            (val k-fail-not-data
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (int kx)
                       void))
            (val k-fail-frozen
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (int int int)
                       void))
            (val k-fail-beyond
                 (subr (maxeff (alloc @t)
                               (goto @z)
                               (read @globals)
                               (read @s)
                               (read @t)
                               (write @t)
                               spin)
                       (kx k-eff k-eff)
                       void))
            (val k-proj-count-error
                 (subr (read @globals) (k-binders (listof k-desc acyclic)) string))
            (val k-prompt-body-error (subr (read @globals) (string string) string))
            (val k-handler-gives
                 (subr (maxeff (alloc @t) (read @globals) (read @t) spin)
                       (int int string)
                       string))
            (val k-handler-wants
                 (subr (maxeff (alloc @t) (read @globals) (read @t) spin) (int int) string))))
