;;; The checker, in FX-26: resolving the trees' descriptions, callables,
;;; regions of types, and masking (substitution is `check-subst.fx`'s).
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

;;; ------------------------------------------------------------ resolving
;;; The parser's trees to `kx`, reading descriptions where the Rust parser
;;; does.

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
;; Its types (`check-resolve-types.fx`), loaded before the module so that they are not
;; among its values; the module names what it uses of them.
(let* ((check-resolve-types (load-module "fx26:check-resolve-types.fx"))
       (check-types-types (load-module "fx26:check-types-types.fx"))
       (check-modorder-types (load-module "fx26:check-modorder-types.fx"))
       (parser-types ((proj (load-module "fx26:parser-types.fx") @s @e @m @c @p)))
       (check-subst-types (load-module "fx26:check-subst-types.fx"))
       (check-subtype-types (load-module "fx26:check-subtype-types.fx"))
       (check-effects-types (load-module "fx26:check-effects-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-read-types (load-module "fx26:check-read-types.fx"))
       (check-syntax-types (load-module "fx26:check-syntax-types.fx"))
       (check-print-types (load-module "fx26:check-print-types.fx"))
       (check-read-descs-types (load-module "fx26:check-read-descs-types.fx"))
       (table-types (load-module "fx26:table-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-subst (select check-subst-types check-subst-sig))
           (check-effects (select check-effects-types check-effects-sig))
           (check-env (select check-env-types check-env-sig))
           (check-read (select check-read-types check-read-sig))
           (check-syntax (select check-syntax-types check-syntax-sig))
           (check-print (select check-print-types check-print-sig))
           (check-read-descs (select check-read-descs-types check-read-descs-sig))
           (tables (select table-types tables-sig)))
    (module
(define-type k-typed-params (select check-resolve-types k-typed-params))
(define-type k-letrec-bs (select check-resolve-types k-letrec-bs))
(define-type k-let-bs (select check-resolve-types k-let-bs))
(define-type k-arms (select check-resolve-types k-arms))
(define-type exp-letrec-bs (select check-resolve-types exp-letrec-bs))
(define-type exp-let-bs (select check-resolve-types exp-let-bs))
(define-type exp-arms (select check-resolve-types exp-arms))
(define-type k-callable (select check-resolve-types k-callable))
(define-type k-region-lists (select check-resolve-types k-region-lists))
(define-type k-def (select check-resolve-types k-def))
(define-type k-run (select check-resolve-types k-run))
;; The types it uses of the files before it.
(define a-comefrom (with check-types-types a-comefrom))
(define a-goto (with check-types-types a-goto))
(define-effect checks (select check-types-types checks))
(define dc (with check-types-types dc))
(define de (with check-types-types de))
(define df (with check-types-types df))
(define dr (with check-types-types dr))
(define ds-var (with check-types-types ds-var))
(define dt (with check-types-types dt))
(define dz (with check-types-types dz))
(define-type k-binders (select check-types-types k-binders))
(define-type k-desc (select check-types-types k-desc))
(define-type k-descs (select check-types-types k-descs))
(define-type k-eff (select check-types-types k-eff))
(define-type k-hyps (select check-types-types k-hyps))
(define-type k-ids (select check-types-types k-ids))
(define-type k-item (select check-types-types k-item))
(define-type k-lemma (select check-types-types k-lemma))
(define-type k-map (select check-types-types k-map))
(define-type k-names (select check-types-types k-names))
(define-type k-parts (select check-types-types k-parts))
(define-type k-region (select check-types-types k-region))
(define-type k-regions (select check-types-types k-regions))
(define-type k-vsub (select check-types-types k-vsub))
(define-effect kreads (select check-types-types kreads))
(define-effect kstate (select check-types-types kstate))
(define-type kx (select check-types-types kx))
(define-type kxs (select check-types-types kxs))
(define r-frozen (with check-types-types r-frozen))
(define r-heap (with check-types-types r-heap))
(define r-var (with check-types-types r-var))
(define ty-app (with check-types-types ty-app))
(define ty-array (with check-types-types ty-array))
(define ty-base (with check-types-types ty-base))
(define ty-bloblet (with check-types-types ty-bloblet))
(define ty-comp (with check-types-types ty-comp))
(define ty-false (with check-types-types ty-false))
(define ty-icell (with check-types-types ty-icell))
(define ty-lam (with check-types-types ty-lam))
(define ty-link (with check-types-types ty-link))
(define ty-markkey (with check-types-types ty-markkey))
(define ty-module (with check-types-types ty-module))
(define ty-named (with check-types-types ty-named))
(define ty-nat (with check-types-types ty-nat))
(define ty-nil (with check-types-types ty-nil))
(define ty-nlist (with check-types-types ty-nlist))
(define ty-pair (with check-types-types ty-pair))
(define ty-param (with check-types-types ty-param))
(define ty-place (with check-types-types ty-place))
(define ty-poly (with check-types-types ty-poly))
(define ty-product (with check-types-types ty-product))
(define ty-proving (with check-types-types ty-proving))
(define ty-ref (with check-types-types ty-ref))
(define ty-select (with check-types-types ty-select))
(define ty-subr (with check-types-types ty-subr))
(define ty-sum (with check-types-types ty-sum))
(define ty-tag (with check-types-types ty-tag))
(define ty-union (with check-types-types ty-union))
(define ty-var (with check-types-types ty-var))
(define ty-void (with check-types-types ty-void))
(define x-app (with check-types-types x-app))
(define x-begin (with check-types-types x-begin))
(define x-bloblet (with check-types-types x-bloblet))
(define x-const (with check-types-types x-const))
(define x-convention (with check-types-types x-convention))
(define x-extract (with check-types-types x-extract))
(define x-if (with check-types-types x-if))
(define x-lambda (with check-types-types x-lambda))
(define x-let (with check-types-types x-let))
(define x-letrec (with check-types-types x-letrec))
(define x-letregion (with check-types-types x-letregion))
(define x-module (with check-types-types x-module))
(define x-plambda (with check-types-types x-plambda))
(define x-product (with check-types-types x-product))
(define x-proj (with check-types-types x-proj))
(define x-prompt (with check-types-types x-prompt))
(define x-rlambda (with check-types-types x-rlambda))
(define x-sum (with check-types-types x-sum))
(define x-tagcase (with check-types-types x-tagcase))
(define x-the (with check-types-types x-the))
(define x-var (with check-types-types x-var))
(define x-with (with check-types-types x-with))
(define-type k-items (select check-types-types k-items))
(define-type k-places (select check-modorder-types k-places))
(define e-app (with parser-types e-app))
(define e-begin (with parser-types e-begin))
(define e-bloblet (with parser-types e-bloblet))
(define e-bool (with parser-types e-bool))
(define e-char (with parser-types e-char))
(define e-convention (with parser-types e-convention))
(define e-extract (with parser-types e-extract))
(define e-float (with parser-types e-float))
(define e-if (with parser-types e-if))
(define e-int (with parser-types e-int))
(define e-lambda (with parser-types e-lambda))
(define e-let (with parser-types e-let))
(define e-letrec (with parser-types e-letrec))
(define e-letregion (with parser-types e-letregion))
(define e-module (with parser-types e-module))
(define e-plambda (with parser-types e-plambda))
(define e-product (with parser-types e-product))
(define e-proj (with parser-types e-proj))
(define e-prompt (with parser-types e-prompt))
(define e-rlambda (with parser-types e-rlambda))
(define e-str (with parser-types e-str))
(define e-sum (with parser-types e-sum))
(define e-sym (with parser-types e-sym))
(define e-tagcase (with parser-types e-tagcase))
(define e-the (with parser-types e-the))
(define e-unit (with parser-types e-unit))
(define e-var (with parser-types e-var))
(define e-with (with parser-types e-with))
(define-type exp (select parser-types exp))
(define-type names (select parser-types names))
(define-type syns-a (select parser-types syns-a))
(define-type exp-params (select check-subst-types exp-params))
(define-type k-pairs (select check-subst-types k-pairs))
(define-effect kmakes (select check-subst-types kmakes))
(define-type k-trail (select check-subtype-types k-trail))
;; What it uses of the modules it is given.
(define k-abstract-funs (with check-types k-abstract-funs))
(define k-arrow-vars (with check-types k-arrow-vars))
(define k-binder-has? (with check-types k-binder-has?))
(define k-bounds (with check-types k-bounds))
(define k-cat3 (with check-types k-cat3))
(define k-certified (with check-types k-certified))
(define k-certified-lengths (with check-types k-certified-lengths))
(define k-certified-nats (with check-types k-certified-nats))
(define k-closure-depth (with check-types k-closure-depth))
(define k-conversions (with check-types k-conversions))
(define k-datas (with check-types k-datas))
(define k-dvar-name (with check-types k-dvar-name))
(define k-dvars (with check-types k-dvars))
(define k-fail (with check-types k-fail))
(define k-freezing (with check-types k-freezing))
(define k-gen-of (with check-types k-gen-of))
(define k-gen-region? (with check-types k-gen-region?))
(define k-gens (with check-types k-gens))
(define k-get (with check-types k-get))
(define k-has-name? (with check-types k-has-name?))
(define k-inside (with check-types k-inside))
(define k-lemmas (with check-types k-lemmas))
(define k-length (with check-types k-length))
(define k-lifetimes (with check-types k-lifetimes))
(define k-links (with check-types k-links))
(define k-narrowed (with check-types k-narrowed))
(define k-ndvars (with check-types k-ndvars))
(define k-new-epoch (with check-types k-new-epoch))
(define k-ngens (with check-types k-ngens))
(define k-ntys (with check-types k-ntys))
(define k-outer-of (with check-types k-outer-of))
(define k-outers (with check-types k-outers))
(define k-path-narrowed (with check-types k-path-narrowed))
(define k-pending-lemma (with check-types k-pending-lemma))
(define k-places (with check-types k-places))
(define k-recursive (with check-types k-recursive))
(define k-resolve (with check-types k-resolve))
(define k-set-outer (with check-types k-set-outer))
(define k-skolems (with check-types k-skolems))
(define k-spin-why (with check-types k-spin-why))
(define k-std (with check-types k-std))
(define k-std-table (with check-types k-std-table))
(define k-transparent (with check-types k-transparent))
(define k-ty-new (with check-types k-ty-new))
(define k-tys (with check-types k-tys))
(define k-visit? (with check-types k-visit?))
(define k-written (with check-types k-written))
(define k-binder-desc (with check-subst k-binder-desc))
(define k-closed-named (with check-subst k-closed-named))
(define k-gen-map (with check-subst k-gen-map))
(define k-subst (with check-subst k-subst))
(define k-atom-region (with check-effects k-atom-region))
(define k-has-region? (with check-effects k-has-region?))
(define k-insert (with check-effects k-insert))
(define k-region=? (with check-effects k-region=?))
(define k-base (with check-env k-base))
(define k-basic (with check-env k-basic))
(define k-broken (with check-env k-broken))
(define k-depth (with check-env k-depth))
(define k-depths (with check-env k-depths))
(define k-dscope (with check-env k-dscope))
(define k-effect-notes (with check-env k-effect-notes))
(define k-env (with check-env k-env))
(define k-expanding (with check-env k-expanding))
(define k-extracts (with check-env k-extracts))
(define k-forget-withs (with check-env k-forget-withs))
(define k-fresh (with check-env k-fresh))
(define k-fx-module? (with check-env k-fx-module?))
(define k-global (with check-env k-global))
(define k-hazard-mods (with check-env k-hazard-mods))
(define k-hazard-names-in (with check-env k-hazard-names-in))
(define k-hide-mark (with check-env k-hide-mark))
(define k-known (with check-env k-known))
(define k-lookup-desc (with check-env k-lookup-desc))
(define k-module-vars (with check-env k-module-vars))
(define k-operator (with check-env k-operator))
(define k-param-map (with check-env k-param-map))
(define k-reshapes (with check-env k-reshapes))
(define k-select-map (with check-env k-select-map))
(define k-trail (with check-env k-trail))
(define k-with-names (with check-env k-with-names))
(define k-effect-selects (with check-read k-effect-selects))
(define k-items (with check-read k-items))
(define k-knots (with check-syntax k-knots))
(define k-map-find (with check-print k-map-find))
(define k-size-facts (with check-print k-size-facts))
(define k-parse-d (with check-read-descs k-parse-d))
(define k-parse-type (with check-read-descs k-parse-type))
(define make-table (with tables make-table))
(define symbol-hash (with tables symbol-hash))

(define k-start (subr pure (kx) int)
  (lambda (x)
    (tagcase x
      (x-var (s a b) a) (x-const (t v a b) a) (x-lambda (ps e a b) a) (x-app (f xs a b) a)
      (x-plambda (bs e a b) a) (x-proj (e ds a b) a) (x-if (p c d a b) a) (x-letrec (bs e a b) a)
      (x-let (bs e a b) a) (x-begin (xs a b) a) (x-prompt (t e h a b) a) (x-the (t e a b) a)
      (x-convention (c e a b) a) (x-bloblet (o i xs a b) a) (x-product (fs a b) a)
      (x-extract (e l a b) a) (x-sum (l e a b) a) (x-tagcase (e arms els a b) a)
      (x-letregion (k r i e a b) a) (x-rlambda (r l a b) a)
      (x-module (items a b) a) (x-with (m e a b) a))))
(define k-end (subr pure (kx) int)
  (lambda (x)
    (tagcase x
      (x-var (s a b) b) (x-const (t v a b) b) (x-lambda (ps e a b) b) (x-app (f xs a b) b)
      (x-plambda (bs e a b) b) (x-proj (e ds a b) b) (x-if (p c d a b) b) (x-letrec (bs e a b) b)
      (x-let (bs e a b) b) (x-begin (xs a b) b) (x-prompt (t e h a b) b) (x-the (t e a b) b)
      (x-convention (c e a b) b) (x-bloblet (o i xs a b) b) (x-product (fs a b) b)
      (x-extract (e l a b) b) (x-sum (l e a b) b) (x-tagcase (e arms els a b) b)
      (x-letregion (k r i e a b) b) (x-rlambda (r l a b) b)
      (x-module (items a b) b) (x-with (m e a b) b))))
(define k-same-span? (subr (read @globals) (kx int int) bool)
  (lambda (x a b) (and (= (k-start x) a) (= (k-end x) b))))

(define k-resolve-params (subr (maxeff checks spin) (exp-params) k-typed-params)
  (lambda (ps)
    (if (null? ps)
        nil
        (let* ((ty (extract (car ps) 2))
               (t (if (null? ty) (the k-ids nil) (the k-ids (cons (k-parse-type (car ty)) nil))))
               (rest (k-resolve-params (cdr ps))))
          (cons (product (1 (extract (car ps) 1)) (2 t)) rest)))))
(define k-resolve-descs (subr (maxeff checks spin) (syns-a) k-descs)
  (lambda (ds)
    (if (null? ds)
        nil
        (let* ((d (k-parse-d (car ds))) (rest (k-resolve-descs (cdr ds))))
          (cons d rest)))))
(define k-copy-names (subr (maxeff (read @globals) (alloc @t)) (names) k-names)
  (lambda (ns) (if (null? ns) nil (cons (car ns) (k-copy-names (cdr ns))))))

;; Where a parser's tree starts and ends.
(define exp-start (subr pure (exp) int)
  (lambda (e)
    (tagcase e
      (e-var (s a b) a) (e-int (n a b) a) (e-bool (v a b) a) (e-str (v a b) a) (e-char (v a b) a)
      (e-float (v a b) a)
      (e-sym (v a b) a) (e-unit (a b) a) (e-lambda (ps x a b) a) (e-app (f xs a b) a)
      (e-plambda (bs x a b) a) (e-proj (x ds a b) a) (e-if (p c d a b) a) (e-letrec (bs x a b) a)
      (e-let (bs x a b) a) (e-begin (xs a b) a) (e-prompt (t x h a b) a) (e-the (t x a b) a)
      (e-convention (c x a b) a) (e-bloblet (o i xs a b) a) (e-product (fs a b) a)
      (e-extract (x l a b) a) (e-sum (l x a b) a) (e-tagcase (x arms els a b) a)
      (e-letregion (k r i x a b) a) (e-rlambda (r l a b) a)
      (e-module (items a b) a) (e-with (m x a b) a))))
(define exp-end (subr pure (exp) int)
  (lambda (e)
    (tagcase e
      (e-var (s a b) b) (e-int (n a b) b) (e-bool (v a b) b) (e-str (v a b) b) (e-char (v a b) b)
      (e-float (v a b) b)
      (e-sym (v a b) b) (e-unit (a b) b) (e-lambda (ps x a b) b) (e-app (f xs a b) b)
      (e-plambda (bs x a b) b) (e-proj (x ds a b) b) (e-if (p c d a b) b) (e-letrec (bs x a b) b)
      (e-let (bs x a b) b) (e-begin (xs a b) b) (e-prompt (t x h a b) b) (e-the (t x a b) b)
      (e-convention (c x a b) b) (e-bloblet (o i xs a b) b) (e-product (fs a b) b)
      (e-extract (x l a b) b) (e-sum (l x a b) b) (e-tagcase (x arms els a b) b)
      (e-letregion (k r i x a b) b) (e-rlambda (r l a b) b)
      (e-module (items a b) b) (e-with (m x a b) b))))

;; A `plambda`'s region and place binders: each won't outlive what is bound
;; around it (`lives`), and each is around what its body binds.
(define k-order-binders (subr kstate (k-binders k-ids) unit)
  (lambda (bs lives)
    (if (null? bs)
        #u
        (let ((v (extract (car bs) 1)) (k (extract (car bs) 2)))
          (begin
            (if (or (= k 0) (= k 3))
                (begin (k-set-outer v lives) (set k-lifetimes (cons v (get k-lifetimes))))
                #u)
            (k-order-binders (cdr bs) lives))))))

;; The place a `letfreeze` names: `heap`, or a place in scope.
(define k-resolve-place (subr checks (symbol int int) k-region)
  (lambda (n a b)
    (if (symbol=? n 'heap)
        (r-heap)
        (let ((d (k-lookup-desc n)))
          (if (null? d)
              (k-fail (k-cat3 "`" (symbol->string n) "` is not a region") a b)
              (tagcase (car d)
                (ds-var (v k)
                  (case k ((3) (r-var v))
                          ((0) (k-fail (k-cat3 "`" (symbol->string n) "` is not a place") a b))
                          (else (k-fail (k-cat3 "`" (symbol->string n) "` is not a region") a b))))
                (else x (k-fail (k-cat3 "`" (symbol->string n) "` is not a region") a b))))))))
;; What a `letfreeze` into `place` freezes into: `(const p)` for its
;; place `p`, and for the heap, -1.
(define* k-freeze-into (subr pure (k-region) k-region)
  (lambda (place) (tagcase place (r-var (p) (r-frozen p #f)) (else y (r-frozen -1 #f)))))
;; What a `letfreeze` into `place` won't outlive: the place, and what it
;; won't.
(define k-place-lives (subr kmakes (k-region) k-ids)
  (lambda (place) (tagcase place (r-var (p) (cons p (k-outer-of p))) (else y nil))))

(define k-as-subr (subr (maxeff kmakes spin) (int) (listof k-callable acyclic))
  (lambda (t)
    (tagcase (k-get t)
      (ty-subr (e ps r cv) (cons (product (1 e) (2 ps) (3 r)) nil))
      (ty-comp (arg answer e r)
        (let ((control (k-insert (a-goto r) (k-insert (a-comefrom r) e))))
          (cons (product (1 control) (2 (the k-ids (cons arg nil))) (3 answer)) nil)))
      (else x nil))))
;; No `vsubr`; one, of latent effect `e`, arguments of type `a`, result `r`.
(define k-vsub-none k-vsub nil)
(define k-vsub-one (subr (alloc @t) (k-eff int int) k-vsub)
  (lambda (e a r) (cons (product (1 e) (2 a) (3 r)) nil)))
;; `vsubr`'s three descriptions, an effect and two types, as `k-vsubr-parts`
;; gives them.
(define* k-vsubr-descs (subr (alloc @t) (k-desc k-desc k-desc) k-vsub)
  (lambda (e a r)
    (tagcase e
      (de (le)
        (tagcase a
          (dt (at) (tagcase r (dt (rt) (k-vsub-one le at rt)) (else z k-vsub-none)))
          (else z k-vsub-none)))
      (else z k-vsub-none))))
;; A `vsubr` (generative type 0), taken apart: its latent effect, the type of
;; each argument, and the result's, in a list; none for any other type.
(define k-vsubr-parts (subr (maxeff kmakes spin) (int) k-vsub)
  (lambda (t)
    (tagcase (k-get t)
      (ty-named (g ds)
        (if (and (= g 0) (= (k-length ds) 3))
            (k-vsubr-descs (car ds) (car (cdr ds)) (car (cdr (cdr ds))))
            k-vsub-none))
      (else y k-vsub-none))))
;; `n` copies of type `t`, onto `acc`.
(define* k-repeat-id (subr (maxeff (alloc @t) spin) (int int k-ids) k-ids)
  (lambda (t n acc) (if (<= n 0) acc (k-repeat-id t (- n 1) (cons t acc)))))
;; What `t` is called as, with `n` arguments: a subroutine; a `vsubr` (a
;; standard `list`), as one of `n` parameters, each of its argument type;
;; or none.
(define k-callee-of (subr (maxeff kmakes spin) (int int) (listof k-callable acyclic))
  (lambda (t n)
    (let ((v (k-vsubr-parts t)))
      (if (null? v)
          (k-as-subr t)
          (let* ((p (car v)) (ps (k-repeat-id (extract p 2) n (the k-ids nil))))
            (cons (product (1 (extract p 1)) (2 ps) (3 (extract p 3))) nil))))))

;;; ------------------------------------------------------------ regions of types

(define k-has-region-in? (subr (maxeff kreads spin) (k-regions k-region) bool)
  (lambda (rs r)
    (cond ((null? rs) #f)
          ((k-region=? (car rs) r) #t)
          (else (k-has-region-in? (cdr rs) r)))))
(define k-add-region (subr (maxeff kmakes spin) (k-regions k-region) k-regions)
  (lambda (rs r) (if (k-has-region-in? rs r) rs (cons r rs))))
;; `out` and each of `rs` that is not a generative type's parameter.
(define k-add-non-gen (subr (maxeff kmakes spin) (k-regions k-regions) k-regions)
  (lambda (out rs)
    (cond ((null? rs) out)
          ((k-gen-region? (car rs)) (k-add-non-gen out (cdr rs)))
          (else (k-add-non-gen (k-add-region out (car rs)) (cdr rs))))))
(define k-add-eff-regions (subr (maxeff kmakes spin) (k-regions k-eff) k-regions)
  (lambda (rs e)
    (cond ((null? e) rs)
          ((k-has-region? (car e))
           (k-add-eff-regions (k-add-region rs (k-atom-region (car e))) (cdr e)))
          (else (k-add-eff-regions rs (cdr e))))))

(define k-regions-memo (ref k-region-lists @t) (new (make-array 512 nil)))

;; The definitions checked so far, newest first, each the latest of its
;; names.
(define k-defs (ref (listof k-def acyclic) @t) (new nil))
;; The free variables of the definition being checked, for `k-record`.
(define k-last-uses (ref k-names @t) (new nil))
(define k-runs (ref (listof k-run acyclic) @t) (new nil))
;; For `k-reset`: forget the description variables, and what is known of
;; the regions and places among them.
(define k-reset-regions (subr kstate () unit)
  (lambda ()
    (begin
      (set k-dvars nil) (set k-ndvars 0) (set k-places nil) (set k-bounds nil) (set k-outers nil)
      (set k-lifetimes nil) (set k-freezing nil) (set k-written nil)
      (set k-arrow-vars nil) (set k-abstract-funs nil))))
;; Forget the names bound, and what is known of them.
(define k-reset-names (subr kstate () unit)
  (lambda ()
    (begin
      (set k-known (make-table symbol-hash symbol=?))
      (set k-global (make-table symbol-hash symbol=?))
      (set k-recursive nil) (set k-std nil) (set k-env (make-table symbol-hash symbol=?))
      (set k-depths (make-table symbol-hash symbol=?))
      (set k-std-table (make-table symbol-hash symbol=?))
      (set k-trail nil) (set k-depth 0))))
;; Forget the lemmas, and the facts learned of data and sizes.
(define k-reset-facts (subr kstate () unit)
  (lambda ()
    (begin
      (set k-lemmas nil) (set k-pending-lemma nil) (set k-datas nil) (set k-certified nil)
      (set k-narrowed nil) (set k-path-narrowed nil) (set k-closure-depth 0)
      (set k-certified-lengths nil) (set k-certified-nats nil) (set k-size-facts nil)
      (set k-skolems nil))))
(define k-reset (subr (maxeff kstate spin) () unit)
  (lambda ()
    (begin
      (set k-extracts nil) (set k-effect-notes nil)
      (set k-ntys 0) (set k-links (+ (get k-links) 1)) (k-reset-regions) (k-reset-names)
      (set k-regions-memo (make-array 512 nil)) (set k-dscope nil)
      (set k-fresh 0) (set k-base nil) (set k-expanding 0) (set k-knots nil) (set k-spin-why nil)
      (set k-closed-named nil)
      (set k-gens nil) (set k-ngens 0) (set k-transparent nil) (set k-inside nil)
      (set k-conversions nil) (k-reset-facts)
      (set k-broken nil) (set k-defs nil) (set k-runs nil) (set k-last-uses nil)
      (k-forget-withs) (set k-module-vars nil) (set k-select-map nil) (set k-reshapes nil)
      (set k-hide-mark -1) (set k-param-map nil) (set k-effect-selects nil)
      (set k-operator (product (1 '||) (2 -1) (3 -1)))
      (k-basic "int") (k-basic "bool") (k-basic "string") (k-basic "unit") (k-basic "char")
      (k-basic "%datum") (k-basic "symbol") (k-basic "tword") (k-basic "wcell") (k-basic "wglobal")
      ;; 10 to 15; `void` 16, `k-void`.
      (k-basic "i32") (k-basic "u32") (k-basic "i64") (k-basic "u64")
      (k-basic "f64") (k-basic "f32")
      (k-ty-new (ty-void))
      ;; 17 and 18, after `void`: as `check.rs` makes them.
      (k-basic "vector") (k-basic "bytevector")
      #u)))
(define n-copy-memo (subr (maxeff kreads (write @t) spin) (k-region-lists k-region-lists int) unit)
  (lambda (from to i)
    (if (= i (array-length from))
        #u
        (begin (array-set! to i (array-ref from i)) (n-copy-memo from to (+ i 1))))))
(define k-remember-regions (subr (maxeff kstate spin) (int k-regions) unit)
  (lambda (t rs)
    (begin
      (if (>= t (array-length (get k-regions-memo)))
          (let ((bigger (the k-region-lists (make-array (* 2 (array-length (get k-tys))) nil))))
            (begin (n-copy-memo (get k-regions-memo) bigger 0) (set k-regions-memo bigger)))
          #u)
      (array-set! (get k-regions-memo) t (cons rs nil)))))
;; Add to `out` the regions of `e`'s atoms.
(define k-note-eff-regions (subr (maxeff kstate spin) ((ref k-regions @t) k-eff) unit)
  (lambda (out e) (set out (k-add-eff-regions (get out) e))))

(define-rec
  (k-regions-walk (subr (maxeff kstate spin) (int int (ref k-regions @t)) unit)
    (lambda (t seen out)
      (let ((t (k-resolve t)))
        (if (k-visit? t seen)
            #u
            (letrec ((add (subr (maxeff kstate spin) (k-region) unit)
                          (lambda (r) (set out (k-add-region (get out) r))))
                     (walk (subr (maxeff kstate spin) (int) unit)
                           (lambda (x) (k-regions-walk x seen out)))
                     (walks (subr (maxeff kstate spin) (k-ids) unit)
                            (lambda (xs) (k-regions-walks xs seen out))))
              (begin
                (tagcase (k-get t)
                  (ty-subr (e ps r cv) (begin (k-note-eff-regions out e) (walks ps) (walk r)))
                  (ty-poly (bs body) (walk body))
                  (ty-ref (a r) (begin (add r) (walk a)))
                  (ty-array (a r) (begin (add r) (walk a)))
                  (ty-icell (a r) (begin (add r) (walk a)))
                  (ty-place (r) (add r))
                  (ty-pair (a b r nl) (begin (add r) (walk a) (walk b)))
                  (ty-tag (a h e r) (begin (add r) (k-note-eff-regions out e) (walk a) (walk h)))
                  (ty-comp (b a e r) (begin (add r) (k-note-eff-regions out e) (walk a) (walk b)))
                  (ty-markkey (a r) (begin (add r) (walk a)))
                  (ty-bloblet (fs z r) (begin (add r) (walks fs)))
                  (ty-product (ps) (k-regions-parts ps seen out))
                  (ty-sum (ps) (k-regions-parts ps seen out))
                  (ty-union (ms) (walks ms))
                  (ty-nlist (e z r) (begin (add r) (walk e)))
                  (ty-module (abs ds vs)
                    (begin (k-regions-parts ds seen out) (k-regions-parts vs seen out)))
                  ;; Transparent to safety: what its representation holds,
                  ;; its parameters' regions standing for what it was given.
                  (ty-named (g ds)
                    (let ((inner (the (ref k-regions @t) (new nil))))
                      (begin (k-regions-walk (extract (k-gen-of g) 4) seen inner)
                             (set out (k-add-non-gen (get out) (get inner)))
                             (k-regions-descs ds seen out))))
                  ;; A description function applied, which cannot be looked
                  ;; into: what it was given; a function, its body.
                  (ty-app (g ds) (k-regions-descs ds seen out))
                  (ty-lam (bs body) (k-regions-descs (the k-descs (cons body nil)) seen out))
                  (else x #u))))))))
  (k-regions-descs (subr (maxeff kstate spin) (k-descs int (ref k-regions @t)) unit)
    (lambda (ds seen out)
      (if (null? ds)
          #u
          (begin (tagcase (car ds)
                   (dt (x) (k-regions-walk x seen out))
                   (dr (r) (set out (k-add-region (get out) r)))
                   (de (e) (k-note-eff-regions out e))
                   (dz (z) #u)
                   (dc (c) #u)
                   (df (f)
                     (tagcase (k-get f)
                       (ty-lam (bs body) (k-regions-descs (the k-descs (cons body nil)) seen out))
                       (else y #u))))
                 (k-regions-descs (cdr ds) seen out)))))
  (k-regions-walks (subr (maxeff kstate spin) (k-ids int (ref k-regions @t)) unit)
    (lambda (ts seen out)
      (if (null? ts)
          #u
          (begin (k-regions-walk (car ts) seen out) (k-regions-walks (cdr ts) seen out)))))
  (k-regions-parts (subr (maxeff kstate spin) (k-parts int (ref k-regions @t)) unit)
    (lambda (ps seen out)
      (if (null? ps)
          #u
          (begin (k-regions-walk (extract (car ps) 2) seen out)
                 (k-regions-parts (cdr ps) seen out))))))
(define k-frozen-places (subr (maxeff kmakes spin) (k-regions k-regions) k-regions)
  (lambda (rs out)
    (if (null? rs)
        out
        (let ((out (tagcase (car rs)
                     (r-frozen (p f) (if (< p 0) out (k-add-region out (r-var p))))
                     (else y out))))
          (k-frozen-places (cdr rs) out)))))
(define k-regions-in (subr (maxeff kstate spin) (int) k-regions)
  (lambda (t)
    (let* ((t (k-resolve t)) (memo (get k-regions-memo)))
      (if (and (< t (array-length memo)) (not (null? (array-ref memo t))))
          (car (array-ref memo t))
          (let ((out (the (ref k-regions @t) (new nil))))
            (begin
              (k-regions-walk t (k-new-epoch) out)
              ;; Frozen data mentions the place it is in.
              (set out (k-frozen-places (get out) (get out)))
              (k-remember-regions t (get out))
              (get out)))))))
(define k-note (subr kmakes (symbol k-names k-names) k-names)
  (lambda (s bound out) (if (or (k-has-name? bound s) (k-has-name? out s)) out (cons s out))))
(define k-names-onto (subr kmakes (k-names k-names) k-names)
  (lambda (ns bound) (if (null? ns) bound (k-names-onto (cdr ns) (cons (car ns) bound)))))
;; `bound`, and the names `ps`, `bs` bind.
(define k-param-names (subr kmakes (k-typed-params k-names) k-names)
  (lambda (ps bound)
    (if (null? ps) bound (k-param-names (cdr ps) (cons (extract (car ps) 1) bound)))))
(define k-letrec-names (subr kmakes (k-letrec-bs k-names) k-names)
  (lambda (bs bound)
    (if (null? bs) bound (k-letrec-names (cdr bs) (cons (extract (car bs) 1) bound)))))
(define k-let-names (subr kmakes (k-let-bs k-names) k-names)
  (lambda (bs bound)
    (if (null? bs) bound (k-let-names (cdr bs) (cons (extract (car bs) 1) bound)))))

;; `up-t` and `down-t`, an abstract type `t`'s conversions, onto `bound`.
(define k-conversion-name (subr (read @globals) (string symbol) symbol)
  (lambda (prefix n) (string->symbol (string-append prefix (symbol->string n)))))
(define k-conversions-onto (subr kmakes (symbol k-names) k-names)
  (lambda (n bound)
    (cons (k-conversion-name "down-" n) (cons (k-conversion-name "up-" n) bound))))
;; The names an item binds for those after it, onto `bound`: an abstract
;; type's conversions, a value's name, a group's.
(define k-item-bound (subr kmakes (k-item k-names) k-names)
  (lambda (it bound)
    (let ((k (extract it 1)) (ns (extract it 2)))
      (cond ((= k 0) (k-conversions-onto (car ns) bound))
            ((or (= k 1) (< k 0) (> k 3)) bound)
            (else (k-names-onto ns bound))))))
;; Every name `items` define, onto `bound`.
(define k-items-bound (subr kmakes (k-items k-names) k-names)
  (lambda (items bound)
    (if (null? items) bound (k-items-bound (cdr items) (k-item-bound (car items) bound)))))

;; The names a `with` of `m` at `a`..`b` binds for its body, bound inside
;; `bound`: its module's values the body names, once checked; before, if
;; `m` is not bound inside, those of an earlier item of a module being
;; ordered whose value is a module as written (`k-hazard-mods`).
(define k-with-bound (subr kreads (symbol int int k-names) k-names)
  (lambda (m a b bound)
    (let ((ns (k-with-names a b)))
      (if (and (null? ns) (not (k-has-name? bound m)))
          (k-hazard-names-in (get k-hazard-mods) m)
          ns))))

(define-rec
  (k-free-list (subr kmakes (kxs k-names k-names) k-names)
    (lambda (xs bound out)
      (if (null? xs) out (k-free-list (cdr xs) bound (k-free-into (car xs) bound out)))))
  (k-free-into (subr kmakes (kx k-names k-names) k-names)
    (lambda (x bound out)
      (tagcase x
        (x-var (s a b) (k-note s bound out))
        (x-const (t v a b) out)
        (x-lambda (ps body a b) (k-free-into body (k-param-names ps bound) out))
        (x-app (f args a b) (k-free-list args bound (k-free-into f bound out)))
        (x-plambda (bs body a b) (k-free-into body bound out))
        (x-letregion (k r i body a b) (k-free-into body (cons (k-dvar-name r) bound) out))
        (x-rlambda (r l a b) (k-free-into l bound (k-free-into r bound out)))
        (x-proj (body ds a b) (k-free-into body bound out))
        (x-if (p c d a b) (k-free-into d bound (k-free-into c bound (k-free-into p bound out))))
        (x-letrec (bs body a b)
          (let ((inner (k-letrec-names bs bound)))
            (k-free-into body inner (k-free-letrec bs inner out))))
        (x-let (bs body a b) (k-free-into body (k-let-names bs bound) (k-free-let bs bound out)))
        (x-begin (xs a b) (k-free-list xs bound out))
        (x-prompt (t body h a b)
          (k-free-into h bound (k-free-into body bound (k-free-into t bound out))))
        (x-the (t body a b) (k-free-into body bound out))
        (x-convention (c body a b) (k-free-into body bound out))
        (x-bloblet (o i xs a b) (k-free-list xs bound out))
        ;; A product's fields are as a `let`'s bindings.
        (x-product (fs a b) (k-free-let fs bound out))
        (x-extract (body l a b) (k-free-into body bound out))
        (x-sum (l body a b) (k-free-into body bound out))
        (x-tagcase (s arms els a b)
          (let ((o (k-free-arms arms bound (k-free-into s bound out))))
            (k-free-else els bound o)))
        (x-module (items a b) (k-free-module items bound out))
        ;; The module, and the body, which sees its values once checked (or, an
        ;; earlier item's of a module being ordered, `k-with-bound`).
        ;; `(with #%fx n)`, the standard `n`: nothing free.
        (x-with (m body a b)
          (if (k-fx-module? m)
              out
              (k-free-into body (k-names-onto (k-with-bound m a b bound) bound)
                           (k-note m bound out)))))))
  ;; A module's free variables, onto `out`: each item's, every item's names
  ;; bound, as a `letrec*`'s (`check-modorder.fx`).
  (k-free-module (subr kmakes (k-items k-names k-names) k-names)
    (lambda (items bound out) (k-free-items items (k-items-bound items bound) out)))
  (k-free-items (subr kmakes (k-items k-names k-names) k-names)
    (lambda (items bound out)
      (if (null? items)
          out
          (k-free-items (cdr items) bound (k-free-list (extract (car items) 5) bound out)))))
  (k-free-letrec (subr kmakes (k-letrec-bs k-names k-names) k-names)
    (lambda (bs bound out)
      (if (null? bs)
          out
          (k-free-letrec (cdr bs) bound (k-free-into (extract (car bs) 3) bound out)))))
  (k-free-let (subr kmakes (k-let-bs k-names k-names) k-names)
    (lambda (bs bound out)
      (if (null? bs)
          out
          (k-free-let (cdr bs) bound (k-free-into (extract (car bs) 2) bound out)))))
  (k-free-arms (subr kmakes (k-arms k-names k-names) k-names)
    (lambda (arms bound out)
      (if (null? arms)
          out
          (let ((arm (car arms)))
            (k-free-arms (cdr arms) bound
                         (k-free-into (extract arm 4) (k-names-onto (extract arm 3) bound) out))))))
  ;; A `tagcase`'s `else` arm, if any: its body's, its variable bound.
  (k-free-else (subr kmakes (k-let-bs k-names k-names) k-names)
    (lambda (els bound out)
      (if (null? els)
          out
          (k-free-into (extract (car els) 2) (cons (extract (car els) 1) bound) out)))))

;;; ------------------------------------------------------------ free variables

(define k-free-vars (subr kmakes (kx) k-names)
  (lambda (x) (k-free-into x nil nil)))

;;; ------------------------------------------------------------ substitution

(define k-ty-rank (subr (maxeff kreads spin) (int) int)
  (lambda (t)
    (tagcase (k-get t)
      (ty-base (s) 0) (ty-void () 1) (ty-var (v) 2) (ty-subr (e ps r cv) 3) (ty-poly (bs x) 4)
      (ty-ref (x r) 5) (ty-pair (x y r nl) 6) (ty-tag (x y e r) 7) (ty-comp (x y e r) 8)
      (ty-markkey (x r) 9) (ty-product (ps) 10) (ty-sum (ps) 11) (ty-array (x r) 12)
      (ty-bloblet (fs z r) 13) (ty-link (x) 14) (ty-icell (x r) 15) (ty-place (r) 16)
      (ty-named (g ds) 17) (ty-nlist (e z r) 18) (ty-nat (z) 19)
      (ty-module (abs ds vs) 20) (ty-select (m n) 21) (ty-param (k n) 22)
      (ty-lam (bs x) 23) (ty-app (f ds) 24) (ty-nil () 25) (ty-union (ms) 26)
      (ty-proving (t e) 27) (ty-false () 28))))
;; Whether no instantiation of `pattern` could fit `actual`.
;; Whether a lemma's side `pat` could fit `t`, by their outermost shapes.
(define k-lemma-head? (subr (maxeff kreads spin) (k-binders int int) bool)
  (lambda (bs pat t)
    (let ((p (k-resolve pat)))
      (tagcase (k-get p)
        (ty-var (v) (or (k-binder-has? bs v) (= (k-ty-rank p) (k-ty-rank t))))
        (ty-named (g xs) (tagcase (k-get t) (ty-named (h ys) (= g h)) (else z #f)))
        (else z (= (k-ty-rank p) (k-ty-rank t)))))))
;; Whether lemma `l`'s two sides could fit `a` and `b`, by their outermost
;; shapes.
(define k-lemma-heads? (subr (maxeff kreads spin) (k-lemma int int) bool)
  (lambda (l a b)
    (let ((bs (extract l 1)))
      (and (k-lemma-head? bs (extract l 2) a) (k-lemma-head? bs (extract l 3) b)))))
(define k-lemma-may-apply? (subr (maxeff kreads spin) ((listof k-lemma acyclic) int int) bool)
  (lambda (ls a b)
    (and (not (null? ls))
         (or (k-lemma-heads? (car ls) a b)
             (k-lemma-may-apply? (cdr ls) a b)))))
(define k-pair-seen? (subr kreads (k-pairs int int) bool)
  (lambda (xs a b)
    (and (not (null? xs))
         (or (and (= (car (car xs)) a) (= (cdr (car xs)) b)) (k-pair-seen? (cdr xs) a b)))))
(define k-all-bound? (subr kreads (k-binders k-map) bool)
  (lambda (bs m)
    (or (null? bs)
        (and (not (null? (k-map-find m (extract (car bs) 1)))) (k-all-bound? (cdr bs) m)))))
(define k-subst-hyps (subr (maxeff kstate spin) (k-hyps k-map) k-hyps)
  (lambda (hs m)
    (if (null? hs)
        nil
        (let* ((x (k-subst (car (car hs)) m)) (y (k-subst (cdr (car hs)) m)))
          (the k-hyps (cons (cons x y) (k-subst-hyps (cdr hs) m)))))))
;; The `g`th generative type's representation, for `ds`.
(define k-unfold (subr (maxeff kstate spin) (int k-descs) int)
  (lambda (g ds)
    (let ((gen (k-gen-of g))) (k-subst (extract gen 4) (k-gen-map (extract gen 2) ds)))))

;; `b`'s binders renamed to `a`'s, for comparing under them.
(define k-rename (subr (maxeff kstate spin) (k-binders k-binders) k-map)
  (lambda (bs as)
    (if (null? bs)
        nil
        (let* ((vb (extract (car bs) 1)) (k (extract (car bs) 2)) (va (extract (car as) 1))
               (d (k-binder-desc k va))
               (rest (k-rename (cdr bs) (cdr as))))
          (cons (cons vb d) rest)))))
(define k-same-kinds? (subr kreads (k-binders k-binders) bool)
  (lambda (xs ys)
    (cond ((null? xs) (null? ys))
          ((null? ys) #f)
          (else (and (= (extract (car xs) 2) (extract (car ys) 2))
                     (k-same-kinds? (cdr xs) (cdr ys))))))))))
