;;; The checker, in FX-26: the rules, each expression's type and effect,
;;; one recursive group: every expression's (`check-synth.fx`'s helpers
;;; before it), and `module`'s and `with`'s, whose items are expressions
;;; (`check-module-rules.fx`'s helpers before it). Part of the checker,
;;; `check-types.fx` first (PLAN.md §11, step 10).

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
(let* ((check-types-types (load-module "fx26:check-types-types.fx"))
       (check-infer-types (load-module "fx26:check-infer-types.fx"))
       (check-binders-types (load-module "fx26:check-binders-types.fx"))
       (check-synth-types (load-module "fx26:check-synth-types.fx"))
       (check-resolve-types (load-module "fx26:check-resolve-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-module-rules-types (load-module "fx26:check-module-rules-types.fx"))
       (check-subtype-types (load-module "fx26:check-subtype-types.fx"))
       (check-sub-env-types (load-module "fx26:check-sub-env-types.fx"))
       (check-test-facts-types (load-module "fx26:check-test-facts-types.fx"))
       (check-modorder-types (load-module "fx26:check-modorder-types.fx"))
       (eager-reader-types ((proj (load-module "fx26:eager-reader-types.fx") @s @e @m @c)))
       (check-errors-types (load-module "fx26:check-errors-types.fx"))
       (check-expect-types (load-module "fx26:check-expect-types.fx"))
       (check-letrec-types (load-module "fx26:check-letrec-types.fx"))
       (check-dependent-types (load-module "fx26:check-dependent-types.fx"))
       (check-read-descs-types (load-module "fx26:check-read-descs-types.fx"))
       (check-proving-types (load-module "fx26:check-proving-types.fx"))
       (check-close-types (load-module "fx26:check-close-types.fx"))
       (check-print-types (load-module "fx26:check-print-types.fx"))
       (check-terminate-types (load-module "fx26:check-terminate-types.fx"))
       (check-sc-graphs-types (load-module "fx26:check-sc-graphs-types.fx"))
       (check-unions-types (load-module "fx26:check-unions-types.fx"))
       (check-modules-types (load-module "fx26:check-modules-types.fx"))
       (check-modules-read-types (load-module "fx26:check-modules-read-types.fx"))
       (check-effects-types (load-module "fx26:check-effects-types.fx"))
       (check-data-types (load-module "fx26:check-data-types.fx"))
       (check-read-types (load-module "fx26:check-read-types.fx"))
       (check-mask-types (load-module "fx26:check-mask-types.fx"))
       (check-calls-types (load-module "fx26:check-calls-types.fx"))
       (check-bounds-types (load-module "fx26:check-bounds-types.fx"))
       (check-holds-types (load-module "fx26:check-holds-types.fx"))
       (check-subst-types (load-module "fx26:check-subst-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-infer (select check-infer-types check-infer-sig))
           (check-synth (select check-synth-types check-synth-sig))
           (check-errors (select check-errors-types check-errors-sig))
           (check-resolve (select check-resolve-types check-resolve-sig))
           (check-env (select check-env-types check-env-sig))
           (check-expect (select check-expect-types check-expect-sig))
           (check-letrec (select check-letrec-types check-letrec-sig))
           (check-dependent (select check-dependent-types check-dependent-sig))
           (check-module-rules (select check-module-rules-types check-module-rules-sig))
           (check-read-descs (select check-read-descs-types check-read-descs-sig))
           (check-proving (select check-proving-types check-proving-sig))
           (check-test-facts (select check-test-facts-types check-test-facts-sig))
           (check-close (select check-close-types check-close-sig))
           (check-print (select check-print-types check-print-sig))
           (check-terminate (select check-terminate-types check-terminate-sig))
           (check-modorder (select check-modorder-types check-modorder-sig))
           (check-unions (select check-unions-types check-unions-sig))
           (check-modules (select check-modules-types check-modules-sig))
           (check-effects (select check-effects-types check-effects-sig))
           (check-data (select check-data-types check-data-sig))
           (check-read (select check-read-types check-read-sig))
           (check-mask (select check-mask-types check-mask-sig))
           (check-calls (select check-calls-types check-calls-sig))
           (check-bounds (select check-bounds-types check-bounds-sig))
           (check-holds (select check-holds-types check-holds-sig))
           (check-subtype (select check-subtype-types check-subtype-sig))
           (check-subst (select check-subst-types check-subst-sig))
           (check-sc-graphs (select check-sc-graphs-types check-sc-graphs-sig))
           (check-binders (select check-binders-types check-binders-sig))
           (check-sub-env (select check-sub-env-types check-sub-env-sig))
           (check-modules-read (select check-modules-read-types check-modules-read-sig)))
    (module

;; The types it uses of the files before it.
(define a-alloc (with check-types-types a-alloc))
(define a-comefrom (with check-types-types a-comefrom))
(define a-goto (with check-types-types a-goto))
(define a-read (with check-types-types a-read))
(define a-spin (with check-types-types a-spin))
(define-effect checks (select check-types-types checks))
(define de (with check-types-types de))
(define dt (with check-types-types dt))
(define-type k-binders (select check-types-types k-binders))
(define-type k-eff (select check-types-types k-eff))
(define-type k-ids (select check-types-types k-ids))
(define-type k-item (select check-types-types k-item))
(define-type k-parts (select check-types-types k-parts))
(define-type k-regions (select check-types-types k-regions))
(define-type k-te (select check-types-types k-te))
(define-type k-ty (select check-types-types k-ty))
(define-type kx (select check-types-types kx))
(define-type kxs (select check-types-types kxs))
(define r-frozen (with check-types-types r-frozen))
(define sz-finite (with check-types-types sz-finite))
(define ty-app (with check-types-types ty-app))
(define ty-bloblet (with check-types-types ty-bloblet))
(define ty-lam (with check-types-types ty-lam))
(define ty-module (with check-types-types ty-module))
(define ty-nat (with check-types-types ty-nat))
(define ty-nlist (with check-types-types ty-nlist))
(define ty-pair (with check-types-types ty-pair))
(define ty-poly (with check-types-types ty-poly))
(define ty-product (with check-types-types ty-product))
(define ty-subr (with check-types-types ty-subr))
(define ty-sum (with check-types-types ty-sum))
(define ty-tag (with check-types-types ty-tag))
(define ty-var (with check-types-types ty-var))
(define ty-void (with check-types-types ty-void))
(define x-app (with check-types-types x-app))
(define x-begin (with check-types-types x-begin))
(define x-bloblet (with check-types-types x-bloblet))
(define x-const (with check-types-types x-const))
(define x-convention (with check-types-types x-convention))
(define x-extract (with check-types-types x-extract))
(define x-if (with check-types-types x-if))
(define x-lambda (with check-types-types x-lambda))
(define x-let (with check-types-types x-let))
(define x-letrec (with check-types-types x-letrec))
(define x-letregion (with check-types-types x-letregion))
(define x-module (with check-types-types x-module))
(define x-plambda (with check-types-types x-plambda))
(define x-product (with check-types-types x-product))
(define x-proj (with check-types-types x-proj))
(define x-prompt (with check-types-types x-prompt))
(define x-rlambda (with check-types-types x-rlambda))
(define x-sum (with check-types-types x-sum))
(define x-tagcase (with check-types-types x-tagcase))
(define x-the (with check-types-types x-the))
(define x-var (with check-types-types x-var))
(define x-with (with check-types-types x-with))
(define-type k-items (select check-types-types k-items))
(define-type k-solved (select check-infer-types k-solved))
(define-type k-done (select check-synth-types k-done))
(define-type k-types-eff (select check-synth-types k-types-eff))
(define-type k-arms (select check-resolve-types k-arms))
(define-type k-callable (select check-resolve-types k-callable))
(define-type k-let-bs (select check-resolve-types k-let-bs))
(define-type k-letrec-bs (select check-resolve-types k-letrec-bs))
(define-type k-bindings (select check-env-types k-bindings))
(define-type k-eff-ty (select check-module-rules-types k-eff-ty))
(define-type k-ends (select check-module-rules-types k-ends))
(define-type k-made (select check-module-rules-types k-made))
(define-type k-mod-checked (select check-module-rules-types k-mod-checked))
(define-type k-saying (select check-subtype-types k-saying))
(define-type k-cert-lens (select check-test-facts-types k-cert-lens))
(define-type k-maybe-size (select check-test-facts-types k-maybe-size))
(define-type k-groups (select check-modorder-types k-groups))
(define-type k-mlams (select check-modorder-types k-mlams))
(define-type result (select eager-reader-types result))
;; What it uses of the modules it is given.
(define k-cat3 (with check-types k-cat3))
(define k-cat4 (with check-types k-cat4))
(define k-cat5 (with check-types k-cat5))
(define k-certified (with check-types k-certified))
(define k-certified-lengths (with check-types k-certified-lengths))
(define k-certified-nats (with check-types k-certified-nats))
(define k-closure-depth (with check-types k-closure-depth))
(define k-fail (with check-types k-fail))
(define k-freezing (with check-types k-freezing))
(define k-get (with check-types k-get))
(define k-has-id? (with check-types k-has-id?))
(define k-length (with check-types k-length))
(define k-recursive (with check-types k-recursive))
(define k-resolve (with check-types k-resolve))
(define k-skolems (with check-types k-skolems))
(define k-std-binding? (with check-types k-std-binding?))
(define k-std-type (with check-types k-std-type))
(define k-te (with check-types k-te))
(define k-ty-new (with check-types k-ty-new))
(define k-written (with check-types k-written))
(define k-any-unknown-type? (with check-infer k-any-unknown-type?))
(define k-beyond (with check-infer k-beyond))
(define k-binders-of (with check-binders k-binders-of))
(define k-cannot-take-apart (with check-infer k-cannot-take-apart))
(define k-default-regions (with check-binders k-default-regions))
(define k-finitized (with check-binders k-finitized))
(define k-forget-nats (with check-binders k-forget-nats))
(define k-inst-shapes (with check-infer k-inst-shapes))
(define k-instantiate-against (with check-infer k-instantiate-against))
(define k-mentions-any-unknown? (with check-infer k-mentions-any-unknown?))
(define k-mentions-unknown-type? (with check-infer k-mentions-unknown-type?))
(define k-named-since (with check-binders k-named-since))
(define k-plambda-matches? (with check-infer k-plambda-matches?))
(define k-push-ids (with check-infer k-push-ids))
(define k-reaches-only? (with check-infer k-reaches-only?))
(define k-result-shape (with check-infer k-result-shape))
(define k-same-labels? (with check-infer k-same-labels?))
(define k-variants-not-named (with check-infer k-variants-not-named))
(define k-zip-fields (with check-infer k-zip-fields))
(define k-arg-found (with check-synth k-arg-found))
(define k-arg-unified (with check-synth k-arg-unified))
(define k-arms-type (with check-synth k-arms-type))
(define k-as-expected (with check-synth k-as-expected))
(define k-as-expected-call (with check-synth k-as-expected-call))
(define k-bind-place (with check-synth k-bind-place))
(define k-bloblet-field (with check-synth k-bloblet-field))
(define k-bloblet-want (with check-synth k-bloblet-want))
(define k-bounded-arg (with check-synth k-bounded-arg))
(define k-certified-arg? (with check-synth k-certified-arg?))
(define k-enter-else (with check-synth k-enter-else))
(define k-enter-then (with check-synth k-enter-then))
(define k-fail-no-arm (with check-synth k-fail-no-arm))
(define k-fx-poly-check (with check-synth k-fx-poly-check))
(define k-handler-callable (with check-synth k-handler-callable))
(define k-join-branches (with check-synth k-join-branches))
(define k-kill-paths (with check-synth k-kill-paths))
(define k-leave-test (with check-synth k-leave-test))
(define k-literal-within? (with check-synth k-literal-within?))
(define k-masked (with check-synth k-masked))
(define k-may-be-empty? (with check-synth k-may-be-empty?))
(define k-new-subr (with check-synth k-new-subr))
(define k-nil-told (with check-synth k-nil-told))
(define k-nlist-te (with check-synth k-nlist-te))
(define k-note-apply-shares (with check-synth k-note-apply-shares))
(define k-note-extract (with check-synth k-note-extract))
(define k-partial-pair-arg (with check-synth k-partial-pair-arg))
(define k-path-te (with check-synth k-path-te))
(define k-place-region (with check-synth k-place-region))
(define k-poly-var-at (with check-synth k-poly-var-at))
(define k-projected (with check-synth k-projected))
(define k-region-form (with check-synth k-region-form))
(define k-solved-instance (with check-synth k-solved-instance))
(define k-te-masked (with check-synth k-te-masked))
(define k-te-onto (with check-synth k-te-onto))
(define k-te-reading (with check-synth k-te-reading))
(define k-te-writing (with check-synth k-te-writing))
(define k-thunk-lambda? (with check-synth k-thunk-lambda?))
(define k-unify-above (with check-synth k-unify-above))
(define k-widen-nil-tail (with check-synth k-widen-nil-tail))
(define k-with-used (with check-synth k-with-used))
(define k-argument-error (with check-errors k-argument-error))
(define k-fail-arg-count (with check-errors k-fail-arg-count))
(define k-fail-arity (with check-errors k-fail-arity))
(define k-fail-at (with check-errors k-fail-at))
(define k-fail-beyond (with check-errors k-fail-beyond))
(define k-fail-effect (with check-errors k-fail-effect))
(define k-fail-frozen (with check-errors k-fail-frozen))
(define k-fail-impure-plambda (with check-errors k-fail-impure-plambda))
(define k-fail-no-part (with check-errors k-fail-no-part))
(define k-fail-not-data (with check-errors k-fail-not-data))
(define k-fail-not-frozen (with check-errors k-fail-not-frozen))
(define k-fail-not-known (with check-errors k-fail-not-known))
(define k-fail-ty (with check-errors k-fail-ty))
(define k-fail-ty-at (with check-errors k-fail-ty-at))
(define k-handler-gives (with check-errors k-handler-gives))
(define k-proj-count-error (with check-errors k-proj-count-error))
(define k-prompt-body-error (with check-errors k-prompt-body-error))
(define k-as-subr (with check-resolve k-as-subr))
(define k-callee-of (with check-resolve k-callee-of))
(define k-conversion-name (with check-resolve k-conversion-name))
(define k-end (with check-resolve k-end))
(define k-free-vars (with check-resolve k-free-vars))
(define k-rename (with check-resolve k-rename))
(define k-start (with check-resolve k-start))
(define k-vsubr-parts (with check-resolve k-vsubr-parts))
(define k-bind (with check-env k-bind))
(define k-bool (with check-env k-bool))
(define k-extracts (with check-env k-extracts))
(define k-fresh-region (with check-env k-fresh-region))
(define k-fx-module? (with check-env k-fx-module?))
(define k-fx-name (with check-env k-fx-name))
(define k-hide-mark (with check-env k-hide-mark))
(define k-int (with check-env k-int))
(define k-last-latent (with check-env k-last-latent))
(define k-lookup (with check-env k-lookup))
(define k-mark (with check-env k-mark))
(define k-named-only (with check-env k-named-only))
(define k-note-with (with check-env k-note-with))
(define k-operator (with check-env k-operator))
(define k-operator-mark (with check-env k-operator-mark))
(define k-operator? (with check-env k-operator?))
(define k-second-class? (with check-env k-second-class?))
(define k-unbind-to (with check-env k-unbind-to))
(define k-unbound (with check-env k-unbound))
(define k-unit (with check-env k-unit))
(define k-bind-all (with check-expect k-bind-all))
(define k-bind-named (with check-expect k-bind-named))
(define k-binding-types (with check-expect k-binding-types))
(define k-conversion (with check-expect k-conversion))
(define k-convert-at (with check-expect k-convert-at))
(define k-expect (with check-expect k-expect))
(define k-generalizable? (with check-expect k-generalizable?))
(define k-lambda? (with check-expect k-lambda?))
(define k-name-nat (with check-expect k-name-nat))
(define k-naming-effect (with check-expect k-naming-effect))
(define k-needs-telling? (with check-expect k-needs-telling?))
(define k-note-let-lambdas (with check-expect k-note-let-lambdas))
(define k-param-types (with check-expect k-param-types))
(define k-rewriting (with check-expect k-rewriting))
(define k-some-untyped? (with check-expect k-some-untyped?))
(define k-bind-group (with check-letrec k-bind-group))
(define k-globals-of (with check-letrec k-globals-of))
(define k-letrec-checked (with check-letrec k-letrec-checked))
(define k-note-ending (with check-letrec k-note-ending))
(define k-with-latent (with check-letrec k-with-latent))
(define k-bind-params (with check-dependent k-bind-params))
(define k-dependent-callee (with check-dependent k-dependent-callee))
(define k-instantiate-params (with check-dependent k-instantiate-params))
(define k-result-back (with check-dependent k-result-back))
(define k-bind-parts (with check-module-rules k-bind-parts))
(define k-comp-names (with check-module-rules k-comp-names))
(define k-ends-with (with check-module-rules k-ends-with))
(define k-group-end (with check-module-rules k-group-end))
(define k-made-of (with check-module-rules k-made-of))
(define k-mod-bind (with check-module-rules k-mod-bind))
(define k-mod-bindings (with check-module-rules k-mod-bindings))
(define k-mod-early (with check-module-rules k-mod-early))
(define k-mod-vals (with check-module-rules k-mod-vals))
(define k-other-member (with check-module-rules k-other-member))
(define k-parts-modules (with check-module-rules k-parts-modules))
(define k-rebind-top (with check-module-rules k-rebind-top))
(define k-saying (with check-module-rules k-saying))
(define k-star-mistake (with check-module-rules k-star-mistake))
(define k-vals-known (with check-module-rules k-vals-known))
(define k-binders-as-descs (with check-read-descs k-binders-as-descs))
(define k-part-onto (with check-read-descs k-part-onto))
(define k-parts-reversed (with check-read-descs k-parts-reversed))
(define k-call-te (with check-proving k-call-te))
(define k-cert-len-has? (with check-test-facts k-cert-len-has?))
(define k-length-arg (with check-test-facts k-length-arg))
(define k-nat-arith-size (with check-test-facts k-nat-arith-size))
(define k-natural-by-itself? (with check-test-facts k-natural-by-itself?))
(define k-operand-size (with check-test-facts k-operand-size))
(define k-size-any? (with check-test-facts k-size-any?))
(define k-close-region (with check-close k-close-region))
(define k-frozen (with check-close k-frozen))
(define k-frozen-result (with check-close k-frozen-result))
(define k-note-effect (with check-close k-note-effect))
(define k-conv=? (with check-print k-conv=?))
(define k-show-ty (with check-print k-show-ty))
(define k-size-nonneg? (with check-print k-size-nonneg?))
(define k-size-plus (with check-print k-size-plus))
(define k-declaring (with check-terminate k-declaring))
(define k-fail-not-lambda (with check-terminate k-fail-not-lambda))
(define k-op-either? (with check-sc-graphs k-op-either?))
(define k-sc-two? (with check-sc-graphs k-sc-two?))
(define k-std? (with check-terminate k-std?))
(define k-early-modules (with check-modorder k-early-modules))
(define k-lambda-item? (with check-modorder k-lambda-item?))
(define k-mod-edges (with check-modorder k-mod-edges))
(define k-mod-groups (with check-modorder k-mod-groups))
(define k-mod-hazards (with check-modorder k-mod-hazards))
(define k-mod-lambdas (with check-modorder k-mod-lambdas))
(define k-mod-recs-lambdas (with check-modorder k-mod-recs-lambdas))
(define k-mod-star-lambdas (with check-modorder k-mod-star-lambdas))
(define k-false-expected? (with check-unions k-false-expected?))
(define k-in-loaded (with check-modules-read k-in-loaded))
(define k-letrec-selected (with check-modules k-letrec-selected))
(define k-resolve-selects (with check-modules k-resolve-selects))
(define k-insert (with check-effects k-insert))
(define k-one (with check-effects k-one))
(define k-union (with check-effects k-union))
(define k-is-data? (with check-data k-is-data?))
(define k-items (with check-read k-items))
(define k-mask (with check-mask k-mask))
(define k-may-spin? (with check-calls k-may-spin?))
(define k-std-op (with check-calls k-std-op))
(define k-under (with check-calls k-under))
(define k-new-bounded-solved (with check-bounds k-new-bounded-solved))
(define k-no-knot (with check-holds k-no-knot))
(define k-part-find (with check-sub-env k-part-find))
(define k-part-index (with check-subtype k-part-index))
(define k-part-of (with check-subtype k-part-of))
(define k-subtype (with check-subtype k-subtype))
(define k-subst (with check-subst k-subst))

(define-rec
  (k-synth (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (let* ((r (k-synth-node x)) (e (k-frozen x (extract r 2))))
        (begin (k-note-effect x e) (k-kill-paths e) (k-path-te x (k-te (extract r 1) e))))))
  (k-synth-node (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (tagcase x
        (x-var (s a b)
          (if (and (k-second-class? s) (k-std? s) (not (k-operator? s a b)))
              (k-fail (k-named-only s) a b)
              (let ((t (k-lookup s)))
                (if (< t 0) (k-fail (k-unbound s) a b) (k-te t (k-naming-effect s t))))))
        (x-const (t v a b) (k-te t nil))
        (x-lambda (ps body a b) (k-synth-lambda-as x nil -1))
        (x-app (f args a b) (k-synth-app x f args -1))
        (x-the (t0 e a b) (let ((t (k-resolve-selects t0 a b))) (k-te t (k-check e t))))
        (x-convention (c e a b)
          (let* ((r (k-synth e)) (t (k-resolve (extract r 1))))
            (tagcase (k-get t)
              (ty-subr (fe ps res from)
                (begin (if (k-conv=? from c) #u (k-convert-at x t c))
                       (k-te (k-ty-new (ty-subr fe ps res c)) (extract r 2))))
              (else y (k-fail-ty "`convention` takes a procedure, and this is a " t a b)))))
        (x-plambda (bs body a b)
          (let ((r (k-synth body)))
            (if (k-generalizable? body (extract r 2))
                (k-te (k-ty-new (ty-poly bs (extract r 1))) (extract r 2))
                (k-fail-impure-plambda (extract r 2) a b))))
        (x-rlambda (r l a b) (k-synth-rlambda x r l -1))
        (x-proj (body ds a b)
          (let* ((r (k-synth body)) (t (extract r 1)))
            (tagcase (k-get t)
              (ty-poly (bs inner)
                (if (not (= (k-length bs) (k-length ds)))
                    (k-fail (k-proj-count-error bs ds) a b)
                    (let ((result (k-projected bs ds inner a b)))
                      (k-te-masked x result (extract r 2)))))
              (else y (k-fail-ty "`proj` needs a polymorphic value, not a " t a b)))))
        (x-if (p c d a b)
          (let ((rp (k-synth p)))
            (if (not (k-subtype (extract rp 1) k-bool))
                (k-fail "an `if` test must be a bool" (k-start p) (k-end p))
                (let* ((tested (k-enter-then p))
                       (rc (k-synth c))
                       (between (k-enter-else tested))
                       (rd (k-synth d))
                       (left (k-leave-test tested))
                       (t (k-join-branches (extract rc 1) (extract rd 1) a b))
                       (e (k-union (extract rp 2) (k-union (extract rc 2) (extract rd 2)))))
                  (k-te-masked x t e)))))
        (x-letrec (bs0 body a b)
          (let ((saved (k-mark)) (rsaved (get k-recursive)) (bs (k-letrec-selected bs0 a b)))
            (begin
              ;; A group whose every run ends needs no `spin`.
              (k-bind-group bs)
              ;; The body's calls of the group are not recursion.
              (let* ((ie (k-letrec-checked bs saved rsaved k-check k-check-letrec))
                     (restored (set k-recursive rsaved))
                     (rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (k-te-masked x (extract rb 1) (k-union ie (extract rb 2))))))))
        (x-let (bs body a b)
          (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
            (begin
              (k-bind-named (extract inits 1))
              (k-note-let-lambdas bs)
              (let ((rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (let ((t (k-forget-nats named (extract rb 1) a b)))
                    (k-te-masked x t (k-union (extract inits 2) (extract rb 2)))))))))
        (x-prompt (t body h a b) (k-synth-prompt x t body h))
        ;; The region's name is a variable too, of type `(place r)`, when
        ;; the form makes a place.
        (x-letregion (k r i body a b)
          (let* ((saved (k-mark))
                 (bound (if (or (= k 0) (= k 3)) #u (k-bind-place r)))
                 (freezing (get k-freezing))
                 (pushed (if (= k 3) (set k-freezing (cons r freezing)) #u))
                 (rb (k-synth body))
                 (rt (extract rb 1))
                 (written (k-has-id? (get k-written) r))
                 (popped (set k-freezing freezing)))
            (begin
              (k-unbind-to saved)
              (let ((t (if (= k 3) (k-frozen-result r i written rt a b) rt)))
                (k-close-region x (k-region-form k) r t (extract rb 2) a b)))))
        (x-bloblet (op i args a b) (k-synth-bloblet x op i args -1))
        (x-product (fs a b)
          (let* ((r (k-synth-fields fs)) (t (k-ty-new (ty-product (extract r 1)))))
            (k-te-masked x t (extract r 2))))
        (x-extract (e l a b)
          (let* ((r (k-synth e)) (pt (extract r 1)))
            (tagcase (k-get pt)
              (ty-product (fs)
                (let ((t (k-part-find fs l)))
                  (if (< t 0)
                      (k-fail-no-part pt " has no " l a b)
                      (begin (k-note-extract a b (k-part-index fs l 0))
                             (k-te-masked x t (extract r 2))))))
              (else y (k-fail-ty-at "a product is expected here, and this is a " pt e)))))
        (x-sum (l e a b)
          (let* ((r (k-synth e))
                 (t (k-ty-new (ty-sum (cons (product (1 l) (2 (extract r 1))) nil)))))
            (k-te-masked x t (extract r 2))))
        (x-tagcase (s arms els a b) (k-synth-tagcase x s arms els -1))
        (x-begin (xs a b) (k-masked x (k-synth-seq xs k-unit nil)))
        (x-module (items a b) (k-module-rule x))
        (x-with (m body a b) (k-module-rule x)))))
  (k-synth-seq (subr (maxeff checks spin) (kxs int k-eff) k-te)
    (lambda (xs last e)
      (if (null? xs)
          (k-te last e)
          (let ((r (k-synth (car xs))))
            (k-synth-seq (cdr xs) (extract r 1) (k-union e (extract r 2)))))))
  (k-synth-fields (subr (maxeff checks spin) (k-let-bs) (productof (1 k-parts) (2 k-eff)))
    (lambda (fs)
      (if (null? fs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car fs) 2))) (rest (k-synth-fields (cdr fs)))
                 (part (product (1 (extract (car fs) 1)) (2 (extract r 1)))))
            (product (1 (cons part (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-synth-lets (subr (maxeff checks spin) (k-let-bs) (productof (1 k-bindings) (2 k-eff)))
    (lambda (bs)
      (if (null? bs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car bs) 2))) (rest (k-synth-lets (cdr bs))))
            (product (1 (cons (cons (extract (car bs) 1) (extract r 1)) (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-check-letrec (subr (maxeff checks spin) (k-letrec-bs) k-eff)
    (lambda (bs)
      (if (null? bs)
          nil
          (let* ((n (extract (car bs) 1)) (t (extract (car bs) 2)) (init (extract (car bs) 3))
                 ;; Only lambdas: then nothing runs before every binding
                 ;; exists, and no one sees the knot tied.
                 (e (if (k-lambda? init) (k-check-declared n t init) (k-fail-not-lambda n init)))
                 (rest (k-check-letrec (cdr bs))))
            (k-union e rest)))))
  ;; Check `init` against `t`, the type `n` is declared; an error at `init`
  ;; itself says so.
  (k-check-declared (subr (maxeff checks spin) (symbol int kx) k-eff)
    (lambda (n t init)
      (let ((r (k-declaring (lambda () (k-te t (k-check init t))) (k-start init) (k-end init) n t)))
        (extract r 2))))
  ;;; ------------------------------------------------------------ lambda

  ;; A `lambda`'s type. `hint` supplies the types of parameters the program
  ;; left out; `result`, when not -1, is what the body is checked against.
  (k-synth-lambda-as (subr (maxeff checks spin) (kx k-ids int) k-te)
    (lambda (x hint result)
      (tagcase x
        (x-lambda (ps body a b)
          (let* ((given (k-param-types ps hint a b))
                 (saved (k-mark))
                 (named (get k-skolems))
                 ;; Bound in order, a dependent procedure's (`check-modules.fx`).
                 (dep (k-bind-params given a b))
                 (typed (extract dep 1))
                 (want (if (>= result 0) (k-instantiate-params result (extract dep 2)) -1)))
            (let* ((deeper (set k-closure-depth (+ (get k-closure-depth) 1)))
                   (r (if (>= want 0)
                          (k-te-masked body want (k-check body want))
                          (k-masked body (k-synth body)))))
              (begin
                (k-unbind-to saved) (set k-closure-depth (- (get k-closure-depth) 1))
                (set k-last-latent (extract r 2))
                (let ((res (k-forget-nats named (k-result-back (extract r 1) (extract dep 3)) a b)))
                  (k-te (k-new-subr (extract r 2) (k-binding-types typed) res) nil))))))
        (else y (k-fail-at "a lambda" x)))))
  ;; An `rlambda`'s type: its `lambda`'s, told `expected`'s parameter and
  ;; result types if it is a subroutine's, with `(read R)` in its latent
  ;; effect, since calling it reads the closure; making it allocates in `R`,
  ;; the region `r` names.
  (k-synth-rlambda (subr (maxeff checks spin) (kx kx kx int) k-te)
    (lambda (x r l expected)
      (let* ((rr (k-synth r))
             (rt (extract rr 1))
             (g (k-place-region rt (k-start r) (k-end r)))
             (c (if (< expected 0) (the (listof k-callable acyclic) nil) (k-as-subr expected)))
             (n (tagcase l (x-lambda (ps body a b) (k-length ps)) (else y 0)))
             (lt (cond
                   ((null? c) (k-synth-lambda-as l nil -1))
                   ((not (= (k-length (extract (car c) 2)) n))
                    (k-fail-arity (k-length (extract (car c) 2)) "rlambda" n (k-start x) (k-end x)))
                   (else (k-synth-lambda-as l (extract (car c) 2) (extract (car c) 3)))))
             (t (tagcase (k-get (extract lt 1))
                  (ty-subr (e ps res cv) (k-ty-new (ty-subr (k-insert (a-read g) e) ps res cv)))
                  (else y (k-fail-at "a lambda" x))))
             (e (k-insert (a-alloc g) (extract rr 2))))
        (k-te-masked x t e))))
  ;;; ------------------------------------------------------------ application
  (k-synth-app (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let ((op (begin (k-note-fx-plain-op (k-under f)) (k-std-op f))))
        (case op
          (("certify-acyclic") (k-certify x args))
          (("certify-length") (k-certify-length x args))
          (("certify-nat") (k-certify-nat x args))
          (("+" "-")
           (if (k-sc-two? args) (k-nat-arith x op args) (k-synth-app-plain x f args expected)))
          (("cons")
           (let ((r (k-nlist-cons x args expected)))
             (if (null? r) (k-synth-app-plain x f args expected) (car r))))
          (else (k-call-te (k-path-te x (k-synth-app-plain x f args expected))))))))
  ;; `+` and `-` of naturals: a natural, of a size when both are known. Only
  ;; what has a type of its own is asked for it; anything else is told it
  ;; is an int, as for any call.
  (k-nat-arith (subr (maxeff checks spin) (kx string kxs) k-te)
    (lambda (x op args)
      (let* ((ra (k-nat-operand (car args)))
             (rb (k-nat-operand (car (cdr args))))
             (za (extract ra 2)) (zb (extract rb 2))
             (sz (k-nat-arith-size op za zb))
             (t (if (null? sz) k-int (k-ty-new (ty-nat (car sz))))))
        (k-te t (k-union (extract ra 1) (extract rb 1))))))
  (k-nat-operand (subr (maxeff checks spin) (kx) (productof (1 k-eff) (2 k-maybe-size)))
    (lambda (x)
      (if (not (k-natural-by-itself? x))
          (product (1 (k-check x k-int)) (2 (the k-maybe-size nil)))
          (let* ((r (k-synth x)) (t (extract r 1)))
            (begin (k-expect x t k-int) (product (1 (extract r 2)) (2 (k-operand-size x t))))))))
  ;; `(certify-length v k)`: `v`'s value as a `(nlist T k)`, where `length-is?`
  ;; has just found it so; nowhere else.
  (k-certify-length (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (let* ((none (the k-cert-lens nil))
             (found (if (k-sc-two? args) (k-length-arg (car args) (car (cdr args))) none))
             (ok (and (not (null? found)) (k-cert-len-has? (get k-certified-lengths) (car found)))))
        (if (not ok)
            (k-fail-at (string-append "`certify-length` takes only a variable and a length "
                                      "`length-is?` has just confirmed")
                       x)
            (let* ((r (k-synth (car args))) (t (k-resolve (extract r 1)))
                   (k (extract (car found) 3)))
              (tagcase (k-get t)
                (ty-pair (e tail rg nl)
                  (if (and (= (k-resolve tail) t) (tagcase rg (r-frozen (p f) #t) (else y #f)))
                      (k-nlist-te e k rg (extract r 2))
                      (k-fail-not-frozen t x)))
                (ty-nlist (e z rg) (k-nlist-te e k rg (extract r 2)))
                (else y (k-fail-not-frozen t x))))))))
  ;; `cons` onto a `nlist`: one more element. Where a `nlist` is expected, the
  ;; tail is checked as one shorter; otherwise, a tail that is a variable of
  ;; `nlist` type gives a `nlist` one longer. None if neither.
  (k-nlist-cons (subr (maxeff checks spin) (kx kxs int) (listof k-te acyclic))
    (lambda (x args expected)
      (if (not (k-sc-two? args))
          nil
          (let ((hd (car args)) (tl (car (cdr args))))
            (let ((want (if (< expected 0) (ty-void) (k-get expected))))
              (tagcase want
                (ty-nlist (e z r)
                  (if (not (or (k-size-any? z) (k-size-nonneg? (k-size-plus z -1))))
                      (k-nlist-cons-tail hd tl)
                      (let* ((tail-ty (k-ty-new (ty-nlist e (k-size-plus z -1) r)))
                             (xe (k-check hd e))
                             (te (k-check tl tail-ty)))
                        (the (listof k-te acyclic) (cons (k-te expected (k-union xe te)) nil)))))
                (else y (k-nlist-cons-tail hd tl))))))))
  (k-nlist-cons-tail (subr (maxeff checks spin) (kx kx) (listof k-te acyclic))
    (lambda (hd tl)
      (tagcase tl
        (x-var (v va vb)
          (let ((t (k-lookup v)))
            (if (< t 0)
                nil
                (tagcase (k-get t)
                  (ty-nlist (e z r)
                    (let* ((xe (k-check hd e)) (rt (k-synth tl))
                           (longer (k-ty-new (ty-nlist e (k-size-plus z 1) r)))
                           (e (k-union xe (extract rt 2))))
                      (the (listof k-te acyclic) (cons (k-te longer e) nil))))
                  (else y nil)))))
        (else y nil))))
  ;; `(certify-nat v)`: `v`'s value as a `nat`, where `nat?` has just found
  ;; `v` no less than 0; nowhere else.
  (k-certify-nat (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (if (not (k-certified-arg? (get k-certified-nats) args))
          (k-fail-at "`certify-nat` takes only a variable `nat?` has just found no less than 0" x)
          (let ((r (k-synth (car args))))
            (begin (k-expect (car args) (extract r 1) k-int)
                   (k-te (k-ty-new (ty-nat (sz-finite))) (extract r 2)))))))
  ;; `(certify-acyclic v)`: `v`'s value at `acyclic`, where `acyclic?` has
  ;; just found `v` acyclic; nowhere else.
  (k-certify (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (if (not (k-certified-arg? (get k-certified) args))
          (k-fail-at "`certify-acyclic` takes only a variable `acyclic?` has just found acyclic" x)
          (let* ((r (k-synth (car args))) (t (extract r 1)))
            (if (k-is-data? t) (k-te (k-finitized t) (extract r 2)) (k-fail-not-data t x))))))
  ;; An application's operator, where a second-class standard operation may
  ;; be named.
  (k-synth-operator (subr (maxeff checks spin) (kx) k-te)
    (lambda (f)
      (let ((outer (get k-operator)))
        (begin (set k-operator (k-operator-mark f))
               (let ((r (k-synth f))) (begin (set k-operator outer) r))))))
  (k-synth-app-plain (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let* ((a (k-start x)) (b (k-end x))
             (rf (k-synth-operator f))
             (n (k-length args))
             (done (product (1 (the (arrayof int @t) (make-array n -1)))
                            (2 (the (arrayof k-eff @t) (make-array n nil)))))
             (ft (tagcase (k-get (extract rf 1))
                   (ty-poly (bs body)
                     (let ((inst (k-instantiate (extract rf 1) args expected a b done f)))
                       (begin (k-no-knot inst a b) inst)))
                   (else y (extract rf 1))))
             (callee (k-dependent-callee (k-as-subr ft) args a b))
             (variadic (k-vsubr-parts ft)))
        (cond
          ;; Any number of arguments, each of the element type.
          ((not (null? variadic))
           (let ((v (car variadic)))
             (k-app-result x f ft args (k-vapp-args args (extract v 2) 0 (extract rf 2))
                           (extract v 1) (extract v 3))))
          ((null? callee) (k-fail-ty "not a subroutine: " ft a b))
          ((not (= (k-length (extract (car callee) 2)) n))
           (k-fail-arg-count (k-length (extract (car callee) 2)) n a b))
          (else
           (let* ((c (car callee))
                  (e (k-app-args args (extract c 2) 0 done (extract rf 2))))
             (begin
               (k-note-apply-shares x f (extract c 2))
               (k-app-result x f ft args e (extract c 1) (extract c 3)))))))))
  ;; A call's type and effect, once its arguments have effect `e`: its
  ;; callee's latent effect too, `spin` where the call may loop, and what
  ;; the call masks; its result, of type `result`.
  (k-app-result (subr (maxeff checks spin) (kx kx int kxs k-eff k-eff int) k-te)
    (lambda (x f ft args e latent result)
      (let* ((e (k-union e latent))
             (e (if (k-may-spin? f ft args) (k-insert (a-spin) e) e)))
        (k-te-masked x result e))))
  (k-app-args (subr (maxeff checks spin) (kxs k-ids int k-done k-eff) k-eff)
    (lambda (args params i done e)
      (if (null? args)
          e
          (let* ((t (array-ref (extract done 1) i))
                 (ae (k-app-arg (car args) (car params) i t (array-ref (extract done 2) i))))
            (k-app-args (cdr args) (cdr params) (+ i 1) done (k-union e ae))))))
  ;; Argument `i`, `arg`, for a parameter of type `p`: its effect. Where it was found a `t` (≥ 0)
  ;; of effect `e`, that, converted if need be; checked against `p` where not.
  (k-app-arg (subr (maxeff checks spin) (kx int int int k-eff) k-eff)
    (lambda (arg p i t e)
      (cond ((< t 0) (k-check-argument arg p i))
            ((k-subtype t p) e)
            (else
             (let ((c (k-conversion t p)))
               (if (null? c)
                   (k-fail-at (k-argument-error i (k-show-ty t) (k-show-ty p)) arg)
                   (begin (k-convert-at arg t (car c)) e)))))))
  ;; A `vsubr` call's arguments, each checked as its element type `t`.
  (k-vapp-args (subr (maxeff checks spin) (kxs int int k-eff) k-eff)
    (lambda (args t i e)
      (if (null? args)
          e
          (k-vapp-args (cdr args) t (+ i 1) (k-union e (k-check-argument (car args) t i))))))
  ;; An argument that failed to check is reported as that argument.
  (k-check-argument (subr (maxeff checks spin) (kx int int) k-eff)
    (lambda (arg p i)
      (let ((r (k-rewriting (lambda () (k-te p (k-check arg p))) (k-start arg) (k-end arg)
                            (lambda (m want got) (k-argument-error i got want)))))
        (extract r 2))))
  (k-instantiate (subr (maxeff checks spin) (int kxs int int int k-done kx) int)
    (lambda (ft args expected a b done f)
      (let* ((bo (k-binders-of ft)) (kinds (extract bo 1)) (inner (extract bo 2))
             (callee (k-callee-of inner (k-length args))))
        (if (null? callee)
            (k-fail-ty "not a subroutine, even once projected: " ft a b)
            (let ((params (extract (car callee) 2)) (result (extract (car callee) 3))
                  (solved (k-new-bounded-solved)))
              (if (not (= (k-length params) (k-length args)))
                  (k-fail-arg-count (k-length params) (k-length args) a b)
                  (begin
                    (if (>= expected 0) (k-unify-above result expected kinds solved) #u)
                    (k-inst-asked args params 0 kinds solved done)
                    (k-partial-pair-arg f (extract done 1) params kinds solved)
                    ;; A shape conflict is the error to report, before any
                    ;; binder is found unsolved (`DONE.md` §20).
                    (k-result-shape expected result kinds solved a b)
                    (k-inst-shapes args params 0 kinds solved (extract done 1))
                    (k-inst-told args params 0 kinds solved done)
                    (k-inst-shapes args params 0 kinds solved (extract done 1))
                    (k-default-regions kinds solved)
                    (if (< expected 0) (k-widen-nil-tail result kinds solved) #u)
                    (k-solved-instance kinds solved a b ft inner))))))))
  ;; What the arguments are, except the ones that need to be told.
  (k-inst-asked (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved k-done) unit)
    (lambda (args params i kinds solved done)
      (if (null? args)
          #u
          (begin
            (if (k-needs-telling? (car args))
                #u
                (let ((p (k-subst (car params) (get solved))))
                  (if (not (k-mentions-any-unknown? p kinds solved))
                      (k-bounded-arg (car args) (car params) p kinds solved done i k-check k-synth)
                      (let ((r (k-synth (car args))))
                        (tagcase (k-get (extract r 1))
                          (ty-poly (bs body) #u)
                          (else y (k-arg-unified (car params) kinds solved done i r)))))))
            (k-inst-asked (cdr args) (cdr params) (+ i 1) kinds solved done)))))
  ;; The arguments that needed telling: each is checked against its parameter
  ;; as solved so far, and what it turns out to be solves more.
  (k-inst-told (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved k-done) unit)
    (lambda (args params i kinds solved done)
      (if (null? args)
          #u
          (begin
            (if (>= (array-ref (extract done 1) i) 0)
                #u
                (let* ((arg (car args))
                       (defaulted (k-default-regions kinds solved))
                       (p (k-subst (car params) (get solved))))
                  (cond
                    ;; A thunk has no parameters to be told: told nothing, it
                    ;; says what it is, as any argument does.
                    ((and (k-needs-telling? arg) (null? (k-as-subr p)) (k-thunk-lambda? arg))
                     (k-arg-unified (car params) kinds solved done i (k-synth arg)))
                    ((k-needs-telling? arg)
                     (let ((c (k-as-subr p)))
                       (if (or (null? c) (k-any-unknown-type? (extract (car c) 2) kinds solved))
                           (k-fail-not-known arg i p)
                           (let* ((res (extract (car c) 3))
                                  (known (if (k-mentions-unknown-type? res kinds solved) -1 res))
                                  (r (k-synth-lambda-as arg (extract (car c) 2) known)))
                             (k-arg-unified (car params) kinds solved done i r)))))
                    ((k-mentions-unknown-type? p kinds solved)
                     (k-nil-told arg i p (car params) kinds solved done))
                    ;; A variable of a polymorphic type: instantiated at the
                    ;; parameter, and what it turns out to be solves more
                    ;; (`(apply list xs)`: `apply`'s effect).
                    (else
                     (let ((pv (k-poly-var-at arg p)))
                       (if (null? pv)
                           (k-arg-found done i p (k-check arg p))
                           (k-arg-unified (car params) kinds solved done i (car pv))))))))
            (k-inst-told (cdr args) (cdr params) (+ i 1) kinds solved done)))))
  ;;; ------------------------------------------------------------ check mode
  (k-check (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let ((e (k-frozen x (k-check-mode x expected))))
        (begin (k-note-effect x e) (k-kill-paths e) e))))
  (k-check-mode (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let* ((et (k-get expected))
             (poly? (tagcase et (ty-poly (bs body) #t) (else y #f)))
             (plambda? (tagcase x (x-plambda (bs body a b) #t) (else y #f)))
             ;; A `let` passes a `poly` to its body, and must then be pure.
             (let? (tagcase x (x-let (bs body a b) #t) (else y #f))))
        (cond
          ((and poly? let?)
           (let ((e (k-check-node x expected et)))
             (if (k-generalizable? x e)
                 e
                 (k-fail-effect "a polymorphic value must be pure, and this has " e
                                (k-start x) (k-end x)))))
          ((and poly? (not plambda?))
           (tagcase et
             (ty-poly (bs body)
               (let ((e (k-check x body)))
                 (if (k-generalizable? x e)
                     e
                     (k-fail-effect "a polymorphic value must be pure, and this has " e
                                    (k-start x) (k-end x)))))
             (else y nil)))
          ((and poly? plambda? (k-plambda-matches? x et))
           (tagcase x
             (x-plambda (binders body a b)
               (tagcase et
                 (ty-poly (bs want)
                   (let* ((want (k-subst want (k-rename bs binders))) (e (k-check body want)))
                     (if (k-generalizable? body e) e (k-fail-impure-plambda e a b))))
                 (else y nil)))
             (else y nil)))
          (else (k-check-node x expected et))))))
  (k-check-node (subr (maxeff checks spin) (kx int k-ty) k-eff)
    (lambda (x expected et)
      (letrec ((otherwise (subr (maxeff (read @globals) checks spin) () k-eff)
                           (lambda () (k-as-expected x (k-synth x) expected))))
       (the k-eff (let ((a (k-start x)) (b (k-end x)))
        (tagcase x
          (x-lambda (ps body xa xb)
            (let ((c (k-as-subr expected)))
              (cond
                ((not (null? c))
                 (let ((want (extract (car c) 2)))
                   (if (not (= (k-length want) (k-length ps)))
                       (k-fail-arity (k-length want) "lambda" (k-length ps) a b)
                       (k-as-expected x (k-synth-lambda-as x want (extract (car c) 3)) expected))))
                ((k-some-untyped? ps) (k-fail-ty "a `lambda` cannot be a " expected a b))
                (else (otherwise)))))
          (x-rlambda (r l xa xb)
            (if (null? (k-as-subr expected))
                (otherwise)
                (k-as-expected x (k-synth-rlambda x r l expected) expected)))
          (x-app (f args xa xb) (k-as-expected-call x (k-synth-app x f args expected) expected))
          (x-bloblet (op i args xa xb)
            (k-as-expected x (k-synth-bloblet x op i args expected) expected))
          (x-tagcase (s arms els xa xb) (extract (k-synth-tagcase x s arms els expected) 2))
          (x-product (fs xa xb)
            (tagcase et
              (ty-product (want)
                (if (k-same-labels? fs want)
                    (k-mask x (k-check-fields fs want) expected)
                    (otherwise)))
              (else y (otherwise))))
          (x-sum (l e xa xb)
            (tagcase et
              (ty-sum (vs)
                (let ((t (k-part-find vs l)))
                  (if (>= t 0) (k-mask x (k-check e t) expected) (otherwise))))
              (else y (otherwise))))
          ;; A natural literal is a `nat`, and a `(nat k)`.
          ;; `#f` where `false` is expected, or a union with it.
          (x-const (ty k xa xb)
            (if (or (and (= ty k-int) (k-literal-within? et k))
                    (and (= ty k-bool) (= k 0) (k-false-expected? expected)))
                nil
                (otherwise)))
          (x-var (s xa xb)
            (let ((t (k-lookup s)))
              (cond
               ;; `nil` is a `nlist` of no elements, or of some.
               ((and (string=? (symbol->string s) "nil") (>= t 0) (k-std-binding? s t)
                     (k-may-be-empty? et))
                nil)
               ((and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #t) (else y #f)))
                (let ((inst (k-instantiate-against t expected a b)))
                  (begin (k-expect x inst expected) (k-naming-effect s t))))
               (else (otherwise)))))
          (x-with (m body xa xb)
            (let ((r (k-fx-poly-check x m body expected)))
              (if (null? r) (otherwise) (begin (k-note-fx-plain body a b) (car r)))))
          (x-if (p c d xa xb)
            (let* ((pe (k-check p k-bool))
                   (tested (k-enter-then p))
                   (ce (k-check c expected))
                   (between (k-enter-else tested))
                   (de (k-check d expected))
                   (left (k-leave-test tested)))
              (k-mask x (k-union pe (k-union ce de)) expected)))
          (x-begin (xs xa xb)
            (let ((e (k-check-seq xs expected nil)))
              (k-mask x e expected)))
          ;; A `letrec`'s body, as a `let`'s, against what is expected.
          (x-letrec (bs0 body xa xb)
            (let ((saved (k-mark)) (rsaved (get k-recursive)) (bs (k-letrec-selected bs0 a b)))
              (begin
                (k-bind-group bs)
                (let* ((ie (k-letrec-checked bs saved rsaved k-check k-check-letrec))
                       (restored (set k-recursive rsaved))
                       (e (k-check body expected)))
                  (begin (k-unbind-to saved) (k-mask x (k-union ie e) expected))))))
          (x-let (bs body xa xb)
            (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
              (begin
                (k-bind-named (extract inits 1))
                (k-note-let-lambdas bs)
                (let ((e (k-check body expected)))
                  (begin (k-unbind-to saved)
                         (set k-skolems named)
                         (k-mask x (k-union (extract inits 2) e) expected))))))
          (else y (otherwise))))))))
  (k-check-seq (subr (maxeff checks spin) (kxs int k-eff) k-eff)
    (lambda (xs expected e)
      (if (null? (cdr xs))
          (k-union e (k-check (car xs) expected))
          (let ((r (k-synth (car xs))))
            (k-check-seq (cdr xs) expected (k-union e (extract r 2)))))))
  (k-check-fields (subr (maxeff checks spin) (k-let-bs k-parts) k-eff)
    (lambda (fs ps)
      (if (null? fs)
          nil
          (let* ((e (k-check (extract (car fs) 2) (extract (car ps) 2)))
                 (rest (k-check-fields (cdr fs) (cdr ps))))
            (k-union e rest)))))
  ;; `body`'s type and effect: checked against `expected` if that is given (≥ 0), found if not.
  (k-synth-as (subr (maxeff checks spin) (kx int) k-te)
    (lambda (body expected)
      (if (>= expected 0) (k-te expected (k-check body expected)) (k-synth body))))
  (k-synth-tagcase (subr (maxeff checks spin) (kx kx k-arms k-let-bs int) k-te)
    (lambda (x s arms els expected)
      (let* ((rs (k-synth s)) (st (extract rs 1)))
        (tagcase (k-get st)
          (ty-sum (variants)
            (let* ((arm-results (k-tagcase-arms arms variants st expected))
                   (rest (k-variants-not-named variants arms))
                   (e (k-union (extract rs 2) (extract arm-results 2)))
                   (armed (product (1 (extract arm-results 1)) (2 e)))
                   (both (k-tagcase-else x armed rest els expected))
                   (t (k-arms-type x (extract both 1) expected)))
              (k-te-masked x t (extract both 2))))
          (else y (k-fail-ty-at "a sum is expected here, and this is a " st s))))))
  ;; A `tagcase`'s arms' types and effect, `armed`, with its `else`, `els`, if any, for the
  ;; variants `rest` not named; an error at `x` if it has none, and some are not named.
  (k-tagcase-else (subr (maxeff checks spin) (kx k-types-eff k-parts k-let-bs int) k-types-eff)
    (lambda (x armed rest els expected)
      (if (null? els)
          (if (null? rest) armed (k-fail-no-arm rest x))
          (let* ((y (extract (car els) 1)) (body (extract (car els) 2))
                 (rest-ty (k-ty-new (ty-sum rest)))
                 (r (k-in-scope-check y rest-ty body expected)))
            (product (1 (k-push-ids (extract armed 1) (cons (extract r 1) nil)))
                     (2 (k-union (extract armed 2) (extract r 2))))))))
  ;; Each arm: its type and the effects of all.
  (k-tagcase-arms (subr (maxeff checks spin) (k-arms k-parts int int) k-types-eff)
    (lambda (arms variants st expected)
      (if (null? arms)
          (product (1 nil) (2 nil))
          (let* ((arm (car arms)) (tag (extract arm 1)) (body (extract arm 4))
                 (t (k-part-find variants tag)))
            (if (< t 0)
                (k-fail-no-part st " has no tag " tag (k-start body) (k-end body))
                (let* ((bound (if (extract arm 2)
                                  (tagcase (k-get t)
                                    (ty-product (fs)
                                      (if (= (k-length fs) (k-length (extract arm 3)))
                                          (k-zip-fields (extract arm 3) fs)
                                          (k-cannot-take-apart tag t (extract arm 3) body)))
                                    (else y (k-cannot-take-apart tag t (extract arm 3) body)))
                                  (the k-bindings (cons (cons (car (extract arm 3)) t) nil))))
                       (saved (k-mark))
                       (r (begin
                            (k-bind-all bound)
                            (k-synth-as body expected)))
                       (restored (k-unbind-to saved))
                       (rest (k-tagcase-arms (cdr arms) variants st expected)))
                  (k-te-onto r rest)))))))
  (k-in-scope-check (subr (maxeff checks spin) (symbol int kx int) k-te)
    (lambda (y t body expected)
      (let ((saved (k-mark)))
        (begin
          (k-bind y t)
          (let ((r (k-synth-as body expected)))
            (begin (k-unbind-to saved) r))))))
  ;;; ------------------------------------------------------------ bloblets
  (k-synth-bloblet (subr (maxeff checks spin) (kx symbol int kxs int) k-te)
    (lambda (x op i args expected)
      (let ((name (symbol->string op)))
        (if (k-op-either? name "make-bloblet" "rmake-bloblet")
            ;; `rmake-bloblet`'s region is its first operand's; `make-bloblet`'s
            ;; the type it is checked against, or a fresh one.
            (k-make-bloblet x (string=? name "rmake-bloblet") args expected)
            (k-bloblet-op x name i args)))))
  ;; `(make-bloblet n f …)`, or, if `rm`, `(rmake-bloblet r n f …)`.
  (k-make-bloblet (subr (maxeff checks spin) (kx bool kxs int) k-te)
    (lambda (x rm args expected)
      (let* ((a (k-start x)) (b (k-end x))
             (gr (if rm (k-synth (car args)) (k-te k-unit (the k-eff nil))))
             (given (the k-regions (if rm (cons (k-place-region (extract gr 1) a b) nil) nil)))
             (args (if rm (cdr args) args))
             (e (k-union (extract gr 2) (k-check (car args) k-int)))
             (fields (cdr args))
             (want (k-bloblet-want expected fields given))
             (made (if (null? want)
                       (let ((r (k-synth-each fields)))
                         (product (1 (extract r 1)) (2 (extract r 2))
                                  (3 (if (null? given) (k-fresh-region "bloblet") (car given)))))
                       (tagcase (car want)
                         (ty-bloblet (fs z r) (product (1 fs) (2 (k-check-each fields fs)) (3 r)))
                         (else y (k-fail "a bloblet" a b)))))
             (region (extract made 3))
             (e (k-insert (a-alloc region) (k-union e (extract made 2))))
             (t (k-ty-new (ty-bloblet (extract made 1) #f region)))
             (unknotted (k-no-knot t a b)))
        (k-te-masked x t e))))
  ;; `(name bx i rest …)`: a bloblet's field `i` read or written, it frozen, or a byte of it.
  (k-bloblet-op (subr (maxeff checks spin) (kx string int kxs) k-te)
    (lambda (x name i args)
      (let* ((a (k-start x)) (b (k-end x))
             (bx (car args)) (rest (cdr args)) (rb (k-synth bx)) (bt (extract rb 1)))
        (tagcase (k-get bt)
          (ty-bloblet (fields frozen region)
            (let* ((e (extract rb 2))
                   (te
                    (case name
                      (("bloblet-ref")
                       (let ((t (k-bloblet-field bt fields i a b)))
                         (if frozen (k-te t e) (k-te-reading t region e))))
                      (("bloblet-set!")
                       (let ((t (k-bloblet-field bt fields i a b)))
                         (if frozen
                             (k-fail-frozen bt a b)
                             (k-te-writing k-unit region (k-union e (k-check (car rest) t))))))
                      (("bloblet-freeze")
                       (k-te-writing (k-ty-new (ty-bloblet fields #t region)) region e))
                      (("bloblet-byte")
                       (k-te-reading k-int region (k-union e (k-check (car rest) k-int))))
                      (("bloblet-set-byte!")
                       (let* ((e1 (k-check (car rest) k-int)) (e2 (k-check (car (cdr rest)) k-int)))
                         (k-te-writing k-unit region (k-union e (k-union e1 e2)))))
                      (else (k-te k-int e)))))
              (k-masked x te)))
          (else y (k-fail-ty-at "a bloblet is expected here, and this is a " bt bx))))))
  (k-synth-each (subr (maxeff checks spin) (kxs) k-types-eff)
    (lambda (xs)
      (if (null? xs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (car xs))) (rest (k-synth-each (cdr xs))))
            (k-te-onto r rest)))))
  (k-check-each (subr (maxeff checks spin) (kxs k-ids) k-eff)
    (lambda (xs ts)
      (if (null? xs)
          nil
          (let* ((e (k-check (car xs) (car ts))) (rest (k-check-each (cdr xs) (cdr ts))))
            (k-union e rest)))))
  ;;; ------------------------------------------------------------ prompts
  ;;; The tag's type fixes what crosses the prompt, and the body's effect must
  ;;; be within the tag's bound apart from control on its region. Then the
  ;;; prompt delimits: that control is removed, if the body can reach no other
  ;;; tag in the region.
  (k-synth-prompt (subr (maxeff checks spin) (kx kx kx kx) k-te)
    (lambda (x tag body handler)
      (let* ((rt (k-synth tag)) (tt (extract rt 1)))
        (tagcase (k-get tt)
          (ty-tag (answer payload bound region)
            (let* ((be (k-prompt-body body answer))
                   (own (k-insert (a-goto region) (k-one (a-comefrom region))))
                   (beyond (k-beyond be bound own)))
              (if (not (null? beyond))
                  (k-fail-beyond body bound beyond)
                  (let* ((rh (k-synth-handler handler payload answer))
                         (c (k-handler-callable handler (extract rh 1) payload answer))
                         (only (k-reaches-only? body tag region))
                         (delimited (if only (k-beyond be nil own) be))
                         (e (k-union (extract rh 2) (k-union (extract c 1) delimited))))
                    (k-te-masked x answer (k-union (extract rt 2) e))))))
          (else y (k-fail-ty-at "a prompt needs a prompt tag, not a " tt tag))))))
  ;; A prompt's body's effect, checked as an `answer`, the type the tag's prompts deliver.
  (k-prompt-body (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (body answer)
      (let ((r (k-rewriting (lambda () (k-te answer (k-check body answer)))
                            (k-start body) (k-end body)
                            (lambda (m want got) (k-prompt-body-error want got)))))
        (extract r 2))))
  ;; A handler written as a `lambda` of one parameter is told what it takes
  ;; and gives.
  (k-synth-handler (subr (maxeff checks spin) (kx int int) k-te)
    (lambda (h payload answer)
      (tagcase h
        (x-lambda (ps hbody a b)
          (if (= (k-length ps) 1)
              (k-rewriting (lambda () (k-synth-lambda-as h (cons payload nil) answer))
                           (k-start hbody) (k-end hbody)
                           (lambda (m want got) (k-handler-gives payload answer got)))
              (k-synth h)))
        (else y (k-synth h)))))
  ;;; ----------------------------------------------- `module` and `with`
  ;; The effect of `name`, the lambda `x` of `define*`, checked again at `tf`,
  ;; the type found.
  (k-star-checked (subr (maxeff checks spin) (symbol int kx) k-eff)
    (lambda (name tf x)
      (let ((r (k-saying (lambda () (k-te tf (k-check-declared name tf x)))
                         (lambda (m) (k-star-mistake name tf m)))))
        (extract r 2))))
  ;; An abstract type `t`, its representation seen only through its own
  ;; conversions, which stay inside the module: each the identity, made as a
  ;; closure is, checked on its representation and bound at `t`. A type
  ;; constructor's representation is a `dlambda` of its parameters: its
  ;; conversions are polymorphic in them, as FX-91's at a higher kind.
  (k-module-abs (subr (maxeff checks spin) (k-item int int k-made) k-made)
    (lambda (it a b made)
      (let* ((n (car (extract it 2)))
             (v (extract it 3))
             (whole (car (extract it 4)))
             (bs (tagcase (k-get whole) (ty-lam (bs body) bs) (else x (the k-binders nil))))
             (inner (tagcase (k-get whole)
                      (ty-lam (bs body) (tagcase body (dt (t) t) (else x whole)))
                      (else x whole)))
             (rep (k-resolve-selects inner a b))
             (var (k-ty-new (ty-var v)))
             (t (if (null? bs) var (k-ty-new (ty-app var (k-binders-as-descs bs)))))
             (identity (k-new-subr nil (the k-ids (cons rep nil)) rep))
             (fns (extract it 5))
             (up (k-check (car fns) identity))
             (down (k-check (car (cdr fns)) identity))
             (up-t (k-new-subr nil (the k-ids (cons rep nil)) t))
             (down-t (k-new-subr nil (the k-ids (cons t nil)) rep)))
        (begin
          (k-bind (k-conversion-name "up-" n) (if (null? bs) up-t (k-ty-new (ty-poly bs up-t))))
          (k-bind (k-conversion-name "down-" n)
                  (if (null? bs) down-t (k-ty-new (ty-poly bs down-t))))
          (k-made-of (k-part-onto n v (extract made 1)) (extract made 2) (extract made 3)
                     (extract made 4))))))
  ;; A value: checked against its type, if it has one, or found; bound, its
  ;; sizes and abstract types named for it, for the items after it.
  (k-module-val (subr (maxeff checks spin) (k-item int int k-made) k-made)
    (lambda (it a b made)
      (let* ((n (car (extract it 2)))
             (ts (extract it 4))
             (init (car (extract it 5)))
             (r (if (null? ts)
                    (k-synth init)
                    (let ((t (k-resolve-selects (car ts) a b))) (k-te t (k-check init t)))))
             (bound (k-bind n (k-name-nat n (extract r 1)))))
        (k-made-of (extract made 1) (extract made 2) (k-part-onto n (extract r 1) (extract made 3))
                   (k-union (extract made 4) (extract r 2))))))
  ;; Lambda `init`, `n`'s, checked against `t`; a `define-rec` member's
  ;; error said as of its declared type.
  (k-mod-check-one (subr (maxeff checks spin) (symbol int kx bool) k-eff)
    (lambda (n t init rec) (if rec (k-check-declared n t init) (k-check init t))))
  ;; A module's `define*` `n`, its lambda `init`, of type `decl` as written:
  ;; checked at `w`, its type reading any global, then at the type with the
  ;; globals its body read, found, its binding given that type, as a
  ;; top-level `define*` is. Only in a group of one (itself, if it calls
  ;; itself), as at the top level, where a `define*` is in no `define-rec`.
  ;; The effect, and the type found.
  (k-mod-star (subr (maxeff checks spin) (symbol int kx int k-letrec-bs string) k-eff-ty)
    (lambda (n w init decl group why)
      (let ((other (k-other-member group n)))
        (if (not (null? other))
            (begin (k-fail-at (k-cat5 "`define*` `" (symbol->string n)
                                      "` is in a recursive group with `"
                                      (symbol->string (extract (car other) 1)) "`: use `define`")
                              init)
                   (product (1 (the k-eff nil)) (2 w)))
            (let* ((rsaved (get k-recursive))
                   ;; Bound at its type as written while it is first checked,
                   ;; as a top-level `define*` is: a call of itself reads
                   ;; nothing more.
                   (as-written (k-rebind-top n decl))
                   (noted (if (null? group) #u (k-note-ending group why)))
                   (e0 (k-check-declared n w init))
                   (restored (set k-recursive rsaved))
                   (f (k-with-latent decl (k-globals-of (get k-last-latent))))
                   (rebound (k-rebind-top n f))
                   (again (the k-letrec-bs (cons (product (1 n) (2 f) (3 init)) nil)))
                   (renoted (if (null? group) #u (k-note-ending again why)))
                   (e (k-star-checked n f init))
                   (back (set k-recursive rsaved)))
              (product (1 e) (2 f)))))))
  (k-mod-check-lambdas
    (subr (maxeff checks spin) (k-letrec-bs k-mlams k-groups k-ends k-ids) k-mod-checked)
    (lambda (bs ls gs ws ds)
      (if (null? bs)
          (product (1 (the k-eff nil)) (2 (the k-letrec-bs nil)))
          (let* ((n (extract (car bs) 1)) (t (extract (car bs) 2)) (init (extract (car bs) 3))
                 (group (car gs))
                 (whys (k-ends-with ws group))
                 (why (if (null? group) "" (k-group-end whys group)))
                 (r (if (extract (car ls) 6)
                        (k-mod-star n t init (car ds) group why)
                        (let* ((rsaved (get k-recursive))
                               (noted (if (null? group) #u (k-note-ending group why)))
                               (e (k-mod-check-one n t init (extract (car ls) 5)))
                               (restored (set k-recursive rsaved)))
                          (product (1 e) (2 t)))))
                 (rest (k-mod-check-lambdas (cdr bs) (cdr ls) (cdr gs) whys (cdr ds))))
            (product (1 (k-union (extract r 1) (extract rest 1)))
                     (2 (the k-letrec-bs (cons (product (1 n) (2 (extract r 2)) (3 init))
                                               (extract rest 2)))))))))
  ;; Items `items` but typed lambdas, each in the scope of those before it
  ;; and of the typed lambdas.
  (k-module-items (subr (maxeff checks spin) (k-items int int k-made) k-made)
    (lambda (items a b made)
      (if (null? items)
          made
          (let* ((it (car items))
                 (k (extract it 1))
                 (next (cond
                         ((= k 0) (k-module-abs it a b made))
                         ((or (< k 0) (> k 3)) made)
                         ((= k 1)
                          (let ((t (k-resolve-selects (car (extract it 4)) a b)))
                            (k-made-of (extract made 1)
                                       (k-part-onto (car (extract it 2)) t (extract made 2))
                                       (extract made 3) (extract made 4))))
                         ;; Typed lambdas are checked after the rest; early ones before.
                         ((k-lambda-item? it) made)
                         ((>= (k-part-of (extract made 3) (car (extract it 2))) 0) made)
                         ((= k 2) (k-module-val it a b made))
                         (else made))))
            (k-module-items (cdr items) a b next)))))
  ;; `(module item …)`, as a `letrec*` (`check-modorder.fx`): its typed
  ;; lambdas bound first, at their written types; every other item checked in
  ;; order, in the scope of those and the items before it; then the lambdas,
  ;; in the scope of everything. The module's type, its abstract types bound
  ;; in it.
  (k-synth-module-here (subr (maxeff checks spin) (kx k-items int int) k-te)
    (lambda (x items a b)
      (let* ((saved (k-mark))
             (named (get k-skolems))
             (ls (k-mod-lambdas items))
             (stars (k-mod-star-lambdas items))
             (recs (k-mod-recs-lambdas ls))
             ;; Its modules as written first, for its lambdas' types to select from.
             (early (k-mod-early items (k-early-modules items)
                                 (lambda (it m) (k-module-val it a b m))
                                 (k-made-of nil nil nil nil)))
             (hazards (k-mod-hazards items ls (k-parts-modules (extract early 3))))
             (bound-ds (k-mod-bindings ls a b))
             (bs (extract bound-ds 1))
             (bound (k-mod-bind bs ls))
             (made (k-module-items items a b early))
             (es (k-mod-edges ls ls))
             (gs (k-mod-groups es bs bs))
             (checked (k-mod-check-lambdas bs ls gs nil (extract bound-ds 2)))
             (le (extract checked 1))
             (unbound (k-unbind-to saved))
             (vs (k-parts-reversed (k-mod-vals items (extract made 3) (extract checked 2) nil) nil))
             ;; A component's module, bound inside, has abstract types no one
             ;; outside can name.
             (known (k-vals-known vs (k-named-since named (get k-skolems) nil) a b))
             (popped (set k-skolems named))
             (abs (k-parts-reversed (extract made 1) nil))
             (t (k-ty-new (ty-module abs (k-parts-reversed (extract made 2) nil) vs))))
        (k-te-masked x t (k-union (extract made 4) le)))))
  ;; The same; a module read from a file (`load-module`, M7) seeing only the
  ;; standard environment, what is wrong in it said where it is read.
  (k-synth-module (subr (maxeff checks spin) (kx k-items int int) k-te)
    (lambda (x items a b)
      (let ((k (if (null? items) 0 (extract (car items) 1))))
        (if (< k 4)
            (k-synth-module-here x items a b)
            (let ((got (the (ref k-te @t) (new (k-te 0 nil)))) (hid (get k-hide-mark)))
              (begin (set k-hide-mark (k-mark))
                     (k-in-loaded (lambda () (set got (k-synth-module-here x items a b))) k a b)
                     (set k-hide-mark hid)
                     (get got)))))))
  ;; `(with m body)`: the body with `m`'s values in scope, by name, at their
  ;; types for `m`.
  (k-synth-with (subr (maxeff checks spin) (kx symbol kx int int) k-te)
    (lambda (x m body a b)
      (let ((mt (k-lookup m)) (shown (symbol->string m)))
        (if (k-fx-module? m)
            (k-synth-fx x mt body a b)
        (if (< mt 0)
            (k-fail (k-cat3 "`" shown "` is not bound") a b)
            (tagcase (k-get mt)
              (ty-module (abs ds vs)
                (let* ((used (k-with-used vs (k-free-vars body) 0))
                       (noted (k-note-with
                                (product (1 a) (2 b) (3 (k-comp-names (extract used 1)))
                                         (4 (extract used 2)))))
                       (naming (k-naming-effect m mt))
                       (saved (k-mark))
                       (bound (k-bind-parts (extract used 1)))
                       (r (k-synth body))
                       (unbound (k-unbind-to saved)))
                  (k-te-masked x (extract r 1) (k-union naming (extract r 2)))))
              (else y
                (let ((what (k-show-ty mt)))
                  (k-fail (k-cat4 "`with` opens a module, and `" shown "` is a " what) a b)))))))))
  ;; `(with #%fx n)`: the standard `n`'s type, whatever binds `n` since.
  (k-synth-fx (subr (maxeff checks spin) (kx int kx int int) k-te)
    (lambda (x mt body a b)
      (cond ((>= mt 0)
             (k-fail "`#%fx` is the standard bindings' module, which nothing else may be" a b))
            (else
             (let ((t (tagcase body
                        (x-var (n c d)
                          (if (and (k-second-class? n) (not (k-operator? n a b)))
                              (k-fail (k-named-only n) a b)
                              (k-std-type n)))
                        (else y -1))))
               (if (< t 0)
                   (k-fail "`(with #%fx name)` names one standard binding" a b)
                   (begin (if (k-operator? (k-fx-name body) a b) #u (k-note-fx-plain body a b))
                          (k-te t nil))))))))
  ;; The operator `(with #%fx n)`, noted as `k-note-fx-plain` notes it, once.
  (k-note-fx-plain-op (subr (maxeff checks spin) (kx) unit)
    (lambda (f)
      (tagcase f
        (x-with (m body a b) (if (k-fx-module? m) (k-note-fx-plain body a b) #u))
        (else y #u))))
  ;; Where nothing shadows `n`, `(with #%fx n)` is the plain `n`: the fact
  ;; -502, for the compiler (the Rust checker's `fx_plain`).
  (k-note-fx-plain (subr (maxeff checks spin) (kx int int) unit)
    (lambda (body a b)
      (if (string=? (k-std-op body) "")
          #u
          (set k-extracts (cons (product (1 a) (2 b) (3 -502)) (get k-extracts))))))
  (k-module-rule (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (tagcase x
        (x-module (items a b) (k-synth-module x items a b))
        (x-with (m body a b) (k-synth-with x m body a b))
        (else y (k-fail-at "a module" x)))))))))
