;;; The checker, in FX-26: the rules, each expression's type and effect.
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
(let* ((check-synth-types (load-module "fx26:check-synth-types.fx"))
       (check-types-types (load-module "fx26:check-types-types.fx"))
       (check-resolve-types (load-module "fx26:check-resolve-types.fx"))
       (check-infer-types (load-module "fx26:check-infer-types.fx"))
       (check-binders-types (load-module "fx26:check-binders-types.fx"))
       (check-subtype-types (load-module "fx26:check-subtype-types.fx"))
       (check-sub-env-types (load-module "fx26:check-sub-env-types.fx"))
       (parser-types ((proj (load-module "fx26:parser-types.fx") @s @e @m @c @p)))
       (eager-reader-types ((proj (load-module "fx26:eager-reader-types.fx") @s @e @m @c)))
       (check-test-facts-types (load-module "fx26:check-test-facts-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-facts-types (load-module "fx26:check-facts-types.fx"))
       (check-print-types (load-module "fx26:check-print-types.fx"))
       (check-bounds-types (load-module "fx26:check-bounds-types.fx"))
       (check-expect-types (load-module "fx26:check-expect-types.fx"))
       (check-errors-types (load-module "fx26:check-errors-types.fx"))
       (check-effects-types (load-module "fx26:check-effects-types.fx"))
       (check-mask-types (load-module "fx26:check-mask-types.fx"))
       (check-unions-types (load-module "fx26:check-unions-types.fx"))
       (check-terminate-types (load-module "fx26:check-terminate-types.fx"))
       (check-holds-types (load-module "fx26:check-holds-types.fx"))
       (check-calls-types (load-module "fx26:check-calls-types.fx"))
       (check-subst-types (load-module "fx26:check-subst-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-test-facts (select check-test-facts-types check-test-facts-sig))
           (check-resolve (select check-resolve-types check-resolve-sig))
           (check-env (select check-env-types check-env-sig))
           (check-infer (select check-infer-types check-infer-sig))
           (check-facts (select check-facts-types check-facts-sig))
           (check-print (select check-print-types check-print-sig))
           (check-bounds (select check-bounds-types check-bounds-sig))
           (check-expect (select check-expect-types check-expect-sig))
           (check-errors (select check-errors-types check-errors-sig))
           (check-effects (select check-effects-types check-effects-sig))
           (check-mask (select check-mask-types check-mask-sig))
           (check-unions (select check-unions-types check-unions-sig))
           (check-terminate (select check-terminate-types check-terminate-sig))
           (check-holds (select check-holds-types check-holds-sig))
           (check-subtype (select check-subtype-types check-subtype-sig))
           (check-calls (select check-calls-types check-calls-sig))
           (check-subst (select check-subst-types check-subst-sig))
           (check-binders (select check-binders-types check-binders-sig))
           (check-sub-env (select check-sub-env-types check-sub-env-sig)))
    (module
(define-type k-types-eff (select check-synth-types k-types-eff))
(define-type k-done (select check-synth-types k-done))
(define-type k-certs (select check-synth-types k-certs))
(define-type k-nar (select check-synth-types k-nar))
(define-type k-nars (select check-synth-types k-nars))
(define-type k-narrowing (select check-synth-types k-narrowing))
(define-type k-path (select check-synth-types k-path))
(define-type k-paths (select check-synth-types k-paths))
(define-type k-reached (select check-synth-types k-reached))
(define-type k-tested (select check-synth-types k-tested))
(define-type k-call-checked (select check-synth-types k-call-checked))
(define-type k-maybe-ty (select check-synth-types k-maybe-ty))
;; The types it uses of the files before it.
(define a-app (with check-types-types a-app))
(define a-await (with check-types-types a-await))
(define a-comefrom (with check-types-types a-comefrom))
(define a-goto (with check-types-types a-goto))
(define a-read (with check-types-types a-read))
(define a-var (with check-types-types a-var))
(define a-write (with check-types-types a-write))
(define-effect checks (select check-types-types checks))
(define dt (with check-types-types dt))
(define-type k-binders (select check-types-types k-binders))
(define-type k-desc (select check-types-types k-desc))
(define-type k-eff (select check-types-types k-eff))
(define-type k-ids (select check-types-types k-ids))
(define-type k-map (select check-types-types k-map))
(define-type k-named (select check-types-types k-named))
(define-type k-names (select check-types-types k-names))
(define-type k-narrows (select check-types-types k-narrows))
(define-type k-parts (select check-types-types k-parts))
(define-type k-path-facts (select check-types-types k-path-facts))
(define-type k-props (select check-types-types k-props))
(define-type k-region (select check-types-types k-region))
(define-type k-regions (select check-types-types k-regions))
(define-type k-size (select check-types-types k-size))
(define-type k-step (select check-types-types k-step))
(define-type k-steps (select check-types-types k-steps))
(define-type k-te (select check-types-types k-te))
(define-type k-ty (select check-types-types k-ty))
(define-effect kreads (select check-types-types kreads))
(define-effect kstate (select check-types-types kstate))
(define-type kx (select check-types-types kx))
(define-type kxs (select check-types-types kxs))
(define pr-shape (with check-types-types pr-shape))
(define r-frozen (with check-types-types r-frozen))
(define r-var (with check-types-types r-var))
(define st-car (with check-types-types st-car))
(define st-cdr (with check-types-types st-cdr))
(define st-field (with check-types-types st-field))
(define sz-finite (with check-types-types sz-finite))
(define ty-base (with check-types-types ty-base))
(define ty-bloblet (with check-types-types ty-bloblet))
(define ty-nat (with check-types-types ty-nat))
(define ty-nil (with check-types-types ty-nil))
(define ty-nlist (with check-types-types ty-nlist))
(define ty-pair (with check-types-types ty-pair))
(define ty-place (with check-types-types ty-place))
(define ty-poly (with check-types-types ty-poly))
(define ty-product (with check-types-types ty-product))
(define ty-subr (with check-types-types ty-subr))
(define ty-union (with check-types-types ty-union))
(define ty-var (with check-types-types ty-var))
(define x-app (with check-types-types x-app))
(define x-extract (with check-types-types x-extract))
(define x-if (with check-types-types x-if))
(define x-lambda (with check-types-types x-lambda))
(define x-var (with check-types-types x-var))
(define-type k-callable (select check-resolve-types k-callable))
(define-type k-solved (select check-infer-types k-solved))
(define-type k-trail (select check-subtype-types k-trail))
(define-type names (select parser-types names))
(define-type result (select eager-reader-types result))
;; What it uses of the modules it is given.
(define k-binder-has? (with check-types k-binder-has?))
(define k-cat4 (with check-types k-cat4))
(define k-cat5 (with check-types k-cat5))
(define k-certified (with check-types k-certified))
(define k-certified-lengths (with check-types k-certified-lengths))
(define k-certified-nats (with check-types k-certified-nats))
(define k-closure-depth (with check-types k-closure-depth))
(define k-dvar-name (with check-types k-dvar-name))
(define k-fail (with check-types k-fail))
(define k-get (with check-types k-get))
(define k-has-name? (with check-types k-has-name?))
(define k-join (with check-types k-join))
(define k-length (with check-types k-length))
(define k-narrowed (with check-types k-narrowed))
(define k-narrows (with check-types k-narrows))
(define k-nth (with check-types k-nth))
(define k-path-narrowed (with check-types k-path-narrowed))
(define k-resolve (with check-types k-resolve))
(define k-set-link (with check-types k-set-link))
(define k-slot (with check-types k-slot))
(define k-std-type (with check-types k-std-type))
(define k-te (with check-types k-te))
(define k-ty-new (with check-types k-ty-new))
(define k-arg-at (with check-test-facts k-arg-at))
(define k-latent-cert (with check-test-facts k-latent-cert))
(define k-latent-props (with check-test-facts k-latent-props))
(define k-length-test (with check-test-facts k-length-test))
(define k-size-any? (with check-test-facts k-size-any?))
(define k-as-subr (with check-resolve k-as-subr))
(define k-end (with check-resolve k-end))
(define k-start (with check-resolve k-start))
(define k-bind (with check-env k-bind))
(define k-extracts (with check-env k-extracts))
(define k-fx-module? (with check-env k-fx-module?))
(define k-lookup (with check-env k-lookup))
(define k-binding-depth (with check-binders k-binding-depth))
(define k-certified-has? (with check-binders k-certified-has?))
(define k-check-bounds (with check-binders k-check-bounds))
(define k-check-finite-sizes (with check-infer k-check-finite-sizes))
(define k-fin-region (with check-binders k-fin-region))
(define k-finish (with check-infer k-finish))
(define k-instantiate-against (with check-infer k-instantiate-against))
(define k-list-of-any? (with check-infer k-list-of-any?))
(define k-mentions-unknown-type? (with check-infer k-mentions-unknown-type?))
(define k-part-names (with check-infer k-part-names))
(define k-sc-one-arg? (with check-binders k-sc-one-arg?))
(define k-unify (with check-infer k-unify))
(define k-upper-bound (with check-infer k-upper-bound))
(define k-bool-lit? (with check-facts k-bool-lit?))
(define k-test-facts (with check-facts k-test-facts))
(define k-with-facts (with check-facts k-with-facts))
(define k-conv-default (with check-print k-conv-default))
(define k-map-find (with check-print k-map-find))
(define k-printing-none (with check-print k-printing-none))
(define k-show-list (with check-print k-show-list))
(define k-show-ty (with check-print k-show-ty))
(define k-size-eq? (with check-print k-size-eq?))
(define k-size-facts (with check-print k-size-facts))
(define k-size-le? (with check-print k-size-le?))
(define k-size-lit (with check-print k-size-lit))
(define k-drop-bounds (with check-bounds k-drop-bounds))
(define k-from-above (with check-bounds k-from-above))
(define k-map-unsettled (with check-bounds k-map-unsettled))
(define k-expect (with check-expect k-expect))
(define k-naming-effect (with check-expect k-naming-effect))
(define k-proj-map (with check-expect k-proj-map))
(define k-fail-at (with check-errors k-fail-at))
(define k-fail-not-known (with check-errors k-fail-not-known))
(define k-fail-ty (with check-errors k-fail-ty))
(define k-fail-ty-at (with check-errors k-fail-ty-at))
(define k-handler-wants (with check-errors k-handler-wants))
(define k-insert (with check-effects k-insert))
(define k-region=? (with check-effects k-region=?))
(define k-union (with check-effects k-union))
(define k-mask (with check-mask k-mask))
(define k-narrowed-by (with check-unions k-narrowed-by))
(define k-nat-ty? (with check-terminate k-nat-ty?))
(define k-no-knot (with check-holds k-no-knot))
(define k-part-find (with check-sub-env k-part-find))
(define k-subtype (with check-subtype k-subtype))
(define k-std-op (with check-calls k-std-op))
(define k-subst (with check-subst k-subst))

;; The error that a `tagcase`, `x`, has no arm for the variants `rest`.
(define k-fail-no-arm (subr (maxeff checks spin) (k-parts kx) void)
  (lambda (rest x)
    (let ((names (k-join (k-part-names rest) ", ")))
      (k-fail-at (string-append "this `tagcase` has no arm for " names) x))))
;; Whether `t` is a list at `acyclic`: a pair's type, its region frozen and
;; never written.
(define k-acyclic-list? (subr (maxeff kreads spin) (int) bool)
  (lambda (t)
    (tagcase (k-get t)
      (ty-pair (a d r nl) (tagcase r (r-frozen (p finite) finite) (else y #f)))
      (else y #f))))
;; Note, for the compilers, that a top-level definition's value `x`, of
;; type `t`, is a list in a frozen region (`acyclic` or `const`): data
;; nothing writes, which they may make once if it is made of literals; the
;; fact -501 (`c-fill-facts`). As the Rust checker's `frozen_defines`.
(define k-note-frozen-define (subr (maxeff checks spin) (int kx) unit)
  (lambda (t x)
    (if (tagcase (k-get t)
          (ty-pair (a d r nl) (tagcase r (r-frozen (p finite) #t) (else y #f)))
          (else y #f))
        (set k-extracts (cons (product (1 (k-start x)) (2 (k-end x)) (3 -501)) (get k-extracts)))
        #u)))
;; Note, for the compilers, that the call `x` of `f` (on parameters
;; `params`) is `apply` of a list at `acyclic`, which it need not copy: the
;; fact -500 (`c-fill-facts`). Every other `apply` copies its list, so that
;; the variadic procedure's is one nothing else can write.
(define k-note-apply-shares (subr (maxeff checks spin) (kx kx k-ids) unit)
  (lambda (x f params)
    (let ((apply? (string=? (k-std-op f) "apply")))
      (if (and apply? (and (= (k-length params) 2) (k-acyclic-list? (car (cdr params)))))
          (set k-extracts (cons (product (1 (k-start x)) (2 (k-end x)) (3 -500)) (get k-extracts)))
          #u))))
;; `car` or `cdr` of a union with a pair member (a `datum`, say) takes that
;; member apart: every machine's `car` checks its argument is a pair, and
;; traps if not, as it does on `nil` (TODO §51).
(define k-partial-pair-arg
  (subr (maxeff checks spin) (kx (arrayof int @t) k-ids k-binders k-solved) unit)
  (lambda (f types ps kinds solved)
    (let* ((op (k-std-op f)) (t (if (> (array-length types) 0) (array-ref types 0) -1)))
      (if (and (or (string=? op "car") (string=? op "cdr")) (>= t 0))
          (tagcase (k-get (k-resolve t))
            (ty-union (ms)
              (let ((m (k-union-pair-member ms)))
                (if (>= m 0)
                    (begin (k-unify (car ps) m kinds solved (k-new-trail)) (array-set! types 0 m))
                    #u)))
            (else y #u))
          #u))))
;; A union's member that is a pair, of members `ms`; or -1.
(define k-union-pair-member (subr (maxeff kreads spin) (k-ids) int)
  (lambda (ms)
    (cond ((null? ms) -1)
          ((tagcase (k-get (k-resolve (car ms))) (ty-pair (x d r nl) #t) (else y #f)) (car ms))
          (else (k-union-pair-member (cdr ms))))))
;; Type `t` and effect `e` of `x`, or `r`, both, with what `x` masks masked.
(define k-te-masked (subr (maxeff kstate spin) (kx int k-eff) k-te)
  (lambda (x t e) (k-te t (k-mask x e t))))
(define k-masked (subr (maxeff kstate spin) (kx k-te) k-te)
  (lambda (x r) (k-te-masked x (extract r 1) (extract r 2))))
;; `r`'s type onto `rest`'s types, and the effects of both.
(define k-te-onto (subr (maxeff kreads (alloc @t) spin) (k-te k-types-eff) k-types-eff)
  (lambda (r rest)
    (let ((ts (the k-ids (cons (extract r 1) (extract rest 1)))))
      (product (1 ts) (2 (k-union (extract r 2) (extract rest 2)))))))
;; The effect `r` says `x` has, once the type it says is found one `expected` takes.
(define k-as-expected (subr (maxeff checks spin) (kx k-te int) k-eff)
  (lambda (x r expected) (begin (k-expect x (extract r 1) expected) (extract r 2))))
;; A new `subr` type, of the default convention.
(define k-new-subr (subr (maxeff kstate spin) (k-eff k-ids int) int)
  (lambda (e ps res) (k-ty-new (ty-subr e ps res (get k-conv-default)))))
;; A `(nlist e k R)`, `R` the region `rg` made finite, and effect `eff`.
(define k-nlist-te (subr (maxeff kstate spin) (int k-size k-region k-eff) k-te)
  (lambda (e k rg eff) (k-te (k-ty-new (ty-nlist e k (k-fin-region rg))) eff)))
;; A fresh trail, for `k-unify`.
(define k-new-trail (subr (alloc @t) () k-trail) (lambda () (the k-trail (new nil))))
;; The region `r` names, bound as a variable of type `(place r)`.
(define k-bind-place (subr (maxeff kstate spin) (int) unit)
  (lambda (r) (k-bind (k-dvar-name r) (k-ty-new (ty-place (r-var r))))))
;; The form a `letregion` of kind `k` is written as.
(define k-region-form (subr pure (int) string)
  (lambda (k)
    (case k ((0) "letregion") ((1) "letrena") ((2) "letreap") (else "letfreeze"))))
;; Note, for the compiler, that the `extract` at `a`..`b` takes part `i`.
(define k-note-extract (subr kstate (int int int) unit)
  (lambda (a b i) (set k-extracts (cons (product (1 a) (2 b) (3 i)) (get k-extracts)))))
;; `inner`, under binders `bs`, with `m` for them, each within its bound and finite if need be.
(define k-subst-checked (subr (maxeff checks spin) (k-binders k-map int int int) int)
  (lambda (bs m inner a b)
    (begin (k-check-bounds bs m a b) (k-check-finite-sizes bs m inner a b) (k-subst inner m))))
;; `inner`, under binders `bs`, projected with `ds`: an error where they do not fit, or knot.
(define k-projected (subr (maxeff checks spin) (k-binders (listof k-desc acyclic) int int int) int)
  (lambda (bs ds inner a b)
    (let ((inst (k-subst-checked bs (k-proj-map bs ds a b) inner a b)))
      (begin (k-no-knot inst a b) inst))))
;; `t`, or, if a list of any elements (`nil`), the type `nil`.
(define k-nil-if-any (subr (maxeff kstate spin) (int) int)
  (lambda (t) (if (k-list-of-any? t) (k-ty-new (ty-nil)) t)))
;; `ts`, each `nil` the type `nil`: what other arms are, as in an `if`.
(define k-nils-if-any (subr (maxeff kstate spin) (k-ids) k-ids)
  (lambda (ts) (if (null? ts) nil (cons (k-nil-if-any (car ts)) (k-nils-if-any (cdr ts))))))
;; Branches' types, each `nil` the type `nil`, and, if one is, each pair one
;; that may be `nil`: their join, if they have one, is then one of them.
(define k-nil-pair (subr (maxeff kstate spin) (int) int)
  (lambda (t)
    (tagcase (k-get (k-resolve t)) (ty-pair (a d r nl) (k-ty-new (ty-pair a d r #t))) (else y t))))
(define k-nil-pairs (subr (maxeff kstate spin) (k-ids) k-ids)
  (lambda (ts) (if (null? ts) nil (cons (k-nil-pair (car ts)) (k-nil-pairs (cdr ts))))))
(define k-any-nil? (subr (maxeff kreads spin) (k-ids) bool)
  (lambda (ts)
    (and (not (null? ts))
         (or (tagcase (k-get (k-resolve (car ts))) (ty-nil () #t) (else y #f))
             (k-any-nil? (cdr ts))))))
(define k-join-with-nil (subr (maxeff kstate spin) (k-ids) k-ids)
  (lambda (ts0)
    (let ((ts (k-nils-if-any ts0))) (if (k-any-nil? ts) (k-nil-pairs ts) ts))))
;; An `if`'s type, its branches a `tc` and a `td`: the greater; an error if neither is.
(define k-join-known (subr (maxeff checks spin) (int int int int) int)
  (lambda (tc td a b)
    (cond ((k-subtype tc td) td)
          ((k-subtype td tc) tc)
          ;; Naturals of sizes not shown equal: a `nat`.
          ((and (k-nat-ty? tc) (k-nat-ty? td)) (k-ty-new (ty-nat (sz-finite))))
          (else
           (k-fail (k-cat4 "the branches are a " (k-show-ty tc) " and a " (k-show-ty td)) a b)))))
;; The same, `nil`, beside another branch, what that is if `nil` is one
;; (`TODO.md` §48); beside `nil`, the type `nil`; beside a pair, the pair
;; that may be `nil`.
(define k-join-branches (subr (maxeff checks spin) (int int int int) int)
  (lambda (tc td a b)
    (let ((ts (k-join-with-nil (list tc td)))) (k-join-known (car ts) (car (cdr ts)) a b))))
;; If `p` certifies a variable acyclic (`acyclic?`, `(acyclic i)`), it, as
;; the binding it is (none or one).
(define k-acyclic-test (subr (maxeff kreads (alloc @t) spin) (kx) k-named)
  (lambda (p) (k-latent-cert p 0)))
;; If `p` certifies a variable a natural (`nat?`, `(nat i)`), it.
(define k-nat-test (subr (maxeff kreads (alloc @t) spin) (kx) k-named)
  (lambda (p) (k-latent-cert p 1)))
(define k-certs-now (subr kreads () k-certs)
  (lambda ()
    (product (1 (get k-certified)) (2 (get k-certified-lengths)) (3 (get k-certified-nats)))))
;; Note what test `p` certifies, if anything: a variable acyclic, of a length, or natural.
(define k-push-certified (subr (maxeff kstate spin) (kx) unit)
  (lambda (p)
    (let ((cert (k-acyclic-test p)) (lens (k-length-test p)) (nats (k-nat-test p)))
      (begin
        (if (null? cert) #u (set k-certified (cons (car cert) (get k-certified))))
        (if (null? lens) #u (set k-certified-lengths (cons (car lens) (get k-certified-lengths))))
        (if (null? nats) #u (set k-certified-nats (cons (car nats) (get k-certified-nats))))))))
(define k-nars-append (subr (read @globals) (k-nars k-nars) k-nars)
  (lambda (xs ys)
    (if (null? xs) ys (the k-nars (cons (car xs) (k-nars-append (cdr xs) ys))))))
(define k-step=? (subr (read @globals) (k-step k-step) bool)
  (lambda (s u)
    (tagcase s
      (st-car () (tagcase u (st-car () #t) (else y #f)))
      (st-cdr () (tagcase u (st-cdr () #t) (else y #f)))
      (st-field (l) (tagcase u (st-field (m) (symbol=? l m)) (else y #f))))))
(define k-steps=? (subr (read @globals) (k-steps k-steps) bool)
  (lambda (xs ys)
    (if (null? xs)
        (null? ys)
        (and (not (null? ys)) (k-step=? (car xs) (car ys)) (k-steps=? (cdr xs) (cdr ys))))))
(define k-steps-snoc (subr (maxeff (read @globals) (alloc @t)) (k-steps k-step) k-steps)
  (lambda (xs s)
    (if (null? xs)
        (the k-steps (cons s nil))
        (the k-steps (cons (car xs) (k-steps-snoc (cdr xs) s))))))
(define k-path-step (subr (maxeff (read @globals) (alloc @t)) (k-paths k-step) k-paths)
  (lambda (ps s)
    (if (null? ps)
        (the k-paths nil)
        (let* ((p (car ps)) (steps (k-steps-snoc (extract p 3) s)))
          (the k-paths (cons (product (1 (extract p 1)) (2 (extract p 2)) (3 steps)) nil))))))
(define k-path-of (subr (maxeff kreads (alloc @t) spin) (kx) k-paths)
  (lambda (x)
    (tagcase x
      (x-var (v a b) (the k-paths (cons (product (1 v) (2 (k-binding-depth v)) (3 nil)) nil)))
      (x-app (f args a b)
        (let ((op (k-std-op f)))
          (if (and (k-sc-one-arg? args) (or (string=? op "car") (string=? op "cdr")))
              (k-path-step (k-path-of (car args)) (if (string=? op "car") (st-car) (st-cdr)))
              (the k-paths nil))))
      (x-extract (e l a b) (k-path-step (k-path-of e) (st-field l)))
      (else y (the k-paths nil)))))
;; The type the fact in force of the path from `v` at `d` by `steps` gives,
;; or -1.
(define k-path-fact-in (subr (maxeff kreads spin) (k-path-facts symbol int k-steps int) int)
  (lambda (fs v d steps depth)
    (cond ((null? fs) -1)
          ((let ((f (car fs)))
             (and (not (extract f 7)) (= (extract f 6) depth) (symbol=? (extract f 1) v)
                  (= (extract f 2) d) (k-steps=? (extract f 3) steps)))
           (extract (car fs) 5))
          (else (k-path-fact-in (cdr fs) v d steps depth)))))
(define k-path-fact-ty (subr (maxeff kreads spin) (symbol int k-steps) int)
  (lambda (v d steps) (k-path-fact-in (get k-path-narrowed) v d steps (get k-closure-depth))))
(define k-reached-of (subr (alloc @t) (int k-regions) k-reached)
  (lambda (t rs) (the k-reached (cons (product (1 t) (2 rs)) nil))))
;; The path from `v` at `d`, `done` taken and `rest` to go, at type `t`
;; having read through `rs`: as the types say and the facts in force
;; narrow it (`check.rs`'s `path_type`).
(define k-path-walk
  (subr (maxeff kreads (alloc @t) spin) (symbol int k-steps k-steps int k-regions) k-reached)
  (lambda (v d done rest t rs)
    (if (null? rest)
        (k-reached-of t rs)
        (let* ((s (car rest))
               (next (tagcase s
                       (st-car ()
                         (tagcase (k-get t)
                           (ty-pair (a b r nl) (k-reached-of a (cons r rs)))
                           (else y (the k-reached nil))))
                       (st-cdr ()
                         (tagcase (k-get t)
                           (ty-pair (a b r nl) (k-reached-of b (cons r rs)))
                           (else y (the k-reached nil))))
                       (st-field (l)
                         (tagcase (k-get t)
                           (ty-product (ps)
                             (let ((f (k-part-find ps l)))
                               (if (< f 0) (the k-reached nil) (k-reached-of f rs))))
                           (else y (the k-reached nil)))))))
          (if (null? next)
              (the k-reached nil)
              (let* ((now (k-steps-snoc done s))
                     (fact (k-path-fact-ty v d now))
                     (t2 (k-resolve (if (>= fact 0) fact (extract (car next) 1)))))
                (k-path-walk v d now (cdr rest) t2 (extract (car next) 2))))))))
(define k-path-type (subr (maxeff kreads (alloc @t) spin) (symbol int k-steps) k-reached)
  (lambda (v d steps)
    (let ((t (k-lookup v)))
      (if (< t 0) (the k-reached nil) (k-path-walk v d nil steps (k-resolve t) nil)))))
;; `x`'s type `t`, or, `x` a path a fact in force narrows, its type there.
(define k-path-ty (subr (maxeff kreads (alloc @t) spin) (kx int) int)
  (lambda (x t)
    (if (null? (get k-path-narrowed))
        t
        (let ((ps (k-path-of x)))
          (if (or (null? ps) (null? (extract (car ps) 3)))
              t
              (let* ((p (car ps)) (f (k-path-fact-ty (extract p 1) (extract p 2) (extract p 3))))
                (if (< f 0) t f)))))))
(define k-path-te (subr (maxeff kreads (alloc @t) spin) (kx k-te) k-te)
  (lambda (x te) (k-te (k-path-ty x (extract te 1)) (extract te 2))))
;; What `out` narrows the path from `v` at `d` by `steps` to (none or one).
(define k-nars-of (subr (maxeff kreads (alloc @t) spin) (k-nars symbol int k-steps) k-reached)
  (lambda (out v d steps)
    (cond ((null? out) (the k-reached nil))
          ((let ((n (car out)))
             (and (symbol=? (extract n 1) v) (= (extract n 2) d) (k-steps=? (extract n 3) steps)))
           (k-reached-of (extract (car out) 5) (extract (car out) 4)))
          (else (k-nars-of (cdr out) v d steps)))))
;; `out` with that path narrowed to `t`, in place of what it had.
(define k-nars-put
  (subr (maxeff (read @globals) (alloc @t) spin) (k-nars symbol int k-steps k-regions int) k-nars)
  (lambda (out v d steps rs t)
    (let ((one (product (1 v) (2 d) (3 steps) (4 rs) (5 t))))
      (cond ((null? out) (the k-nars (cons one nil)))
            ((let ((n (car out)))
               (and (symbol=? (extract n 1) v) (= (extract n 2) d) (k-steps=? (extract n 3) steps)))
             (the k-nars (cons one (cdr out))))
            (else (the k-nars (cons (car out) (k-nars-put (cdr out) v d steps rs t))))))))
;; The variables and paths among `args` narrowed by `props`, a conjunction:
;; each proposition of a shape, in turn.
(define k-props-narrow (subr (maxeff kstate spin) (k-props kxs k-nars) k-nars)
  (lambda (props args out)
    (if (null? props)
        out
        (let* ((p (car props))
               (i (tagcase p (pr-shape (i k f) i) (else y -1)))
               (x (if (< i 0) (the kxs nil) (k-arg-at args i)))
               (path (if (null? x) (the k-paths nil) (k-path-of (car x)))))
          (if (null? path)
              (k-props-narrow (cdr props) args out)
              (let* ((pt (car path)) (n (extract pt 1)) (d (extract pt 2)) (steps (extract pt 3))
                     (had (k-nars-of out n d steps))
                     (tr (if (null? had) (k-path-type n d steps) had)))
                (if (null? tr)
                    (k-props-narrow (cdr props) args out)
                    (let* ((shape (tagcase p (pr-shape (i k f) k) (else y 0)))
                           (negated (tagcase p (pr-shape (i k f) f) (else y #f)))
                           (split (k-narrowed-by (k-resolve (extract (car tr) 1)) shape))
                           (to (if negated (extract split 2) (extract split 1))))
                      (k-props-narrow
                       (cdr props) args
                       (if (< to 0) out (k-nars-put out n d steps (extract (car tr) 2) to)))))))))))
;; A test: what its callee's type says it proves (`ty-proving`), of those of
;; its arguments that are variables or paths, where it holds and where not.
(define k-latent-narrowing (subr (maxeff kstate spin) (kx) k-narrowing)
  (lambda (p)
    (let ((l (k-latent-props p)))
      (if (null? l)
          (the k-narrowing (cons nil nil))
          (let ((x (car l)))
            (cons (k-props-narrow (extract x 1) (extract x 3) nil)
                  (k-props-narrow (extract x 2) (extract x 3) nil)))))))
(define k-narrowings (subr (maxeff kstate spin) (kx) k-narrowing)
  (lambda (p)
    (let ((none (the k-narrowing (cons nil nil))))
      (tagcase p
        (x-if (q c d a b)
          (let ((nq (k-narrowings q)))
            (cond ((k-bool-lit? c #t) (cons nil (k-nars-append (cdr nq) (cdr (k-narrowings d)))))
                  ((k-bool-lit? d #f) (cons (k-nars-append (car nq) (car (k-narrowings c))) nil))
                  (else none))))
        (x-app (f args a b)
          (if (and (string=? (k-std-op f) "not") (k-sc-one-arg? args))
              (let ((ns (k-narrowings (car args)))) (cons (cdr ns) (car ns)))
              (k-latent-narrowing p)))
        (else y none)))))
;; The variables' narrowings among `ns`, as `k-narrowed` keeps them.
(define k-var-narrows (subr (maxeff (read @globals) (alloc @t)) (k-nars) k-narrows)
  (lambda (ns)
    (cond ((null? ns) nil)
          ((null? (extract (car ns) 3))
           (let ((n (car ns)))
             (the k-narrows
                  (cons (product (1 (extract n 1)) (2 (extract n 2)) (3 (extract n 5)))
                        (k-var-narrows (cdr ns))))))
          (else (k-var-narrows (cdr ns))))))
;; The paths' narrowings among `ns` put in force, in turn.
(define k-push-paths (subr kstate (k-nars) unit)
  (lambda (ns)
    (if (null? ns)
        #u
        (let ((n (car ns)))
          (begin
            (if (null? (extract n 3))
                #u
                (set k-path-narrowed
                     (cons (product (1 (extract n 1)) (2 (extract n 2)) (3 (extract n 3))
                                    (4 (extract n 4)) (5 (extract n 5))
                                    (6 (get k-closure-depth)) (7 #f))
                           (get k-path-narrowed))))
            (k-push-paths (cdr ns)))))))
;; Narrowings `ns` put in force, the variables' onto `saved`.
(define k-put-narrowing (subr kstate (k-nars k-narrows) unit)
  (lambda (ns saved)
    (begin (set k-narrowed (k-narrows-append (k-var-narrows ns) saved)) (k-push-paths ns))))
(define k-drop-facts (subr (read @globals) (k-path-facts int) k-path-facts)
  (lambda (fs m) (if (or (<= m 0) (null? fs)) fs (k-drop-facts (cdr fs) (- m 1)))))
;; The paths' facts cut back to the `n` oldest, as they are now (one an
;; effect has ended since stays ended).
(define k-cut-paths (subr kstate (int) unit)
  (lambda (n)
    (let ((fs (get k-path-narrowed)))
      (set k-path-narrowed (k-drop-facts fs (- (k-length fs) n))))))
(define k-narrows-append (subr (read @globals) (k-narrows k-narrows) k-narrows)
  (lambda (xs ys)
    (if (null? xs) ys (the k-narrows (cons (car xs) (k-narrows-append (cdr xs) ys))))))
;; What effect `e`, of an expression just checked, ends of the paths' facts
;; at this closure depth (`check.rs`'s `kill_paths`): a write to a region
;; a path reads through, or to one that may be it (a region variable may be
;; any region), and any transfer of control or effect not known. A path
;; through frozen data, or products' fields alone, is never written.
(define k-may-alias? (subr (maxeff (read @globals) spin) (k-region k-region) bool)
  (lambda (w r)
    (or (k-region=? w r)
        (tagcase w (r-var (v) #t) (else y #f))
        (tagcase r (r-var (v) #t) (else y #f)))))
(define k-hits? (subr (maxeff (read @globals) spin) (k-region k-regions) bool)
  (lambda (w rs)
    (and (not (null? rs)) (or (k-may-alias? w (car rs)) (k-hits? w (cdr rs))))))
(define k-open-regions (subr (maxeff (read @globals) (alloc @t)) (k-regions) k-regions)
  (lambda (rs)
    (cond ((null? rs) nil)
          ((tagcase (car rs) (r-frozen (p f) #t) (else y #f)) (k-open-regions (cdr rs)))
          (else (the k-regions (cons (car rs) (k-open-regions (cdr rs))))))))
(define k-kills? (subr (maxeff (read @globals) spin) (k-eff k-regions) bool)
  (lambda (e open)
    (and (not (null? e))
         (or (tagcase (car e)
               (a-write (w) (k-hits? w open))
               (a-goto (r) #t) (a-comefrom (r) #t) (a-await (r) #t) (a-var (v) #t)
               (a-app (v ds) #t)
               (else y #f))
             (k-kills? (cdr e) open)))))
(define k-kill-each
  (subr (maxeff (read @globals) (alloc @t) spin) (k-path-facts k-eff int) k-path-facts)
  (lambda (fs e depth)
    (if (null? fs)
        nil
        (let* ((f (car fs))
               (open (k-open-regions (extract f 4)))
               (ends (and (not (extract f 7)) (= (extract f 6) depth) (not (null? open))
                          (k-kills? e open)))
               (g (if ends
                      (product (1 (extract f 1)) (2 (extract f 2)) (3 (extract f 3))
                               (4 (extract f 4)) (5 (extract f 5)) (6 (extract f 6)) (7 #t))
                      f)))
          (the k-path-facts (cons g (k-kill-each (cdr fs) e depth)))))))
(define k-all-dead? (subr (read @globals) (k-path-facts) bool)
  (lambda (fs) (or (null? fs) (and (extract (car fs) 7) (k-all-dead? (cdr fs))))))
(define k-kill-paths (subr (maxeff kstate spin) (k-eff) unit)
  (lambda (e)
    (let ((fs (get k-path-narrowed)))
      (if (k-all-dead? fs) #u (set k-path-narrowed (k-kill-each fs e (get k-closure-depth)))))))
;; Before the branch where `p` holds: what it certifies, and the facts it shows, in force.
(define k-enter-then (subr (maxeff kstate spin) (kx) k-tested)
  (lambda (p)
    (let* ((certs (k-certs-now))
           (pushed (k-push-certified p))
           (facts (k-test-facts p))
           (narrowing (k-narrowings p))
           (fsaved (get k-size-facts))
           (nsaved (get k-narrowed))
           (psaved (k-length (get k-path-narrowed)))
           (fyes (set k-size-facts (k-with-facts (car facts) fsaved)))
           (nyes (k-put-narrowing (car narrowing) nsaved)))
      (product (1 certs) (2 fsaved) (3 facts) (4 nsaved) (5 narrowing) (6 psaved)))))
;; After it, before the branch where `p` does not: nothing certified, and what `p` shows so.
(define k-enter-else (subr kstate (k-tested) unit)
  (lambda (tested)
    (let ((certs (extract tested 1)) (fsaved (extract tested 2)))
      (begin
        (set k-certified (extract certs 1))
        (set k-certified-lengths (extract certs 2))
        (set k-certified-nats (extract certs 3))
        (set k-size-facts (k-with-facts (cdr (extract tested 3)) fsaved))
        (k-cut-paths (extract tested 6))
        (k-put-narrowing (cdr (extract tested 5)) (extract tested 4))))))
;; After both: the facts, and what was narrowed, as they were.
(define k-leave-test (subr kstate (k-tested) unit)
  (lambda (t)
    (begin (set k-size-facts (extract t 2)) (set k-narrowed (extract t 4))
           (k-cut-paths (extract t 6)))))
;; Whether `args` are one variable, as the binding it is, among `cs`.
(define k-certified-arg? (subr (maxeff kreads spin) (k-named kxs) bool)
  (lambda (cs args)
    (and (k-sc-one-arg? args)
         (tagcase (car args)
           (x-var (v va vb) (k-certified-has? cs v (k-binding-depth v)))
           (else y #f)))))
;; Whether `x` is a `lambda` of no parameters.
(define k-thunk-lambda? (subr (read @globals) (kx) bool)
  (lambda (x) (tagcase x (x-lambda (ps body a b) (null? ps)) (else y #f))))
;; Note argument `i` found to be a `t`, of effect `e`.
(define k-arg-found (subr kstate (k-done int int k-eff) unit)
  (lambda (done i t e) (begin (array-set! (extract done 1) i t) (array-set! (extract done 2) i e))))
;; Note argument `i` found to be what `r` says, and what that solves of its parameter's type `p`.
(define k-arg-unified (subr (maxeff kstate spin) (int k-binders k-solved k-done int k-te) unit)
  (lambda (p kinds solved done i r)
    (begin (k-unify p (extract r 1) kinds solved (k-new-trail))
           (k-arg-found done i (extract r 1) (extract r 2)))))
(define k-checked-call (ref k-call-checked @t) (new (product (1 -1) (2 -1) (3 -1))))
;; Call `x`, found `r`, as `expected`: its effect, and its type noted.
(define k-as-expected-call (subr (maxeff checks spin) (kx k-te int) k-eff)
  (lambda (x r expected)
    (let ((e (k-as-expected x r expected)))
      (begin (set k-checked-call (product (1 (k-start x)) (2 (k-end x)) (3 (extract r 1)))) e))))
;; `k-unify` of a call's `result` against what is `expected` of it: bounds
;; from above.
(define k-unify-above (subr (maxeff kstate spin) (int int k-binders k-solved) unit)
  (lambda (result expected kinds solved)
    (k-from-above (lambda () (k-unify result expected kinds solved (k-new-trail))))))
;; The instance `kinds` solved make of `inner`, and `solved`'s bounds
;; dropped.
(define k-solved-instance (subr (maxeff checks spin) (k-binders k-solved int int int int) int)
  (lambda (kinds solved a b ft inner)
    (k-drop-bounds solved (k-subst-checked kinds (k-finish kinds solved a b ft) inner a b))))
;; Whether `param` mentions a type binder whose bounds have not met: one
;; open once those binders' solutions are set aside.
(define k-mentions-unsettled? (subr (maxeff kstate spin) (int k-binders k-solved) bool)
  (lambda (param kinds solved)
    (let ((without (the k-solved (new (k-map-unsettled solved (get solved) #f)))))
      (k-mentions-unknown-type? param kinds without))))
;; `param` with each binder whose bounds have not met at its upper bound,
;; where it has one.
(define k-at-most (subr (maxeff kstate spin) (int k-solved) int)
  (lambda (param solved) (k-subst param (k-map-unsettled solved (get solved) #t))))
;; Whether `x` is a variable of a type not polymorphic.
(define k-mono-var? (subr (maxeff kreads spin) (kx) bool)
  (lambda (x)
    (tagcase x
      (x-var (s a b)
        (let ((t (k-lookup s)))
          (and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #f) (else y #t)))))
      (else y #f))))
;; Argument `i`, `arg`, of parameter type `param`, `p` as solved so far:
;; checked against `p`, its type and effect noted. Where `param` mentions a
;; type binder whose bounds have not met, what the argument is bounds it
;; too, rather than being told (the Rust checker's `bounded_argument`): a
;; variable says its own type; a call, checked against the binders' upper
;; bounds where they have them (else what they are so far), its own result
;; there; anything else, checked so, is what it was checked against.
;; `check` and `synth`, the rules'.
(define k-bounded-arg
  (subr (maxeff checks spin)
        (kx int int k-binders k-solved k-done int (subr (maxeff checks spin) (kx int) k-eff)
            (subr (maxeff checks spin) (kx) k-te))
        unit)
  (lambda (arg param p kinds solved done i check synth)
    (cond ((not (k-mentions-unsettled? param kinds solved))
           (k-arg-found done i p (check arg p)))
          ;; A variable's type is its own; a call, told what it is, is told
          ;; its regions too.
          ((k-mono-var? arg) (k-arg-unified param kinds solved done i (synth arg)))
          (else
           (let ((q (k-at-most param solved)))
             (begin
               (set k-checked-call (product (1 -1) (2 -1) (3 -1)))
               (let* ((e (check arg q)) (c (get k-checked-call))
                      (t (if (and (= (extract c 1) (k-start arg)) (= (extract c 2) (k-end arg)))
                             (extract c 3)
                             q)))
                 (begin (k-unify param t kinds solved (k-new-trail))
                        (k-arg-found done i t e)))))))))
;; Variable `s`, of polymorphic type `t`, at `a`..`b`: `t` instantiated at
;; `p`, and the effect of naming `s`.
(define k-poly-instance (subr (maxeff checks spin) (symbol int int int int) k-te)
  (lambda (s t p a b) (k-te (k-instantiate-against t p a b) (k-naming-effect s t))))
;; `x`, if a variable of a polymorphic type (a standard `list`): its type
;; instantiated at `p`, and the effect of naming it; else none.
(define k-poly-var-at (subr (maxeff checks spin) (kx int) (listof k-te @t))
  (lambda (x p)
    (tagcase x
      (x-var (s a b)
        (let ((t (k-lookup s)))
          (if (and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #t) (else y #f)))
              (the (listof k-te @t) (cons (k-poly-instance s t p a b) nil))
              (the (listof k-te @t) nil))))
      (else y (the (listof k-te @t) nil)))))
;; `nil` (a variable of a list of any elements), argument `i`, where its
;; parameter `q`, `p` so far, is not yet known: the type `nil` (`TODO.md`
;; §48), heard last, after what the context expects and every other
;; argument; anything else, the error.
(define k-nil-told (subr (maxeff checks spin) (kx int int int k-binders k-solved k-done) unit)
  (lambda (arg i p q kinds solved done)
    (tagcase arg
      (x-var (s a b)
        (let ((t (k-lookup s)))
          (if (and (>= t 0) (k-list-of-any? t))
              (let ((nil-ty (k-ty-new (ty-nil))))
                (begin
                  (k-unify q nil-ty kinds solved (k-new-trail))
                  (if (k-mentions-unknown-type? q kinds solved) (k-fail-not-known arg i p) #u)
                  (k-arg-found done i nil-ty (k-naming-effect s t))))
              (k-fail-not-known arg i p))))
      (else y (k-fail-not-known arg i p)))))
;; The parts of `ps`, from position `i`, that `free` names, and their
;; positions: what a `with` binds.
(define k-with-used (subr (maxeff kreads (alloc @t)) (k-parts k-names int)
                   (productof (1 k-parts) (2 k-ids)))
  (lambda (ps free i)
    (if (null? ps)
        (product (1 (the k-parts nil)) (2 (the k-ids nil)))
        (let ((rest (k-with-used (cdr ps) free (+ i 1))))
          (if (k-has-name? free (extract (car ps) 1))
              (product (1 (the k-parts (cons (car ps) (extract rest 1))))
                       (2 (the k-ids (cons i (extract rest 2)))))
              rest)))))
;; A result `(pairof A v R)`, `v` solved to `nil` and nothing expected of
;; it, has `v` a `(listof A R)` instead (`DONE.md` §48): the pair is new, so
;; no alias sees its tail as `nil` alone, and `(cons 1 nil)` is a list. Each
;; argument is checked against what its parameter then is.
(define k-widen-nil-tail (subr (maxeff kstate spin) (int k-binders k-solved) unit)
  (lambda (result kinds solved)
    (tagcase (k-get (k-resolve result))
      (ty-pair (h tl r nl)
        (tagcase (k-get (k-resolve tl))
          (ty-var (v) (if (k-binder-has? kinds v) (k-widen-tail-at v h r kinds solved) #u))
          (else y #u)))
      (else y #u))))
(define k-widen-tail-at (subr (maxeff kstate spin) (int int k-region k-binders k-solved) unit)
  (lambda (v h r kinds solved)
    (let ((f (k-map-find (get solved) v)) (head (k-subst h (get solved))))
      (if (and (not (null? f))
               (tagcase (cdr (car f))
                 (dt (t) (tagcase (k-get (k-resolve t)) (ty-nil () #t) (else y #f)))
                 (else y #f))
               (not (k-mentions-unknown-type? head kinds solved)))
          (let* ((slot (k-slot)) (pair (k-ty-new (ty-pair head slot r #t))))
            (begin
              (k-set-link slot pair)
              (set solved (cons (cons v (dt (k-subst slot (get solved)))) (get solved)))))
          #u))))
;; `(with m body)` checked as a `expected`, if `m` is `#%fx` and `body` a
;; standard name of a polymorphic type: instantiated as the plain name is
;; (`TODO.md` §46); its effect, in a list of one, or none.
(define k-fx-poly-check (subr (maxeff checks spin) (kx symbol kx int) (listof k-eff @t))
  (lambda (x m body expected)
    (let ((t (tagcase body (x-var (n a b) (if (k-fx-module? m) (k-std-type n) -1)) (else y -1))))
      (if (and (>= t 0) (tagcase (k-get t) (ty-poly (bs pb) #t) (else y #f)))
          (begin (k-expect x (k-instantiate-against t expected (k-start x) (k-end x)) expected)
                 (the (listof k-eff @t) (cons nil nil)))
          (the (listof k-eff @t) nil)))))
;; Whether `et` is a `(nat z)` that literal `k` is one of, or an `i32` or a
;; `u32` whose range it is in.
(define k-literal-within? (subr kreads (k-ty int) bool)
  (lambda (et k)
    (tagcase et
      (ty-nat (z) (and (>= k 0) (k-size-le? (k-size-lit k) z)))
      (ty-base (b)
        (case (symbol->string b)
          (("i32") (and (>= k -2147483648) (<= k 2147483647)))
          (("u32") (and (>= k 0) (<= k 4294967295)))
          (else #f)))
      (else w #f))))
;; Whether `et` is a `nlist` of no elements, or of any number.
(define k-may-be-empty? (subr kreads (k-ty) bool)
  (lambda (et)
    (tagcase et
      (ty-nlist (e z r) (or (k-size-any? z) (k-size-eq? z (k-size-lit 0))))
      (else w #f))))
;; A `tagcase`'s type, its arms of `types`: `expected` if given (≥ 0), or the least they all are.
(define k-arms-type (subr (maxeff checks spin) (kx k-ids int) int)
  (lambda (x types expected)
    (if (>= expected 0)
        expected
        (let* ((ts (k-join-with-nil types)) (found (k-upper-bound ts ts)))
          (if (< found 0)
              (let ((shown (k-join (k-show-list types k-printing-none) ", ")))
                (k-fail-at (string-append "the arms are " shown) x))
              found)))))
;; The region a place of type `t` is at; an error at `a`..`b` if `t` is not a place.
(define k-place-region (subr (maxeff checks spin) (int int int) k-region)
  (lambda (t a b)
    (tagcase (k-get t)
      (ty-place (r) r)
      (else y (k-fail-ty "a region is expected here, and this is a " t a b)))))
;; What a `make-bloblet` of `fields`, checked against `expected` (≥ 0), is told: that type, if a
;; bloblet not frozen, of as many fields, at the region `given` (if any).
(define k-bloblet-want (subr (maxeff kreads (alloc @t) spin) (int kxs k-regions) k-maybe-ty)
  (lambda (expected fields given)
    (if (< expected 0)
        nil
        (tagcase (k-get expected)
          (ty-bloblet (fs z r)
            (if (and (not z) (= (k-length fs) (k-length fields))
                     (or (null? given) (k-region=? r (car given))))
                (cons (k-get expected) nil)
                nil))
          (else y nil)))))
;; Field `i`'s type, of a bloblet of type `bt` whose fields are `fields`; an error if none.
(define k-bloblet-field (subr (maxeff checks spin) (int k-ids int int int) int)
  (lambda (bt fields i a b)
    (if (< i (k-length fields))
        (k-nth fields i)
        (let ((last (- (k-length fields) 1)))
          (k-fail (k-cat5 "a " (k-show-ty bt) " has no field " (int->string i)
                          (string-append ": its fields are 0 to " (int->string last))) a b)))))
;; Type `t` and effect `e`, with `region` read, or written.
(define k-te-reading (subr (maxeff kreads (alloc @t) spin) (int k-region k-eff) k-te)
  (lambda (t region e) (k-te t (k-insert (a-read region) e))))
(define k-te-writing (subr (maxeff kreads (alloc @t) spin) (int k-region k-eff) k-te)
  (lambda (t region e) (k-te t (k-insert (a-write region) e))))
;; Whether a handler that is a `c` takes a `payload` to an `answer`.
(define k-handles? (subr (maxeff kstate spin) (k-callable int int) bool)
  (lambda (c payload answer)
    (let ((ps (extract c 2)))
      (and (= (k-length ps) 1) (k-subtype payload (car ps)) (k-subtype (extract c 3) answer)))))
;; What a handler of type `ht` is called as, taking a `payload` to an `answer`; or an error.
(define k-handler-callable (subr (maxeff checks spin) (kx int int int) k-callable)
  (lambda (handler ht payload answer)
    (let ((c (k-as-subr ht)))
      (cond ((null? c) (k-fail-ty-at "a handler is a subroutine, not a " ht handler))
            ((k-handles? (car c) payload answer) (car c))
            (else
             (let ((wants (k-handler-wants payload answer)))
               (k-fail-at (k-cat4 wants "; it is a " (k-show-ty ht) "") handler))))))))))
