;;; The checker, in FX-26: reading types, one knot (a module's `letrec*`):
;;; type forms and effects (`check-syntax.fx`'s), descriptions and their
;;; functions and kinds (`check-kinds.fx`'s and `check-args.fx`'s), module
;;; types (`check-modules.fx`'s) and dependent parameters
;;; (`check-dependent.fx`'s), each reading the others. After
;;; `check-subst.fx`; part of the checker, `check-types.fx` first.

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
(let* ((check-types-types (load-module "fx26:check-types-types.fx"))
       (eager-reader-types ((proj (load-module "fx26:eager-reader-types.fx") @s @e @m @c)))
       (parser-types ((proj (load-module "fx26:parser-types.fx") @s @e @m @c @p)))
       (check-syntax-types (load-module "fx26:check-syntax-types.fx"))
       (check-read-types (load-module "fx26:check-read-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-holds-types (load-module "fx26:check-holds-types.fx"))
       (check-read-helpers-types (load-module "fx26:check-read-helpers-types.fx"))
       (check-subst-types (load-module "fx26:check-subst-types.fx"))
       (check-print-types (load-module "fx26:check-print-types.fx"))
       (check-print-parts-types (load-module "fx26:check-print-parts-types.fx"))
       (check-proving-types (load-module "fx26:check-proving-types.fx"))
       (check-effects-types (load-module "fx26:check-effects-types.fx"))
       (check-unions-types (load-module "fx26:check-unions-types.fx"))
       (reader-types (load-module "fx26:reader-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-read-helpers (select check-read-helpers-types check-read-helpers-sig))
           (check-syntax (select check-syntax-types check-syntax-sig))
           (check-read (select check-read-types check-read-sig))
           (check-subst (select check-subst-types check-subst-sig))
           (check-env (select check-env-types check-env-sig))
           (check-print (select check-print-types check-print-sig))
           (check-holds (select check-holds-types check-holds-sig))
           (check-proving (select check-proving-types check-proving-sig))
           (check-effects (select check-effects-types check-effects-sig))
           (check-unions (select check-unions-types check-unions-sig))
           (parser (select reader-types parser-sig))
           (check-print-parts (select check-print-parts-types check-print-parts-sig)))
    (module

;; The types it uses of the files before it.
(define a-spin (with check-types-types a-spin))
(define a-var (with check-types-types a-var))
(define-effect checks (select check-types-types checks))
(define cv-var (with check-types-types cv-var))
(define dc (with check-types-types dc))
(define de (with check-types-types de))
(define df (with check-types-types df))
(define dr (with check-types-types dr))
(define ds-abbrev (with check-types-types ds-abbrev))
(define ds-conv (with check-types-types ds-conv))
(define ds-eff (with check-types-types ds-eff))
(define ds-fun (with check-types-types ds-fun))
(define ds-gen (with check-types-types ds-gen))
(define ds-rec (with check-types-types ds-rec))
(define ds-region (with check-types-types ds-region))
(define ds-size (with check-types-types ds-size))
(define ds-var (with check-types-types ds-var))
(define dt (with check-types-types dt))
(define dz (with check-types-types dz))
(define-type k-binders (select check-types-types k-binders))
(define-type k-desc (select check-types-types k-desc))
(define-type k-descs (select check-types-types k-descs))
(define-type k-ds (select check-types-types k-ds))
(define-type k-eff (select check-types-types k-eff))
(define-type k-hyps (select check-types-types k-hyps))
(define-type k-ids (select check-types-types k-ids))
(define-type k-names (select check-types-types k-names))
(define-type k-parts (select check-types-types k-parts))
(define-effect kstate (select check-types-types kstate))
(define r-frozen (with check-types-types r-frozen))
(define r-heap (with check-types-types r-heap))
(define r-var (with check-types-types r-var))
(define sz-finite (with check-types-types sz-finite))
(define ty-app (with check-types-types ty-app))
(define ty-array (with check-types-types ty-array))
(define ty-bloblet (with check-types-types ty-bloblet))
(define ty-comp (with check-types-types ty-comp))
(define ty-false (with check-types-types ty-false))
(define ty-icell (with check-types-types ty-icell))
(define ty-markkey (with check-types-types ty-markkey))
(define ty-module (with check-types-types ty-module))
(define ty-named (with check-types-types ty-named))
(define ty-nat (with check-types-types ty-nat))
(define ty-nil (with check-types-types ty-nil))
(define ty-nlist (with check-types-types ty-nlist))
(define ty-pair (with check-types-types ty-pair))
(define ty-place (with check-types-types ty-place))
(define ty-poly (with check-types-types ty-poly))
(define ty-product (with check-types-types ty-product))
(define ty-ref (with check-types-types ty-ref))
(define ty-select (with check-types-types ty-select))
(define ty-subr (with check-types-types ty-subr))
(define ty-sum (with check-types-types ty-sum))
(define ty-tag (with check-types-types ty-tag))
(define ty-var (with check-types-types ty-var))
(define-type k-items (select check-types-types k-items))
(define atom (with eager-reader-types atom))
(define lst (with eager-reader-types lst))
(define-type result (select eager-reader-types result))
(define-type names (select parser-types names))
(define-type syn (select parser-types syn))
(define-type k-slots (select check-syntax-types k-slots))
(define-type k-params (select check-read-types k-params))
(define-type k-syns (select check-read-types k-syns))
(define-type k-scope (select check-env-types k-scope))
(define-type k-selects (select check-env-types k-selects))
(define-type k-seen (select check-holds-types k-seen))
;; What it uses of the modules it is given.
(define k-arrow (with check-types k-arrow))
(define k-arrow-kind? (with check-types k-arrow-kind?))
(define k-arrow-parts (with check-types k-arrow-parts))
(define k-arrow-result (with check-types k-arrow-result))
(define k-cat3 (with check-types k-cat3))
(define k-cat4 (with check-types k-cat4))
(define k-gen-of (with check-types k-gen-of))
(define k-get (with check-types k-get))
(define k-has-id? (with check-types k-has-id?))
(define k-length (with check-types k-length))
(define k-nth (with check-types k-nth))
(define k-pending-lemma (with check-types k-pending-lemma))
(define k-quote (with check-types k-quote))
(define k-resolve (with check-types k-resolve))
(define k-set-link (with check-types k-set-link))
(define k-slot (with check-types k-slot))
(define k-ty-new (with check-types k-ty-new))
(define k-abs-bound (with check-read-helpers k-abs-bound))
(define k-abs-usage (with check-read-helpers k-abs-usage))
(define k-all-unnamed? (with check-read-helpers k-all-unnamed?))
(define k-arity-fail (with check-read-helpers k-arity-fail))
(define k-binders-as-scope (with check-read-helpers k-binders-as-scope))
(define k-component-names (with check-read-helpers k-component-names))
(define k-ctor-eta (with check-read-helpers k-ctor-eta))
(define k-dlambda-empty (with check-read-helpers k-dlambda-empty))
(define k-effect-shaped? (with check-read-helpers k-effect-shaped?))
(define k-fresh-named (with check-read-helpers k-fresh-named))
(define k-fun-bound? (with check-read-helpers k-fun-bound?))
(define k-gen-eta (with check-read-helpers k-gen-eta))
(define k-gives-fail (with check-read-helpers k-gives-fail))
(define k-lam (with check-read-helpers k-lam))
(define k-moduleof-usage (with check-read-helpers k-moduleof-usage))
(define k-names-once (with check-read-helpers k-names-once))
(define k-no-name (with check-read-helpers k-no-name))
(define k-not-giving (with check-read-helpers k-not-giving))
(define k-param-name (with check-read-helpers k-param-name))
(define k-param-selects (with check-read-helpers k-param-selects))
(define k-params-kinds (with check-read-helpers k-params-kinds))
(define k-params-names (with check-read-helpers k-params-names))
(define k-parse-select (with check-read-helpers k-parse-select))
(define k-part-onto (with check-read-helpers k-part-onto))
(define k-parts-reversed (with check-read-helpers k-parts-reversed))
(define k-selects-reversed (with check-read-helpers k-selects-reversed))
(define k-ty-kids (with check-read-helpers k-ty-kids))
(define k-ahead-filled (with check-syntax k-ahead-filled))
(define k-ahead-take (with check-syntax k-ahead-take))
(define k-arity-message (with check-syntax k-arity-message))
(define k-dletrec-grounded (with check-syntax k-dletrec-grounded))
(define k-dletrec-no-knot (with check-syntax k-dletrec-no-knot))
(define k-dletrec-slots (with check-syntax k-dletrec-slots))
(define k-ds-applied? (with check-syntax k-ds-applied?))
(define k-effect-atom (with check-syntax k-effect-atom))
(define k-endless (with check-syntax k-endless))
(define k-grounded (with check-syntax k-grounded))
(define k-has-label? (with check-syntax k-has-label?))
(define k-hyp-coercions (with check-syntax k-hyp-coercions))
(define k-knot-of (with check-syntax k-knot-of))
(define k-knots (with check-syntax k-knots))
(define k-list-head (with check-syntax k-list-head))
(define k-module-type-head? (with check-syntax k-module-type-head?))
(define k-parse-conv (with check-syntax k-parse-conv))
(define k-parse-conv-form (with check-syntax k-parse-conv-form))
(define k-parse-size (with check-syntax k-parse-size))
(define k-push-all (with check-syntax k-push-all))
(define k-select-alias (with check-syntax k-select-alias))
(define k-shape (with check-syntax k-shape))
(define k-stated-lemma (with check-syntax k-stated-lemma))
(define k-storage-head? (with check-syntax k-storage-head?))
(define k-syn-label (with check-syntax k-syn-label))
(define k-twice (with check-syntax k-twice))
(define k-type-kind? (with check-syntax k-type-kind?))
(define k-any-typed-kind? (with check-read k-any-typed-kind?))
(define k-arrow-syntax (with check-read k-arrow-syntax))
(define k-at-name? (with check-read k-at-name?))
(define k-atom-head? (with check-read k-atom-head?))
(define k-ctor-params (with check-read k-ctor-params))
(define k-effect-desc (with check-read k-effect-desc))
(define k-effect-named (with check-read k-effect-named))
(define k-effect-selected (with check-read k-effect-selected))
(define k-frozen-into (with check-read k-frozen-into))
(define k-head (with check-read k-head))
(define k-items (with check-read k-items))
(define k-items-or-nil (with check-read k-items-or-nil))
(define k-name-of (with check-read k-name-of))
(define k-not-applied (with check-read k-not-applied))
(define k-parse-binders (with check-read k-parse-binders))
(define k-parse-place (with check-read k-parse-place))
(define k-parse-region (with check-read k-parse-region))
(define k-region-constant (with check-read k-region-constant))
(define k-sfail (with check-read k-sfail))
(define k-symbol-head (with check-read k-symbol-head))
(define k-apply-fun (with check-subst k-apply-fun))
(define k-note-closed (with check-subst k-note-closed))
(define k-subst (with check-subst k-subst))
(define k-base (with check-env k-base))
(define k-dscope (with check-env k-dscope))
(define k-expanding (with check-env k-expanding))
(define k-find (with check-env k-find))
(define k-ids-but-last (with check-env k-ids-but-last))
(define k-ids-last (with check-env k-ids-last))
(define k-lookup-desc (with check-env k-lookup-desc))
(define k-push-desc (with check-env k-push-desc))
(define k-select-map (with check-env k-select-map))
(define k-void (with check-env k-void))
(define k-conv-default (with check-print-parts k-conv-default))
(define k-kind-text (with check-print-parts k-kind-text))
(define k-show-ty (with check-print k-show-ty))
(define k-size-var (with check-print-parts k-size-var))
(define k-fun-kind (with check-holds k-fun-kind))
(define k-new-seen (with check-holds k-new-seen))
(define k-no-knot (with check-holds k-no-knot))
(define k-seen? (with check-holds k-seen?))
(define k-names-snoc (with check-proving k-names-snoc))
(define k-parse-proving (with check-proving k-parse-proving))
(define k-one (with check-effects k-one))
(define k-union (with check-effects k-union))
(define k-union-of (with check-unions k-union-of))
(define syn-end (with parser syn-end))
(define syn-head (with parser syn-head))
(define syn-name (with parser syn-name))
(define syn-start (with parser syn-start))
(define syn-symbol? (with parser syn-symbol?))

(define k-effects (subr (maxeff checks spin) (k-syns) k-eff)
  (lambda (xs)
    (if (null? xs)
        nil
        (let* ((e (k-parse-effect (car xs))) (rest (k-effects (cdr xs)))) (k-union e rest)))))
(define k-parse-effect (subr (maxeff checks spin) (syn) k-eff)
  (lambda (s)
    (if (syn-symbol? s)
        (k-effect-named s)
        (let* ((items (k-items s "an effect"))
               (head (k-head items))
               ;; `(select m e)`: module `m`'s effect `e`, found where the
               ;; type it is in is checked, as a type's `select` is.
               (selected (if (string=? head "select")
                             (k-effect-selected s items)
                             (the (listof k-eff acyclic) nil)))
               ;; `(e d …)`: a description function to an effect, applied.
               (applied (if (null? selected) (k-parse-effect-app s items) selected)))
          (cond ((not (null? selected)) (car selected))
                ((not (null? applied)) (car applied))
                ((string=? head "maxeff") (k-effects (cdr items)))
                ((k-atom-head? head)
                 (if (= (k-length items) 2)
                     (k-effect-atom head (k-nth items 1))
                     (k-sfail (k-cat3 "`(" head " region)`") s)))
                (else (k-sfail "expected an effect" s)))))))
(define k-parse-types (subr (maxeff checks spin) (k-syns) k-ids)
  (lambda (xs)
    (if (null? xs)
        nil
        (let* ((t (k-parse-type (car xs))) (rest (k-parse-types (cdr xs)))) (cons t rest)))))
(define k-parse-parts (subr (maxeff checks spin) (k-syns k-parts) k-parts)
  (lambda (ps done)
    (if (null? ps)
        (reverse done)
        (let ((pair (k-items (car ps) "`(label type)`")))
          (if (= (k-length pair) 2)
              (let ((l (k-syn-label (car pair))))
                (if (k-has-label? done l)
                    (k-sfail (k-twice (symbol->string l)) (car ps))
                    (let ((t (k-parse-type (k-nth pair 1))))
                      (k-parse-parts (cdr ps) (cons (product (1 l) (2 t)) done)))))
              (k-sfail "`(label type)`" (car ps)))))))
;; Storage written: a procedure kept there may not reach itself unsaid
;; (`spin`).
(define k-parse-type (subr (maxeff checks spin) (syn) int)
  (lambda (s)
    (let ((t (k-parse-type-node s)))
      (begin
        (if (and (not (syn-symbol? s)) (k-storage-head? (k-head (k-items s "a type"))))
            (k-no-knot t (syn-start s) (syn-end s))
            #u)
        t))))
;; What `(proves prop)` states: the type of its proof, with the lemma kept
;; pending for the definition it declares.
(define k-parse-proves (subr (maxeff checks spin) (syn string) int)
  (lambda (prop usage)
    (let* ((items (k-items prop "a proposition"))
           (head (k-symbol-head items))
           (poly? (string=? head "poly"))
           (shape (cond (poly? (if (>= (k-length items) 3) #u (k-sfail usage prop)))
                        ((string=? head "<=") #u)
                        (else (k-sfail usage prop))))
           (bs (if poly? (k-parse-binders (k-nth items 1)) (the k-binders nil)))
           (conc (k-le (if poly? (k-nth items 2) prop)))
           (hyps (if poly? (k-les (cdr (cdr (cdr items)))) (the k-hyps nil)))
           (spin (k-one (a-spin)))
           (params (k-hyp-coercions hyps spin (the k-ids (cons (car conc) nil))))
           (body (k-ty-new (ty-subr spin params (cdr conc) (get k-conv-default))))
           (t (if (null? bs) body (k-ty-new (ty-poly bs body)))))
      (begin
        (set k-pending-lemma (cons (k-stated-lemma bs conc hyps) nil))
        t))))
(define k-le (subr (maxeff checks spin) (syn) (pairof int int @t))
  (lambda (s)
    (let ((items (k-items s "a proposition")))
      (if (and (= (k-length items) 3) (string=? (k-symbol-head items) "<="))
          (let* ((a (k-parse-type (k-nth items 1))) (b (k-parse-type (k-nth items 2))))
            (cons a b))
          (k-sfail "a proposition is `(<= type type)`" s)))))
(define k-les (subr (maxeff checks spin) (k-syns) k-hyps)
  (lambda (xs)
    (if (null? xs) nil (let* ((h (k-le (car xs))) (rest (k-les (cdr xs)))) (cons h rest)))))
;; `(name d …)` for the `g`th generative type: a node, never expanded.
(define k-apply-gen (subr (maxeff checks spin) (syn int k-syns) int)
  (lambda (s g args)
    (let* ((gen (k-gen-of g)) (ps (extract gen 2)))
      (if (not (= (k-length args) (k-length ps)))
          (k-sfail (k-arity-message (extract gen 1) (k-length ps) (k-length args)) s)
          (let ((t (k-ty-new (ty-named g (k-gen-args ps args)))))
            ;; What it holds may keep a procedure that reaches itself.
            (begin (k-no-knot t (syn-start s) (syn-end s)) t))))))
(define k-gen-args (subr (maxeff checks spin) (k-binders k-syns) k-descs)
  (lambda (ps args)
    (if (null? ps)
        nil
        (let* ((k (extract (car ps) 2))
               (d (cond ((k-type-kind? k) (dt (k-parse-type (car args))))
                        ((= k 0) (dr (k-parse-region (car args))))
                        ((= k 3) (dr (k-parse-place (car args))))
                        ((= k 5) (dz (k-parse-size (car args))))
                        ((= k 6) (dc (k-parse-conv (car args))))
                        ((>= k 100) (df (k-parse-fun (car args) k)))
                        (else (de (k-parse-effect (car args))))))
               (rest (k-gen-args (cdr ps) (cdr args))))
          (cons d rest)))))
;; The type a name stands for.
(define k-type-named (subr (maxeff checks spin) (syn) int)
  (lambda (s)
    (let* ((n (syn-name s)) (sym (string->symbol n)) (base (k-find (get k-base) sym)))
      (cond ((string=? n "void") k-void)
            ;; The empty list's own type (`docs/research/logical-types.md`, L1).
            ((and (string=? n "nil") (null? (k-lookup-desc sym))) (k-ty-new (ty-nil)))
            ((and (string=? n "false") (null? (k-lookup-desc sym))) (k-ty-new (ty-false)))
            ((and (string=? n "nat") (null? (k-lookup-desc sym)))
             (k-ty-new (ty-nat (sz-finite))))
            ((>= base 0) base)
            (else
             (let ((d (k-lookup-desc sym))
                   (no (lambda () (string-append (k-quote n) " is not a type"))))
               (if (null? d)
                   (k-sfail (no) s)
                   (tagcase (car d)
                     (ds-var (v k)
                       (cond ((k-type-kind? k) (k-ty-new (ty-var v)))
                             ((k-arrow-kind? k) (k-sfail (k-not-applied n k) s))
                             (else (k-sfail (no) s))))
                     (ds-fun (f)
                       (let ((k (k-fun-kind f))) (k-sfail (k-not-applied n (if (< k 0) 2 k)) s)))
                     (ds-rec (t) t)
                     (ds-gen (g) (k-apply-gen s g nil))
                     (else x (k-sfail (no) s))))))))))
(define k-parse-type-node (subr (maxeff checks spin) (syn) int)
  (lambda (s)
    (if (syn-symbol? s)
        (k-type-named s)
        (let* ((items (k-items s "a type"))
               (hd (if (null? items) '|()| (syn-head (car items))))
               (abbrev (if (symbol=? hd '|()|)
                           (the (listof k-ds acyclic) nil)
                           (k-lookup-desc hd)))
               (alias (k-select-alias abbrev)))
          (cond ((and (not (null? abbrev)) (k-ds-applied? (car abbrev)))
                 (tagcase (car abbrev)
                   (ds-abbrev (ps body) (k-expand-abbrev s hd ps body (cdr items)))
                   (ds-gen (g) (k-apply-gen s g (cdr items)))
                   ;; A description function applied (`check-kinds.fx`).
                   (ds-var (v k) (k-parse-app s (k-ty-new (ty-var v)) (cdr items)))
                   (ds-fun (f) (k-parse-app s f (cdr items)))
                   (else x (k-sfail "an abbreviation" s))))
                ((>= alias 0) (k-parse-app s alias (cdr items)))
                ;; `((dlambda …) d …)` and `((select m f) d …)`.
                ((and (not (null? items)) (tagcase (car items) (lst (xs d a b) #t) (else x #f)))
                 (k-parse-app s (k-parse-fun (car items) -1) (cdr items)))
                (else (k-parse-type-form s items hd)))))))
;; `(subr effect (param …) result)`, or with a convention first, `(subr
;; (conv C) effect (param …) result)`; left out, it is the program's.
(define k-parse-subr (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (let* ((conv? (and (= (k-length items) 5) (string=? (k-list-head (k-nth items 1)) "conv")))
           (cv (if conv? (k-parse-conv-form (k-nth items 1)) (get k-conv-default)))
           (items (if conv? (the k-syns (cons (car items) (cdr (cdr items)))) items)))
      (begin
        (k-shape (= (k-length items) 4) "`(subr effect (param …) result)`" s)
        (let* ((e (k-parse-effect (k-nth items 1)))
               (ts (k-read-params (k-items-or-nil (k-nth items 2) "parameter types")
                                         (k-nth items 3))))
          (k-ty-new (ty-subr e (k-ids-but-last ts) (k-ids-last ts) cv)))))))
;; `(proves prop)`.
(define k-parse-proves-type (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (let ((usage (string-append "`(proves (<= type type))` or `(proves (poly ((name kind) …) "
                                "(<= type type) (<= type type) …))`")))
      (begin
        (k-shape (= (k-length items) 2) usage s)
        (let* ((saved (get k-dscope)) (t (k-parse-proves (k-nth items 1) usage)))
          (begin (set k-dscope saved) t))))))
;; A type written as a form, `(hd …)`, `hd` no family's name.
(define k-parse-type-form (subr (maxeff checks spin) (syn k-syns symbol) int)
  (lambda (s items hd)
    (let ((n (k-length items)))
      (case hd
        ((subr) (k-parse-subr s items))
        ((proves) (k-parse-proves-type s items))
        ((bool) (k-sfail "`(bool …)` is a procedure's result, and only that" s))
        ((poly)
         (begin
           (k-shape (= n 3) "`(poly ((name kind) …) type)`" s)
           (let* ((saved (get k-dscope))
                  (bs (k-parse-binders (k-nth items 1)))
                  (body (k-parse-type (k-nth items 2))))
             (begin (set k-dscope saved) (k-ty-new (ty-poly bs body))))))
        ((nlist)
         (begin
           (k-shape (or (= n 3) (= n 4)) "`(nlist type size)` or `(nlist type size place)`" s)
           (let* ((e (k-parse-type (k-nth items 1)))
                  (z (k-parse-size (k-nth items 2)))
                  (r (if (= n 4)
                         (k-frozen-into (k-parse-place (k-nth items 3)) #t)
                         (r-frozen -1 #t))))
             (k-ty-new (ty-nlist e z r)))))
        ((nat)
         (begin
           (k-shape (= n 2) "`(nat size)`" s)
           (k-ty-new (ty-nat (k-parse-size (k-nth items 1))))))
        ((ref)
         (begin
           (k-shape (= n 3) "`(ref type region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
             (k-ty-new (ty-ref t r)))))
        ((pairof)
         (begin
           (k-shape (= n 4) "`(pairof type type region)`" s)
           (let* ((a (k-parse-type (k-nth items 1))) (b (k-parse-type (k-nth items 2)))
                  (r (k-parse-region (k-nth items 3))))
             (k-ty-new (ty-pair a b r #f)))))
        ((union) (k-parse-union s items))
        ((dletrec) (k-parse-dletrec s items))
        ((mu) (k-parse-mu s items))
        ((listof)
         (begin
           (k-shape (= n 3) "`(listof type region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2)))
                  (slot (k-slot)) (pair (k-ty-new (ty-pair t slot r #t))))
             (begin (k-set-link slot pair) slot))))
        ((prompt-tag)
         (begin
           (k-shape (= n 5) "`(prompt-tag answer payload effect region)`" s)
           (let* ((a (k-parse-type (k-nth items 1))) (h (k-parse-type (k-nth items 2)))
                  (e (k-parse-effect (k-nth items 3))) (r (k-parse-region (k-nth items 4))))
             (k-ty-new (ty-tag a h e r)))))
        ((composable)
         (begin
           (k-shape (= n 5) "`(composable argument answer effect region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (a (k-parse-type (k-nth items 2)))
                  (e (k-parse-effect (k-nth items 3))) (r (k-parse-region (k-nth items 4))))
             (k-ty-new (ty-comp t a e r)))))
        ((bloblet)
         (begin
           (k-shape (= n 3) "`(bloblet (fields type …) region)`, or `(frozen type …)`" s)
           (let* ((fields (k-nth items 1))
                  (parts (k-items fields "`(fields type …)`"))
                  (which (k-head parts)))
             (if (or (string=? which "fields") (string=? which "frozen"))
                 (let* ((fs (k-parse-types (cdr parts))) (r (k-parse-region (k-nth items 2))))
                   (k-ty-new (ty-bloblet fs (string=? which "frozen") r)))
                 (k-sfail "`(fields type …)` or `(frozen type …)`" fields)))))
        ((productof) (k-ty-new (ty-product (k-parse-parts (cdr items) nil))))
        ((sumof) (k-ty-new (ty-sum (k-parse-parts (cdr items) nil))))
        ((arrayof)
         (begin
           (k-shape (= n 3) "`(arrayof type region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
             (k-ty-new (ty-array t r)))))
        ((icell)
         (begin
           (k-shape (= n 3) "`(icell type region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
             (k-ty-new (ty-icell t r)))))
        ((place)
         (begin
           (k-shape (= n 2) "`(place region)`" s)
           (k-ty-new (ty-place (k-parse-place (k-nth items 1))))))
        ((mark-key)
         (begin
           (k-shape (= n 3) "`(mark-key type region)`" s)
           (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
             (k-ty-new (ty-markkey t r)))))
        (else
         (cond ((k-module-type-head? hd) (k-read-module-type s items hd))
               (else (k-sfail "expected a type" s))))))))
;; `(dletrec ((name type) …) type)`: each name gets a forwarding slot
;; before any body is read, so the bodies can refer to it and each other.
(define k-parse-dletrec (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (begin
      (k-shape (= (k-length items) 3) "`(dletrec ((name type) …) type)`" s)
      (let* ((saved (get k-dscope))
             (slots (k-dletrec-slots (k-items (k-nth items 1) "dletrec bindings")))
             (filled (k-dletrec-fill slots))
             (grounded (k-dletrec-grounded slots s))
             (unknotted (k-dletrec-no-knot slots s))
             (body (k-parse-type (k-nth items 2))))
        (begin (set k-dscope saved) body)))))
;; `(mu name type)`: a recursive type, anonymous; the same as `(dletrec
;; ((name type)) name)`.
;; A union of members of disjoint shapes at run time
;; (`docs/research/logical-types.md`, L1), normalized.
(define k-parse-union (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (begin
      (k-shape (>= (k-length items) 3) "`(union type type …)`" s)
      (k-union-of (k-parse-types (cdr items)) (syn-start s) (syn-end s)))))
(define k-parse-mu (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (begin
      (k-shape (= (k-length items) 3) "`(mu name type)`" s)
      (let* ((name (k-name-of (k-nth items 1) "a name"))
             (saved (get k-dscope))
             (slot (k-slot))
             (pushed (k-push-desc name (ds-rec slot)))
             (t (k-parse-type (k-nth items 2)))
             (restored (set k-dscope saved))
             (filled (k-set-link slot t))
             (grounded (k-grounded slot (syn-start s) (syn-end s))))
        slot))))
(define k-dletrec-fill (subr (maxeff checks spin) (k-slots) unit)
  (lambda (ss)
    (if (null? ss)
        #u
        (let ((t (k-parse-type (cdr (car ss)))))
          (begin (k-set-link (car (car ss)) t) (k-dletrec-fill (cdr ss)))))))
;; A use of a parametric abbreviation: its body, read with each parameter
;; bound to the description given for it.
(define k-expand-abbrev (subr (maxeff checks spin) (syn symbol k-params syn k-syns) int)
  (lambda (s name ps body args)
    (cond
      ((not (= (k-length args) (k-length ps)))
       (k-sfail (k-arity-message name (k-length ps) (k-length args)) s))
      ((> (get k-expanding) 64) (k-endless s name))
      (else (k-expand-bound s name body (k-abbrev-args ps args))))))
;; The family `name`'s body, read with its parameters bound as `bound`
;; says: a use inside with the same descriptions is the slot its type
;; will fill, a knot.
(define k-expand-bound (subr (maxeff checks spin) (syn symbol syn k-scope) int)
  (lambda (s name body bound)
    (let ((knot (k-knot-of (get k-knots) name bound)))
      (if (>= knot 0)
          knot
          (let* ((saved (get k-dscope)) (slot (k-slot)) (kept (get k-knots)))
            (begin
              (set k-knots (cons (product (1 name) (2 bound) (3 slot)) kept))
              (k-push-all bound)
              (set k-expanding (+ (get k-expanding) 1))
              (let ((t (k-parse-type body)))
                (begin (set k-expanding (- (get k-expanding) 1))
                       (set k-dscope saved)
                       (set k-knots kept)
                       (k-set-link slot t)
                       (k-grounded slot (syn-start s) (syn-end s))
                       slot))))))))
(define k-abbrev-args (subr (maxeff checks spin) (k-params k-syns) k-scope)
  (lambda (ps args)
    (if (null? ps)
        nil
        (let* ((k (extract (car ps) 2))
               (d (cond ((k-type-kind? k) (ds-rec (k-parse-type (car args))))
                        ((= k 0) (ds-region (k-parse-region (car args))))
                        ((= k 3) (ds-region (k-parse-place (car args))))
                        ((= k 5) (ds-size (k-parse-size (car args))))
                        ((= k 6) (ds-conv (k-parse-conv (car args))))
                        ((>= k 100) (ds-fun (k-parse-fun (car args) k)))
                        (else (ds-eff (k-parse-effect (car args))))))
               (rest (k-abbrev-args (cdr ps) (cdr args))))
          (cons (cons (extract (car ps) 1) d) rest)))))
(define* k-define-type (subr (maxeff checks spin) (symbol syn int int) int)
  (lambda (name def a b)
    (let ((ahead (k-ahead-take name)))
      (if (>= ahead 0)
          ;; Declared ahead: its slot is in scope already; fill it, and check
          ;; it grounded once every slot is filled.
          (let ((t (k-parse-type def)))
            (begin (k-set-link ahead t)
                   (set k-ahead-filled (cons (product (1 ahead) (2 a) (3 b)) (get k-ahead-filled)))
                   ahead))
          (let ((slot (k-slot)))
            (begin
              (k-push-desc name (ds-rec slot))
              (let ((t (k-parse-type def)))
                (begin (k-set-link slot t) (k-grounded slot a b) (k-note-closed slot)))))))))
;; Name or `dlambda` `s`, a description function.
(define k-fun-d (subr (maxeff checks spin) (syn) k-desc)
  (lambda (s) (df (k-parse-fun s -1))))
;; A `proj` argument: which kind it is shows in its shape, or, for a bare
;; name, in how the name is bound.
;; A convention, if name `s` is one of FX-26's own; else a type.
(define k-parse-conv-or-type (subr (maxeff checks spin) (syn) k-desc)
  (lambda (s)
    (let ((n (syn-name s)))
      (if (or (string=? n "cellular") (string=? n "native") (string=? n "fx"))
          (dc (k-parse-conv s))
          (dt (k-parse-type s))))))
;; What name `s`, meaning `d` (none or one), is as a `proj` argument: by how
;; it is bound; if it is not bound as a description, a convention or a type.
(define k-parse-d-bound (subr (maxeff checks spin) (syn (listof k-ds acyclic)) k-desc)
  (lambda (s d)
    (if (null? d)
        (if (null? (k-ctor-params (syn-name s))) (k-parse-conv-or-type s) (k-fun-d s))
        (tagcase (car d)
          (ds-fun (f) (k-fun-d s))
          (ds-abbrev (ps body) (if (null? ps) (k-parse-conv-or-type s) (k-fun-d s)))
          (ds-gen (g)
            (if (null? (extract (k-gen-of g) 2)) (k-parse-conv-or-type s) (k-fun-d s)))
          (ds-var (v k)
            (cond ((>= k 100) (k-fun-d s))
                  ((or (= k 0) (= k 3)) (dr (r-var v)))
                  ((= k 1) (de (k-one (a-var v))))
                  ((= k 5) (dz (k-size-var v)))
                  ((= k 6) (dc (cv-var v)))
                  (else (k-parse-conv-or-type s))))
          (ds-region (r) (dr r))
          (ds-eff (e) (de e))
          (ds-size (z) (dz z))
          (ds-conv (c) (dc c))
          (else x (k-parse-conv-or-type s))))))
;; A `proj` argument that is a name.
(define k-parse-d-name (subr (maxeff checks spin) (syn) k-desc)
  (lambda (s)
    (let* ((n (syn-name s)) (sym (string->symbol n)))
      (cond ((k-at-name? n) (dr (k-region-constant sym)))
            ((string=? n "pure") (de nil))
            ((string=? n "spin") (de (k-one (a-spin))))
            ((string=? n "const") (dr (r-frozen -1 #f)))
            ((string=? n "acyclic") (dr (r-frozen -1 #t)))
            ((string=? n "finite") (dz (sz-finite)))
            ((string=? n "heap") (dr (r-heap)))
            (else (k-parse-d-bound s (k-lookup-desc sym)))))))
(define k-parse-d (subr (maxeff checks spin) (syn) k-desc)
  (lambda (s)
    (cond ((tagcase s (atom (d a b) (datum-int? d)) (else x #f))
           ;; A natural number can only be a size.
           (dz (k-parse-size s)))
          ((syn-symbol? s) (k-parse-d-name s))
          (else
           (let ((hd (k-head (k-items s "a description"))))
             (cond ((string=? hd "dlambda") (k-fun-d s))
                   ((or (k-atom-head? hd) (string=? hd "maxeff")) (de (k-parse-effect s)))
                   ((or (string=? hd "+") (string=? hd "-")) (dz (k-parse-size s)))
                   (else (dt (k-parse-type s)))))))))
;; A description of kind `k`, as written.
(define k-parse-desc-at (subr (maxeff checks spin) (syn int) k-desc)
  (lambda (s k)
    (cond ((k-type-kind? k) (dt (k-parse-type s)))
          ((= k 0) (dr (k-parse-region s)))
          ((= k 3) (dr (k-parse-place s)))
          ((= k 1) (de (k-parse-effect s)))
          ((= k 5) (dz (k-parse-size s)))
          ((= k 6) (dc (k-parse-conv s)))
          (else (df (k-parse-fun s k))))))
;; Descriptions `xs`, each of its kind in `ks`.
(define k-parse-descs-at (subr (maxeff checks spin) (k-syns k-ids) k-descs)
  (lambda (xs ks)
    (if (null? xs)
        nil
        (let ((d (k-parse-desc-at (car xs) (car ks))))
          (cons d (k-parse-descs-at (cdr xs) (cdr ks)))))))
;; Description `s`, of kind `k` if that is known (not -1).
(define k-parse-desc-of (subr (maxeff checks spin) (syn int) k-desc)
  (lambda (s k) (if (>= k 0) (k-parse-desc-at s k) (k-parse-d s))))
;; A description function, as written where one of kind `want` (-1 if not
;; known) is wanted.
(define k-parse-fun (subr (maxeff checks spin) (syn int) int)
  (lambda (s want)
    (let* ((f (k-parse-fun-node s want)) (got (k-fun-kind f)))
      (if (and (>= want 0) (>= got 0) (not (= got want)))
          (k-sfail (k-cat4 "a description function of kind " (k-kind-text want)
                           " is wanted, and this is of kind " (k-kind-text got))
                   s)
          f))))
(define k-parse-fun-node (subr (maxeff checks spin) (syn int) int)
  (lambda (s want)
    (if (syn-symbol? s)
        (k-fun-named s)
        (let ((usage (string-append "a description function: a name, `(dlambda ((name kind) …) "
                                    "description)` or `(select module name)`")))
          (tagcase s
            (lst (items d a b)
              (let ((hd (k-symbol-head items)))
                (case hd (("dlambda") (k-parse-dlambda s items want))
                         (("select") (k-parse-select s items))
                         (else
                          (cond ((k-fun-bound? hd) (k-parse-fun-app s items))
                                (else (k-sfail usage s)))))))
            (else x (k-sfail usage s)))))))
;; `(dlambda ((x k) …) d)`.
(define k-parse-dlambda (subr (maxeff checks spin) (syn k-syns int) int)
  (lambda (s items want)
    (if (not (= (k-length items) 3))
        (k-sfail "`(dlambda ((name kind) …) description)`" s)
        (let* ((result (if (>= want 0) (k-arrow-result want) -1))
               (saved (get k-dscope))
               (bs (k-parse-binders (k-nth items 1)))
               (none (if (null? bs) (k-sfail k-dlambda-empty (k-nth items 1)) #u))
               (body (k-parse-desc-of (k-nth items 2) result)))
          (begin (set k-dscope saved) (k-lam bs body))))))
;; `(g d …)`, where `g` gives a description function.
(define k-parse-fun-app (subr (maxeff checks spin) (syn k-syns) int)
  (lambda (s items)
    (let* ((g (k-parse-fun (car items) -1))
           (shown (k-quote (k-show-ty g)))
           (parts (k-arrow-parts (k-fun-kind g)))
           (no (k-cat3 shown " does not give a description function" "")))
      (cond ((or (null? parts) (not (k-arrow-kind? (cdr (car parts))))) (k-sfail no s))
            ((not (= (k-length (cdr items)) (k-length (car (car parts)))))
             (k-arity-fail g (k-length (car (car parts))) (k-length (cdr items)) s))
            (else
             (let ((d (k-apply-fun g (k-parse-descs-at (cdr items) (car (car parts))))))
               (tagcase d (df (f) f) (else y (k-sfail no s)))))))))
;; A description function named.
(define k-fun-named (subr (maxeff checks spin) (syn) int)
  (lambda (s)
    (let* ((n (syn-name s)) (sym (string->symbol n)) (d (k-lookup-desc sym))
           (no (k-cat3 (k-quote n) " is not a description function" "")))
      (if (null? d)
          (let ((ctor (k-ctor-params n)))
            (if (null? ctor) (k-sfail no s) (k-ctor-eta n (car ctor))))
          (tagcase (car d)
            (ds-var (v k) (if (k-arrow-kind? k) (k-ty-new (ty-var v)) (k-sfail no s)))
            (ds-fun (f) f)
            (ds-abbrev (ps body) (if (null? ps) (k-sfail no s) (k-abbrev-eta s sym ps body)))
            (ds-gen (g)
              (let ((ps (extract (k-gen-of g) 2)))
                (if (null? ps) (k-sfail no s) (k-gen-eta g ps))))
            (else x (k-sfail no s)))))))
;; A type family as a description function: `(dlambda ((p k) …) (name p …))`.
(define k-abbrev-eta (subr (maxeff checks spin) (syn symbol k-params syn) int)
  (lambda (s name ps body)
    (let* ((bs (k-fresh-named (k-params-names ps) (k-params-kinds ps)))
           (t (if (> (get k-expanding) 64)
                  (k-endless s name)
                  (k-expand-bound s name body (k-binders-as-scope bs)))))
      (k-lam bs (dt t)))))
;; `(f d …)` as a type: `f` given the descriptions `args` are, of the
;; kinds it takes; reduced, if it is a `dlambda`. Where `f`'s kind is not
;; known yet (a `select`), what it is given is read by its shape, and
;; checked once it is resolved.
(define k-parse-app (subr (maxeff checks spin) (syn int k-syns) int)
  (lambda (s f args)
    (let ((parts (k-arrow-parts (k-fun-kind f))))
      (if (null? parts)
          (k-ty-new (ty-app f (k-parse-ds args)))
          (let ((ps (car (car parts))) (result (cdr (car parts))))
            (cond ((not (= (k-length args) (k-length ps)))
                   (k-arity-fail f (k-length ps) (k-length args) s))
                  ((not (k-type-kind? result)) (k-gives-fail f result "a type" s))
                  (else
                   (tagcase (k-apply-fun f (k-parse-descs-at args ps))
                     (dt (t) t)
                     (else y (k-not-giving f "a type" s))))))))))
(define k-parse-ds (subr (maxeff checks spin) (k-syns) k-descs)
  (lambda (xs)
    (if (null? xs) nil (let ((d (k-parse-d (car xs)))) (cons d (k-parse-ds (cdr xs)))))))
;; `(e d …)` in an effect, where `e` is a description function to an
;; effect: its effect, reduced if it is a `dlambda`; none if `items` are
;; no such application.
(define k-parse-effect-app (subr (maxeff checks spin) (syn k-syns) (listof k-eff acyclic))
  (lambda (s items)
    (let ((f (if (null? items)
                 -1
                 (let ((head (car items)))
                   (if (syn-symbol? head)
                       (if (k-fun-bound? (syn-name head)) (k-fun-named head) -1)
                       (if (string=? (k-list-head head) "dlambda") (k-parse-fun head -1) -1))))))
      (if (< f 0)
          nil
          (let ((parts (k-arrow-parts (k-fun-kind f))))
            (if (null? parts)
                nil
                (let ((ps (car (car parts))) (result (cdr (car parts))))
                  (cond ((not (= result 1)) (k-gives-fail f result "an effect" s))
                        ((not (= (k-length (cdr items)) (k-length ps)))
                         (k-arity-fail f (k-length ps) (k-length (cdr items)) s))
                        (else
                         (tagcase (k-apply-fun f (k-parse-descs-at (cdr items) ps))
                           (de (e) (the (listof k-eff acyclic) (cons e nil)))
                           (else y (k-not-giving f "an effect" s))))))))))))
(define k-try-kind (subr (maxeff kstate (read @s) spin) (syn) int)
  (lambda (s)
    (let ((n (if (syn-symbol? s) (syn-name s) "")))
      (case n (("region") 0)
              (("place") 3)
              (("effect") 1)
              (("type") 2)
              (("data") 4)
              (("size") 5)
              (("conv") 6)
              (else
               (cond ((syn-symbol? s) -1)
                     (else (k-try-arrow-kind s))))))))
(define k-try-arrow-kind (subr (maxeff kstate (read @s) spin) (syn) int)
  (lambda (s)
    (let ((parts (k-arrow-syntax s)))
      (if (null? parts)
          -1
          (let* ((params (k-try-kinds (car (car parts))))
                 (result (k-try-kind (cdr (car parts)))))
            (cond ((or (k-has-id? params -1) (< result 0)) -1)
                  ((or (= result 0) (= result 3) (= result 5) (= result 6)) -1)
                  ((and (= result 1) (k-any-typed-kind? params)) -1)
                  (else (k-arrow params result))))))))
(define k-try-kinds (subr (maxeff kstate (read @s) spin) (k-syns) k-ids)
  (lambda (xs)
    (if (null? xs)
        nil
        (let* ((k (k-try-kind (car xs))) (rest (k-try-kinds (cdr xs))))
          (the k-ids (cons k rest))))))
;; A `moduleof`'s description `what` of `name`, in scope in what follows it:
;; `(desc e E)`, an effect, as a module's `define-effect` gives; a description
;; function; or a type.
(define k-moduleof-desc (subr (maxeff checks spin) (symbol syn) int)
  (lambda (name what)
    (cond ((k-effect-shaped? what)
           (let* ((e (k-parse-effect what)) (d (k-effect-desc e)))
             (begin (k-push-desc name (ds-eff e)) d)))
          ((string=? (k-list-head what) "dlambda")
           (let ((f (k-parse-fun what -1))) (begin (k-push-desc name (ds-fun f)) f)))
          (else (let ((t (k-parse-type what))) (begin (k-push-desc name (ds-rec t)) t))))))
;; A `moduleof`'s components `cs`, those before them read into `abs`, `ds`
;; and `vs` (newest first), their names `seen` (types and effects) and `vseen`
;; (values): a value may have a type's name.
(define k-moduleof-comps
  (subr (maxeff checks spin) (k-syns k-parts k-parts k-parts k-names k-names) int)
  (lambda (cs abs ds vs seen vseen)
    (if (null? cs)
        (let ((ds (k-parts-reversed ds nil)) (vs (k-parts-reversed vs nil)))
          (k-ty-new (ty-module (k-parts-reversed abs nil) ds vs)))
        (let* ((c (car cs))
               (parts (k-items c "a module component"))
               (shaped (k-shape (= (k-length parts) 3) k-moduleof-usage c))
               (head (k-symbol-head parts))
               (names (k-component-names (k-nth parts 1) head))
               (val? (string=? head "val"))
               (seen (if val? seen (k-names-once names seen c)))
               (vseen (if val? (k-names-once names vseen c) vseen))
               (what (k-nth parts 2)))
          (case head
            (("abs")
             (let ((k (k-try-kind what)))
               (if (or (= k 2) (and (k-arrow-kind? k) (= (k-arrow-result k) 2)))
                   (k-moduleof-comps (cdr cs) (k-abs-bound names k abs) ds vs seen vseen)
                   (k-sfail k-abs-usage what))))
            (("desc")
             (let ((d (k-moduleof-desc (car names) what)))
               (k-moduleof-comps (cdr cs) abs (k-part-onto (car names) d ds) vs seen vseen)))
            (("val")
             (let ((t (k-parse-type what)))
               (k-moduleof-comps (cdr cs) abs ds (k-part-onto (car names) t vs) seen vseen)))
            (else (k-sfail k-moduleof-usage (car parts))))))))
;; `(moduleof …)`, each abstract type a binder in scope in what follows it;
;; or `(select m t)`.
(define k-read-module-type (subr (maxeff checks spin) (syn k-syns symbol) int)
  (lambda (s items hd)
    (if (symbol=? hd 'select)
        (k-parse-select s items)
        (let* ((saved (get k-dscope)) (t (k-moduleof-comps (cdr items) nil nil nil nil nil)))
          (begin (set k-dscope saved) t)))))
(define k-selects-from (subr (maxeff kstate spin) (int k-seen (ref k-selects @t)) unit)
  (lambda (t seen out)
    (let ((t (k-resolve t)))
      (if (k-seen? seen t)
          #u
          (begin
            (tagcase (k-get t)
              (ty-select (m n) (set out (cons (product (1 m) (2 n) (3 t)) (get out))))
              (else y (k-selects-each (k-ty-kids t) seen out))))))))
(define k-selects-each (subr (maxeff kstate spin) (k-ids k-seen (ref k-selects @t)) unit)
  (lambda (ts seen out)
    (if (null? ts)
        #u
        (begin (k-selects-from (car ts) seen out) (k-selects-each (cdr ts) seen out)))))
;; The `select`s in `t`, in the order first met.
(define k-selects-in (subr (maxeff kstate spin) (int) k-selects)
  (lambda (t)
    (let ((out (the (ref k-selects @t) (new nil))))
      (begin (k-selects-from t (k-new-seen) out)
             (k-selects-reversed (get out) nil)))))
;; `t` with each `(select m x)` of a parameter named before it, the `k`th,
;; made `(select $k x)`.
(define k-select-params (subr (maxeff kstate spin) (int k-names) int)
  (lambda (t names)
    (let ((sel (if (k-all-unnamed? names)
                   (the k-selects nil)
                   (k-param-selects (k-selects-in t) names))))
      (if (null? sel)
          t
          (let ((outer (get k-select-map)))
            (begin (set k-select-map sel)
                   (let ((r (k-subst t nil))) (begin (set k-select-map outer) r))))))))
;; A `subr` type's parameters `ps` (from those named `names`) and its
;; result `r`, read: their types, the result last.
(define k-read-params-from (subr (maxeff checks spin) (k-syns syn k-names) k-ids)
  (lambda (ps r names)
    (if (null? ps)
        ;; A test's result, `(bool …)`: here, and only here.
        (let ((t (if (string=? (k-list-head r) "bool")
                     (k-parse-proving r (k-length names))
                     (k-parse-type r))))
          (cons (k-select-params t names) nil))
        (let* ((named (k-param-name (car ps)))
               (written (if (null? named) (car ps) (k-nth (k-items (car ps) "a parameter") 1)))
               (t (k-select-params (k-parse-type written) names))
               (name (if (null? named) k-no-name (car named)))
               (rest (k-read-params-from (cdr ps) r (k-names-snoc names name))))
          (cons t rest)))))
(define k-read-params (subr (maxeff checks spin) (k-syns syn) k-ids)
  (lambda (ps r) (k-read-params-from ps r nil))))))
