;;; The checker, in FX-26: the rules, each expression's type and effect.
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

(define-rec
  (k-synth (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (let* ((r (k-synth-node x)) (e (k-frozen x (extract r 2))))
        (begin (k-note-effect x e) (k-te (extract r 1) e)))))
  (k-synth-node (subr (maxeff checks spin) (kx) k-te)
    (lambda (x)
      (tagcase x
        (x-var (s a b)
          (let ((t (k-lookup s)))
            (if (< t 0) (k-fail (k-unbound s) a b) (k-te t (k-naming-effect s t)))))
        (x-const (t v a b) (k-te t nil))
        (x-lambda (ps body a b) (k-synth-lambda-as x nil -1))
        (x-app (f args a b) (k-synth-app x f args -1))
        (x-the (t e a b) (k-te t (k-check e t)))
        (x-convention (c e a b)
          (let* ((r (k-synth e)) (t (k-resolve (extract r 1))))
            (tagcase (k-get t)
              (ty-subr (fe ps res from)
                (begin (if (k-conv=? from c) #u (k-convert-at x t c))
                       (k-te (k-ty-new (ty-subr fe ps res c)) (extract r 2))))
              (else y (k-fail (string-append "`convention` takes a procedure, and this is a " (k-show-ty t)) a b)))))
        (x-plambda (bs body a b)
          (let ((r (k-synth body)))
            (if (k-generalizable? body (extract r 2))
                (k-te (k-ty-new (ty-poly bs (extract r 1))) (extract r 2))
                (k-fail (string-append "a `plambda` body must be pure, and this one has " (k-show-effect (extract r 2))) a b))))
        (x-rlambda (r l a b) (k-synth-rlambda x r l -1))
        (x-proj (body ds a b)
          (let* ((r (k-synth body)) (t (extract r 1)))
            (tagcase (k-get t)
              (ty-poly (bs inner)
                (if (not (= (k-length bs) (k-length ds)))
                    (k-fail (k-cat5 "this `poly` binds " (int->string (k-length bs)) " description(s); `proj` gave "
                                    (int->string (k-length ds)) "")
                            a b)
                    (let ((result (let ((m (k-proj-map bs ds a b)))
                                    (begin (k-check-bounds bs m a b) (k-check-finite-sizes bs m inner a b) (let ((inst (k-subst inner m))) (begin (k-no-knot inst a b) inst))))))
                      (k-te result (k-mask x (extract r 2) result)))))
              (else y (k-fail (string-append "`proj` needs a polymorphic value, not a " (k-show-ty t)) a b)))))
        (x-if (p c d a b)
          (let ((rp (k-synth p)))
            (if (not (k-subtype (extract rp 1) k-bool))
                (k-fail "an `if` test must be a bool" (k-start p) (k-end p))
                (let* ((cert (k-acyclic-test p))
                       (saved (get k-certified))
                       (pushed (set k-certified (if (null? cert) saved (the (listof (pairof symbol int @t) acyclic) (cons (car cert) saved)))))
                       (lens (k-length-test p))
                       (lsaved (get k-certified-lengths))
                       (lpushed (set k-certified-lengths (if (null? lens) lsaved (the (listof k-cert-len acyclic) (cons (car lens) lsaved)))))
                   (nats (k-nat-test p))
                   (nsaved (get k-certified-nats))
                   (npushed (set k-certified-nats (if (null? nats) nsaved (the (listof (pairof symbol int @t) acyclic) (cons (car nats) nsaved)))))
                       (facts (k-test-facts p))
                       (fsaved (get k-size-facts))
                       (fyes (set k-size-facts (k-with-fact (car facts) fsaved)))
                       (rc (k-synth c))
                       (fpopped (set k-size-facts fsaved))
                       (popped (set k-certified saved))
                       (lpopped (set k-certified-lengths lsaved)) (npopped (set k-certified-nats nsaved))
                       (fno (set k-size-facts (k-with-fact (cdr facts) fsaved)))
                       (rd (k-synth d))
                       (fdone (set k-size-facts fsaved)) (tc (extract rc 1)) (td (extract rd 1))
                       (t (cond ((k-subtype tc td) td)
                                ((k-subtype td tc) tc)
                                ;; Naturals of sizes not shown equal: a `nat`.
                                ((and (tagcase (k-get (k-resolve tc)) (ty-nat (z) #t) (else w #f))
                                      (tagcase (k-get (k-resolve td)) (ty-nat (z) #t) (else w #f)))
                                 (k-ty-new (ty-nat (sz-finite))))
                                (else (k-fail (k-cat4 "the branches are a " (k-show-ty tc) " and a " (k-show-ty td)) a b)))))
                  (k-te t (k-mask x (k-union (extract rp 2) (k-union (extract rc 2) (extract rd 2))) t))))))
        (x-letrec (bs body a b)
          (let ((saved (k-mark)) (rsaved (get k-recursive)))
            (begin
              (k-bind-letrec bs)
              ;; A group whose every run ends needs no `spin`.
              (k-letrec-lambdas bs)
              (let ((why (k-termination bs)))
                (begin (k-note-letrec bs (not (string=? why ""))) (if (string=? why "") #u (k-note-why bs why))))
              ;; The body's calls of the group are not recursion.
              (let* ((ie (k-check-letrec bs)) (restored (set k-recursive rsaved)) (rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (k-te (extract rb 1) (k-mask x (k-union ie (extract rb 2)) (extract rb 1))))))))
        (x-let (bs body a b)
          (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
            (begin
              (k-bind-named (extract inits 1))
              (k-note-let-lambdas bs)
              (let ((rb (k-synth body)))
                (begin
                  (k-unbind-to saved)
                  (let ((t (k-forget-nats named (extract rb 1) a b)))
                    (k-te t (k-mask x (k-union (extract inits 2) (extract rb 2)) t))))))))
        (x-prompt (t body h a b) (k-synth-prompt x t body h))
        ;; The region's name is a variable too, of type `(place r)`, when
        ;; the form makes a place.
        (x-letregion (k r i body a b)
          (let* ((saved (k-mark))
                 (bound (if (or (= k 0) (= k 3)) #u (k-bind (k-dvar-name r) (k-ty-new (ty-place (r-var r))))))
                 (freezing (get k-freezing))
                 (pushed (if (= k 3) (set k-freezing (cons r freezing)) #u))
                 (rb (k-synth body))
                 (written (k-has-id? (get k-written) r))
                 (popped (set k-freezing freezing)))
            (begin
              (k-unbind-to saved)
              (k-close-region x (cond ((= k 0) "letregion") ((= k 1) "letrena") ((= k 2) "letreap") (else "letfreeze"))
                              r (if (= k 3) (k-frozen-result r i written (extract rb 1) a b) (extract rb 1)) (extract rb 2) a b))))
        (x-bloblet (op i args a b) (k-synth-bloblet x op i args -1))
        (x-product (fs a b)
          (let* ((r (k-synth-fields fs)) (t (k-ty-new (ty-product (extract r 1)))))
            (k-te t (k-mask x (extract r 2) t))))
        (x-extract (e l a b)
          (let* ((r (k-synth e)) (pt (extract r 1)))
            (tagcase (k-get pt)
              (ty-product (fs)
                (let ((t (k-part-find fs l)))
                  (if (< t 0)
                      (k-fail (k-cat4 "a " (k-show-ty pt) " has no " (k-quote (symbol->string l))) a b)
                      (begin
                        (set k-extracts (cons (product (1 a) (2 b) (3 (k-part-index fs l 0))) (get k-extracts)))
                        (k-te t (k-mask x (extract r 2) t))))))
              (else y (k-fail (string-append "a product is expected here, and this is a " (k-show-ty pt)) (k-start e) (k-end e))))))
        (x-sum (l e a b)
          (let* ((r (k-synth e)) (t (k-ty-new (ty-sum (cons (product (1 l) (2 (extract r 1))) nil)))))
            (k-te t (k-mask x (extract r 2) t))))
        (x-tagcase (s arms els a b) (k-synth-tagcase x s arms els -1))
        (x-begin (xs a b)
          (let ((r (k-synth-seq xs k-unit nil)))
            (k-te (extract r 1) (k-mask x (extract r 2) (extract r 1))))))))
  (k-synth-seq (subr (maxeff checks spin) (kxs int k-eff) k-te)
    (lambda (xs last e)
      (if (null? xs) (k-te last e) (let ((r (k-synth (car xs)))) (k-synth-seq (cdr xs) (extract r 1) (k-union e (extract r 2)))))))
  (k-synth-fields (subr (maxeff checks spin) ((listof (productof (1 symbol) (2 kx)) acyclic)) (productof (1 k-parts) (2 k-eff)))
    (lambda (fs)
      (if (null? fs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car fs) 2))) (rest (k-synth-fields (cdr fs))))
            (product (1 (cons (product (1 (extract (car fs) 1)) (2 (extract r 1))) (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-synth-lets (subr (maxeff checks spin) ((listof (productof (1 symbol) (2 kx)) acyclic)) (productof (1 k-bindings) (2 k-eff)))
    (lambda (bs)
      (if (null? bs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (extract (car bs) 2)))
                 (rest (k-synth-lets (cdr bs))))
            (product (1 (cons (cons (extract (car bs) 1) (extract r 1)) (extract rest 1)))
                     (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-check-letrec (subr (maxeff checks spin) ((listof (productof (1 symbol) (2 int) (3 kx)) acyclic)) k-eff)
    (lambda (bs)
      (if (null? bs)
          nil
          (let* ((n (extract (car bs) 1)) (t (extract (car bs) 2)) (init (extract (car bs) 3))
                 ;; Only lambdas: then nothing runs before every binding
                 ;; exists, and no one sees the knot tied.
                 (e (if (k-lambda? init)
                        (k-check-declared n t init)
                        (k-fail (k-letrec-not-lambda n) (k-start init) (k-end init))))
                 (rest (k-check-letrec (cdr bs))))
            (k-union e rest)))))
  ;; Check `init` against `t`, the type `n` is declared; an error at `init`
  ;; itself says so.
  (k-check-declared (subr (maxeff checks spin) (symbol int kx) k-eff)
    (lambda (n t init)
      (extract (k-declaring (lambda () (k-te t (k-check init t))) (k-start init) (k-end init) n t) 2)))
  ;;; ------------------------------------------------------------ lambda

  ;; A `lambda`'s type. `hint` supplies the types of parameters the program
  ;; left out; `result`, when not -1, is what the body is checked against.
  (k-synth-lambda-as (subr (maxeff checks spin) (kx k-ids int) k-te)
    (lambda (x hint result)
      (tagcase x
        (x-lambda (ps body a b)
          (let* ((typed (k-param-types ps hint a b)) (saved (k-mark)) (named (get k-skolems)))
            (begin
              (k-bind-named typed)
              (let* ((r (if (>= result 0)
                            (let ((e (k-check body result))) (k-te result (k-mask body e result)))
                            (let ((r (k-synth body))) (k-te (extract r 1) (k-mask body (extract r 2) (extract r 1)))))))
                (begin
                  (k-unbind-to saved)
                  (set k-last-latent (extract r 2))
                  (k-te (k-ty-new (ty-subr (extract r 2) (k-binding-types typed) (k-forget-nats named (extract r 1) a b) (get k-conv-default))) nil))))))
        (else y (k-fail "a lambda" (k-start x) (k-end x))))))
  ;; An `rlambda`'s type: its `lambda`'s, told `expected`'s parameter and
  ;; result types if it is a subroutine's, with `(read R)` in its latent
  ;; effect, since calling it reads the closure; making it allocates in `R`,
  ;; the region `r` names.
  (k-synth-rlambda (subr (maxeff checks spin) (kx kx kx int) k-te)
    (lambda (x r l expected)
      (let* ((rr (k-synth r))
             (rt (extract rr 1))
             (g (tagcase (k-get rt)
                  (ty-place (g) g)
                  (else y (k-fail (k-cat3 "a region is expected here, and this is a " (k-show-ty rt) "") (k-start r) (k-end r)))))
             (c (if (< expected 0) (the (listof k-callable acyclic) nil) (k-as-subr expected)))
             (n (tagcase l (x-lambda (ps body a b) (k-length ps)) (else y 0)))
             (lt (cond
                   ((null? c) (k-synth-lambda-as l nil -1))
                   ((not (= (k-length (extract (car c) 2)) n))
                    (k-fail (k-cat4 "a subroutine of " (int->string (k-length (extract (car c) 2))) " parameter(s) is expected, and this `rlambda` has "
                                    (int->string n))
                            (k-start x) (k-end x)))
                   (else (k-synth-lambda-as l (extract (car c) 2) (extract (car c) 3)))))
             (t (tagcase (k-get (extract lt 1))
                  (ty-subr (e ps res cv) (k-ty-new (ty-subr (k-insert (a-read g) e) ps res cv)))
                  (else y (k-fail "a lambda" (k-start x) (k-end x)))))
             (e (k-insert (a-alloc g) (extract rr 2))))
        (k-te t (k-mask x e t)))))
  ;;; ------------------------------------------------------------ application
  (k-synth-app (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let ((op (tagcase f
                  (x-var (op fa fb) (let ((t (k-lookup op))) (if (and (>= t 0) (k-named-has? (get k-std) op t)) (symbol->string op) "")))
                  (else y ""))))
        (cond ((string=? op "certify-acyclic") (k-certify x args))
              ((string=? op "certify-length") (k-certify-length x args))
              ((string=? op "certify-nat") (k-certify-nat x args))
              ((and (or (string=? op "+") (string=? op "-")) (not (null? args)) (not (null? (cdr args))) (null? (cdr (cdr args))))
               (k-nat-arith x op args))
              ((string=? op "cons")
               (let ((r (k-nlist-cons x args expected))) (if (null? r) (k-synth-app-plain x f args expected) (car r))))
              (else (k-synth-app-plain x f args expected))))))
  ;; `+` and `-` of naturals: a natural, of a size when both are known. Only
  ;; what has a type of its own is asked for it; anything else is told it
  ;; is an int, as for any call.
  (k-nat-arith (subr (maxeff checks spin) (kx string kxs) k-te)
    (lambda (x op args)
      (let* ((ra (k-nat-operand (car args)))
             (rb (k-nat-operand (car (cdr args))))
             (za (extract ra 2)) (zb (extract rb 2))
             (sz (if (or (null? za) (null? zb)) (the (listof k-size acyclic) nil) (k-nat-arith-size op (car za) (car zb)))))
        (k-te (if (null? sz) k-int (k-ty-new (ty-nat (car sz)))) (k-union (extract ra 1) (extract rb 1))))))
  (k-nat-operand (subr (maxeff checks spin) (kx) (productof (1 k-eff) (2 (listof k-size acyclic))))
    (lambda (x)
      (if (not (k-natural-by-itself? x))
          (product (1 (k-check x k-int)) (2 (the (listof k-size acyclic) nil)))
          (let* ((r (k-synth x)) (t (extract r 1)))
            (begin (k-expect x t k-int) (product (1 (extract r 2)) (2 (k-operand-size x t))))))))
  ;; `(certify-length v k)`: `v`'s value as a `(nlist T k)`, where `length-is?`
  ;; has just found it so; nowhere else.
  (k-certify-length (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (let* ((none (the (listof k-cert-len acyclic) nil))
             (found (if (and (not (null? args)) (not (null? (cdr args))) (null? (cdr (cdr args))))
                        (k-length-arg (car args) (car (cdr args)))
                        none))
             (ok (and (not (null? found)) (k-cert-len-has? (get k-certified-lengths) (car found)))))
        (if (not ok)
            (k-fail "`certify-length` takes only a variable and a length `length-is?` has just confirmed" (k-start x) (k-end x))
            (let* ((r (k-synth (car args))) (t (k-resolve (extract r 1))) (k (extract (car found) 3)))
              (tagcase (k-get t)
                (ty-pair (e tail rg)
                  (if (and (= (k-resolve tail) t) (tagcase rg (r-frozen (p f) #t) (else y #f)))
                      (k-te (k-ty-new (ty-nlist e k (k-fin-region rg))) (extract r 2))
                      (k-fail (k-cat3 "`certify-length` takes a frozen list, and this is a " (k-show-ty t) "") (k-start x) (k-end x))))
                (ty-nlist (e z rg) (k-te (k-ty-new (ty-nlist e k (k-fin-region rg))) (extract r 2)))
                (else y (k-fail (k-cat3 "`certify-length` takes a frozen list, and this is a " (k-show-ty t) "") (k-start x) (k-end x)))))))))
  ;; `cons` onto a `nlist`: one more element. Where a `nlist` is expected, the
  ;; tail is checked as one shorter; otherwise, a tail that is a variable of
  ;; `nlist` type gives a `nlist` one longer. None if neither.
  (k-nlist-cons (subr (maxeff checks spin) (kx kxs int) (listof k-te acyclic))
    (lambda (x args expected)
      (if (not (and (not (null? args)) (not (null? (cdr args))) (null? (cdr (cdr args)))))
          nil
          (let ((hd (car args)) (tl (car (cdr args))))
            (let ((want (if (< expected 0) (ty-void) (k-get expected))))
              (tagcase want
                (ty-nlist (e z r)
                  (if (not (or (tagcase z (sz-finite () #t) (else w #f)) (k-size-nonneg? (k-size-plus z -1))))
                      (k-nlist-cons-tail hd tl)
                      (let* ((tail-ty (k-ty-new (ty-nlist e (k-size-plus z -1) r)))
                             (xe (k-check hd e))
                             (te (k-check tl tail-ty)))
                        (the (listof k-te acyclic) (cons (k-te expected (k-union xe te)) nil)))))
                (else y (k-nlist-cons-tail hd tl))))))))
  (k-nlist-cons-tail (subr (maxeff checks spin) (kx kx) (listof k-te acyclic))
    (lambda (hd tl)
      (tagcase tl
        (x-var (v va vb)
          (let ((t (k-lookup v)))
            (if (< t 0)
                nil
                (tagcase (k-get t)
                  (ty-nlist (e z r)
                    (let* ((xe (k-check hd e)) (rt (k-synth tl)))
                      (the (listof k-te acyclic) (cons (k-te (k-ty-new (ty-nlist e (k-size-plus z 1) r)) (k-union xe (extract rt 2))) nil))))
                  (else y nil)))))
        (else y nil))))
  ;; `(certify-nat v)`: `v`'s value as a `nat`, where `nat?` has just found
  ;; `v` no less than 0; nowhere else.
  (k-certify-nat (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (let ((ok (and (k-sc-one-arg? args)
                     (tagcase (car args) (x-var (v va vb) (k-certified-has? (get k-certified-nats) v (k-binding-depth v))) (else y #f)))))
        (if (not ok)
            (k-fail "`certify-nat` takes only a variable `nat?` has just found no less than 0" (k-start x) (k-end x))
            (let ((r (k-synth (car args))))
              (begin (k-expect (car args) (extract r 1) k-int)
                     (k-te (k-ty-new (ty-nat (sz-finite))) (extract r 2))))))))
  ;; `(certify-acyclic v)`: `v`'s value at `acyclic`, where `acyclic?` has
  ;; just found `v` acyclic; nowhere else.
  (k-certify (subr (maxeff checks spin) (kx kxs) k-te)
    (lambda (x args)
      (let ((ok (and (k-sc-one-arg? args)
                     (tagcase (car args) (x-var (v va vb) (k-certified-has? (get k-certified) v (k-binding-depth v))) (else y #f)))))
        (if (not ok)
            (k-fail "`certify-acyclic` takes only a variable `acyclic?` has just found acyclic" (k-start x) (k-end x))
            (let* ((r (k-synth (car args))) (t (extract r 1)))
              (if (k-is-data? t)
                  (k-te (k-finitized t) (extract r 2))
                  (k-fail (k-cat3 "`certify-acyclic` takes data, and a " (k-show-ty t) " is not data") (k-start x) (k-end x))))))))
  (k-synth-app-plain (subr (maxeff checks spin) (kx kx kxs int) k-te)
    (lambda (x f args expected)
      (let* ((a (k-start x)) (b (k-end x))
             (rf (k-synth f))
             (n (k-length args))
             (done-t (the (arrayof int @t) (make-array n -1)))
             (done-e (the (arrayof k-eff @t) (make-array n nil)))
             (ft (tagcase (k-get (extract rf 1))
                   (ty-poly (bs body)
                     (let ((inst (k-instantiate (extract rf 1) args expected a b done-t done-e)))
                       (begin (k-no-knot inst a b) inst)))
                   (else y (extract rf 1))))
             (callee (k-as-subr ft))
             (variadic (k-vsubr-parts ft)))
        (cond
          ;; Any number of arguments, each of the element type.
          ((not (null? variadic))
           (let ((v (car variadic)))
             (k-app-result x f ft args (k-vapp-args args (extract v 2) 0 (extract rf 2))
                           (extract v 1) (extract v 3))))
          ((null? callee) (k-fail (string-append "not a subroutine: " (k-show-ty ft)) a b))
          ((not (= (k-length (extract (car callee) 2)) n))
           (k-fail (k-cat4 "expected " (int->string (k-length (extract (car callee) 2)))
                           " argument(s), got " (int->string n))
                   a b))
          (else
           (let* ((c (car callee))
                  (e (k-app-args args (extract c 2) 0 done-t done-e (extract rf 2))))
             (k-app-result x f ft args e (extract c 1) (extract c 3))))))))
  ;; A call's type and effect, once its arguments have effect `e`: its
  ;; callee's latent effect too, `spin` where the call may loop, and what
  ;; the call masks; its result, of type `result`.
  (k-app-result (subr (maxeff checks spin) (kx kx int kxs k-eff k-eff int) k-te)
    (lambda (x f ft args e latent result)
      (let* ((e (k-union e latent))
             (e (if (k-may-spin? f ft args) (k-insert (a-spin) e) e)))
        (k-te result (k-mask x e result)))))
  (k-app-args (subr (maxeff checks spin) (kxs k-ids int (arrayof int @t) (arrayof k-eff @t) k-eff) k-eff)
    (lambda (args params i done-t done-e e)
      (if (null? args)
          e
          (let* ((arg (car args)) (p (car params)) (t (array-ref done-t i))
                 (ae (if (>= t 0)
                         (if (k-subtype t p)
                             (array-ref done-e i)
                             (let ((c (k-conversion t p)))
                               (if (null? c)
                                   (k-fail (k-cat5 "argument " (int->string (+ i 1)) " is a " (k-show-ty t)
                                                   (k-cat3 ", where a " (k-show-ty p) " is expected"))
                                           (k-start arg) (k-end arg))
                                   (begin (k-convert-at arg t (car c)) (array-ref done-e i)))))
                         (k-check-argument arg p i))))
            (k-app-args (cdr args) (cdr params) (+ i 1) done-t done-e (k-union e ae))))))
  ;; A `vsubr` call's arguments, each checked as its element type `t`.
  (k-vapp-args (subr (maxeff checks spin) (kxs int int k-eff) k-eff)
    (lambda (args t i e)
      (if (null? args)
          e
          (k-vapp-args (cdr args) t (+ i 1) (k-union e (k-check-argument (car args) t i))))))
  ;; An argument that failed to check is reported as that argument.
  (k-check-argument (subr (maxeff checks spin) (kx int int) k-eff)
    (lambda (arg p i)
      (extract (k-rewriting (lambda () (k-te p (k-check arg p))) (k-start arg) (k-end arg)
                            (lambda (m want got) (k-cat5 "argument " (int->string (+ i 1)) " is a " got
                                                         (k-cat3 ", where a " want " is expected"))))
               2)))
  (k-instantiate (subr (maxeff checks spin) (int kxs int int int (arrayof int @t) (arrayof k-eff @t)) int)
    (lambda (ft args expected a b done-t done-e)
      (let* ((bo (k-binders-of ft)) (kinds (extract bo 1)) (inner (extract bo 2)) (callee (k-as-subr inner)))
        (if (null? callee)
            (k-fail (string-append "not a subroutine, even once projected: " (k-show-ty ft)) a b)
            (let ((params (extract (car callee) 2)) (result (extract (car callee) 3)) (solved (the k-solved (new nil))))
              (if (not (= (k-length params) (k-length args)))
                  (k-fail (k-cat4 "expected " (int->string (k-length params)) " argument(s), got " (int->string (k-length args))) a b)
                  (begin
                    (if (>= expected 0) (k-unify result expected kinds solved (the k-trail (new nil))) #u)
                    (k-inst-asked args params 0 kinds solved done-t done-e)
                    (k-inst-told args params 0 kinds solved done-t done-e)
                    (k-inst-shapes args params 0 solved done-t)
                    (k-default-regions kinds solved)
                    (let ((m (k-finish kinds solved a b ft))) (begin (k-check-bounds kinds m a b) (k-check-finite-sizes kinds m inner a b) (k-subst inner m))))))))))
  ;; What the arguments are, except the ones that need to be told.
  (k-inst-asked (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved (arrayof int @t) (arrayof k-eff @t)) unit)
    (lambda (args params i kinds solved done-t done-e)
      (if (null? args)
          #u
          (begin
            (if (k-needs-telling? (car args))
                #u
                (let ((p (k-subst (car params) (get solved))))
                  (if (not (k-mentions-any-unknown? p kinds solved))
                      (let ((e (k-check (car args) p))) (begin (array-set! done-t i p) (array-set! done-e i e)))
                      (let ((r (k-synth (car args))))
                        (tagcase (k-get (extract r 1))
                          (ty-poly (bs body) #u)
                          (else y
                            (begin (k-unify (car params) (extract r 1) kinds solved (the k-trail (new nil)))
                                   (array-set! done-t i (extract r 1))
                                   (array-set! done-e i (extract r 2)))))))))
            (k-inst-asked (cdr args) (cdr params) (+ i 1) kinds solved done-t done-e)))))
  ;; The arguments that needed telling: each is checked against its parameter
  ;; as solved so far, and what it turns out to be solves more.
  (k-inst-told (subr (maxeff checks spin) (kxs k-ids int k-binders k-solved (arrayof int @t) (arrayof k-eff @t)) unit)
    (lambda (args params i kinds solved done-t done-e)
      (if (null? args)
          #u
          (begin
            (if (>= (array-ref done-t i) 0)
                #u
                (let* ((arg (car args))
                       (defaulted (k-default-regions kinds solved))
                       (p (k-subst (car params) (get solved))))
                 (letrec ((not-known (subr (maxeff (read @globals) checks spin) (int) void)
                         (lambda (t)
                           (k-fail (k-cat5 "argument " (int->string (+ i 1)) " must be a " (k-show-ty t)
                                           ", which is not yet known here; give the other arguments first, or `proj` the operator")
                                   (k-start arg) (k-end arg)))))
                  (cond
                    ;; A thunk has no parameters to be told: told nothing, it
                    ;; says what it is, as any argument does.
                    ((and (k-needs-telling? arg) (null? (k-as-subr p)) (tagcase arg (x-lambda (ps body a b) (null? ps)) (else y #f)))
                     (let ((r (k-synth arg)))
                       (begin (k-unify (car params) (extract r 1) kinds solved (the k-trail (new nil)))
                              (array-set! done-t i (extract r 1))
                              (array-set! done-e i (extract r 2)))))
                    ((k-needs-telling? arg)
                     (let ((c (k-as-subr p)))
                       (if (or (null? c) (k-any-unknown-type? (extract (car c) 2) kinds solved))
                           (not-known p)
                           (let* ((res (extract (car c) 3))
                                  (r (k-synth-lambda-as arg (extract (car c) 2)
                                                        (if (k-mentions-unknown-type? res kinds solved) -1 res))))
                             (begin (k-unify (car params) (extract r 1) kinds solved (the k-trail (new nil)))
                                    (array-set! done-t i (extract r 1))
                                    (array-set! done-e i (extract r 2)))))))
                    ((k-mentions-unknown-type? p kinds solved) (not-known p))
                    (else (let ((e (k-check arg p))) (begin (array-set! done-t i p) (array-set! done-e i e))))))))
            (k-inst-told (cdr args) (cdr params) (+ i 1) kinds solved done-t done-e)))))
  ;;; ------------------------------------------------------------ check mode
  (k-check (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let ((e (k-frozen x (k-check-mode x expected))))
        (begin (k-note-effect x e) e))))
  (k-check-mode (subr (maxeff checks spin) (kx int) k-eff)
    (lambda (x expected)
      (let* ((et (k-get expected))
             (poly? (tagcase et (ty-poly (bs body) #t) (else y #f)))
             (plambda? (tagcase x (x-plambda (bs body a b) #t) (else y #f))))
        (cond
          ((and poly? (not plambda?))
           (tagcase et
             (ty-poly (bs body)
               (let ((e (k-check x body)))
                 (if (k-generalizable? x e) e (k-fail (string-append "a polymorphic value must be pure, and this has " (k-show-effect e)) (k-start x) (k-end x)))))
             (else y nil)))
          ((and poly? plambda? (k-plambda-matches? x et))
           (tagcase x
             (x-plambda (binders body a b)
               (tagcase et
                 (ty-poly (bs want)
                   (let* ((want (k-subst want (k-rename bs binders))) (e (k-check body want)))
                     (if (k-generalizable? body e) e (k-fail (string-append "a `plambda` body must be pure, and this one has " (k-show-effect e)) a b))))
                 (else y nil)))
             (else y nil)))
          (else (k-check-node x expected et))))))
  (k-check-node (subr (maxeff checks spin) (kx int k-ty) k-eff)
    (lambda (x expected et)
      (letrec ((otherwise (subr (maxeff (read @globals) checks spin) () k-eff)
                           (lambda () (let ((r (k-synth x))) (begin (k-expect x (extract r 1) expected) (extract r 2))))))
       (the k-eff (let ((a (k-start x)) (b (k-end x)))
        (tagcase x
          (x-lambda (ps body xa xb)
            (let ((c (k-as-subr expected)))
              (cond
                ((not (null? c))
                 (let ((want (extract (car c) 2)))
                   (if (not (= (k-length want) (k-length ps)))
                       (k-fail (k-cat4 "a subroutine of " (int->string (k-length want)) " parameter(s) is expected, and this `lambda` has "
                                       (int->string (k-length ps)))
                               a b)
                       (let ((r (k-synth-lambda-as x want (extract (car c) 3))))
                         (begin (k-expect x (extract r 1) expected) (extract r 2))))))
                ((k-some-untyped? ps) (k-fail (string-append "a `lambda` cannot be a " (k-show-ty expected)) a b))
                (else (otherwise)))))
          (x-rlambda (r l xa xb)
            (if (null? (k-as-subr expected))
                (otherwise)
                (let ((rr (k-synth-rlambda x r l expected))) (begin (k-expect x (extract rr 1) expected) (extract rr 2)))))
          (x-app (f args xa xb)
            (let ((r (k-synth-app x f args expected))) (begin (k-expect x (extract r 1) expected) (extract r 2))))
          (x-bloblet (op i args xa xb)
            (let ((r (k-synth-bloblet x op i args expected))) (begin (k-expect x (extract r 1) expected) (extract r 2))))
          (x-tagcase (s arms els xa xb) (extract (k-synth-tagcase x s arms els expected) 2))
          (x-product (fs xa xb)
            (tagcase et
              (ty-product (want)
                (if (k-same-labels? fs want)
                    (k-mask x (k-check-fields fs want) expected)
                    (otherwise)))
              (else y (otherwise))))
          (x-sum (l e xa xb)
            (tagcase et
              (ty-sum (vs)
                (let ((t (k-part-find vs l)))
                  (if (>= t 0) (k-mask x (k-check e t) expected) (otherwise))))
              (else y (otherwise))))
          ;; A natural literal is a `nat`, and a `(nat k)`.
          (x-const (ty k xa xb)
            (if (and (= ty k-int) (>= k 0) (tagcase et (ty-nat (z) (k-size-le? (k-size-lit k) z)) (else w #f)))
                nil
                (otherwise)))
          (x-var (s xa xb)
            (let ((t (k-lookup s)))
              (cond
               ;; `nil` is a `nlist` of no elements, or of some.
               ((and (string=? (symbol->string s) "nil") (>= t 0) (k-named-has? (get k-std) s t)
                     (tagcase et (ty-nlist (e z r) (or (tagcase z (sz-finite () #t) (else w #f)) (k-size-eq? z (k-size-lit 0)))) (else w #f)))
                nil)
               ((and (>= t 0) (tagcase (k-get t) (ty-poly (bs body) #t) (else y #f)))
                (let ((inst (k-instantiate-against t expected a b)))
                  (begin (k-expect x inst expected) (k-naming-effect s t))))
               (else (otherwise)))))
          (x-if (p c d xa xb)
            (let* ((pe (k-check p k-bool))
                   (cert (k-acyclic-test p))
                   (saved (get k-certified))
                   (pushed (set k-certified (if (null? cert) saved (the (listof (pairof symbol int @t) acyclic) (cons (car cert) saved)))))
                   (lens (k-length-test p))
                   (lsaved (get k-certified-lengths))
                   (lpushed (set k-certified-lengths (if (null? lens) lsaved (the (listof k-cert-len acyclic) (cons (car lens) lsaved)))))
                   (nats (k-nat-test p))
                   (nsaved (get k-certified-nats))
                   (npushed (set k-certified-nats (if (null? nats) nsaved (the (listof (pairof symbol int @t) acyclic) (cons (car nats) nsaved)))))
                   (facts (k-test-facts p))
                   (fsaved (get k-size-facts))
                   (fyes (set k-size-facts (k-with-fact (car facts) fsaved)))
                   (ce (k-check c expected))
                   (fpopped (set k-size-facts fsaved))
                   (popped (set k-certified saved))
                   (lpopped (set k-certified-lengths lsaved)) (npopped (set k-certified-nats nsaved))
                   (fno (set k-size-facts (k-with-fact (cdr facts) fsaved)))
                   (de (k-check d expected))
                   (fdone (set k-size-facts fsaved)))
              (k-mask x (k-union pe (k-union ce de)) expected)))
          (x-begin (xs xa xb)
            (let ((e (k-check-seq xs expected nil)))
              (k-mask x e expected)))
          (x-let (bs body xa xb)
            (let* ((inits (k-synth-lets bs)) (saved (k-mark)) (named (get k-skolems)))
              (begin
                (k-bind-named (extract inits 1))
                (k-note-let-lambdas bs)
                (let ((e (k-check body expected)))
                  (begin (k-unbind-to saved) (set k-skolems named) (k-mask x (k-union (extract inits 2) e) expected))))))
          (else y (otherwise))))))))
  (k-check-seq (subr (maxeff checks spin) (kxs int k-eff) k-eff)
    (lambda (xs expected e)
      (if (null? (cdr xs))
          (k-union e (k-check (car xs) expected))
          (let ((r (k-synth (car xs)))) (k-check-seq (cdr xs) expected (k-union e (extract r 2)))))))
  (k-check-fields (subr (maxeff checks spin) ((listof (productof (1 symbol) (2 kx)) acyclic) k-parts) k-eff)
    (lambda (fs ps)
      (if (null? fs)
          nil
          (let* ((e (k-check (extract (car fs) 2) (extract (car ps) 2))) (rest (k-check-fields (cdr fs) (cdr ps))))
            (k-union e rest)))))
  (k-synth-tagcase (subr (maxeff checks spin) (kx kx k-arms (listof (productof (1 symbol) (2 kx)) acyclic) int) k-te)
    (lambda (x s arms els expected)
      (let* ((rs (k-synth s)) (st (extract rs 1)))
        (tagcase (k-get st)
          (ty-sum (variants)
            (let* ((arm-results (k-tagcase-arms arms variants st expected))
                   (rest (k-variants-not-named variants arms))
                   (e (k-union (extract rs 2) (extract arm-results 2)))
                   (both
                    (if (null? els)
                        (if (null? rest)
                            (product (1 (extract arm-results 1)) (2 e))
                            (k-fail (string-append "this `tagcase` has no arm for " (k-join (k-part-names rest) ", ")) (k-start x) (k-end x)))
                        (let* ((y (extract (car els) 1)) (body (extract (car els) 2))
                               (rest-ty (k-ty-new (ty-sum rest)))
                               (r (k-in-scope-check y rest-ty body expected)))
                          (product (1 (k-push-ids (extract arm-results 1) (cons (extract r 1) nil))) (2 (k-union e (extract r 2)))))))
                   (types (extract both 1))
                   (t (if (>= expected 0)
                          expected
                          (let ((found (k-upper-bound types types)))
                            (if (< found 0)
                                (k-fail (string-append "the arms are " (k-join (k-show-list types nil) ", ")) (k-start x) (k-end x))
                                found)))))
              (k-te t (k-mask x (extract both 2) t))))
          (else y (k-fail (string-append "a sum is expected here, and this is a " (k-show-ty st)) (k-start s) (k-end s)))))))
  ;; Each arm: its type and the effects of all.
  (k-tagcase-arms (subr (maxeff checks spin) (k-arms k-parts int int) (productof (1 k-ids) (2 k-eff)))
    (lambda (arms variants st expected)
      (if (null? arms)
          (product (1 nil) (2 nil))
          (let* ((arm (car arms)) (tag (extract arm 1)) (body (extract arm 4)) (t (k-part-find variants tag)))
            (if (< t 0)
                (k-fail (k-cat4 "a " (k-show-ty st) " has no tag " (k-quote (symbol->string tag))) (k-start body) (k-end body))
                (let* ((bound (if (extract arm 2)
                                  (tagcase (k-get t)
                                    (ty-product (fs)
                                      (if (= (k-length fs) (k-length (extract arm 3)))
                                          (k-zip-fields (extract arm 3) fs)
                                          (k-cannot-take-apart tag t (extract arm 3) body)))
                                    (else y (k-cannot-take-apart tag t (extract arm 3) body)))
                                  (the k-bindings (cons (cons (car (extract arm 3)) t) nil))))
                       (saved (k-mark))
                       (r (begin
                            (k-bind-all bound)
                            (if (>= expected 0) (k-te expected (k-check body expected)) (k-synth body))))
                       (restored (k-unbind-to saved))
                       (rest (k-tagcase-arms (cdr arms) variants st expected)))
                  (product (1 (cons (extract r 1) (extract rest 1))) (2 (k-union (extract r 2) (extract rest 2))))))))))
  (k-in-scope-check (subr (maxeff checks spin) (symbol int kx int) k-te)
    (lambda (y t body expected)
      (let ((saved (k-mark)))
        (begin
          (k-bind y t)
          (let ((r (if (>= expected 0) (k-te expected (k-check body expected)) (k-synth body))))
            (begin (k-unbind-to saved) r))))))
  ;;; ------------------------------------------------------------ bloblets
  (k-synth-bloblet (subr (maxeff checks spin) (kx symbol int kxs int) k-te)
    (lambda (x op i args expected)
      (let ((name (symbol->string op)) (a (k-start x)) (b (k-end x)))
        (if (or (string=? name "make-bloblet") (string=? name "rmake-bloblet"))
            ;; `rmake-bloblet`'s region is its first operand's; `make-bloblet`'s
            ;; the type it is checked against, or a fresh one.
            (let* ((rm (string=? name "rmake-bloblet"))
                   (gr (if rm (k-synth (car args)) (k-te k-unit (the k-eff nil))))
                   (given (the (listof k-region acyclic)
                            (if rm
                                (tagcase (k-get (extract gr 1))
                                  (ty-place (r) (cons r nil))
                                  (else y (k-fail (k-cat3 "a region is expected here, and this is a " (k-show-ty (extract gr 1)) "") a b)))
                                nil)))
                   (args (if rm (cdr args) args))
                   (e (k-union (extract gr 2) (k-check (car args) k-int)))
                   (fields (cdr args))
                   (want (the (listof k-ty acyclic)
                           (if (< expected 0)
                               nil
                               (tagcase (k-get expected)
                                 (ty-bloblet (fs z r)
                                   (if (and (not z) (= (k-length fs) (k-length fields)) (or (null? given) (k-region=? r (car given))))
                                       (cons (k-get expected) nil)
                                       nil))
                                 (else y nil)))))
                   (made (if (null? want)
                             (let ((r (k-synth-each fields)))
                               (product (1 (extract r 1)) (2 (extract r 2))
                                        (3 (if (null? given) (k-fresh-region "bloblet") (car given)))))
                             (tagcase (car want)
                               (ty-bloblet (fs z r) (product (1 fs) (2 (k-check-each fields fs)) (3 r)))
                               (else y (k-fail "a bloblet" a b)))))
                   (region (extract made 3))
                   (e (k-insert (a-alloc region) (k-union e (extract made 2))))
                   (t (k-ty-new (ty-bloblet (extract made 1) #f region)))
                   (unknotted (k-no-knot t a b)))
              (k-te t (k-mask x e t)))
            (let* ((bx (car args)) (rest (cdr args)) (rb (k-synth bx)) (bt (extract rb 1)))
              (tagcase (k-get bt)
                (ty-bloblet (fields frozen region)
                  (letrec ((field (subr (maxeff (read @globals) checks spin) () int)
                                  (lambda ()
                                    (if (< i (k-length fields))
                                        (k-nth fields i)
                                        (k-fail (k-cat5 "a " (k-show-ty bt) " has no field " (int->string i)
                                                        (string-append ": its fields are 0 to " (int->string (- (k-length fields) 1))))
                                                a b)))))
                  (let* ((e (extract rb 2))
                         (te
                          (cond
                            ((string=? name "bloblet-ref")
                             (let ((t (field))) (k-te t (if frozen e (k-insert (a-read region) e)))))
                            ((string=? name "bloblet-set!")
                             (let ((t (field)))
                               (if frozen
                                   (k-fail (k-cat3 "a " (k-show-ty bt) " cannot be changed: its fields are frozen") a b)
                                   (k-te k-unit (k-insert (a-write region) (k-union e (k-check (car rest) t)))))))
                            ((string=? name "bloblet-freeze")
                             (k-te (k-ty-new (ty-bloblet fields #t region)) (k-insert (a-write region) e)))
                            ((string=? name "bloblet-byte")
                             (k-te k-int (k-insert (a-read region) (k-union e (k-check (car rest) k-int)))))
                            ((string=? name "bloblet-set-byte!")
                             (let* ((e1 (k-check (car rest) k-int)) (e2 (k-check (car (cdr rest)) k-int)))
                               (k-te k-unit (k-insert (a-write region) (k-union e (k-union e1 e2))))))
                            (else (k-te k-int e)))))
                    (k-te (extract te 1) (k-mask x (extract te 2) (extract te 1))))))
                (else y (k-fail (string-append "a bloblet is expected here, and this is a " (k-show-ty bt)) (k-start bx) (k-end bx)))))))))
  (k-synth-each (subr (maxeff checks spin) (kxs) (productof (1 k-ids) (2 k-eff)))
    (lambda (xs)
      (if (null? xs)
          (product (1 nil) (2 nil))
          (let* ((r (k-synth (car xs))) (rest (k-synth-each (cdr xs))))
            (product (1 (cons (extract r 1) (extract rest 1))) (2 (k-union (extract r 2) (extract rest 2))))))))
  (k-check-each (subr (maxeff checks spin) (kxs k-ids) k-eff)
    (lambda (xs ts)
      (if (null? xs) nil (let* ((e (k-check (car xs) (car ts))) (rest (k-check-each (cdr xs) (cdr ts)))) (k-union e rest)))))
  ;;; ------------------------------------------------------------ prompts
  ;;; The tag's type fixes what crosses the prompt, and the body's effect must
  ;;; be within the tag's bound apart from control on its region. Then the
  ;;; prompt delimits: that control is removed, if the body can reach no other
  ;;; tag in the region.
  (k-synth-prompt (subr (maxeff checks spin) (kx kx kx kx) k-te)
    (lambda (x tag body handler)
      (let* ((rt (k-synth tag)) (tt (extract rt 1)))
        (tagcase (k-get tt)
          (ty-tag (answer payload bound region)
            (let* ((be (extract (k-rewriting (lambda () (k-te answer (k-check body answer))) (k-start body) (k-end body)
                                             (lambda (m want got) (k-cat4 "the tag's prompts deliver a " want ", and this body is a " got)))
                                2))
                   (own (k-insert (a-goto region) (k-one (a-comefrom region))))
                   (beyond (k-beyond be bound own)))
              (if (not (null? beyond))
                  (k-fail (k-cat4 "the tag allows its delimited computations " (k-show-effect bound) ", and this body also has " (k-show-effect beyond))
                          (k-start body) (k-end body))
                  (let* ((rh (k-synth-handler handler payload answer))
                         (ht (extract rh 1))
                         (c (k-as-subr ht)))
                    (if (null? c)
                        (k-fail (string-append "a handler is a subroutine, not a " (k-show-ty ht)) (k-start handler) (k-end handler))
                        (let ((ps (extract (car c) 2)))
                          (if (or (not (= (k-length ps) 1)) (not (k-subtype payload (car ps))) (not (k-subtype (extract (car c) 3) answer)))
                              (k-fail (k-cat5 (k-cat3 "the handler must take a " (k-show-ty payload) " to a ") (k-show-ty answer) "; it is a " (k-show-ty ht) "")
                                      (k-start handler) (k-end handler))
                              (let* ((delimited (if (k-reaches-only? body tag region) (k-beyond be nil own) be))
                                     (e (k-union (extract rt 2) (k-union (extract rh 2) (k-union (extract (car c) 1) delimited)))))
                                (k-te answer (k-mask x e answer))))))))))
          (else y (k-fail (string-append "a prompt needs a prompt tag, not a " (k-show-ty tt)) (k-start tag) (k-end tag)))))))
  ;; A handler written as a `lambda` of one parameter is told what it takes
  ;; and gives.
  (k-synth-handler (subr (maxeff checks spin) (kx int int) k-te)
    (lambda (h payload answer)
      (tagcase h
        (x-lambda (ps hbody a b)
          (if (= (k-length ps) 1)
              (k-rewriting (lambda () (k-synth-lambda-as h (cons payload nil) answer)) (k-start hbody) (k-end hbody)
                           (lambda (m want got)
                             (k-cat5 (k-cat3 "the handler must take a " (k-show-ty payload) " to a ") (k-show-ty answer) ", and this gives a " got "")))
              (k-synth h)))
        (else y (k-synth h))))))
