;;; The checker, in FX-26: which recursive groups need not say `spin` (size-
;;; change termination).
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

;;; ------------------------------------------------- well-founded recursion
;;; Which recursive groups need not say `spin`: size-change termination
;;; (Lee, Jones and Ben-Amram, POPL 2001), as `terminate.rs` does it. Each
;;; call within the group is a graph of how the callee's arguments relate to
;;; the caller's parameters; closed under composition, every graph from a
;;; member to itself that is its own composition must have a parameter
;;; strictly smaller. The measures: parts (of sums, products, pairs at a
;;; `acyclic` region, datums), and integers counting down to a bound below or
;;; up to one above. A member named but not called escapes, and fails.

;; Its types, those it uses of the files before it, and the signatures of
;; what it is given.
(let* ((check-terminate-types (load-module "fx26:check-terminate-types.fx"))
       (check-types-types (load-module "fx26:check-types-types.fx"))
       (check-synth-types (load-module "fx26:check-synth-types.fx"))
       (check-resolve-types (load-module "fx26:check-resolve-types.fx"))
       (table-types (load-module "fx26:table-types.fx"))
       (check-holds-types (load-module "fx26:check-holds-types.fx"))
       (check-env-types (load-module "fx26:check-env-types.fx"))
       (check-expect-types (load-module "fx26:check-expect-types.fx"))
       (check-sc-graphs-types (load-module "fx26:check-sc-graphs-types.fx"))
       (check-print-types (load-module "fx26:check-print-types.fx")))
  ;; What it is given: the modules of the files before it that it uses.
  (lambda ((check-types (select check-types-types check-types-sig))
           (check-resolve (select check-resolve-types check-resolve-sig))
           (check-holds (select check-holds-types check-holds-sig))
           (check-env (select check-env-types check-env-sig))
           (check-expect (select check-expect-types check-expect-sig))
           (check-sc-graphs (select check-sc-graphs-types check-sc-graphs-sig))
           (check-print (select check-print-types check-print-sig))
           (tables (select table-types tables-sig)))
    (module
(define-type k-tr (select check-terminate-types k-tr))
(define tr-part (with check-terminate-types tr-part))
(define tr-int (with check-terminate-types tr-int))
(define-type k-trs (select check-terminate-types k-trs))
(define-type k-tscope (select check-terminate-types k-tscope))
(define-type k-guards (select check-terminate-types k-guards))
(define-type k-edge (select check-terminate-types k-edge))
(define-type k-graph (select check-terminate-types k-graph))
(define-type k-call (select check-terminate-types k-call))
(define-type k-calls (select check-terminate-types k-calls))
(define-type k-passed (select check-terminate-types k-passed))
(define-type k-texts (select check-terminate-types k-texts))
(define-type k-whys (select check-terminate-types k-whys))
(define-type k-thunk (select check-terminate-types k-thunk))
;; The types it uses of the files before it.
(define-effect checks (select check-types-types checks))
(define k-done (with check-types-types k-done))
(define k-err (with check-types-types k-err))
(define-type k-ids (select check-types-types k-ids))
(define-type k-names (select check-types-types k-names))
(define k-ok (with check-types-types k-ok))
(define-type k-te (select check-types-types k-te))
(define-effect kreads (select check-types-types kreads))
(define-effect kstate (select check-types-types kstate))
(define-type kx (select check-types-types kx))
(define ty-nat (with check-types-types ty-nat))
(define ty-poly (with check-types-types ty-poly))
(define ty-subr (with check-types-types ty-subr))
(define x-lambda (with check-types-types x-lambda))
(define x-plambda (with check-types-types x-plambda))
(define x-rlambda (with check-types-types x-rlambda))
(define x-the (with check-types-types x-the))
(define-type k-done (select check-synth-types k-done))
(define-type k-letrec-bs (select check-resolve-types k-letrec-bs))
(define-type k-typed-params (select check-resolve-types k-typed-params))
(define-type table (select table-types table))
;; What it uses of the modules it is given.
(define k-cat3 (with check-types k-cat3))
(define k-cat4 (with check-types k-cat4))
(define k-cat5 (with check-types k-cat5))
(define k-fail (with check-types k-fail))
(define k-get (with check-types k-get))
(define k-join (with check-types k-join))
(define k-length (with check-types k-length))
(define k-nth (with check-types k-nth))
(define k-quote (with check-types k-quote))
(define k-resolve (with check-types k-resolve))
(define k-spin-why (with check-types k-spin-why))
(define k-std-binding? (with check-types k-std-binding?))
(define k-tag (with check-types k-tag))
(define k-te (with check-types k-te))
(define k-end (with check-resolve k-end))
(define k-start (with check-resolve k-start))
(define k-id-hash (with check-holds k-id-hash))
(define k-id=? (with check-holds k-id=?))
(define k-int (with check-env k-int))
(define k-lookup (with check-env k-lookup))
(define k-lambda? (with check-expect k-lambda?))
(define k-letrec-not-lambda (with check-expect k-letrec-not-lambda))
(define k-sc-add (with check-sc-graphs k-sc-add))
(define k-sc-bind (with check-sc-graphs k-sc-bind))
(define k-sc-calls (with check-sc-graphs k-sc-calls))
(define k-sc-current (with check-sc-graphs k-sc-current))
(define k-sc-escapes (with check-sc-graphs k-sc-escapes))
(define k-sc-guarded? (with check-sc-graphs k-sc-guarded?))
(define k-sc-hints (with check-sc-graphs k-sc-hints))
(define k-sc-invariant (with check-sc-graphs k-sc-invariant))
(define k-sc-members (with check-sc-graphs k-sc-members))
(define k-sc-naturals (with check-sc-graphs k-sc-naturals))
(define k-sc-passed (with check-sc-graphs k-sc-passed))
(define k-sc-too-many (with check-sc-graphs k-sc-too-many))
(define k-sc-walk (with check-sc-graphs k-sc-walk))
(define k-sc-with (with check-sc-graphs k-sc-with))
(define k-show-ty (with check-print k-show-ty))
(define make-table (with tables make-table))
(define table-ref (with tables table-ref))
(define table-set! (with tables table-set!))

(define k-sc-compose-one (subr kstate (k-edge k-graph k-graph) k-graph)
  (lambda (e b out)
    (cond ((null? b) out)
          ((= (extract e 2) (extract (car b) 1))
           (let* ((d (car b)) (strict (or (extract e 3) (extract d 3))))
             (k-sc-compose-one e (cdr b) (k-sc-add out (extract e 1) (extract d 2) strict))))
          (else (k-sc-compose-one e (cdr b) out)))))
(define k-sc-compose (subr kstate (k-graph k-graph k-graph) k-graph)
  (lambda (a b out) (if (null? a) out (k-sc-compose (cdr a) b (k-sc-compose-one (car a) b out)))))
(define k-sc-same? (subr (maxeff (read @globals) (read @t)) (k-graph k-graph) bool)
  (lambda (a b)
    (if (null? a)
        (null? b)
        (and (not (null? b))
             (= (extract (car a) 1) (extract (car b) 1))
             (= (extract (car a) 2) (extract (car b) 2))
             (if (extract (car a) 3) (extract (car b) 3) (not (extract (car b) 3)))
             (k-sc-same? (cdr a) (cdr b))))))
;; Whether `c` and `d` are the same call: from and to the same members, of the same graph.
(define k-sc-call=? (subr kreads (k-call k-call) bool)
  (lambda (c d)
    (and (= (extract c 1) (extract d 1))
         (= (extract c 2) (extract d 2))
         (k-sc-same? (extract c 3) (extract d 3)))))
(define k-sc-has? (subr kreads (k-calls k-call) bool)
  (lambda (cs c) (and (not (null? cs)) (or (k-sc-call=? (car cs) c) (k-sc-has? (cdr cs) c)))))
;; A call's members, from and to, as one key.
(define k-sc-key (subr (read @globals) (k-call) int)
  (lambda (c) (+ (* (extract c 1) 65536) (extract c 2))))
;; Whether `c` is among the calls in `seen` (by `k-sc-key`); if not, it is now.
(define k-sc-seen? (subr kstate ((table int k-calls @t) k-call) bool)
  (lambda (seen c)
    (let ((here (table-ref seen (k-sc-key c) nil)))
      (if (k-sc-has? here c) #t (begin (table-set! seen (k-sc-key c) (cons c here)) #f)))))
(define k-sc-seen-all (subr kstate ((table int k-calls @t) k-calls) (table int k-calls @t))
  (lambda (seen cs)
    (if (null? cs) seen (begin (k-sc-seen? seen (car cs)) (k-sc-seen-all seen (cdr cs))))))
;; `cs` without repeats, onto `out` in reverse: each call compared only with
;; those of the same members (by `seen`, from and to), not every one kept.
(define k-sc-dedup-in (subr kstate (k-calls k-calls (table int k-calls @t)) k-calls)
  (lambda (cs out seen)
    (if (null? cs)
        out
        (let* ((c (car cs)) (key (k-sc-key c)) (here (table-ref seen key nil)))
          (if (k-sc-has? here c)
              (k-sc-dedup-in (cdr cs) out seen)
              (begin (table-set! seen key (cons c here))
                     (k-sc-dedup-in (cdr cs) (cons c out) seen)))))))
(define k-sc-dedup (subr kstate (k-calls k-calls) k-calls)
  (lambda (cs out) (k-sc-dedup-in cs out (make-table k-id-hash k-id=?))))
;; Whether `e` is a strict edge from a slot to itself.
(define k-sc-strict-self? (subr (read @globals) (k-edge) bool)
  (lambda (e) (and (= (extract e 1) (extract e 2)) (extract e 3))))
(define k-sc-strict-loop? (subr (maxeff (read @globals) (read @t)) (k-graph) bool)
  (lambda (g) (and (not (null? g)) (or (k-sc-strict-self? (car g)) (k-sc-strict-loop? (cdr g))))))
;; Whether every graph from a member to itself that is its own composition
;; has a strict loop.
(define k-sc-ok? (subr kstate (k-calls) bool)
  (lambda (cs)
    (or (null? cs)
        (let ((c (car cs)))
          (and (or (not (= (extract c 1) (extract c 2)))
                   (not (k-sc-same? (k-sc-compose (extract c 3) (extract c 3) nil) (extract c 3)))
                   (k-sc-strict-loop? (extract c 3)))
               (k-sc-ok? (cdr cs)))))))
;; A graph's closure may grow; beyond this many, the group does not pass.
(define k-sc-most int 4000)
(define-rec
  ;; `seen`: `all`, by `k-sc-key`, for whether a call is new.
  (k-sc-close (subr kstate (k-calls k-calls int (table int k-calls @t)) bool)
    (lambda (todo all n seen)
      (if (null? todo)
          (k-sc-ok? all)
          (let ((c (car todo)) (calls (get k-sc-calls)))
            (k-sc-extend (extract c 1) (extract c 2) (extract c 3) calls (cdr todo) all n seen)))))
  (k-sc-extend
    (subr kstate (int int k-graph k-calls k-calls k-calls int (table int k-calls @t)) bool)
    (lambda (f g a calls todo all n seen)
      (cond ((null? calls) (k-sc-close todo all n seen))
            ((not (= (extract (car calls) 1) g)) (k-sc-extend f g a (cdr calls) todo all n seen))
            (else
             (let* ((rest (cdr calls)) (cg (k-sc-compose a (extract (car calls) 3) nil))
                    (h (extract (car calls) 2)) (new (product (1 f) (2 h) (3 cg))))
               (cond ((k-sc-seen? seen new) (k-sc-extend f g a rest todo all n seen))
                     ((>= n k-sc-most) (begin (set k-sc-too-many #t) #f))
                     (else
                      (k-sc-extend f g a rest (cons new todo) (cons new all) (+ n 1) seen)))))))))

;; A binding's lambda, under `plambda`, `the` and `rlambda`.
(define k-sc-lambda-of (subr (read @globals) (kx) kx)
  (lambda (x)
    (tagcase x
      (x-plambda (bs body a b) (k-sc-lambda-of body))
      (x-the (t body a b) (k-sc-lambda-of body))
      (x-rlambda (r l a b) (k-sc-lambda-of l))
      (else y y))))
;; The parameter types of a declared type, under its binders.
(define k-sc-param-types (subr (maxeff (read @globals) (read @t) spin) (int) k-ids)
  (lambda (t)
    (tagcase (k-get t)
      (ty-poly (bs body) (k-sc-param-types body))
      (ty-subr (e ps r cv) ps)
      (else y nil))))
;; Whether `s` names the standard binding of that name.
(define k-std? (subr (maxeff kreads spin) (symbol) bool)
  (lambda (s) (k-std-binding? s (k-lookup s))))
;; Whether `t` is a natural, of a size or not.
(define k-nat-ty? (subr (maxeff kreads spin) (int) bool)
  (lambda (t) (tagcase (k-get (k-resolve t)) (ty-nat (z) #t) (else y #f))))
;; What is known of parameter `j`, of type `t`, on entry: itself, and a count if an integer.
(define k-sc-param-knows (subr (maxeff kstate spin) (int int bool) k-trs)
  (lambda (j t natural)
    (let ((count (or natural (= (k-resolve t) (k-resolve k-int)))))
      (the k-trs (cons (tr-part j #f t) (if count (the k-trs (cons (tr-int j 0) nil)) nil))))))
;; The parameters `ps`, the `j`th on, each known as itself.
(define k-sc-param-scope (subr (maxeff kstate spin) (k-typed-params k-ids int k-tscope) k-tscope)
  (lambda (ps ts j sc)
    (if (null? ps)
        sc
        (let* ((t (car ts))
               (natural (k-nat-ty? t))
               (noted (if natural (set k-sc-naturals (cons j (get k-sc-naturals))) #u))
               (ks (k-sc-param-knows j t natural)))
          (k-sc-param-scope (cdr ps) (cdr ts) (+ j 1) (k-sc-bind (extract (car ps) 1) ks sc))))))
(define k-sc-walk-members (subr (maxeff kstate spin) (k-letrec-bs int) bool)
  (lambda (bs i)
    (or (null? bs)
        (tagcase (k-sc-lambda-of (extract (car bs) 3))
          (x-lambda (ps body a b)
            (let ((ts (k-sc-param-types (extract (car bs) 2))))
              (and (<= (k-length ps) (k-length ts))
                   (begin (set k-sc-current i)
                          (set k-sc-naturals nil)
                          (k-sc-walk body (k-sc-param-scope ps ts 0 nil) nil)
                          (and (null? (get k-sc-escapes)) (k-sc-walk-members (cdr bs) (+ i 1)))))))
          (else y #f)))))
(define k-sc-names (subr kstate (k-letrec-bs) k-names)
  (lambda (bs) (if (null? bs) nil (the k-names (cons (extract (car bs) 1) (k-sc-names (cdr bs)))))))
(define k-sc-upto (subr kstate (int int) k-ids)
  (lambda (j n)
    (letrec ((down (subr kstate (int k-ids) k-ids)
                   (lambda (i acc) (if (< i j) acc (down (- i 1) (the k-ids (cons i acc)))))))
      (down (- n 1) nil))))
;; Every (member . parameter) of the group, the `i`th member on.
(define k-sc-all-params (subr kstate (k-letrec-bs int k-guards) k-guards)
  (lambda (bs i out)
    (if (null? bs)
        out
        (k-sc-all-params (cdr bs) (+ i 1)
          (tagcase (k-sc-lambda-of (extract (car bs) 3))
            (x-lambda (ps body a b) (k-sc-with i (k-sc-upto 0 (k-length ps)) out))
            (else y out))))))
(define k-sc-drop (subr kstate (k-guards int int) k-guards)
  (lambda (gs i j)
    (cond ((null? gs) gs)
          ((and (= (car (car gs)) i) (= (cdr (car gs)) j)) (k-sc-drop (cdr gs) i j))
          (else (the k-guards (cons (car gs) (k-sc-drop (cdr gs) i j)))))))
;; `inv` less what the call from `from` to `to` passing `args` changes.
(define k-sc-keep-args (subr kstate (k-guards int int k-ids int) k-guards)
  (lambda (inv from to args j)
    (if (null? args)
        inv
        (let* ((p (car args))
               (kept (if (and (>= p 0) (k-sc-guarded? inv from p)) inv (k-sc-drop inv to j))))
          (k-sc-keep-args kept from to (cdr args) (+ j 1))))))
(define k-sc-keep-all (subr kstate (k-guards k-passed) k-guards)
  (lambda (inv ps)
    (if (null? ps)
        inv
        (let* ((c (car ps)) (kept (k-sc-keep-args inv (extract c 1) (extract c 2) (extract c 3) 0)))
          (k-sc-keep-all kept (cdr ps))))))
;; The invariant parameters: the greatest set every call keeps.
(define k-sc-invariants (subr (maxeff kstate spin) (k-guards) k-guards)
  (lambda (inv)
    (let ((next (k-sc-keep-all inv (get k-sc-passed))))
      (if (= (k-length next) (k-length inv)) inv (k-sc-invariants next)))))
(define k-sc-member-name (subr (maxeff (read @globals) (read @t)) (int) string)
  (lambda (i) (symbol->string (k-nth (get k-sc-members) i))))
(define k-sc-strict-any? (subr (read @globals) (k-graph) bool)
  (lambda (g) (and (not (null? g)) (or (extract (car g) 3) (k-sc-strict-any? (cdr g))))))
(define k-sc-has-string? (subr (read @globals) (k-texts string) bool)
  (lambda (xs s) (and (not (null? xs)) (or (string=? (car xs) s) (k-sc-has-string? (cdr xs) s)))))
;; The call `c`, in words.
(define k-sc-call-words (subr kreads (k-call) string)
  (lambda (c)
    (let ((callee (k-sc-member-name (extract c 2))) (caller (k-sc-member-name (extract c 1))))
      (k-cat5 "the call of `" callee "` in `" caller "`"))))
;; The calls, in the order met, that pass nothing strictly smaller, and
;; either nothing related to the caller's parameters or with a hint why;
;; each once, in words (newest first). One passing its caller's parameters
;; on unchanged is harmless.
(define k-sc-flat (subr kstate (k-calls k-texts k-texts) k-texts)
  (lambda (cs hs out)
    (if (null? cs)
        out
        (let* ((c (car cs))
               (s1 (k-sc-call-words c))
               (s (if (string=? (car hs) "") s1 (k-cat4 s1 " (" (car hs) ")"))))
          (k-sc-flat (cdr cs) (cdr hs)
                     (if (or (k-sc-strict-any? (extract c 3))
                             (and (not (null? (extract c 3))) (string=? (car hs) ""))
                             (k-sc-has-string? out s))
                         out
                         (the k-texts (cons s out))))))))
(define k-sc-escape-why (subr (maxeff (read @globals) (read @t)) () string)
  (lambda ()
    (let* ((e (car (get k-sc-escapes))) (escapes (k-sc-member-name (cdr e)))
           (named (k-cat4 "`" escapes "` is named in `" (k-sc-member-name (car e)))))
      (k-cat3 named "` other than as a call's operator: "
              "whoever is given it may call it again, with anything"))))
;; Why the walked calls, not too many, may not end: those that pass nothing smaller, in words.
(define k-sc-shrinks-why (subr kstate () string)
  (lambda ()
    (let* ((calls (the k-calls (reverse (get k-sc-calls))))
           (hints (the k-texts (reverse (get k-sc-hints))))
           (flat (the k-texts (reverse (k-sc-flat calls hints nil)))))
      (if (null? flat)
          "no argument keeps shrinking around every loop of calls"
          (string-append "nothing smaller, or related, is passed by " (k-join flat ", "))))))
;; Why the walked calls may not end.
(define k-sc-calls-why (subr kstate () string)
  (lambda ()
    (let ((all (k-sc-dedup (get k-sc-calls) nil)))
      (cond ((k-sc-close all all (k-length all) (k-sc-seen-all (make-table k-id-hash k-id=?) all))
             "")
            ((get k-sc-too-many) "the calls combine in too many ways to follow")
            (else (k-sc-shrinks-why))))))
;; Whether every run of the group `bs` ends, so that calls within it need
;; not say `spin`: "" if so, and otherwise why not, in words for an error.
;; Walked twice: first to learn which parameters every call passes on
;; unchanged, then with them as bounds.
(define k-termination (subr (maxeff kstate spin) (k-letrec-bs) string)
  (lambda (bs)
    (begin
      (set k-sc-members (k-sc-names bs))
      (set k-sc-calls nil)
      (set k-sc-hints nil)
      (set k-sc-passed nil)
      (set k-sc-invariant nil)
      (set k-sc-escapes nil)
      (set k-sc-too-many #f)
      (let ((walked (k-sc-walk-members bs 0)))
        (cond ((not (null? (get k-sc-escapes))) (k-sc-escape-why))
              ((not walked) "it is not a lambda")
              (else
               (let ((inv (k-sc-invariants (k-sc-all-params bs 0 nil))))
                 (if (null? inv)
                     (k-sc-calls-why)
                     (begin
                       (set k-sc-invariant inv)
                       (set k-sc-calls nil)
                       (set k-sc-hints nil)
                       (set k-sc-passed nil)
                       (let ((again (k-sc-walk-members bs 0)))
                         (cond ((not (null? (get k-sc-escapes))) (k-sc-escape-why))
                               ((not again) "it is not a lambda")
                               (else (k-sc-calls-why)))))))))))))
;; Note why each of `g` may not end.
(define k-note-why (subr kstate (k-letrec-bs string) unit)
  (lambda (g why)
    (if (null? g)
        #u
        (let ((w (product (1 (extract (car g) 1)) (2 (extract (car g) 2)) (3 why))))
          (begin (set k-spin-why (cons w (get k-spin-why)))
                 (k-note-why (cdr g) why))))))
(define k-why-of (subr kreads (k-whys symbol int) string)
  (lambda (ws n t)
    (cond ((null? ws) "")
          ((and (symbol=? (extract (car ws) 1) n) (= (extract (car ws) 2) t)) (extract (car ws) 3))
          (else (k-why-of (cdr ws) n t)))))
;; Whether `needle` is in `hay` at `i`.
(define k-text-at? (subr (read @globals) (string string int) bool)
  (lambda (hay needle i) (string=? (substring hay i (+ i (string-length needle))) needle)))
(define k-text-has? (subr (maxeff (read @globals) spin) (string string int) bool)
  (lambda (hay needle i)
    (and (<= (+ i (string-length needle)) (string-length hay))
         (or (k-text-at? hay needle i) (k-text-has? hay needle (+ i 1))))))
;; Error `m` where `n`, declared `t`, is defined: saying so, and, if about `spin`, why.
(define k-declared-error (subr (maxeff kreads (alloc @t) spin) (string symbol int) string)
  (lambda (m n t)
    (let* ((why (k-why-of (get k-spin-why) n t))
           (spins (and (not (string=? why "")) (k-text-has? m "spin" 0)))
           (tail (if spins (string-append "; it may not end: " why) ""))
           (declared (k-cat4 (k-quote (symbol->string n)) " is declared a " (k-show-ty t) ": ")))
      (k-cat4 declared m tail ""))))
;; `f`, checking what `n` is declared `t`; an error at `a`..`b` itself says
;; so, and, if it is about `spin` and `n`'s group may not end, why not.
(define k-declaring (subr (maxeff (read @globals) checks spin) (k-thunk int int symbol int) k-te)
  (lambda (f a b n t)
    (let ((r (prompt k-tag (k-done (f)) (lambda (r) r))))
      (tagcase r
        (k-done (te) te)
        (k-err (m ea eb)
          (if (and (= ea a) (= eb b))
              (k-fail (k-declared-error m n t) ea eb)
              (k-fail m ea eb)))
        (k-ok (xs) (k-fail "k-ok inside" a b))))))

;; The error for `n`, bound in a recursive group to `x`, which is not a lambda.
(define k-fail-not-lambda (subr checks (symbol kx) void)
  (lambda (n x) (k-fail (k-letrec-not-lambda n) (k-start x) (k-end x))))
;; Every binding of a `letrec` a lambda, or an error at the first that is not.
(define k-letrec-lambdas (subr checks (k-letrec-bs) unit)
  (lambda (bs)
    (cond ((null? bs) #u)
          ((k-lambda? (extract (car bs) 3)) (k-letrec-lambdas (cdr bs)))
          (else (k-fail-not-lambda (extract (car bs) 1) (extract (car bs) 3)))))))))
