;;; The checker, in FX-26: descriptions read from their syntax into the arena.
;;; Part of the checker, `check-types.fx` first (PLAN.md §11, step 10).

;;; ------------------------------------------------------------ reading syntax

(define k-sfail (subr checks (string syn) void)
  (lambda (m s) (k-fail m (syn-start s) (syn-end s))))
(define k-items (subr checks (syn string) (listof syn acyclic))
  (lambda (s what)
    (tagcase s (lst (items d a b) items) (else x (k-sfail (string-append what ": expected a list") s)))))
(define k-head (subr (maxeff (read @globals) (read @s)) ((listof syn acyclic)) string)
  (lambda (items) (if (null? items) "" (syn-name (car items)))))
(define k-name-of (subr checks (syn string) symbol)
  (lambda (s what) (if (syn-symbol? s) (syn-head s) (k-sfail what s))))
(define k-at-name? (subr pure (string) bool)
  (lambda (n) (and (> (string-length n) 0) (string=? (substring n 0 1) "@"))))
(define k-nil-syn? (subr (read @s) (syn) bool)
  (lambda (s) (tagcase s (lst (items d a b) (null? items)) (else x #f))))
;; The items of a list that may be written `()`.
(define k-items-or-nil (subr checks (syn string) (listof syn acyclic))
  (lambda (s what) (if (k-nil-syn? s) nil (k-items s what))))

(define k-parse-kind (subr checks (syn) int)
  (lambda (s)
    (let ((n (if (syn-symbol? s) (syn-name s) "")))
      (cond ((string=? n "region") 0) ((string=? n "place") 3) ((string=? n "effect") 1) ((string=? n "type") 2)
            ((string=? n "data") 4)
            ((string=? n "size") 5)
            ((string=? n "conv") 6)
            (else (k-sfail "a kind is `region`, `place`, `effect`, `type`, `data`, `size` or `conv`" s))))))

;; `@globals`, or `(globals g …)` as the regions of each `g`, in a list of
;; one; none if `s` is neither.
(define k-global-names (subr (maxeff checks spin) ((listof syn acyclic)) k-regions)
  (lambda (ns) (if (null? ns) nil (the k-regions (cons (r-global (k-name-of (car ns) "a global's name")) (k-global-names (cdr ns)))))))
(define k-globals-region (subr (maxeff checks spin) (syn) (listof k-regions acyclic))
  (lambda (s)
    (if (syn-symbol? s)
        (if (string=? (syn-name s) "@globals") (the (listof k-regions acyclic) (cons (the k-regions (cons (r-globals) nil)) nil)) nil)
        (let ((items (k-items-or-nil s "a region")))
          (if (and (not (null? items)) (and (syn-symbol? (car items)) (string=? (syn-name (car items)) "globals")))
              (if (null? (cdr items))
                  (k-sfail "`(globals name …)`: at least one global" s)
                  (the (listof k-regions acyclic) (cons (k-global-names (cdr items)) nil)))
              nil)))))
;; Each of `rs`, read (or written).
(define k-atoms-on (subr (maxeff (read @globals) (read @t) (alloc @t) spin) (bool k-regions) k-eff)
  (lambda (read rs) (if (null? rs) nil (k-insert (if read (a-read (car rs)) (a-write (car rs))) (k-atoms-on read (cdr rs))))))
;; The region `@name` stands for: the program's own, if `private-regions`
;; declared it, and otherwise the constant of that name.
(define k-region-constant (subr (maxeff (read @globals) (read @t) (alloc @t)) (symbol) k-region)
  (lambda (sym)
    (let ((d (k-lookup-desc sym)))
      (if (null? d) (r-const sym) (tagcase (car d) (ds-private (r) r) (else x (r-const sym)))))))

(define-rec
  (k-parse-region (subr (maxeff checks spin) (syn) k-region)
    (lambda (s)
      (if (not (null? (k-globals-region s)))
          (k-sfail "globals are a region only in effects: `(read @globals)`, `(write (globals g))`" s)
      (if (not (syn-symbol? s))
          ;; `(const p)`: data frozen into place `p`; `(acyclic p)`, and never
          ;; written, so with no cycle through it.
          (let ((items (k-items-or-nil s "a region")))
            (if (and (= (k-length items) 2)
                     (and (syn-symbol? (car items)) (or (string=? (syn-name (car items)) "const") (string=? (syn-name (car items)) "acyclic"))))
                (let ((p (k-parse-region (k-nth items 1))) (f (string=? (syn-name (car items)) "acyclic")))
                  (if (k-place? p)
                      (tagcase p (r-var (v) (r-frozen v f)) (else y (r-frozen -1 f)))
                      (k-sfail (string-append (k-quote (k-region-show p)) " is not a place") (k-nth items 1))))
                (k-sfail "expected a region" s)))
          (let* ((n (syn-name s)) (sym (string->symbol n)))
            (cond ((k-at-name? n) (k-region-constant sym))
                  ((string=? n "const") (r-frozen -1 #f))
                  ((string=? n "acyclic") (r-frozen -1 #t))
                  ((string=? n "finite") (k-sfail "`finite` is a size; data with no cycle through it is at `acyclic`" s))
                  ((string=? n "heap") (r-heap))
                  (else
                   (let ((d (k-lookup-desc sym)) (no (lambda () (string-append (k-quote n) " is not a region"))))
                     (if (null? d)
                         (k-sfail (no) s)
                         (tagcase (car d)
                           (ds-var (v k) (if (or (= k 0) (= k 3)) (r-var v) (k-sfail (no) s)))
                           (ds-region (r) r)
                           (else x (k-sfail (no) s)))))))))))))

;; A place: a region that is one.
(define k-parse-place (subr (maxeff checks spin) (syn) k-region)
  (lambda (s)
    (let ((r (k-parse-region s)))
      (if (k-place? r) r (k-sfail (string-append (k-quote (k-region-show r)) " is not a place") s)))))

(define k-binders-each (subr (maxeff checks spin) ((listof syn acyclic)) k-binders)
  (lambda (bs)
    (if (null? bs)
        nil
        (let ((pair (k-items (car bs) "a binder")))
          (if (or (= (k-length pair) 2) (= (k-length pair) 3))
              (let* ((name (k-name-of (car pair) "a binder's name"))
                     (kind (k-parse-kind (k-nth pair 1)))
                     ;; `(r region p)`: a region that won't outlive `p`, a
                     ;; place bound before it.
                     (bound (cond ((= (k-length pair) 2) (the (listof k-region acyclic) nil))
                                  ((= kind 0) (the (listof k-region acyclic) (cons (k-parse-place (k-nth pair 2)) nil)))
                                  (else (k-sfail "only a region binder has a bound: `(name region place)`" (k-nth pair 2)))))
                     (v (k-new-dvar-of name kind))
                     (bounded (if (null? bound) #u (set k-bounds (cons (cons v (car bound)) (get k-bounds)))))
                     (pushed (k-push-desc name (ds-var v kind)))
                     (rest (k-binders-each (cdr bs))))
                (cons (product (1 v) (2 kind)) rest))
              (k-sfail "a binder is `(name kind)`, or `(name region place)`" (car bs)))))))

;; `((name kind) …)`, binding each name for the rest of the reading.
(define k-parse-binders (subr (maxeff checks spin) (syn) k-binders)
  (lambda (s) (k-binders-each (k-items s "binders"))))

(define-rec
  (k-effects (subr (maxeff checks spin) ((listof syn acyclic)) k-eff)
    (lambda (xs) (if (null? xs) nil (let* ((e (k-parse-effect (car xs))) (rest (k-effects (cdr xs)))) (k-union e rest)))))
  (k-parse-effect (subr (maxeff checks spin) (syn) k-eff)
    (lambda (s)
      (if (syn-symbol? s)
          (let ((n (syn-name s)))
            (if (string=? n "pure")
                nil
                (if (string=? n "spin")
                (k-one (a-spin))
                (let ((d (k-lookup-desc (string->symbol n))) (no (lambda () (string-append (k-quote n) " is not an effect"))))
                  (if (null? d)
                      (k-sfail (no) s)
                      (tagcase (car d)
                        (ds-var (v k) (if (= k 1) (k-one (a-var v)) (k-sfail (no) s)))
                        (ds-eff (e) e)
                        (else x (k-sfail (no) s))))))))
          (let* ((items (k-items s "an effect")) (head (k-head items)))
            (cond ((string=? head "maxeff") (k-effects (cdr items)))
                  ((or (string=? head "read") (string=? head "write") (string=? head "alloc")
                       (string=? head "goto") (string=? head "comefrom") (string=? head "await"))
                   (if (= (k-length items) 2)
                       (let ((gs (k-globals-region (k-nth items 1))))
                        (cond
                         ((null? gs)
                       (let ((r (k-parse-region (k-nth items 1))))
                         (k-one (cond ((string=? head "read") (a-read r)) ((string=? head "write") (a-write r))
                                      ((string=? head "alloc") (a-alloc r)) ((string=? head "goto") (a-goto r))
                                      ((string=? head "await") (a-await r))
                                      (else (a-comefrom r))))))
                         ;; Globals' bindings, which are only read and written.
                         ((or (string=? head "read") (string=? head "write")) (k-atoms-on (string=? head "read") (car gs)))
                         (else (k-sfail (k-cat3 "globals are only read and written, not `" head "`") (k-nth items 1)))))
                       (k-sfail (k-cat3 "`(" head " region)`") s)))
                  (else (k-sfail "expected an effect" s))))))))

;; A label or tag: a name, or a positive integer, which is its digits.
(define k-syn-label (subr checks (syn) symbol)
  (lambda (s)
    (cond ((syn-symbol? s) (syn-head s))
          ((> (syn-int s) 0) (string->symbol (int->string (syn-int s))))
          (else (k-sfail "a label is a name or a positive integer" s)))))
(define k-has-label? (subr (maxeff (read @globals) (read @t)) (k-parts symbol) bool)
  (lambda (ps l) (cond ((null? ps) #f) ((symbol=? (extract (car ps) 1) l) #t) (else (k-has-label? (cdr ps) l)))))

(define k-shape (subr checks (bool string syn) unit)
  (lambda (ok shape s) (if ok #u (k-sfail shape s))))
(define-type k-slots (listof (pairof int syn @t) acyclic))
(define k-dletrec-slots (subr (maxeff checks spin) ((listof syn acyclic)) k-slots)
  (lambda (bs)
    (if (null? bs)
        nil
        (let ((pair (k-items (car bs) "a dletrec binding")))
          (if (= (k-length pair) 2)
              (let* ((name (k-name-of (car pair) "a name"))
                     (slot (k-slot))
                     (pushed (k-push-desc name (ds-rec slot)))
                     (rest (k-dletrec-slots (cdr bs))))
                (cons (cons slot (k-nth pair 1)) rest))
              (k-sfail "a dletrec binding is `(name type)`" (car bs)))))))
;; Regions storage is kept in, for `k-knot-in`.
(define-type k-kept (listof k-region acyclic))
(define k-kept-has? (subr (maxeff (read @globals) (read @t) spin) (k-kept k-region) bool)
  (lambda (rs r) (and (not (null? rs)) (or (k-region=? (car rs) r) (k-kept-has? (cdr rs) r)))))
(define k-kept-add (subr (maxeff (read @globals) (read @t) (alloc @t) spin) (k-kept k-region) k-kept)
  (lambda (rs r) (if (k-kept-has? rs r) rs (cons r rs))))
;; The regions of everything in `t` that can be written: storage a
;; generative type's representation may keep what it was given in.
(define-rec
  (k-storage-walk (subr (maxeff kstate spin) (int int (ref k-kept @t)) unit)
    (lambda (t seen out)
      (let ((t (k-resolve t)))
        (if (k-visit? t seen)
            #u
            (letrec ((add (subr (maxeff (read @globals) kstate spin) (k-region) unit) (lambda (r) (set out (k-kept-add (get out) r))))
                     (walk (subr (maxeff (read @globals) kstate spin) (int) unit) (lambda (x) (k-storage-walk x seen out)))
                     (walks (subr (maxeff (read @globals) kstate spin) (k-ids) unit) (lambda (xs) (k-storage-walks xs seen out))))
              (tagcase (k-get t)
                (ty-ref (a r) (begin (add r) (walk a)))
                (ty-array (a r) (begin (add r) (walk a)))
                (ty-icell (a r) (begin (add r) (walk a)))
                (ty-markkey (a r) (begin (add r) (walk a)))
                (ty-pair (a b r) (begin (tagcase r (r-frozen (q f) #u) (else y (add r))) (walk a) (walk b)))
                (ty-bloblet (fs z r) (begin (if z #u (add r)) (walks fs)))
                (ty-subr (e ps r cv) (begin (walks ps) (walk r)))
                (ty-poly (bs body) (walk body))
                (ty-product (ps) (k-storage-parts ps seen out))
                (ty-sum (ps) (k-storage-parts ps seen out))
                (ty-tag (a h e r) (begin (walk a) (walk h)))
                (ty-comp (b a e r) (begin (walk b) (walk a)))
                (ty-named (g ds) (begin (walk (extract (k-gen-of g) 4)) (walks (k-desc-types ds))))
                (ty-nlist (e z r) (walk e))
                (else x #u)))))))
  (k-storage-walks (subr (maxeff kstate spin) (k-ids int (ref k-kept @t)) unit)
    (lambda (ts seen out) (if (null? ts) #u (begin (k-storage-walk (car ts) seen out) (k-storage-walks (cdr ts) seen out)))))
  (k-storage-parts (subr (maxeff kstate spin) (k-parts int (ref k-kept @t)) unit)
    (lambda (ps seen out) (if (null? ps) #u (begin (k-storage-walk (extract (car ps) 2) seen out) (k-storage-parts (cdr ps) seen out))))))
(define k-storage-regions (subr (maxeff kstate spin) (int) k-kept)
  (lambda (t) (let ((out (the (ref k-kept @t) (new nil)))) (begin (k-storage-walk t (k-new-epoch) out) (get out)))))
;; `kept`, and each of `rs` that is not a generative type's parameter nor
;; frozen.
(define k-kept-extend (subr (maxeff (read @globals) (read @t) (alloc @t) spin) (k-kept (listof k-region acyclic)) k-kept)
  (lambda (kept rs)
    (cond ((null? rs) kept)
          ((or (k-gen-region? (car rs)) (tagcase (car rs) (r-frozen (q f) #t) (else y #f))) (k-kept-extend kept (cdr rs)))
          (else (k-kept-extend (k-kept-add kept (car rs)) (cdr rs))))))
(define k-append-regions (subr (maxeff (read @globals) (alloc @t)) ((listof k-region acyclic) (listof k-region acyclic)) (listof k-region acyclic))
  (lambda (xs ys) (if (null? xs) ys (the (listof k-region acyclic) (cons (car xs) (k-append-regions (cdr xs) ys))))))
;; Whether `t` keeps, in storage at some region `r`, a procedure whose
;; latent effect reads or awaits `r` and does not say `spin`: a knot tied
;; through the store, a loop with no recursive call, which only its type can
;; show. The region and the procedure's type, if so.
(define k-reads-kept (subr (maxeff (read @globals) (read @t) (alloc @t) spin) (k-eff k-kept) (listof k-region acyclic))
  (lambda (e kept)
    (if (k-contains? e (a-spin))
        (the (listof k-region acyclic) nil)
        (letrec ((find (subr (maxeff (read @globals) (read @t) (alloc @t) spin) (k-eff) (listof k-region acyclic))
                   (lambda (xs)
                     (if (null? xs)
                         (the (listof k-region acyclic) nil)
                         (let ((r (tagcase (car xs)
                                    (a-read (r) (if (k-kept-has? kept r) (the (listof k-region acyclic) (cons r nil)) (the (listof k-region acyclic) nil)))
                                    (a-await (r) (if (k-kept-has? kept r) (the (listof k-region acyclic) (cons r nil)) (the (listof k-region acyclic) nil)))
                                    (else y (the (listof k-region acyclic) nil)))))
                           (if (null? r) (find (cdr xs)) r))))))
          (find e)))))
(define k-kept-same? (subr (maxeff (read @globals) (read @t) spin) (k-kept k-kept) bool)
  (lambda (x y)
    (letrec ((within (subr (maxeff (read @globals) (read @t) spin) (k-kept k-kept) bool)
               (lambda (a b) (or (null? a) (and (k-kept-has? b (car a)) (within (cdr a) b))))))
      (and (within x y) (within y x)))))
(define-type k-knot (listof (pairof k-region int @t) acyclic))
(define-type k-kseen (ref (listof (pairof int k-kept @t) acyclic) @t))
(define k-kseen-has? (subr (maxeff (read @globals) (read @t) spin) ((listof (pairof int k-kept @t) acyclic) int k-kept) bool)
  (lambda (xs t kept)
    (and (not (null? xs)) (or (and (= (car (car xs)) t) (k-kept-same? (cdr (car xs)) kept)) (k-kseen-has? (cdr xs) t kept)))))
(define-rec
  (k-knot-in (subr (maxeff kstate spin) (int k-kept k-kseen) k-knot)
    (lambda (t kept seen)
      (let ((t (k-resolve t)))
        (if (k-kseen-has? (get seen) t kept)
            (the k-knot nil)
            (begin
              (set seen (cons (cons t kept) (get seen)))
              (tagcase (k-get t)
                (ty-ref (a r) (k-knot-in a (k-kept-add kept r) seen))
                (ty-array (a r) (k-knot-in a (k-kept-add kept r) seen))
                (ty-icell (a r) (k-knot-in a (k-kept-add kept r) seen))
                (ty-markkey (a r) (k-knot-in a (k-kept-add kept r) seen))
                (ty-pair (a b r)
                  (let ((k (tagcase r (r-frozen (p f) kept) (else y (k-kept-add kept r)))))
                    (let ((x (k-knot-in a k seen))) (if (null? x) (k-knot-in b k seen) x))))
                (ty-bloblet (fs z r) (k-knot-list fs (if z kept (k-kept-add kept r)) seen))
                (ty-product (ps) (k-knot-parts ps kept seen))
                (ty-sum (ps) (k-knot-parts ps kept seen))
                (ty-poly (bs body) (k-knot-in body kept seen))
                ;; A procedure: kept where it is, it may not read there
                ;; unsaid; what it takes and gives is kept nowhere yet.
                (ty-subr (e ps r cv)
                  (let ((found (k-reads-kept e kept)))
                    (if (null? found)
                        (let ((x (k-knot-list ps nil seen))) (if (null? x) (k-knot-in r nil seen) x))
                        (the k-knot (cons (cons (car found) t) nil)))))
                (ty-comp (x a e r)
                  (let ((found (k-reads-kept e kept)))
                    (if (null? found)
                        (let ((y (k-knot-in x nil seen))) (if (null? y) (k-knot-in a nil seen) y))
                        (the k-knot (cons (cons (car found) t) nil)))))
                (ty-tag (a h e r) (let ((y (k-knot-in a nil seen))) (if (null? y) (k-knot-in h nil seen) y)))
                (ty-nlist (e z r) (k-knot-in e kept seen))
                ;; Transparent to safety: its representation, and what it
                ;; was given, kept, cautiously, wherever its representation
                ;; keeps anything and in every region it was given.
                (ty-named (g ds)
                  (let* ((rep (extract (k-gen-of g) 4))
                         (k (k-kept-extend kept (k-append-regions (k-storage-regions rep) (k-desc-regions ds))))
                         (x (k-knot-in rep kept seen)))
                    (if (null? x) (k-knot-list (k-desc-types ds) k seen) x)))
                (else y (the k-knot nil))))))))
  (k-knot-list (subr (maxeff kstate spin) (k-ids k-kept k-kseen) k-knot)
    (lambda (ts kept seen)
      (if (null? ts) (the k-knot nil) (let ((x (k-knot-in (car ts) kept seen))) (if (null? x) (k-knot-list (cdr ts) kept seen) x)))))
  (k-knot-parts (subr (maxeff kstate spin) (k-parts k-kept k-kseen) k-knot)
    (lambda (ps kept seen)
      (if (null? ps) (the k-knot nil) (let ((x (k-knot-in (extract (car ps) 2) kept seen))) (if (null? x) (k-knot-parts (cdr ps) kept seen) x))))))
(define k-no-knot (subr (maxeff checks spin) (int int int) unit)
  (lambda (t a b)
    (let ((found (k-knot-in t nil (the k-kseen (new nil)))))
      (if (null? found)
          #u
          (let ((r (k-region-show (car (car found)))))
            (k-fail (k-cat5 "a procedure kept in `" r "` reads `" r
                            (k-cat3 "`, so it could reach itself: it must say `spin`, and it is a " (k-show-ty (cdr (car found))) ""))
                    a b))))))

;; Where description variable `v` is among binders `bs`, from `i`, or -1.
(define k-binder-index (subr (read @globals) (k-binders int int) int)
  (lambda (bs v i) (cond ((null? bs) -1) ((= (extract (car bs) 1) v) i) (else (k-binder-index (cdr bs) v (+ i 1))))))
;; The `i`th description of `ds`, none or one.
(define k-desc-at (subr (read @globals) ((listof k-desc acyclic) int) (listof k-desc acyclic))
  (lambda (ds i) (cond ((null? ds) nil) ((= i 0) (the (listof k-desc acyclic) (cons (car ds) nil))) (else (k-desc-at (cdr ds) (- i 1))))))
;; The `i`th parameter of binders `ps` a type `t` is, or -1.
(define k-param-of (subr (maxeff (read @globals) (read @t) spin) (k-binders int) int)
  (lambda (ps t) (tagcase (k-get (k-resolve t)) (ty-var (v) (k-binder-index ps v 0)) (else y -1))))
;; Descriptions `inner`, with each that is one of parameters `ps` replaced
;; by what `args` gives for it.
(define k-descs-given (subr (maxeff (read @globals) (read @t) spin) ((listof k-desc acyclic) k-binders (listof k-desc acyclic)) (listof k-desc acyclic))
  (lambda (inner ps args)
    (if (null? inner)
        nil
        (let* ((d (car inner))
               (given (tagcase d (dt (t) (let ((i (k-param-of ps t))) (if (< i 0) (the (listof k-desc acyclic) nil) (k-desc-at args i)))) (else y (the (listof k-desc acyclic) nil))))
               (rest (k-descs-given (cdr inner) ps args)))
          (the (listof k-desc acyclic) (cons (if (null? given) d (car given)) rest))))))
;; The type the `g`th generative type, given `args`, is at its head, if its
;; representation is one of its type parameters, perhaps through other such
;; generative types: what it is given there (none or one). None if its
;; representation has a constructor at its head
;; (`docs/research/soundness-findings.md`, A2).
(define k-named-head (subr (maxeff (read @globals) (read @t) spin) (int (listof k-desc acyclic) k-ids) (listof int acyclic))
  (lambda (g args seen)
    (if (k-has-id? seen g)
        nil
        (let* ((gen (k-gen-of g)) (ps (extract gen 2)) (rep (extract gen 4)))
          (tagcase (k-get (k-resolve rep))
            (ty-var (v)
              (let ((i (k-param-of ps rep)))
                (if (< i 0)
                    nil
                    (let ((d (k-desc-at args i)))
                      (if (null? d) nil (tagcase (car d) (dt (t) (the (listof int acyclic) (cons t nil))) (else y nil)))))))
            (ty-named (h inner) (k-named-head h (k-descs-given inner ps args) (the k-ids (cons g seen))))
            (else y nil))))))
(define k-grounded-from (subr (maxeff checks spin) (int k-ids int int) unit)
  (lambda (id seen a b)
    (tagcase (k-raw id)
      (ty-link (to)
        (cond ((null? to) #u)
              ((k-has-id? seen id) (k-fail "a recursive type must be built from a constructor, not only from names" a b))
              (else (k-grounded-from (car to) (cons id seen) a b))))
      ;; A `poly` is no constructor either: a cycle through `poly`s alone
      ;; describes no type, and unfolding it would never end.
      (ty-poly (bs x)
        (if (k-has-id? seen id)
            (k-fail "a recursive type must be built from a constructor, not only from names" a b)
            (k-grounded-from x (cons id seen) a b)))
      ;; Nor is a generative type whose representation is one of what it is
      ;; given: it is that.
      (ty-named (g ds)
        (let ((h (k-named-head g ds nil)))
          (cond ((null? h) #u)
                ((k-has-id? seen id) (k-fail "a recursive type must be built from a constructor, not only from names" a b))
                (else (k-grounded-from (car h) (cons id seen) a b)))))
      (else x #u))))

;; A name defined as another name, round a loop, describes nothing.
(define k-grounded (subr (maxeff checks spin) (int int int) unit)
  (lambda (slot a b) (k-grounded-from slot nil a b)))
(define k-dletrec-no-knot (subr (maxeff checks spin) (k-slots syn) unit)
  (lambda (ss s)
    (if (null? ss) #u (begin (k-no-knot (car (car ss)) (syn-start s) (syn-end s)) (k-dletrec-no-knot (cdr ss) s)))))
(define k-dletrec-grounded (subr (maxeff checks spin) (k-slots syn) unit)
  (lambda (ss s)
    (if (null? ss) #u (begin (k-grounded (car (car ss)) (syn-start s) (syn-end s)) (k-dletrec-grounded (cdr ss) s)))))
(define k-family-params (subr checks ((listof syn acyclic)) (listof (productof (1 symbol) (2 int)) acyclic))
  (lambda (ps)
    (if (null? ps)
        nil
        (let ((pair (k-items (car ps) "`(name kind)`")))
          (if (= (k-length pair) 2)
              (let* ((n (k-name-of (car pair) "a parameter's name")) (k (k-parse-kind (k-nth pair 1)))
                     (rest (k-family-params (cdr ps))))
                (cons (product (1 n) (2 k)) rest))
              (k-sfail "a parameter is `(name kind)`" (car ps)))))))

;; `(define-type (name (param kind) …) type)`: nothing is read until it is
;; used.
(define k-define-family (subr checks (symbol (listof syn acyclic) syn) unit)
  (lambda (name params body) (k-push-desc name (ds-abbrev (k-family-params params) body))))
;; Push a scope's entries, the first first.
(define k-push-all (subr kstate (k-scope) unit)
  (lambda (bs) (if (null? bs) #u (begin (k-push-desc (car (car bs)) (cdr (car bs))) (k-push-all (cdr bs))))))

;; The type families being expanded, each with the descriptions given it
;; and the slot its type will fill: a use inside with the same descriptions
;; is that slot, a knot (regular recursion).
(define-type k-family-knot (productof (1 symbol) (2 k-scope) (3 int)))
(define k-knots (ref (listof k-family-knot acyclic) @t) (new nil))
(define k-ds=? (subr (maxeff (read @globals) (read @t) spin) (k-ds k-ds) bool)
  (lambda (x y)
    (tagcase x
      (ds-rec (a) (tagcase y (ds-rec (b) (= (k-resolve a) (k-resolve b))) (else z #f)))
      (ds-region (a) (tagcase y (ds-region (b) (k-region=? a b)) (else z #f)))
      (ds-eff (a) (tagcase y (ds-eff (b) (k-eff=? a b)) (else z #f)))
      (ds-size (a) (tagcase y (ds-size (b) (k-size=? a b)) (else z #f)))
      (ds-conv (a) (tagcase y (ds-conv (b) (k-conv=? a b)) (else z #f)))
      (else z #f))))
(define k-scope=? (subr (maxeff (read @globals) (read @t) spin) (k-scope k-scope) bool)
  (lambda (xs ys)
    (if (null? xs)
        (null? ys)
        (and (not (null? ys)) (k-ds=? (cdr (car xs)) (cdr (car ys))) (k-scope=? (cdr xs) (cdr ys))))))
;; The head of a list's first item, or "" for anything else.
(define k-list-head (subr (maxeff (read @globals) (read @s)) (syn) string)
  (lambda (s) (tagcase s (lst (items d a b) (k-head items)) (else x ""))))
;; A convention: `cellular`, `native`, `fx`, or a name bound as one.
(define k-parse-conv (subr (maxeff checks spin) (syn) k-conv)
  (lambda (s)
    (if (not (syn-symbol? s))
        (k-sfail "a convention is `cellular`, `native`, `fx`, or a name bound as one" s)
        (let* ((n (syn-name s)) (no (k-cat3 "`" n "` is not a convention")))
          (cond ((string=? n "cellular") (cv-cellular))
                ((string=? n "native") (cv-native))
                ((string=? n "fx") (cv-fx))
                (else
                 (let ((d (k-lookup-desc (string->symbol n))))
                   (if (null? d)
                       (k-sfail no s)
                       (tagcase (car d)
                         (ds-var (v k) (if (= k 6) (cv-var v) (k-sfail no s)))
                         (ds-conv (c) c)
                         (else x (k-sfail no s)))))))))))
;; `(conv C)`: the convention `C`.
(define k-parse-conv-form (subr (maxeff checks spin) (syn) k-conv)
  (lambda (s)
    (let ((items (k-items s "`(conv convention)`")))
      (if (= (k-length items) 2) (k-parse-conv (k-nth items 1)) (k-sfail "`(conv convention)`" s)))))
;; The slot of the expansion of `name` with `bound` in progress, or -1.
(define k-knot-of (subr (maxeff (read @globals) (read @t) spin) ((listof k-family-knot acyclic) symbol k-scope) int)
  (lambda (ks name bound)
    (cond ((null? ks) -1)
          ((and (symbol=? (extract (car ks) 1) name) (k-scope=? (extract (car ks) 2) bound)) (extract (car ks) 3))
          (else (k-knot-of (cdr ks) name bound)))))

(define-rec
  (k-parse-types (subr (maxeff checks spin) ((listof syn acyclic)) k-ids)
    (lambda (xs) (if (null? xs) nil (let* ((t (k-parse-type (car xs))) (rest (k-parse-types (cdr xs)))) (cons t rest)))))
  (k-parse-parts (subr (maxeff checks spin) ((listof syn acyclic) k-parts) k-parts)
    (lambda (ps done)
      (if (null? ps)
          (reverse done)
          (let ((pair (k-items (car ps) "`(label type)`")))
            (if (= (k-length pair) 2)
                (let ((l (k-syn-label (car pair))))
                  (if (k-has-label? done l)
                      (k-sfail (string-append (k-quote (symbol->string l)) " appears twice") (car ps))
                      (let ((t (k-parse-type (k-nth pair 1))))
                        (k-parse-parts (cdr ps) (cons (product (1 l) (2 t)) done)))))
                (k-sfail "`(label type)`" (car ps)))))))
  ;; Storage written: a procedure kept there may not reach itself unsaid
  ;; (`spin`).
  (k-parse-type (subr (maxeff checks spin) (syn) int)
    (lambda (s)
      (let ((t (k-parse-type-node s)))
        (begin
          (if (and (not (syn-symbol? s))
                   (let ((h (k-head (k-items s "a type"))))
                     (or (string=? h "ref") (or (string=? h "icell") (or (string=? h "pairof") (or (string=? h "listof")
                         (or (string=? h "bloblet") (or (string=? h "arrayof") (or (string=? h "mark-key") (string=? h "mu"))))))))))
              (k-no-knot t (syn-start s) (syn-end s))
              #u)
          t))))
  ;; A size: a natural literal, or `finite`, some number not known.
  (k-parse-size (subr (maxeff checks spin) (syn) k-size)
    (lambda (s)
      (let ((usage "a size is a natural number, `finite`, a size variable, `(+ size …)` or `(- size k)`"))
        (cond ((>= (syn-int s) 0) (k-size-lit (syn-int s)))
              ((syn-symbol? s)
               (if (string=? (syn-name s) "finite")
                   (sz-finite)
                   (let ((d (k-lookup-desc (string->symbol (syn-name s)))))
                     (if (null? d)
                         (k-sfail usage s)
                         (tagcase (car d)
                           (ds-var (v k) (if (= k 5) (k-size-var v) (k-sfail usage s)))
                           (ds-size (z) z)
                           (else x (k-sfail usage s)))))))
              (else
               (let* ((items (k-items s "a size"))
                      (hd (if (and (not (null? items)) (syn-symbol? (car items))) (syn-name (car items)) "")))
                 (cond ((and (string=? hd "+") (not (null? (cdr items)))) (k-parse-size-sum (cdr items) (k-size-lit 0)))
                       ((and (string=? hd "-") (= (k-length items) 3))
                        (let ((a (k-parse-size (k-nth items 1))) (k (syn-int (k-nth items 2))))
                          (if (>= k 0) (k-size-plus a (- 0 k)) (k-sfail usage (k-nth items 2)))))
                       (else (k-sfail usage s)))))))))
  (k-parse-size-sum (subr (maxeff checks spin) ((listof syn acyclic) k-size) k-size)
    (lambda (xs out) (if (null? xs) out (k-parse-size-sum (cdr xs) (k-size-add-scaled out (k-parse-size (car xs)) 1)))))
  ;; What `(proves prop)` states: the type of its proof, with the lemma kept
  ;; pending for the definition it declares.
  (k-parse-proves (subr (maxeff checks spin) (syn string) int)
    (lambda (prop usage)
      (let* ((items (k-items prop "a proposition"))
             (head (if (and (not (null? items)) (syn-symbol? (car items))) (syn-name (car items)) ""))
             (poly? (string=? head "poly"))
             (shape (cond (poly? (if (>= (k-length items) 3) #u (k-sfail usage prop)))
                          ((string=? head "<=") #u)
                          (else (k-sfail usage prop))))
             (bs (if poly? (k-parse-binders (k-nth items 1)) (the k-binders nil)))
             (conc (k-le (if poly? (k-nth items 2) prop)))
             (hyps (if poly? (k-les (cdr (cdr (cdr items)))) (the k-hyps nil)))
             (spin (k-one (a-spin)))
             (params (k-hyp-coercions hyps spin (the k-ids (cons (car conc) nil))))
             (body (k-ty-new (ty-subr spin params (cdr conc) (get k-conv-default))))
             (t (if (null? bs) body (k-ty-new (ty-poly bs body)))))
        (begin
          (set k-pending-lemma (cons (product (1 bs) (2 (car conc)) (3 (cdr conc)) (4 hyps) (5 (the k-named nil))) nil))
          t))))
  (k-le (subr (maxeff checks spin) (syn) (pairof int int @t))
    (lambda (s)
      (let ((items (k-items s "a proposition")))
        (if (and (= (k-length items) 3) (syn-symbol? (car items)) (string=? (syn-name (car items)) "<="))
            (let* ((a (k-parse-type (k-nth items 1))) (b (k-parse-type (k-nth items 2)))) (cons a b))
            (k-sfail "a proposition is `(<= type type)`" s)))))
  (k-les (subr (maxeff checks spin) ((listof syn acyclic)) k-hyps)
    (lambda (xs) (if (null? xs) nil (let* ((h (k-le (car xs))) (rest (k-les (cdr xs)))) (cons h rest)))))
  (k-hyp-coercions (subr (maxeff checks spin) (k-hyps k-eff k-ids) k-ids)
    (lambda (hs spin tail)
      (if (null? hs)
          tail
          (let ((c (k-ty-new (ty-subr spin (the k-ids (cons (car (car hs)) nil)) (cdr (car hs)) (get k-conv-default)))))
            (cons c (k-hyp-coercions (cdr hs) spin tail))))))
  ;; `(name d …)` for the `g`th generative type: a node, never expanded.
  (k-apply-gen (subr (maxeff checks spin) (syn int (listof syn acyclic)) int)
    (lambda (s g args)
      (let* ((gen (k-gen-of g)) (ps (extract gen 2)))
        (if (not (= (k-length args) (k-length ps)))
            (k-sfail (k-cat5 (k-quote (symbol->string (extract gen 1))) " takes " (int->string (k-length ps))
                             " description(s), and has " (int->string (k-length args)))
                     s)
            (let ((t (k-ty-new (ty-named g (k-gen-args ps args)))))
              ;; What it holds may keep a procedure that reaches itself.
              (begin (k-no-knot t (syn-start s) (syn-end s)) t))))))
  (k-gen-args (subr (maxeff checks spin) (k-binders (listof syn acyclic)) (listof k-desc acyclic))
    (lambda (ps args)
      (if (null? ps)
          nil
          (let* ((k (extract (car ps) 2))
                 (d (cond ((or (= k 2) (= k 4)) (dt (k-parse-type (car args))))
                          ((= k 0) (dr (k-parse-region (car args))))
                          ((= k 3) (dr (k-parse-place (car args))))
                          ((= k 5) (dz (k-parse-size (car args))))
                          ((= k 6) (dc (k-parse-conv (car args))))
                          (else (de (k-parse-effect (car args))))))
                 (rest (k-gen-args (cdr ps) (cdr args))))
            (cons d rest)))))
  (k-parse-type-node (subr (maxeff checks spin) (syn) int)
    (lambda (s)
      (if (syn-symbol? s)
          (let* ((n (syn-name s)) (sym (string->symbol n)) (base (k-find (get k-base) sym)))
            (cond ((string=? n "void") k-void)
                  ((and (string=? n "nat") (null? (k-lookup-desc sym))) (k-ty-new (ty-nat (sz-finite))))
                  ((>= base 0) base)
                  (else
                   (let ((d (k-lookup-desc sym)) (no (lambda () (string-append (k-quote n) " is not a type"))))
                     (if (null? d)
                         (k-sfail (no) s)
                         (tagcase (car d)
                           (ds-var (v k) (if (or (= k 2) (= k 4)) (k-ty-new (ty-var v)) (k-sfail (no) s)))
                           (ds-rec (t) t)
                           (ds-gen (g) (k-apply-gen s g nil))
                           (else x (k-sfail (no) s))))))))
          (let* ((items (k-items s "a type"))
                 (hd (if (null? items) '|()| (syn-head (car items))))
                 (abbrev (if (symbol=? hd '|()|) (the (listof k-ds acyclic) nil) (k-lookup-desc hd)))
                 (n (k-length items)))
            (if (and (not (null? abbrev)) (tagcase (car abbrev) (ds-abbrev (ps body) #t) (ds-gen (g) #t) (else x #f)))
                (tagcase (car abbrev)
                  (ds-abbrev (ps body) (k-expand-abbrev s hd ps body (cdr items)))
                  (ds-gen (g) (k-apply-gen s g (cdr items)))
                  (else x (k-sfail "an abbreviation" s)))
                (cond
                  ;; `(subr effect (param …) result)`, or with a convention
                  ;; first, `(subr (conv C) effect (param …) result)`; left
                  ;; out, it is the program's.
                  ((symbol=? hd 'subr)
                   (let* ((conv? (and (= n 5) (string=? (k-list-head (k-nth items 1)) "conv")))
                          (cv (if conv? (k-parse-conv-form (k-nth items 1)) (get k-conv-default)))
                          (items (if conv? (the (listof syn acyclic) (cons (car items) (cdr (cdr items)))) items))
                          (n (if conv? 4 n)))
                     (begin
                       (k-shape (= n 4) "`(subr effect (param …) result)`" s)
                       (let* ((e (k-parse-effect (k-nth items 1)))
                              (ps (k-parse-types (k-items-or-nil (k-nth items 2) "parameter types")))
                              (r (k-parse-type (k-nth items 3))))
                         (k-ty-new (ty-subr e ps r cv))))))
                  ((symbol=? hd 'proves)
                   (let ((usage "`(proves (<= type type))` or `(proves (poly ((name kind) …) (<= type type) (<= type type) …))`"))
                     (begin
                       (k-shape (= n 2) usage s)
                       (let* ((saved (get k-dscope)) (t (k-parse-proves (k-nth items 1) usage)))
                         (begin (set k-dscope saved) t)))))
                  ((symbol=? hd 'poly)
                   (begin
                     (k-shape (= n 3) "`(poly ((name kind) …) type)`" s)
                     (let* ((saved (get k-dscope))
                            (bs (k-parse-binders (k-nth items 1)))
                            (body (k-parse-type (k-nth items 2))))
                       (begin (set k-dscope saved) (k-ty-new (ty-poly bs body))))))
                  ((symbol=? hd 'nlist)
                   (begin
                     (k-shape (or (= n 3) (= n 4)) "`(nlist type size)` or `(nlist type size place)`" s)
                     (let* ((e (k-parse-type (k-nth items 1)))
                            (z (k-parse-size (k-nth items 2)))
                            (r (if (= n 4)
                                   (tagcase (k-parse-place (k-nth items 3)) (r-var (v) (r-frozen v #t)) (else y (r-frozen -1 #t)))
                                   (r-frozen -1 #t))))
                       (k-ty-new (ty-nlist e z r)))))
                  ((symbol=? hd 'nat)
                   (begin
                     (k-shape (= n 2) "`(nat size)`" s)
                     (k-ty-new (ty-nat (k-parse-size (k-nth items 1))))))
                  ((symbol=? hd 'ref)
                   (begin
                     (k-shape (= n 3) "`(ref type region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
                       (k-ty-new (ty-ref t r)))))
                  ((symbol=? hd 'pairof)
                   (begin
                     (k-shape (= n 4) "`(pairof type type region)`" s)
                     (let* ((a (k-parse-type (k-nth items 1))) (b (k-parse-type (k-nth items 2)))
                            (r (k-parse-region (k-nth items 3))))
                       (k-ty-new (ty-pair a b r)))))
                  ((symbol=? hd 'dletrec) (k-parse-dletrec s items))
                  ((symbol=? hd 'mu) (k-parse-mu s items))
                  ((symbol=? hd 'listof)
                   (begin
                     (k-shape (= n 3) "`(listof type region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2)))
                            (slot (k-slot)) (pair (k-ty-new (ty-pair t slot r))))
                       (begin (k-set-link slot pair) slot))))
                  ((symbol=? hd 'prompt-tag)
                   (begin
                     (k-shape (= n 5) "`(prompt-tag answer payload effect region)`" s)
                     (let* ((a (k-parse-type (k-nth items 1))) (h (k-parse-type (k-nth items 2)))
                            (e (k-parse-effect (k-nth items 3))) (r (k-parse-region (k-nth items 4))))
                       (k-ty-new (ty-tag a h e r)))))
                  ((symbol=? hd 'composable)
                   (begin
                     (k-shape (= n 5) "`(composable argument answer effect region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (a (k-parse-type (k-nth items 2)))
                            (e (k-parse-effect (k-nth items 3))) (r (k-parse-region (k-nth items 4))))
                       (k-ty-new (ty-comp t a e r)))))
                  ((symbol=? hd 'bloblet)
                   (begin
                     (k-shape (= n 3) "`(bloblet (fields type …) region)`, or `(frozen type …)`" s)
                     (let* ((fields (k-nth items 1))
                            (parts (k-items fields "`(fields type …)`"))
                            (which (k-head parts)))
                       (if (or (string=? which "fields") (string=? which "frozen"))
                           (let* ((fs (k-parse-types (cdr parts))) (r (k-parse-region (k-nth items 2))))
                             (k-ty-new (ty-bloblet fs (string=? which "frozen") r)))
                           (k-sfail "`(fields type …)` or `(frozen type …)`" fields)))))
                  ((symbol=? hd 'productof) (k-ty-new (ty-product (k-parse-parts (cdr items) nil))))
                  ((symbol=? hd 'sumof) (k-ty-new (ty-sum (k-parse-parts (cdr items) nil))))
                  ((symbol=? hd 'arrayof)
                   (begin
                     (k-shape (= n 3) "`(arrayof type region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
                       (k-ty-new (ty-array t r)))))
                  ((symbol=? hd 'icell)
                   (begin
                     (k-shape (= n 3) "`(icell type region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
                       (k-ty-new (ty-icell t r)))))
                  ((symbol=? hd 'place)
                   (begin
                     (k-shape (= n 2) "`(place region)`" s)
                     (k-ty-new (ty-place (k-parse-place (k-nth items 1))))))
                  ((symbol=? hd 'mark-key)
                   (begin
                     (k-shape (= n 3) "`(mark-key type region)`" s)
                     (let* ((t (k-parse-type (k-nth items 1))) (r (k-parse-region (k-nth items 2))))
                       (k-ty-new (ty-markkey t r)))))
                  (else (k-sfail "expected a type" s))))))))
  ;; `(dletrec ((name type) …) type)`: each name gets a forwarding slot
  ;; before any body is read, so the bodies can refer to it and each other.
  (k-parse-dletrec (subr (maxeff checks spin) (syn (listof syn acyclic)) int)
    (lambda (s items)
      (begin
        (k-shape (= (k-length items) 3) "`(dletrec ((name type) …) type)`" s)
        (let* ((saved (get k-dscope))
               (slots (k-dletrec-slots (k-items (k-nth items 1) "dletrec bindings")))
               (filled (k-dletrec-fill slots))
               (grounded (k-dletrec-grounded slots s))
               (unknotted (k-dletrec-no-knot slots s))
               (body (k-parse-type (k-nth items 2))))
          (begin (set k-dscope saved) body)))))
  ;; `(mu name type)`: a recursive type, anonymous; the same as `(dletrec
  ;; ((name type)) name)`.
  (k-parse-mu (subr (maxeff checks spin) (syn (listof syn acyclic)) int)
    (lambda (s items)
      (begin
        (k-shape (= (k-length items) 3) "`(mu name type)`" s)
        (let* ((name (k-name-of (k-nth items 1) "a name"))
               (saved (get k-dscope))
               (slot (k-slot))
               (pushed (k-push-desc name (ds-rec slot)))
               (t (k-parse-type (k-nth items 2)))
               (restored (set k-dscope saved))
               (filled (k-set-link slot t))
               (grounded (k-grounded slot (syn-start s) (syn-end s))))
          slot))))
  (k-dletrec-fill (subr (maxeff checks spin) (k-slots) unit)
    (lambda (ss)
      (if (null? ss)
          #u
          (let ((t (k-parse-type (cdr (car ss)))))
            (begin (k-set-link (car (car ss)) t) (k-dletrec-fill (cdr ss)))))))
  ;; A use of a parametric abbreviation: its body, read with each parameter
  ;; bound to the description given for it.
  (k-expand-abbrev (subr (maxeff checks spin) (syn symbol (listof (productof (1 symbol) (2 int)) acyclic) syn (listof syn acyclic)) int)
    (lambda (s name ps body args)
      (cond
        ((not (= (k-length args) (k-length ps)))
         (k-sfail (k-cat5 (k-quote (symbol->string name)) " takes " (int->string (k-length ps)) " description(s), and has "
                          (int->string (k-length args)))
                  s))
        ((> (get k-expanding) 64)
         (k-sfail (string-append (k-quote (symbol->string name)) " expands without end: a type family may mention itself only with the same descriptions") s))
        (else
         (let* ((bound (k-abbrev-args ps args))
                (knot (k-knot-of (get k-knots) name bound)))
           (if (>= knot 0)
               knot
               (let* ((saved (get k-dscope)) (slot (k-slot)) (kept (get k-knots)))
                 (begin
                   (set k-knots (cons (product (1 name) (2 bound) (3 slot)) kept))
                   (k-push-all bound)
                   (set k-expanding (+ (get k-expanding) 1))
                   (let ((t (k-parse-type body)))
                     (begin (set k-expanding (- (get k-expanding) 1))
                            (set k-dscope saved)
                            (set k-knots kept)
                            (k-set-link slot t)
                            (k-grounded slot (syn-start s) (syn-end s))
                            slot))))))))))
  (k-abbrev-args (subr (maxeff checks spin) ((listof (productof (1 symbol) (2 int)) acyclic) (listof syn acyclic)) k-scope)
    (lambda (ps args)
      (if (null? ps)
          nil
          (let* ((k (extract (car ps) 2))
                 (d (cond ((or (= k 2) (= k 4)) (ds-rec (k-parse-type (car args))))
                          ((= k 0) (ds-region (k-parse-region (car args))))
                          ((= k 3) (ds-region (k-parse-place (car args))))
                          ((= k 5) (ds-size (k-parse-size (car args))))
                          ((= k 6) (ds-conv (k-parse-conv (car args))))
                          (else (ds-eff (k-parse-effect (car args))))))
                 (rest (k-abbrev-args (cdr ps) (cdr args))))
            (cons (cons (extract (car ps) 1) d) rest))))))

;; Each polarity (0 covariant, 1 contravariant, 2 invariant) at which `v`
;; occurs in `t`, reached at polarity `at`.
(define k-flip (subr pure (int) int) (lambda (p) (cond ((= p 0) 1) ((= p 1) 0) (else 2))))
(define k-reg-is? (subr pure (k-region int) bool)
  (lambda (r v) (tagcase r (r-var (x) (= x v)) (r-frozen (x f) (= x v)) (else y #f))))
(define k-eff-var? (subr (maxeff (read @globals) (read @t)) (k-eff int) bool)
  (lambda (e v) (and (not (null? e)) (or (tagcase (car e) (a-var (x) (= x v)) (else y #f)) (k-eff-var? (cdr e) v)))))
(define k-eff-region-var? (subr (maxeff (read @globals) (read @t)) (k-eff int) bool)
  (lambda (e v)
    (and (not (null? e))
         (or (tagcase (car e)
               (a-read (r) (k-reg-is? r v)) (a-write (r) (k-reg-is? r v)) (a-alloc (r) (k-reg-is? r v))
               (a-goto (r) (k-reg-is? r v)) (a-comefrom (r) (k-reg-is? r v)) (a-await (r) (k-reg-is? r v))
               (else y #f))
             (k-eff-region-var? (cdr e) v)))))
(define k-pol-seen? (subr (maxeff (read @globals) (read @t)) ((listof (pairof int int @t) acyclic) int int) bool)
  (lambda (xs t at) (and (not (null? xs)) (or (and (= (car (car xs)) t) (= (cdr (car xs)) at)) (k-pol-seen? (cdr xs) t at)))))
(define-rec
  (k-polarity (subr (maxeff kstate spin) (int int int (ref (listof (pairof int int @t) acyclic) @t) (ref k-ids @t)) unit)
    (lambda (t v at seen found)
      (let ((t (k-resolve t)))
        (if (k-pol-seen? (get seen) t at)
            #u
            (letrec ((push (subr (maxeff (read @globals) kstate) (int) unit) (lambda (p) (set found (cons p (get found)))))
                     (reg (subr (maxeff (read @globals) kstate) (k-region) unit) (lambda (r) (if (k-reg-is? r v) (push 2) #u)))
                     (eff (subr (maxeff (read @globals) kstate) (k-eff int) unit)
                          (lambda (e p) (begin (if (k-eff-var? e v) (push p) #u) (if (k-eff-region-var? e v) (push 2) #u))))
                     (go (subr (maxeff (read @globals) kstate spin) (int int) unit) (lambda (x p) (k-polarity x v p seen found)))
                     (gos (subr (maxeff (read @globals) kstate spin) (k-ids int) unit) (lambda (xs p) (k-polarities xs v p seen found))))
              (begin
                (set seen (cons (cons t at) (get seen)))
                (tagcase (k-get t)
                  (ty-var (x) (if (= x v) (push at) #u))
                  (ty-subr (e ps r cv) (begin (eff e at) (gos ps (k-flip at)) (go r at)))
                  (ty-poly (bs body) (go body at))
                  (ty-ref (a r) (begin (reg r) (go a 2)))
                  (ty-array (a r) (begin (reg r) (go a 2)))
                  (ty-icell (a r) (begin (reg r) (go a 2)))
                  (ty-markkey (a r) (begin (reg r) (go a 2)))
                  (ty-pair (a b r)
                    (let ((p (tagcase r (r-frozen (q f) at) (else y 2)))) (begin (reg r) (go a p) (go b p))))
                  (ty-bloblet (fs z r) (begin (reg r) (gos fs (if z at 2))))
                  (ty-product (ps) (k-polarity-parts ps v at seen found))
                  (ty-sum (ps) (k-polarity-parts ps v at seen found))
                  (ty-tag (a h e r) (begin (reg r) (eff e 2) (go a 2) (go h 2)))
                  (ty-comp (a h e r) (begin (reg r) (eff e 2) (go a 2) (go h 2)))
                  (ty-place (r) (reg r))
                  (ty-named (g ds) (k-polarity-descs ds (extract (k-gen-of g) 3) v at seen found))
                  (ty-nlist (e z r) (begin (reg r) (go e at)))
                  (else y #u))))))))
  (k-polarities (subr (maxeff kstate spin) (k-ids int int (ref (listof (pairof int int @t) acyclic) @t) (ref k-ids @t)) unit)
    (lambda (ts v at seen found) (if (null? ts) #u (begin (k-polarity (car ts) v at seen found) (k-polarities (cdr ts) v at seen found)))))
  (k-polarity-parts (subr (maxeff kstate spin) (k-parts int int (ref (listof (pairof int int @t) acyclic) @t) (ref k-ids @t)) unit)
    (lambda (ps v at seen found)
      (if (null? ps) #u (begin (k-polarity (extract (car ps) 2) v at seen found) (k-polarity-parts (cdr ps) v at seen found)))))
  (k-polarity-descs (subr (maxeff kstate spin) ((listof k-desc acyclic) k-ids int int (ref (listof (pairof int int @t) acyclic) @t) (ref k-ids @t)) unit)
    (lambda (ds ws v at seen found)
      (if (null? ds)
          #u
          (let* ((w (car ws))
                 (p (cond ((or (= w 2) (= at 2)) 2) ((= w 0) at) (else (k-flip at)))))
            (begin
              (tagcase (car ds)
                (dt (x) (k-polarity x v p seen found))
                (dr (r) (if (k-reg-is? r v) (set found (cons 2 (get found))) #u))
                (de (e) (begin (if (k-eff-var? e v) (set found (cons p (get found))) #u)
                               (if (k-eff-region-var? e v) (set found (cons 2 (get found))) #u)))
                (dz (z) #u)
                (dc (c) #u))
              (k-polarity-descs (cdr ds) (cdr ws) v at seen found)))))))
(define k-all-ints? (subr (read @globals) (k-ids int) bool)
  (lambda (xs n) (or (null? xs) (and (= (car xs) n) (k-all-ints? (cdr xs) n)))))
;; Whether the `g`th generative type's representation bears out the variance
;; declared for its parameters.
(define k-check-variance (subr (maxeff checks spin) (int syn) unit)
  (lambda (g s)
    (let ((gen (k-gen-of g)))
      (letrec ((each (subr (maxeff (read @globals) checks spin) (k-binders k-ids) unit)
                     (lambda (bs vs)
                       (if (null? bs)
                           #u
                           (let ((v (extract (car bs) 1)) (want (car vs)))
                             (begin
                               (if (= want 2)
                                   #u
                                   (let ((found (the (ref k-ids @t) (new nil))))
                                     (begin
                                       (k-polarity (extract gen 4) v 0 (the (ref (listof (pairof int int @t) acyclic) @t) (new nil)) found)
                                       (if (k-all-ints? (get found) want)
                                           #u
                                           (k-sfail (k-cat5 (k-quote (symbol->string (k-dvar-name v))) " is declared "
                                                            (if (= want 0) "covariant (+)" "contravariant (-)")
                                                            " in " (string-append (k-quote (symbol->string (extract gen 1)))
                                                                                  ", but occurs where it may not"))
                                                    s)))))
                               (each (cdr bs) (cdr vs))))))))
        (each (extract gen 2) (extract gen 3))))))
;; `(define-generative (name (param kind [+|-]) …) rep)`, or with no
;; parameters `(define-generative name rep)`: a new type, equal only to
;; itself, converted by `up-name` and `down-name`.
(define k-gen-params (subr (maxeff checks spin) ((listof syn acyclic) int) (productof (1 k-binders) (2 k-ids)))
  (lambda (ps depth)
    (if (null? ps)
        (product (1 (the k-binders nil)) (2 (the k-ids nil)))
        (let* ((p (car ps))
               (items (k-items p "a parameter"))
               (n (k-length items))
               (v (cond ((= n 2) 2)
                        ((= n 3)
                         (let ((x (k-nth items 2)))
                           (cond ((and (syn-symbol? x) (string=? (syn-name x) "+")) 0)
                                 ((and (syn-symbol? x) (string=? (syn-name x) "-")) 1)
                                 (else (k-sfail "a parameter's variance is `+` or `-`" x)))))
                        (else (k-sfail "a parameter is `(name kind)`, `(name kind +)` or `(name kind -)`" p))))
               (name (k-name-of (car items) "a parameter's name"))
               (kind (k-parse-kind (k-nth items 1)))
               (checked (if (and (not (= v 2)) (or (= kind 0) (= kind 3)))
                            (k-sfail "a region or place parameter is invariant: it names where data is" p)
                            #u))
               (dv (k-new-dvar-of name kind))
               (pushed (k-push-desc name (ds-var dv kind)))
               (rest (k-gen-params (cdr ps) depth)))
          (product (1 (the k-binders (cons (product (1 dv) (2 kind)) (extract rest 1))))
                   (2 (the k-ids (cons v (extract rest 2)))))))))
(define k-define-generative (subr (maxeff checks spin) (syn syn) symbol)
  (lambda (head rep)
    (let* ((hs (tagcase head (lst (items d a b) items) (else x (the (listof syn acyclic) nil))))
           (name-syn (if (null? hs) head (car hs)))
           (ps (if (null? hs) (the (listof syn acyclic) nil) (cdr hs)))
           (name (k-name-of name-syn "a generative type's name"))
           (saved (get k-dscope))
           (params (k-gen-params ps 0))
           (g (get k-ngens))
           (slot (k-slot)))
      (begin
        (set k-gens (cons (product (1 name) (2 (extract params 1)) (3 (extract params 2)) (4 slot)) (get k-gens)))
        (set k-ngens (+ g 1))
        ;; In scope in its own representation: recursion through the name.
        (k-push-desc name (ds-gen g))
        (let ((r (k-parse-type rep)))
          (begin
            (set k-dscope saved)
            (k-set-link slot r)
            (k-check-variance g rep)
            (k-push-desc name (ds-gen g))
            name))))))

;; `(define-type name type)`: `name` stands for the type from here on, and
;; may appear in its own definition.
(define k-define-type (subr (maxeff checks spin) (symbol syn int int) int)
  (lambda (name def a b)
    (let ((slot (k-slot)))
      (begin
        (k-push-desc name (ds-rec slot))
        (let ((t (k-parse-type def)))
          (begin (k-set-link slot t) (k-grounded slot a b) slot))))))

;; A `proj` argument: which kind it is shows in its shape, or, for a bare
;; name, in how the name is bound.
(define k-parse-d (subr (maxeff checks spin) (syn) k-desc)
  (lambda (s)
    (if (tagcase s (atom (d a b) (datum-int? d)) (else x #f))
        ;; A natural number can only be a size.
        (dz (k-parse-size s))
    (if (syn-symbol? s)
        (let* ((n (syn-name s)) (sym (string->symbol n)))
          (cond ((k-at-name? n) (dr (k-region-constant sym)))
                ((string=? n "pure") (de nil))
                ((string=? n "spin") (de (k-one (a-spin))))
                ((string=? n "const") (dr (r-frozen -1 #f)))
                ((string=? n "acyclic") (dr (r-frozen -1 #t)))
                ((string=? n "finite") (dz (sz-finite)))
                ((string=? n "heap") (dr (r-heap)))
                (else
                 (let ((d (k-lookup-desc sym))
                       (conv? (or (string=? n "cellular") (string=? n "native") (string=? n "fx"))))
                   (if (null? d)
                       (if conv? (dc (k-parse-conv s)) (dt (k-parse-type s)))
                       (tagcase (car d)
                         (ds-var (v k)
                           (cond ((or (= k 0) (= k 3)) (dr (r-var v))) ((= k 1) (de (k-one (a-var v)))) ((= k 5) (dz (k-size-var v)))
                                 ((= k 6) (dc (cv-var v)))
                                 (else (if conv? (dc (k-parse-conv s)) (dt (k-parse-type s))))))
                         (ds-eff (e) (de e))
                         (ds-size (z) (dz z))
                         (ds-conv (c) (dc c))
                         (else x (if conv? (dc (k-parse-conv s)) (dt (k-parse-type s))))))))))
        (let ((hd (k-head (k-items s "a description"))))
          (cond ((or (string=? hd "read") (string=? hd "write") (string=? hd "alloc") (string=? hd "goto")
                     (string=? hd "comefrom") (string=? hd "await") (string=? hd "maxeff"))
                 (de (k-parse-effect s)))
                ((or (string=? hd "+") (string=? hd "-")) (dz (k-parse-size s)))
                (else (dt (k-parse-type s))))))))) 
