;;; The signature of `layout.fx`, its `layout-module`, as its clients use it
;;; (`TODO.md` §68): a module file of no state. That file is generated; this
;;; one is not.

;; What `native.fx` uses of the routines' numbers.
(define-type layout-sig
  (moduleof (val global-writes int)
            (val routine-docol int)
            (val routine-exit int)
            (val routine-halt int)
            (val routine-lit int)
            (val routine-branch int)
            (val routine-zbranch int)
            (val routine-execute int)
            (val routine-dup int)
            (val routine-drop int)
            (val routine-swap int)
            (val routine-over int)
            (val routine-add int)
            (val routine-sub int)
            (val routine-less int)
            (val routine-eq int)
            (val routine-field-ref int)
            (val routine-car int)
            (val routine-cdr int)
            (val routine-slot int)
            (val routine-slot! int)
            (val routine-free int)
            (val routine-global int)
            (val routine-global! int)
            (val routine-call int)
            (val routine-tailcall int)
            (val routine-return int)
            (val routine-tcall int)
            (val routine-ttailcall int)
            (val routine-int-add int)
            (val routine-int-sub int)
            (val routine-int-less int)
            (val routine-pair-car int)
            (val routine-pair-cdr int)
            (val routine-field int)
            (val routine-int-eq int)
            (val routine-cons int)
            (val rop-args int)
            (val rop-reg int)
            (val rop-setreg int)
            (val rop-save int)
            (val rop-setstk int)
            (val rop-store int)
            (val rop-op1 int)
            (val rop-op2 int)
            (val rop-field int)
            (val rop-prim int)
            (val rop-cellular int)
            (val rop-prim1 int)
            (val rop-prim2 int)
            (val register-regs int)
            (val cellular-closure-free0 int)
            (val routine-prompt int)
            (val routine-withmark-tail int)
            (val rop-const int)
            (val rop-global int)
            (val rop-movereg int)
            (val rop-stack int)
            (val rop-load int)
            (val rop-setfield int)
            (val rop-lambda int)
            (val rop-invoke int)
            (val rop-tailinvoke int)
            (val rop-return int)
            (val rop-invokeself int)
            (val rop-prim2imm int)
            (val rop-lexical int)
            (val rop-op2imm int)))
