;;; Generated by `fixpt_native::cellular::fx26_module` from the hand-encoded
;;; machine; `FIXPT_BLESS=1 cargo test -p fixpt-fx26 --test layout` rewrites it.

;; A module (`TODO.md` §34: the front end into modules, a file at a time);
;; what other files use re-exported after it.
(define native-layout-module (module
(define n-base int 19)  ; a register
(define n-ip int 20)  ; a register
(define n-cur int 21)  ; a register
(define n-dsp int 22)  ; a register
(define n-rsp int 23)  ; a register
(define n-st int 24)  ; a register
(define n-table int 25)  ; a register
(define n-fp int 26)  ; a register
(define n-clo int 27)  ; a register
(define n-fuel int 28)  ; a register
(define n-w int 9)  ; a register
(define n-x10 int 10)  ; a register
(define n-x11 int 11)  ; a register
(define n-x13 int 13)  ; a register
(define n-x14 int 14)  ; a register
(define n-x15 int 15)  ; a register
(define n-x16 int 16)  ; a register
(define n-st-base int 0)  ; a State field's offset
(define n-st-cur int 8)  ; a State field's offset
(define n-st-d int 16)  ; a State field's offset
(define n-st-dsp int 24)  ; a State field's offset
(define n-st-rsp int 32)  ; a State field's offset
(define n-st-table int 40)  ; a State field's offset
(define n-st-fuel int 64)  ; a State field's offset
(define n-st-callout int 88)  ; a State field's offset
(define n-st-ds-base int 112)  ; a State field's offset
(define n-st-ds-limit int 128)  ; a State field's offset
(define n-st-rs-limit int 136)  ; a State field's offset
(define n-st-fp int 144)  ; a State field's offset
(define n-st-clo int 152)  ; a State field's offset
(define n-st-resume int 168)  ; a State field's offset
(define n-st-trap int 728)  ; a State field's offset
(define n-st-exit int 736)  ; a State field's offset
(define n-st-cards int 208)  ; a State field's offset
(define n-false int 3)  ; a Value's bits
(define n-true int 11)  ; a Value's bits
(define n-prompt-mark int 51)  ; a Value's bits
(define n-mark-mark int 43)  ; a Value's bits
(define n-tag-bloblet int 4)  ; a tag
(define n-tag-pair int 1)  ; a tag
(define n-tag-trailer int 5)  ; a tag
(define n-kind-word int 33)  ; the kind of a cellular word
(define n-kind-closure int 38)  ; the kind of a cellular closure
(define n-closure-word int 2)  ; a closure's field
(define n-closure-free0 int 3)  ; a closure's field
(define n-word-entry int 2)  ; a word's field
(define n-word-cell0 int 5)  ; a word's field
(define n-primitives int 51)  ; routines that may be cells
(define n-trap-type int 1)  ; a trap's code; a routine's number is its detail
(define n-trap-overflow int 2)  ; a trap's code; a routine's number is its detail
(define n-trap-underflow int 3)  ; a trap's code; a routine's number is its detail
(define n-trap-field int 4)  ; a trap's code; a routine's number is its detail
(define n-trap-no-routine int 5)  ; a trap's code; a routine's number is its detail
(define n-trap-not-a-word int 6)  ; a trap's code; a routine's number is its detail
(define n-trap-out-of-fuel int 7)  ; a trap's code; a routine's number is its detail
(define n-trap-stack-overflow int 8)  ; a trap's code; a routine's number is its detail
(define n-trap-too-deep int 9)  ; a trap's code; a routine's number is its detail

;; How many operand cells follow routine `n`.
(define n-operands (subr pure (int) int)
  (lambda (n)
    (case n
      ((3) 1)  ; lit
      ((4) 1)  ; branch
      ((5) 1)  ; 0branch
      ((20) 1)  ; slot
      ((21) 1)  ; slot!
      ((22) 1)  ; free
      ((23) 1)  ; global
      ((24) 1)  ; global!
      ((25) 2)  ; closure
      ((26) 1)  ; call
      ((27) 1)  ; tailcall
      ((29) 2)  ; prim
      ((39) 1)  ; tcall
      ((40) 1)  ; ttailcall
      ((48) 1)  ; field
      (else 0))))

;; Whether routine `n`'s call-out may leave the machine anywhere.
(define n-control? (subr pure (int) bool)
  (lambda (n)
    (case n
      ((0) #t)  ; docol
      ((1) #t)  ; exit
      ((2) #t)  ; halt
      ((6) #t)  ; execute
      ((26) #t)  ; call
      ((27) #t)  ; tailcall
      ((28) #t)  ; return
      ((30) #t)  ; prompt
      ((31) #t)  ; abort
      ((32) #t)  ; callcomp
      ((33) #t)  ; callcc
      ((34) #t)  ; withmark
      ((38) #t)  ; withmark-tail
      ((39) #t)  ; tcall
      ((40) #t)  ; ttailcall
      ((41) #t)  ; resume
      ((42) #t)  ; undefined
      (else #f))))))

(define n-base (with native-layout-module n-base))
(define n-ip (with native-layout-module n-ip))
(define n-cur (with native-layout-module n-cur))
(define n-dsp (with native-layout-module n-dsp))
(define n-rsp (with native-layout-module n-rsp))
(define n-st (with native-layout-module n-st))
(define n-table (with native-layout-module n-table))
(define n-fp (with native-layout-module n-fp))
(define n-clo (with native-layout-module n-clo))
(define n-fuel (with native-layout-module n-fuel))
(define n-w (with native-layout-module n-w))
(define n-x10 (with native-layout-module n-x10))
(define n-x11 (with native-layout-module n-x11))
(define n-x13 (with native-layout-module n-x13))
(define n-x14 (with native-layout-module n-x14))
(define n-x15 (with native-layout-module n-x15))
(define n-x16 (with native-layout-module n-x16))
(define n-st-base (with native-layout-module n-st-base))
(define n-st-cur (with native-layout-module n-st-cur))
(define n-st-d (with native-layout-module n-st-d))
(define n-st-dsp (with native-layout-module n-st-dsp))
(define n-st-rsp (with native-layout-module n-st-rsp))
(define n-st-table (with native-layout-module n-st-table))
(define n-st-fuel (with native-layout-module n-st-fuel))
(define n-st-callout (with native-layout-module n-st-callout))
(define n-st-ds-base (with native-layout-module n-st-ds-base))
(define n-st-ds-limit (with native-layout-module n-st-ds-limit))
(define n-st-rs-limit (with native-layout-module n-st-rs-limit))
(define n-st-fp (with native-layout-module n-st-fp))
(define n-st-clo (with native-layout-module n-st-clo))
(define n-st-resume (with native-layout-module n-st-resume))
(define n-st-trap (with native-layout-module n-st-trap))
(define n-st-exit (with native-layout-module n-st-exit))
(define n-st-cards (with native-layout-module n-st-cards))
(define n-false (with native-layout-module n-false))
(define n-true (with native-layout-module n-true))
(define n-prompt-mark (with native-layout-module n-prompt-mark))
(define n-mark-mark (with native-layout-module n-mark-mark))
(define n-tag-bloblet (with native-layout-module n-tag-bloblet))
(define n-tag-pair (with native-layout-module n-tag-pair))
(define n-tag-trailer (with native-layout-module n-tag-trailer))
(define n-kind-word (with native-layout-module n-kind-word))
(define n-kind-closure (with native-layout-module n-kind-closure))
(define n-closure-word (with native-layout-module n-closure-word))
(define n-closure-free0 (with native-layout-module n-closure-free0))
(define n-word-entry (with native-layout-module n-word-entry))
(define n-word-cell0 (with native-layout-module n-word-cell0))
(define n-primitives (with native-layout-module n-primitives))
(define n-trap-type (with native-layout-module n-trap-type))
(define n-trap-overflow (with native-layout-module n-trap-overflow))
(define n-trap-underflow (with native-layout-module n-trap-underflow))
(define n-trap-field (with native-layout-module n-trap-field))
(define n-trap-no-routine (with native-layout-module n-trap-no-routine))
(define n-trap-not-a-word (with native-layout-module n-trap-not-a-word))
(define n-trap-out-of-fuel (with native-layout-module n-trap-out-of-fuel))
(define n-trap-stack-overflow (with native-layout-module n-trap-stack-overflow))
(define n-trap-too-deep (with native-layout-module n-trap-too-deep))
(define n-operands (with native-layout-module n-operands))
(define n-control? (with native-layout-module n-control?))
