;;; The signature of `native-layout.fx`, a module file the conductor loads,
;;; as its clients use it (`TODO.md` §68): a module file of no state. That
;;; file is generated; this one is not.

;; What `native.fx` uses of the machine's registers, state and traps.
(define-type native-layout-sig
  (moduleof (val n-base int)
            (val n-ip int)
            (val n-cur int)
            (val n-dsp int)
            (val n-rsp int)
            (val n-st int)
            (val n-table int)
            (val n-fp int)
            (val n-clo int)
            (val n-fuel int)
            (val n-w int)
            (val n-x10 int)
            (val n-x11 int)
            (val n-x13 int)
            (val n-x14 int)
            (val n-x15 int)
            (val n-x16 int)
            (val n-st-base int)
            (val n-st-cur int)
            (val n-st-d int)
            (val n-st-dsp int)
            (val n-st-rsp int)
            (val n-st-table int)
            (val n-st-fuel int)
            (val n-st-callout int)
            (val n-st-ds-base int)
            (val n-st-ds-limit int)
            (val n-st-rs-limit int)
            (val n-st-fp int)
            (val n-st-clo int)
            (val n-st-resume int)
            (val n-st-trap int)
            (val n-st-exit int)
            (val n-st-cards int)
            (val n-false int)
            (val n-true int)
            (val n-prompt-mark int)
            (val n-mark-mark int)
            (val n-tag-bloblet int)
            (val n-tag-pair int)
            (val n-tag-trailer int)
            (val n-kind-word int)
            (val n-kind-closure int)
            (val n-closure-word int)
            (val n-closure-free0 int)
            (val n-word-entry int)
            (val n-word-cell0 int)
            (val n-primitives int)
            (val n-trap-type int)
            (val n-trap-overflow int)
            (val n-trap-underflow int)
            (val n-trap-field int)
            (val n-trap-no-routine int)
            (val n-trap-not-a-word int)
            (val n-trap-out-of-fuel int)
            (val n-trap-stack-overflow int)
            (val n-trap-too-deep int)
            (val n-operands (subr pure (int) int))
            (val n-control? (subr pure (int) bool))))
