;;; Generated by `fixpt_native::threaded::fx26_module` from the hand-encoded
;;; machine; `FIXPT_BLESS=1 cargo test -p fixpt-fx26 --test layout` rewrites it.

(define n-base int 19)  ; a register
(define n-ip int 20)  ; a register
(define n-cur int 21)  ; a register
(define n-dsp int 22)  ; a register
(define n-rsp int 23)  ; a register
(define n-st int 24)  ; a register
(define n-table int 25)  ; a register
(define n-fp int 26)  ; a register
(define n-clo int 27)  ; a register
(define n-fuel int 28)  ; a register
(define n-w int 9)  ; a register
(define n-x10 int 10)  ; a register
(define n-x11 int 11)  ; a register
(define n-x13 int 13)  ; a register
(define n-x14 int 14)  ; a register
(define n-x15 int 15)  ; a register
(define n-x16 int 16)  ; a register
(define n-st-base int 0)  ; a State field's offset
(define n-st-cur int 8)  ; a State field's offset
(define n-st-d int 16)  ; a State field's offset
(define n-st-dsp int 24)  ; a State field's offset
(define n-st-rsp int 32)  ; a State field's offset
(define n-st-table int 40)  ; a State field's offset
(define n-st-fuel int 64)  ; a State field's offset
(define n-st-callout int 88)  ; a State field's offset
(define n-st-ds-base int 112)  ; a State field's offset
(define n-st-ds-limit int 128)  ; a State field's offset
(define n-st-rs-limit int 136)  ; a State field's offset
(define n-st-fp int 144)  ; a State field's offset
(define n-st-clo int 152)  ; a State field's offset
(define n-st-resume int 168)  ; a State field's offset
(define n-false int 3)  ; a Value's bits
(define n-true int 11)  ; a Value's bits
(define n-prompt-mark int 51)  ; a Value's bits
(define n-mark-mark int 43)  ; a Value's bits
(define n-tag-bloblet int 4)  ; a tag
(define n-tag-pair int 1)  ; a tag
(define n-tag-trailer int 5)  ; a tag
(define n-kind-word int 33)  ; the kind of a threaded word
(define n-kind-closure int 38)  ; the kind of a threaded closure
(define n-closure-word int 2)  ; a closure's field
(define n-closure-free0 int 3)  ; a closure's field
(define n-word-entry int 2)  ; a word's field
(define n-word-cell0 int 5)  ; a word's field
(define n-primitives int 49)  ; routines that may be cells
(define n-trap-type int 1)  ; a trap's code; a routine's number is its detail
(define n-trap-overflow int 2)  ; a trap's code; a routine's number is its detail
(define n-trap-underflow int 3)  ; a trap's code; a routine's number is its detail
(define n-trap-field int 4)  ; a trap's code; a routine's number is its detail
(define n-trap-no-routine int 5)  ; a trap's code; a routine's number is its detail
(define n-trap-not-a-word int 6)  ; a trap's code; a routine's number is its detail
(define n-trap-out-of-fuel int 7)  ; a trap's code; a routine's number is its detail
(define n-trap-stack-overflow int 8)  ; a trap's code; a routine's number is its detail
(define n-trap-too-deep int 9)  ; a trap's code; a routine's number is its detail

;; How many operand cells follow routine `n`.
(define n-operands (subr pure (int) int)
  (lambda (n)
    (cond
      ((= n 3) 1)  ; lit
      ((= n 4) 1)  ; branch
      ((= n 5) 1)  ; 0branch
      ((= n 20) 1)  ; slot
      ((= n 21) 1)  ; slot!
      ((= n 22) 1)  ; free
      ((= n 23) 1)  ; global
      ((= n 24) 1)  ; global!
      ((= n 25) 2)  ; closure
      ((= n 26) 1)  ; call
      ((= n 27) 1)  ; tailcall
      ((= n 29) 2)  ; prim
      ((= n 39) 1)  ; tcall
      ((= n 40) 1)  ; ttailcall
      ((= n 48) 1)  ; field
      (else 0))))

;; Whether routine `n`'s call-out may leave the machine anywhere.
(define n-control? (subr pure (int) bool)
  (lambda (n)
    (or (= n 0) (= n 1) (= n 2) (= n 6) (= n 26) (= n 27) (= n 28) (= n 30) (= n 31) (= n 32) (= n 33) (= n 34) (= n 38) (= n 39) (= n 40) (= n 41) (= n 42))))
