;;; The FX-26 parser, in FX-26: expressions, and `(load-module "file")`
;;; (`docs/research/first-class-modules.md`, M7), as the Rust parser's
;;; `parse_load_module` reads it: the file's forms a module's items, as an
;;; inline module's are (`parse-module-items`: its `define-datatype`s
;;; expanded, its `define-generative`s left a module's own); one recursive
;;; group, since a module is an expression and a file's items hold them.
;;; After `parser.fx`.
;;;
;;; FX-26 code reads no files: the driver reads each file a program's
;;; `load-module`s name, with the reader written in FX-26, before the
;;; program is parsed (`loaded-files!`), as a system call would. A file's
;;; positions are its own, each moved past the program's by its base, a
;;; multiple of `load-base`, so that what is said of a place in it can say
;;; which file and where.

(module-parameters ((rs region) (re region) (rm region) (rc region) (rp region)))
;; The parser's first part at these regions, the reader in it, and what this
;; file uses of them.
(define parser-module ((proj (load-module "fx26:parser.fx") rs re rm rc rp)))
(define eager-reader-module (with parser-module eager-reader-module))
(define-type data (select eager-reader-module data))
(define-type syn (select eager-reader-module syn))
(define syn->datum (with eager-reader-module syn->datum))
(define str3 (with eager-reader-module str3))
(define atom (with eager-reader-module atom))
(define lst (with eager-reader-module lst))
(define dotted (with eager-reader-module dotted))
(define vec (with eager-reader-module vec))
(define-effect parses (select parser-module parses))
(define-type syns-a (select parser-module syns-a))
(define-type exp (select parser-module exp))
(define-type top (select parser-module top))
(define-type exp-list (select parser-module exp-list))
(define-type mod-item (select parser-module mod-item))
(define-type mod-items (select parser-module mod-items))
(define parse-tag (with parser-module parse-tag))
(define syn-start (with parser-module syn-start))
(define syn-end (with parser-module syn-end))
(define pfail (with parser-module pfail))
(define pfail-at (with parser-module pfail-at))
(define syn-symbol? (with parser-module syn-symbol?))
(define syn-name (with parser-module syn-name))
(define syn-head (with parser-module syn-head))
(define syn-symbol (with parser-module syn-symbol))
(define syn-items (with parser-module syn-items))
(define len (with parser-module len))
(define nth (with parser-module nth))
(define drop (with parser-module drop))
(define label (with parser-module label))
(define keep (with parser-module keep))
(define arity (with parser-module arity))
(define big-literal (with parser-module big-literal))
(define mod-item-of (with parser-module mod-item-of))
(define with-includes (with parser-module with-includes))
(define any-include? (with parser-module any-include?))
(define hide-forms (with parser-module hide-forms))
(define hide-form? (with parser-module hide-form?))
(define hidden-marks (with parser-module hidden-marks))
(define item-in-includes (with parser-module item-in-includes))
(define datatype? (with parser-module datatype?))
(define expand-datatype (with parser-module expand-datatype))
(define e-var (with parser-module e-var))
(define e-int (with parser-module e-int))
(define e-bool (with parser-module e-bool))
(define e-str (with parser-module e-str))
(define e-char (with parser-module e-char))
(define e-float (with parser-module e-float))
(define e-sym (with parser-module e-sym))
(define e-unit (with parser-module e-unit))
(define e-lambda (with parser-module e-lambda))
(define e-app (with parser-module e-app))
(define e-plambda (with parser-module e-plambda))
(define e-proj (with parser-module e-proj))
(define e-if (with parser-module e-if))
(define e-letrec (with parser-module e-letrec))
(define e-let (with parser-module e-let))
(define e-begin (with parser-module e-begin))
(define e-prompt (with parser-module e-prompt))
(define e-letregion (with parser-module e-letregion))
(define e-rlambda (with parser-module e-rlambda))
(define e-the (with parser-module e-the))
(define e-convention (with parser-module e-convention))
(define e-bloblet (with parser-module e-bloblet))
(define e-product (with parser-module e-product))
(define e-extract (with parser-module e-extract))
(define e-sum (with parser-module e-sum))
(define e-tagcase (with parser-module e-tagcase))
(define e-module (with parser-module e-module))
(define e-with (with parser-module e-with))
(define t-define (with parser-module t-define))
(define t-exp (with parser-module t-exp))
(define p-ok (with parser-module p-ok))
(define p-err (with parser-module p-err))
(define-type letrec-list (select parser-module letrec-list))
(define-type let-list (select parser-module let-list))
(define-type arm-list (select parser-module arm-list))
(define sym-true (with parser-module sym-true))
(define sym-false (with parser-module sym-false))
(define sym-unit (with parser-module sym-unit))
(define at-least (with parser-module at-least))
(define vlambda-usage (with parser-module vlambda-usage))
(define parse-vparam (with parser-module parse-vparam))
(define region-form? (with parser-module region-form?))
(define confirm-length-k (with parser-module confirm-length-k))
(define bloblet-form? (with parser-module bloblet-form?))
(define syn-string? (with parser-module syn-string?))
(define syn-string (with parser-module syn-string))
(define parse-params (with parser-module parse-params))
(define freeze-pair (with parser-module freeze-pair))
(define region-kind (with parser-module region-kind))
(define region-name-error (with parser-module region-name-error))
(define one-let (with parser-module one-let))
(define call-tmp (with parser-module call-tmp))
(define standard-ref (with parser-module standard-ref))
(define field-index (with parser-module field-index))
(define bloblet-untagged? (with parser-module bloblet-untagged?))
(define arm-else? (with parser-module arm-else?))
(define arm-names (with parser-module arm-names))
(define identity-at (with parser-module identity-at))
(define one-syn (with parser-module one-syn))
(define param-head? (with parser-module param-head?))
(define param-desc-item (with parser-module param-desc-item))
(define mk-symbol (with parser-module mk-symbol))
(define quoted (with parser-module quoted))
(define rec-names (with parser-module rec-names))
(define rec-types (with parser-module rec-types))
(define rec-inits (with parser-module rec-inits))
(define module-usage (with parser-module module-usage))
(define loaded (with parser-module loaded))
(define loaded-next-at (with parser-module loaded-next-at))
(define in-loaded (with parser-module in-loaded))
(define loaded-mark (with parser-module loaded-mark))
(define loaded-error (with parser-module loaded-error))
(define loaded-params (with parser-module loaded-params))
(define loaded-made (with parser-module loaded-made))
(define-type loaded-file (select parser-module loaded-file))
(define shared-keys (with parser-module shared-keys))
(define shared-pending (with parser-module shared-pending))
(define shared-key? (with parser-module shared-key?))
(define input-items (with parser-module input-items))
;;; ------------------------------------------------------------ expressions
;; Whether `s` mentions the name `n` anywhere, quoted or not.
(define syn-mentions? (subr spin (symbol syn) bool)
  (lambda (n s)
    (tagcase s
      (atom (d a b) (and (symbol? d) (symbol=? d n)))
      (lst (items d a b) (syns-mention? n items))
      (dotted (items t d a b) (or (syns-mention? n items) (syn-mentions? n t)))
      (vec (items d a b) (syns-mention? n items)))))
(define syns-mention? (subr spin (symbol syns-a) bool)
  (lambda (n ss) (and (not (null? ss)) (or (syn-mentions? n (car ss)) (syns-mention? n (cdr ss))))))
;; A name for an expansion's own variable that `forms` never mention:
;; `base`, else `base1`, `base2` and so on. Its scope is within the form,
;; and nothing refers to a name it does not write, so it captures nothing
;; and nothing captures it.
(define fresh-name (subr spin (string syns-a) symbol)
  (lambda (base forms) (fresh-from base forms 0)))
(define fresh-from (subr spin (string syns-a int) symbol)
  (lambda (base forms i)
    (let ((n (string->symbol (if (= i 0) base (string-append base (int->string i))))))
      (if (syns-mention? n forms) (fresh-from base forms (+ i 1)) n))))
;; The shapes `typecase` tests (`check.rs`'s `SHAPES`, those with a
;; standard predicate), and the predicate of each; `||` if not one.
(define typecase-predicate (subr (read @globals) (symbol) symbol)
  (lambda (s)
    (case s
      ((int) 'int?) ((char) 'char?) ((bool) 'bool?) ((nil) 'null?) ((pair) 'pair?)
      ((string) 'string?) ((symbol) 'symbol?) ((procedure) 'procedure?) ((bloblet) 'array?)
      ((f64) 'f64?) ((f32) 'f32?) ((box) 'ref?) ((sum) 'sum?) ((product) 'product?)
      ((vector) 'vector?) ((bytevector) 'bytevector?)
      (else '||))))
(define typecase-usage string "`(typecase expression (shape name body) … (else name body))`")
(define typecase-needs-else string "a `typecase` needs at least an `else` clause")
(define typecase-else string
  "a `typecase` must end with an `else` clause, `(else body)` or `(else name body)`")
(define typecase-shapes string
  (string-append "a shape `typecase` tests is one of "
                 (string-append "int, char, bool, nil, pair, string, symbol, procedure, bloblet, "
                                "f64, f32, box, sum, product, vector, bytevector")))
;; A `case` datum's kind (`TODO.md` §46): 0 an integer, 1 a character, 2
;; a string, 3 a symbol, 4 a boolean, and -1 none of these.
(define case-kind (subr (read @globals) (syn) int)
  (lambda (s)
    (tagcase s
      (atom (d a b)
        (cond ((or (datum-int? d) (int? d)) 0)
              ((char? d) 1)
              ((string? d) 2)
              ((bool? d) 4)
              ((symbol? d)
               (let ((n d))
                 (cond ((or (symbol=? n sym-true) (symbol=? n sym-false)) 4)
                       ((symbol=? n sym-unit) -1)
                       (else 3))))
              (else -1)))
      (else x -1))))
;; A boolean datum's value, read as a literal or as `#t`.
(define case-bool (subr (read @globals) (datum) bool)
  (lambda (d) (typecase d (bool b b) (symbol n (symbol=? n sym-true)) (else x #f))))
;; Whether two data of kind `k` are the same.
(define case-same? (subr (read @globals) (int syn syn) bool)
  (lambda (k s t)
    (let ((d (syn->datum s)) (e (syn->datum t)))
      (case k ((0) (and (int? d) (int? e) (= d e)))
              ((1) (and (char? d) (char? e) (char=? d e)))
              ((2) (and (string? d) (string? e) (string=? d e)))
              ((3) (and (symbol? d) (symbol? e) (symbol=? d e)))
              (else (bool=? (case-bool d) (case-bool e)))))))
(define case-seen? (subr (read @globals) (int syn syns-a) bool)
  (lambda (k s seen)
    (and (not (null? seen)) (or (case-same? k s (car seen)) (case-seen? k s (cdr seen))))))
;; A clause's data, checked against those before it, `seen`, last first;
;; and `seen` with them.
(define case-datums (subr parses (syns-a syns-a) syns-a)
  (lambda (data seen)
    (if (null? data)
        seen
        (let* ((d (car data)) (k (case-kind d)))
          (if (= k -1)
              (pfail "a `case` datum is an integer, a character, a string, a symbol or a boolean" d)
              #u)
          (if (and (not (null? seen)) (not (= k (case-kind (car seen)))))
              (pfail (string-append "a `case`'s data are all of one kind: integers, characters, "
                                    "strings, symbols or booleans")
                     d)
              #u)
          (if (case-seen? k d seen) (pfail "a datum appears twice in this `case`" d) #u)
          (case-datums (cdr data) (cons d seen))))))
;; The clauses before a `case`'s `else`, each `((datum …) expression …)`.
(define case-clauses (subr parses (syns-a syns-a) unit)
  (lambda (clauses seen)
    (if (null? (cdr clauses))
        #u
        (let* ((c (car clauses)) (parts (syn-items c "a case clause")))
          (if (null? parts) (pfail "a case clause is `((datum …) expression …)`" c) #u)
          (let ((data (syn-items (car parts) "a case clause's data, `(datum …)`")))
            (if (null? data) (pfail "a case clause has at least one datum" c) #u)
            (case-clauses (cdr clauses) (case-datums data seen)))))))
;; `(or t rest)`, spanning a clause.
(define case-or (subr (read @globals) (exp exp int int) exp)
  (lambda (t rest ca cb) (e-if t (e-bool #t ca cb) rest ca cb)))
;; A `case`'s data by halving (`TODO.md` §46): each datum's test, the
;; value it sorts by, and its clause.
(define-type case-entry (productof (1 exp) (2 int) (3 int)))
(define-type case-entries (listof case-entry acyclic))
;; The fewest data a `case` searches by halving, by kind (the Rust parser's
;; `CASE_TREE_*`, measured): integers, strings, symbols; never characters.
;; Where the leaves give an index for a second search (`direct` false),
;; integers and symbols pay only from more.
(define case-tree-from (subr pure (int bool) int)
  (lambda (k direct)
    (case k ((0) (if direct 8 32)) ((2) 16) ((3) (if direct 32 64)) (else 1000000000))))
;; The kind of the clauses' first datum, -1 if there is none.
(define case-clauses-kind (subr (maxeff parses spin) (syns-a) int)
  (lambda (clauses)
    (if (null? (cdr clauses))
        -1
        (case-kind (car (syn-items (car (syn-items (car clauses) "c")) "data"))))))
(define case-data-count (subr (maxeff parses spin) (syns-a) int)
  (lambda (clauses)
    (if (null? (cdr clauses))
        0
        (+ (len (syn-items (car (syn-items (car clauses) "c")) "data"))
           (case-data-count (cdr clauses))))))
;; Whether every datum has a sort value: integers only if fixnums.
(define case-all-keyed? (subr (maxeff parses spin) (int syns-a) bool)
  (lambda (k clauses)
    (or (not (= k 0)) (null? (cdr clauses))
        (and (case-fixnums? (syn-items (car (syn-items (car clauses) "c")) "data"))
             (case-all-keyed? k (cdr clauses))))))
(define case-fixnums? (subr (maxeff (read @globals) spin) (syns-a) bool)
  (lambda (ds) (or (null? ds) (and (datum-int? (syn->datum (car ds))) (case-fixnums? (cdr ds))))))
;; What datum `d`, of kind `k`, sorts by: the integer, or the runtime's hash.
(define case-sort-key (subr (read @globals) (int syn) int)
  (lambda (k d)
    (let ((x (syn->datum d)))
      (case k
        ((0) (if (int? x) x 0))
        ((2) (if (string? x) (string-hash x) 0))
        (else (if (symbol? x) (symbol-name-hash x) 0))))))
;; `e` into `sorted`, after those of no greater value: a stable sort.
(define case-insert (subr (read @globals) (case-entry case-entries) case-entries)
  (lambda (e sorted)
    (if (or (null? sorted) (< (extract e 2) (extract (car sorted) 2)))
        (the case-entries (cons e sorted))
        (the case-entries (cons (car sorted) (case-insert e (cdr sorted)))))))
(define case-sort (subr (read @globals) (case-entries case-entries) case-entries)
  (lambda (es sorted) (if (null? es) sorted (case-sort (cdr es) (case-insert (car es) sorted)))))
(define case-entries-length (subr (read @globals) (case-entries) int)
  (lambda (es) (if (null? es) 0 (+ 1 (case-entries-length (cdr es))))))
(define case-exps-length (subr (read @globals) (exp-list) int)
  (lambda (es) (if (null? es) 0 (+ 1 (case-exps-length (cdr es))))))
(define case-key-at (subr (maxeff (read @globals) spin) (case-entries int) int)
  (lambda (es i) (if (= i 0) (extract (car es) 2) (case-key-at (cdr es) (- i 1)))))
(define case-take (subr (read @globals) (case-entries int) case-entries)
  (lambda (es k) (if (= k 0) nil (the case-entries (cons (car es) (case-take (cdr es) (- k 1)))))))
(define case-drop (subr (read @globals) (case-entries int) case-entries)
  (lambda (es k) (if (= k 0) es (case-drop (cdr es) (- k 1)))))
;; Where to halve `n` sorted entries: nearest the middle, between unequal
;; values (0 if none), as the Rust parser's `case_index`.
(define case-mid-up (subr (maxeff (read @globals) spin) (case-entries int int) int)
  (lambda (es mid n)
    (if (and (< mid n) (> mid 0) (= (case-key-at es mid) (case-key-at es (- mid 1))))
        (case-mid-up es (+ mid 1) n)
        mid)))
(define case-mid-down (subr (maxeff (read @globals) spin) (case-entries int) int)
  (lambda (es mid)
    (if (and (> mid 0) (= (case-key-at es mid) (case-key-at es (- mid 1))))
        (case-mid-down es (- mid 1))
        mid)))
(define case-mid (subr (maxeff (read @globals) spin) (case-entries int) int)
  (lambda (es n)
    (let ((up (case-mid-up es (quotient n 2) n)))
      (if (= up n) (case-mid-down es (quotient n 2)) up))))
;; A `case`'s `else` clause, if its body is one atom: in a list of one.
(define case-atom-else (subr (maxeff parses spin) (syn) syns-a)
  (lambda (c)
    (let ((parts (cdr (syn-items c "a case clause"))))
      (if (and (not (null? parts)) (null? (cdr parts)))
          (tagcase (car parts) (atom (d x y) parts) (else z nil))
          nil))))
;; The entries' tests in turn, each giving its clause (or, `bodies` given,
;; its body); `m` (or `els`) for none.
(define case-leaf (subr (maxeff parses spin) (case-entries int exp-list exp int int) exp)
  (lambda (es m bodies els a b)
    (cond ((and (null? es) (null? bodies)) (e-int m a b))
          ((null? es) els)
          (else
           (let ((then (if (null? bodies)
                           (e-int (extract (car es) 3) a b)
                           (case-body-at bodies (extract (car es) 3)))))
             (e-if (extract (car es) 1) then (case-leaf (cdr es) m bodies els a b) a b))))))
;; The clause index of sorted entries, `by` halved against their values.
(define case-index
  (subr (maxeff parses spin) (exp case-entries int int exp-list exp int int) exp)
  (lambda (by es n m bodies els a b)
    (if (<= n 3)
        (case-leaf es m bodies els a b)
        (let ((mid (case-mid es n)))
          (if (= mid 0)
              (case-leaf es m bodies els a b)
              (e-if (e-app (standard-ref '< a b) (list by (e-int (case-key-at es mid) a b)) a b)
                    (case-index by (case-take es mid) mid m bodies els a b)
                    (case-index by (case-drop es mid) (- n mid) m bodies els a b)
                    a b))))))
;; The body of index `lo`..`hi` that `i` names, by halving.
(define case-pick (subr (maxeff parses spin) (exp exp-list int int int int) exp)
  (lambda (i bodies lo hi a b)
    (if (= lo hi)
        (case-body-at bodies lo)
        (let ((mid (quotient (+ (+ lo hi) 1) 2)))
          (e-if (e-app (standard-ref '< a b) (list i (e-int mid a b)) a b)
                (case-pick i bodies lo (- mid 1) a b)
                (case-pick i bodies mid hi a b)
                a b)))))
(define case-body-at (subr (maxeff (read @globals) spin) (exp-list int) exp)
  (lambda (es i) (if (= i 0) (car es) (case-body-at (cdr es) (- i 1)))))
;; Whether a `case`, `xs` its key and clauses, compares its key as it is:
;; a variable (not `#t`, `#f` or `#u`), with a clause before the `else`.
(define case-direct? (subr (read @globals) (syns-a) bool)
  (lambda (xs)
    (and (syn-symbol? (car xs)) (not (null? (cdr (cdr xs))))
         (let ((n (syn-head (car xs))))
           (not (or (symbol=? n sym-true) (symbol=? n sym-false) (symbol=? n sym-unit)))))))
;; A `case`'s last clause, which must be `else`.
(define case-else (subr parses (syn) unit)
  (lambda (c)
    (let ((parts (syn-items c "a case clause")))
      (if (and (not (null? parts)) (symbol=? (syn-head (car parts)) 'else))
          #u
          (pfail "a `case` must end with an `else` clause: FX has no unspecified value" c)))))
(define case-last (subr pure (syns-a) syn)
  (lambda (xs) (if (null? (cdr xs)) (car xs) (case-last (cdr xs)))))
(define-rec
  (parse-exps (subr (maxeff parses spin) (syns-a) exp-list)
    (lambda (xs) (if (null? xs) nil (cons (parse-exp (car xs)) (parse-exps (cdr xs))))))
  ;; One or more expressions, an implicit `begin` spanning `a`..`b`.
  (parse-body (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (forms a b)
      (cond ((null? forms) (pfail-at "an empty body" a b))
            ((null? (cdr forms)) (parse-exp (car forms)))
            (else (e-begin (parse-exps forms) a b)))))
  (parse-exp (subr (maxeff parses spin) (syn) exp)
    (lambda (s)
      (tagcase s
        (atom (d a b)
          (cond ((datum-int? d) (e-int d a b))
                ((int? d) (big-literal d a b))
                ((string? d) (e-str d a b))
                ((bool? d) (e-bool d a b))
                ((char? d) (e-char d a b))
                ((f64? d) (e-float d a b))
                ((symbol? d)
                 (let ((n d))
                   (cond ((symbol=? n sym-true) (e-bool #t a b))
                         ((symbol=? n sym-false) (e-bool #f a b))
                         ((symbol=? n sym-unit) (e-unit a b))
                         (else (e-var n a b)))))
                (else (pfail "not an expression in the FX-26 kernel" s))))
        (lst (items d a b)
          (if (null? items)
              (pfail "not an expression in the FX-26 kernel" s)
              (parse-form s items (syn-head (car items)) a b)))
        (else x (pfail "not an expression in the FX-26 kernel" s)))))
  (parse-form (subr (maxeff parses spin) (syn syns-a symbol int int) exp)
    (lambda (s items head a b)
      (case head
        ((lambda)
         (begin (at-least items 3 "`(lambda ((name type) …) body …)`" a b)
                (parse-lambda-at items 1 a b)))
        ((vlambda)
         (begin (at-least items 3 vlambda-usage a b)
                (let ((param (parse-vparam (nth items 1) a b)))
                  (e-app (e-var '%vlambda a b)
                         (cons (e-lambda (cons param nil) (parse-body (drop items 2) a b) a b) nil)
                         a b))))
        ((rlambda)
         (begin (at-least items 3 "`(rlambda region ((name type) …) body …)`" a b)
                (let ((r (parse-exp (nth items 1))))
                  (e-rlambda r (parse-lambda-at items 2 a b) a b))))
        ((plambda)
         (begin (at-least items 3 "`(plambda ((name kind) …) body …)`" a b)
                (e-plambda (nth items 1) (parse-body (drop items 2) a b) a b)))
        ((proj)
         (begin (at-least items 2 "`(proj expression description …)`" a b)
                (if (null? (drop items 2))
                    (pfail-at "`proj` needs at least one description" a b)
                    #u)
                (e-proj (parse-exp (nth items 1)) (keep (drop items 2)) a b)))
        ((if)
         (begin (arity items 4 "`(if test then else)`" a b)
                (e-if (parse-nth items 1) (parse-nth items 2) (parse-nth items 3) a b)))
        ((letrec)
         (begin (at-least items 3 "`(letrec ((name type expression) …) body …)`" a b)
                (e-letrec (parse-letrec-bindings (syn-items (nth items 1) "letrec bindings"))
                          (parse-body (drop items 2) a b) a b)))
        ((let)
         (begin (at-least items 3 "`(let ((name expression) …) body …)`" a b)
                (e-let (parse-let-bindings (syn-items (nth items 1) "let bindings"))
                       (parse-body (drop items 2) a b) a b)))
        ((begin) (parse-body (cdr items) a b))
        ((cond) (parse-cond (cdr items) a b))
        ((case) (parse-case (cdr items) a b))
        ((typecase) (parse-typecase items a b))
        ((confirm-length)
         (let ((usage "`(confirm-length expression length (name body) else)`"))
           (begin
             (arity items 5 usage a b)
             ;; A natural literal, or a variable holding a `nat`.
             (let* ((n (nth items 2))
                    (k (confirm-length-k n))
                    (length (if (< k 0) (e-var (syn-symbol n) a b) (e-int k a b))))
               (parse-confirm items 3 usage "%confirm-value" 'length-is? 'certify-length
                              (the exp-list (cons length nil)) a b)))))
        ((acyclic)
         (let ((usage "`(acyclic expression (name body) else)`"))
           (begin
             (arity items 4 usage a b)
             (parse-confirm items 2 usage "%acyclic-value" 'acyclic? 'certify-acyclic nil a b))))
        ((confirm-nat)
         (let ((usage "`(confirm-nat expression (name body) else)`"))
           (begin
             (arity items 4 usage a b)
             (parse-confirm items 2 usage "%nat-value" 'nat? 'certify-nat nil a b))))
        ((and) (parse-and (cdr items) a b))
        ((or) (parse-or (cdr items) a b))
        ((let*)
         (begin (at-least items 3 "`(let* ((name expression) …) body …)`" a b)
                (parse-let* (syn-items (nth items 1) "let* bindings")
                            (parse-body (drop items 2) a b))))
        ((the)
         (begin (arity items 3 "`(the type expression)`" a b)
                (e-the (nth items 1) (parse-exp (nth items 2)) a b)))
        ((convention)
         (begin (arity items 3 "`(convention C expression)`" a b)
                (e-convention (nth items 1) (parse-exp (nth items 2)) a b)))
        ((product) (e-product (parse-fields (cdr items)) a b))
        ((extract)
         (begin (arity items 3 "`(extract expression label)`" a b)
                (let ((l (label (nth items 2)))) (e-extract (parse-exp (nth items 1)) l a b))))
        ((sum)
         (begin (arity items 3 "`(sum tag expression)`" a b)
                (let ((t (label (nth items 1)))) (e-sum t (parse-exp (nth items 2)) a b))))
        ((tagcase)
         (begin (at-least items 2 "`(tagcase expression (tag name body …) …)`" a b)
                (let ((scrutinee (parse-exp (nth items 1))) (arms (drop items 2)))
                  (e-tagcase scrutinee (parse-arms arms) (parse-else arms) a b))))
        ((quote)
         (begin (arity items 2 "`(quote datum)`" a b)
                (if (syn-symbol? (nth items 1))
                    (e-sym (syn-symbol (nth items 1)) a b)
                    (parse-exp (quoted (nth items 1) -1)))))
        ((quasiquote)
         (begin (arity items 2 "`(quasiquote datum)`" a b)
                (parse-exp (quoted (nth items 1) 1))))
        ((prompt)
         (begin (arity items 4 "`(prompt tag body handler)`" a b)
                (e-prompt (parse-nth items 1) (parse-nth items 2) (parse-nth items 3) a b)))
        ((module) (e-module (parse-module-items (cdr items)) a b))
        ;; `(extend e0 e1)` (`TODO.md` §69): a module of the two, made of
        ;; their values by the checker (`k-extended`), as `parse.rs`.
        ((extend)
         (begin (arity items 3 "`(extend module module)`" a b)
                (e-module (the mod-items
                            (list (mod-item-of 2 '%extend-0 nil (list (parse-nth items 1)))
                                  (mod-item-of 2 '%extend-1 nil (list (parse-nth items 2)))))
                          a b)))
        ((load-module load-input)
         (let* ((input? (eq? head 'load-input))
                (usage (str3 "`(" (if input? "load-input" "load-module") " \"file\")`")))
           (begin (arity items 2 usage a b)
                  (if (syn-string? (nth items 1))
                      (parse-loaded (syn-string (nth items 1)) input? (car items) a b)
                      (pfail (string-append usage ": the file's name, as a string")
                             (nth items 1))))))
        ((with)
         (begin (at-least items 2 "`(with module body …)`" a b)
                (if (syn-symbol? (nth items 1))
                    (e-with (syn-symbol (nth items 1)) (parse-body (drop items 2) a b) a b)
                    (pfail "`with` opens a module named by a variable" (nth items 1)))))
        (else
         (cond ((region-form? head) (parse-region-form items head a b))
               ((bloblet-form? head) (parse-bloblet head (cdr items) a b))
               (else (let ((f (parse-exp (car items))))
                       (e-app f (parse-exps (cdr items)) a b))))))))
  ;; Item `i`, an expression.
  (parse-nth (subr (maxeff parses spin) (syns-a int) exp)
    (lambda (items i) (parse-exp (nth items i))))
  ;; A `lambda` of the parameters at `i` and the body after them.
  (parse-lambda-at (subr (maxeff parses spin) (syns-a int int int) exp)
    (lambda (items i a b)
      (e-lambda (parse-params (nth items i)) (parse-body (drop items (+ i 1)) a b) a b)))
  ;; `(letregion name body …)` and the other region forms.
  (parse-region-form (subr (maxeff parses spin) (syns-a symbol int int) exp)
    (lambda (items head a b)
      (begin (at-least items 2 (str3 "`(" (symbol->string head) " name body …)`") a b)
             ;; `(letfreeze (r p) body …)` freezes into place `p`;
             ;; `(letfreeze r body …)` into the heap.
             (let* ((given (nth items 1))
                    (pair (freeze-pair head given))
                    (name (if (null? pair) given (car pair)))
                    (into (if (null? pair) 'heap (syn-symbol (nth pair 1)))))
               (if (and (syn-symbol? name) (not (char=? (string-ref (syn-name name) 0) #\@)))
                   (e-letregion (region-kind head)
                                (syn-symbol name) into (parse-body (drop items 2) a b) a b)
                   (pfail (region-name-error head) name))))))
  ;; A confirming form, `(form e … (x body) else)` with its arm at `i`:
  ;; `(let ((tmp e)) (if (test tmp more …) (let ((x (cert tmp more …)))
  ;; body) else))`, `tmp` named `tmp-name`.
  (parse-confirm
    (subr (maxeff parses spin) (syns-a int string string symbol symbol exp-list int int) exp)
    (lambda (items i usage tmp-name test cert more a b)
      (let* ((arm (syn-items (nth items i) usage))
             (shaped (if (= (len arm) 2) #u (pfail usage (nth items i))))
             (x (if (syn-symbol? (car arm)) (syn-symbol (car arm)) (pfail "a name" (car arm))))
             (e (parse-exp (nth items 1)))
             (body (parse-exp (nth arm 1)))
             (els (parse-exp (nth items (+ i 1))))
             (tmp (fresh-name tmp-name items))
             (then (e-let (one-let x (call-tmp cert tmp more a b)) body a b)))
        (e-let (one-let tmp e) (e-if (call-tmp test tmp more a b) then els a b) a b))))
  (parse-letrec-bindings (subr (maxeff parses spin) (syns-a) letrec-list)
    (lambda (bs)
      (parse-typed-bindings bs "a letrec binding" "a letrec binding is `(name type expression)`")))
  ;; Bindings `(name type expression)`, a `letrec`'s or a `define-rec`'s:
  ;; each `what`, and `usage` when one is not.
  (parse-typed-bindings (subr (maxeff parses spin) (syns-a string string) letrec-list)
    (lambda (bs what usage)
      (if (null? bs)
          nil
          (let ((parts (syn-items (car bs) what)))
            (if (= (len parts) 3)
                (let* ((name (syn-symbol (car parts)))
                       (init (parse-exp (nth parts 2)))
                       (rest (parse-typed-bindings (cdr bs) what usage)))
                  (cons (product (1 name) (2 (nth parts 1)) (3 init)) rest))
                (pfail usage (car bs)))))))
  ;; `(let ((name expression) …) …)`; `()` is no bindings.
  (parse-let-bindings (subr (maxeff parses spin) (syns-a) let-list)
    (lambda (bs)
      (if (null? bs)
          nil
          (let ((parts (syn-items (car bs) "a let binding")))
            (if (= (len parts) 2)
                (let* ((name (syn-symbol (car parts))) (init (parse-exp (nth parts 1))))
                  (cons (product (1 name) (2 init)) (parse-let-bindings (cdr bs))))
                (pfail "a let binding is `(name expression)`" (car bs)))))))
  ;; `let*`: nested one-binding `let`s, each spanning its binding.
  (parse-let* (subr (maxeff parses spin) (syns-a exp) exp)
    (lambda (bs body)
      (if (null? bs)
          body
          (let ((parts (syn-items (car bs) "a let* binding")))
            (if (= (len parts) 2)
                (let* ((name (syn-symbol (car parts)))
                       (init (parse-exp (nth parts 1)))
                       (inner (parse-let* (cdr bs) body)))
                  (e-let (one-let name init) inner (syn-start (car bs)) (syn-end (car bs))))
                (pfail "a let* binding is `(name expression)`" (car bs)))))))
  ;; `(cond (test e …) … (else e …))`: nested `if`s, each spanning its clause.
  (parse-cond (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (clauses a b)
      (cond ((null? clauses) (pfail-at "a `cond` needs at least an `else` clause" a b))
            (else
             (let* ((c (car clauses)) (parts (syn-items c "a cond clause")))
               (if (null? (cdr clauses))
                   (parse-cond-else c parts)
                   (if (null? parts)
                       (pfail "a cond clause is `(test expression …)`" c)
                       (let* ((test (parse-exp (car parts)))
                              (then (parse-body (cdr parts) (syn-start c) (syn-end c)))
                              (rest (parse-cond (cdr clauses) a b)))
                         (e-if test then rest (syn-start c) (syn-end c))))))))))
  ;; A `cond`'s last clause, `c`, which must be `else`.
  (parse-cond-else (subr (maxeff parses spin) (syn syns-a) exp)
    (lambda (c parts)
      (if (symbol=? (syn-head (car parts)) 'else)
          (parse-body (cdr parts) (syn-start c) (syn-end c))
          (pfail "a `cond` must end with an `else` clause: FX has no unspecified value" c))))
  ;; `(and a b …)`: `(if a (and b …) #f)`, and `(and)` is `#t`.
  (parse-and (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (xs a b)
      (cond ((null? xs) (e-bool #t a b))
            ((null? (cdr xs)) (parse-exp (car xs)))
            (else (let* ((x (parse-exp (car xs))) (rest (parse-and (cdr xs) a b)))
                    (e-if x rest (e-bool #f a b) a b))))))
  ;; `(or a b …)`: `(if a #t (or b …))`, and `(or)` is `#f`.
  (parse-or (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (xs a b)
      (cond ((null? xs) (e-bool #f a b))
            ((null? (cdr xs)) (parse-exp (car xs)))
            (else (let* ((x (parse-exp (car xs))) (rest (parse-or (cdr xs) a b)))
                    (e-if x (e-bool #t a b) rest a b))))))
  ;; `(typecase e (shape name body) … (else name body))` on a union's members
  ;; (`docs/research/logical-types.md`, L1): `(let ((%typecase-value e)) (if
  ;; (int? %typecase-value) (let ((name %typecase-value)) body) … else))`,
  ;; each arm's test its shape's standard predicate, which narrows the value
  ;; for the arm and those after it. The `else` is required, as `case`'s is.
  (parse-typecase (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (items a b)
      (cond ((< (len items) 2) (pfail-at typecase-usage a b))
            ((null? (cdr (cdr items))) (pfail-at typecase-needs-else a b))
            ;; A variable, which nothing assigns, is tested as it is, so
            ;; that what each test narrows it to holds of it after.
            ((case-direct? (cdr items))
             (parse-typecase-arms (drop items 2) (syn-head (nth items 1)) a b))
            (else
             (let* ((e (parse-exp (nth items 1))) (tmp (fresh-name "%typecase-value" items)))
               (e-let (one-let tmp e) (parse-typecase-arms (drop items 2) tmp a b) a b))))))
  (parse-typecase-arms (subr (maxeff parses spin) (syns-a symbol int int) exp)
    (lambda (arms tmp a b)
      (if (null? (cdr arms))
          ;; `(else body)`, or `(else name body)`, `name` the value as what
          ;; the arms leave it.
          (let* ((parts (syn-items (car arms) typecase-usage))
                 (n (len parts))
                 (shaped (if (or (= n 2) (= n 3)) #u (pfail typecase-else (car arms))))
                 (name (if (= n 3)
                           (if (syn-symbol? (nth parts 1))
                               (syn-symbol (nth parts 1))
                               (pfail "a name" (nth parts 1)))
                           '||))
                 (is-else (if (and (syn-symbol? (car parts))
                                   (symbol=? (syn-symbol (car parts)) 'else))
                              #u
                              (pfail typecase-else (car arms))))
                 (body (parse-exp (nth parts (- n 1)))))
            (if (= n 3) (e-let (one-let name (e-var tmp a b)) body a b) body))
          (let* ((parts (syn-items (car arms) typecase-usage))
                 (shaped (if (= (len parts) 3) #u (pfail typecase-usage (car arms))))
                 (shape (car parts))
                 (pred (if (syn-symbol? shape) (typecase-predicate (syn-symbol shape)) '||))
                 (known (if (symbol=? pred '||) (pfail typecase-shapes shape) #u))
                 (x (if (syn-symbol? (nth parts 1))
                        (syn-symbol (nth parts 1))
                        (pfail "a name" (nth parts 1))))
                 (body (parse-exp (nth parts 2)))
                 (rest (parse-typecase-arms (cdr arms) tmp a b)))
            (e-if (call-tmp pred tmp nil a b) (e-let (one-let x (e-var tmp a b)) body a b) rest
                  a b)))))
  ;; `(case key ((datum …) e …) … (else e …))` on atoms (`TODO.md` §46):
  ;; `(let ((%case-key key)) …)` and nested `if`s, each datum compared by
  ;; its kind's equality. The data are of one kind and distinct, and the
  ;; `else` is required, as `cond`'s is.
  (parse-case (subr (maxeff parses spin) (syns-a int int) exp)
    (lambda (xs a b)
      (cond ((null? xs)
             (pfail-at "`(case key ((datum …) expression …) … (else expression …))`" a b))
            ((null? (cdr xs)) (pfail-at "a `case` needs at least an `else` clause" a b))
            (else
             (begin (case-else (case-last (cdr xs)))
                    (let* ((kx (car xs)) (ka (syn-start kx)) (kb (syn-end kx)))
                      (if (case-direct? xs)
                          ;; A variable, which nothing assigns: compared as it is.
                          (begin (case-clauses (cdr xs) nil)
                                 (parse-case-body (e-var (syn-head kx) ka kb) xs a b))
                          (let ((key (parse-exp kx)) (k (fresh-name "%case-key" xs)))
                            (case-clauses (cdr xs) nil)
                            (e-let (one-let k key) (parse-case-body (e-var k ka kb) xs a b)
                                   a b)))))))))
  ;; A chain of tests, or, for many data of a kind that pays (`case-tree-from`)
  ;; all with a sort value, two searches (`case-tree`): as the Rust parser's.
  (parse-case-body (subr (maxeff parses spin) (exp syns-a int int) exp)
    (lambda (kv xs a b)
      (let* ((clauses (cdr xs)) (k (case-clauses-kind clauses)) (n (case-data-count clauses))
             (direct (and (not (null? (case-atom-else (case-last clauses))))
                          (= n (- (len clauses) 1)))))
        (if (and (>= n (case-tree-from k direct)) (case-all-keyed? k clauses))
            (case-tree kv xs (case-entries kv k clauses 0) k a b)
            (parse-case-arms kv clauses)))))
  ;; Each datum of the clauses before the `else`: its test, sort value, clause.
  (case-entries (subr (maxeff parses spin) (exp int syns-a int) case-entries)
    (lambda (kv k clauses c)
      (if (null? (cdr clauses))
          nil
          (case-entries-of kv k (syn-items (car (syn-items (car clauses) "c")) "data") c
                           (case-entries kv k (cdr clauses) (+ c 1))))))
  (case-entries-of (subr (maxeff parses spin) (exp int syns-a int case-entries) case-entries)
    (lambda (kv k data c rest)
      (if (null? data)
          rest
          (let ((d (car data)))
            (the case-entries
              (cons (product (1 (case-test kv d)) (2 (case-sort-key k d)) (3 c))
                    (case-entries-of kv k (cdr data) c rest)))))))
  ;; The clause's index by halving the sorted data, then its body by halving
  ;; the indices (`case_tree` in the Rust parser).
  (case-tree (subr (maxeff parses spin) (exp syns-a case-entries int int int) exp)
    (lambda (kv xs es k a b)
      (let* ((sorted (case-sort es nil))
             (bodies (case-bodies (cdr xs)))
             (m (- (case-exps-length bodies) 1))
             (hash (fresh-name "%case-hash" xs))
             (index (fresh-name "%case-index" xs))
             (by (if (= k 0) kv (e-var hash a b)))
             (n (case-entries-length sorted))
             (els (case-atom-else (case-last (cdr xs))))
             (tree (if (and (not (null? els)) (= n m))
                       ;; A clause per datum, an `else` of one atom: bodies at the leaves.
                       (case-index by sorted n m bodies (case-body-at bodies m) a b)
                       (let ((found (case-index by sorted n m nil (e-unit a b) a b)))
                         (e-let (one-let index found) (case-pick (e-var index a b) bodies 0 m a b)
                                a b)))))
        (if (= k 0)
            tree
            (let ((op (if (= k 2) 'string-hash 'symbol-name-hash)))
              (e-let (one-let hash (e-app (standard-ref op a b) (list kv) a b)) tree a b))))))
  ;; Each clause's body, first to last, the `else`'s last.
  (case-bodies (subr (maxeff parses spin) (syns-a) exp-list)
    (lambda (clauses)
      (if (null? clauses)
          nil
          (let* ((c (car clauses)) (parts (syn-items c "a case clause"))
                 (body (parse-body (cdr parts) (syn-start c) (syn-end c))))
            (the exp-list (cons body (case-bodies (cdr clauses))))))))
  (parse-case-arms (subr (maxeff parses spin) (exp syns-a) exp)
    (lambda (k clauses)
      (let* ((c (car clauses)) (parts (syn-items c "a case clause"))
             (ca (syn-start c)) (cb (syn-end c)))
        (if (null? (cdr clauses))
            (parse-body (cdr parts) ca cb)
            (let* ((test (case-tests k (syn-items (car parts) "data") ca cb))
                   (then (parse-body (cdr parts) ca cb)))
              (e-if test then (parse-case-arms k (cdr clauses)) ca cb))))))
  ;; `(if d1 #t (if d2 #t … dn))`, each `di` the key compared with a datum.
  (case-tests (subr (maxeff parses spin) (exp syns-a int int) exp)
    (lambda (key data ca cb)
      (let ((t (case-test key (car data))))
        (if (null? (cdr data)) t (case-or t (case-tests key (cdr data) ca cb) ca cb)))))
  (case-test (subr (maxeff parses spin) (exp syn) exp)
    (lambda (key d)
      (let* ((da (syn-start d)) (db (syn-end d)) (k (case-kind d))
             (eq (case k ((0) '=) ((1) 'char=?) ((2) 'string=?)
                         ((3) 'symbol=?) (else 'bool=?)))
             (lit (if (= k 3) (e-sym (syn-head d) da db) (parse-exp d))))
        (e-app (standard-ref eq da db) (list key lit) da db))))
  (parse-bloblet (subr (maxeff parses spin) (symbol syns-a int int) exp)
    (lambda (op args a b)
      (let ((n (len args)))
        (cond ((and (symbol=? op 'make-bloblet) (>= n 1)) (e-bloblet op -1 (parse-exps args) a b))
              ((and (symbol=? op 'rmake-bloblet) (>= n 2)) (e-bloblet op -1 (parse-exps args) a b))
              ((and (symbol=? op 'bloblet-ref) (= n 2))
               (let* ((i (field-index (nth args 1))) (x (parse-exp (car args))))
                 (e-bloblet op i (the exp-list (cons x nil)) a b)))
              ((and (symbol=? op 'bloblet-set!) (= n 3))
               (let* ((i (field-index (nth args 1)))
                      (x (parse-exp (car args)))
                      (v (parse-exp (nth args 2))))
                 (e-bloblet op i (list x v) a b)))
              ((bloblet-untagged? op n) (e-bloblet op -1 (parse-exps args) a b))
              (else (pfail-at (str3 "`(" (symbol->string op) " …)`") a b))))))
  (parse-fields (subr (maxeff parses spin) (syns-a) let-list)
    (lambda (ps)
      (if (null? ps)
          nil
          (let ((pair (syn-items (car ps) "`(label expression)`")))
            (if (= (len pair) 2)
                (let* ((l (label (car pair))) (e (parse-exp (nth pair 1))))
                  (cons (product (1 l) (2 e)) (parse-fields (cdr ps))))
                (pfail "`(product (label expression) …)`" (car ps)))))))
  ;; The arms of a `tagcase` other than `else`.
  (parse-arms (subr (maxeff parses spin) (syns-a) arm-list)
    (lambda (cs)
      (cond ((null? cs) nil)
            ((arm-else? (car cs))
             (if (null? (cdr cs)) nil (pfail "`else` must be the last arm" (car cs))))
            (else
             (let* ((c (car cs)) (parts (syn-items c "a tagcase arm")))
               (if (< (len parts) 3)
                   (if (< (len parts) 2)
                       (pfail "a tagcase arm is `(tag name body …)`" c)
                       (pfail "a tagcase arm needs a body" c))
                   (let* ((tag (label (car parts)))
                          (bind (nth parts 1))
                          (fields (not (syn-symbol? bind)))
                          (ns (arm-names fields bind))
                          (body (parse-arm-body parts c))
                          (rest (parse-arms (cdr cs))))
                     (cons (product (1 tag) (2 fields) (3 ns) (4 body)) rest))))))))
  ;; An arm's body, `c`'s items after its first two.
  (parse-arm-body (subr (maxeff parses spin) (syns-a syn) exp)
    (lambda (parts c) (parse-body (drop parts 2) (syn-start c) (syn-end c))))
  ;; The `else` arm, as a list of none or one.
  (parse-else (subr (maxeff parses spin) (syns-a) let-list)
    (lambda (cs)
      (cond ((null? cs) nil)
            ((arm-else? (car cs))
             (let* ((c (car cs)) (parts (syn-items c "a tagcase arm")))
               (if (< (len parts) 3)
                   (pfail "a tagcase arm needs a body" c)
                   (if (syn-symbol? (nth parts 1))
                       (let* ((y (syn-symbol (nth parts 1))) (body (parse-arm-body parts c)))
                         (cons (product (1 y) (2 body)) nil))
                       (pfail "`else` binds one name" (nth parts 1))))))
            (else (parse-else (cdr cs))))))
  ;; A `module`'s items, in order.
  ;; A module's forms, its `define-datatype`s expanded.
  (parse-module-items (subr (maxeff parses spin) (syns-a) mod-items)
    (lambda (fs) (with-includes (parse-module-items-in fs (any-include? fs) #f))))
  ;; The same, each item's values in `(with %include …)` if `inc?`, each
  ;; hidden if `hid?` (`hidden-marks`).
  (parse-module-items-in (subr (maxeff parses spin) (syns-a bool bool) mod-items)
    (lambda (fs inc? hid?)
      (cond ((null? fs) nil)
            ((hide-form? (car fs))
             (append (parse-module-items-in (hide-forms (car fs)) inc? #t)
                     (parse-module-items-in (cdr fs) inc? hid?)))
            ((datatype? (car fs))
             (parse-module-items-in (append (expand-datatype (car fs)) (cdr fs)) inc? hid?))
            (else (let* ((item (parse-module-item (car fs)))
                         (item (if inc? (item-in-includes item (car fs)) item))
                         (rest (parse-module-items-in (cdr fs) inc? hid?)))
                    (if hid? (hidden-marks item (car fs) rest) (cons item rest)))))))
  ;; `(define-generative t T)`, `(define-type d T)`, `(define x e)`, `(define
  ;; x T e)` or `(define-rec (f T e) …)`.
  (parse-module-item (subr (maxeff parses spin) (syn) mod-item)
    (lambda (f)
      (let* ((parts (syn-items f "a module's definition"))
             (n (len parts))
             (head (if (null? parts) '|()| (syn-head (car parts)))))
        (cond ((and (symbol=? head 'define-generative) (= n 3))
               ;; `(define-generative (t (p k) …) T)`: a type constructor, its
               ;; head kept after its representation for the checker to read.
               (let* ((head (nth parts 1))
                      (hs (tagcase head (lst (xs d a b) xs) (else x (the syns-a nil))))
                      (params? (and (not (null? hs)) (not (null? (cdr hs)))))
                      (name (syn-symbol (if params? (car hs) head)))
                      (up (identity-at (syn-start f) (syn-end f)))
                      (down (identity-at (syn-start f) (syn-end f)))
                      (ts (if params?
                              (the syns-a (list (nth parts 2) head))
                              (one-syn (nth parts 2)))))
                 (mod-item-of 0 name ts (list up down))))
              ((and (symbol=? head 'define-type) (= n 3) (param-head? (nth parts 1)))
               (param-desc-item (syn-start f) (syn-end f) (nth parts 1) (nth parts 2)))
              ((and (symbol=? head 'define-type) (= n 3))
               (mod-item-of 1 (syn-symbol (nth parts 1)) (one-syn (nth parts 2)) nil))
              ((and (symbol=? head 'define) (= n 3))
               (let* ((name (syn-symbol (nth parts 1))) (init (parse-exp (nth parts 2))))
                 (mod-item-of 2 name (the syns-a nil) (the exp-list (cons init nil)))))
              ((and (symbol=? head 'define) (= n 4))
               (let* ((name (syn-symbol (nth parts 1))) (init (parse-exp (nth parts 3))))
                 (mod-item-of 2 name (one-syn (nth parts 2)) (the exp-list (cons init nil)))))
              ;; `(define-effect e E)`: a description, its types the effect
              ;; and a mark.
              ((and (symbol=? head 'define-effect) (= n 3))
               (let* ((mark (mk-symbol "effect" (syn-start f) (syn-end f)))
                      (ts (the syns-a (list (nth parts 2) mark))))
                 (mod-item-of 1 (syn-symbol (nth parts 1)) ts nil)))
              ;; `(define* f T e)`: a `define`, its types the type and a mark.
              ((and (symbol=? head 'define*) (= n 4))
               (let* ((name (syn-symbol (nth parts 1))) (init (parse-exp (nth parts 3)))
                      (mark (mk-symbol "*" (syn-start f) (syn-end f))))
                 (mod-item-of 2 name (the syns-a (list (nth parts 2) mark))
                              (the exp-list (cons init nil)))))
              ;; `(include m)` (`TODO.md` §69): kind 9, its form kept.
              ((and (symbol=? head 'include) (= n 2))
               (mod-item-of 9 '%include (one-syn f) (list (parse-exp (nth parts 1)))))
              ((symbol=? head 'define-rec)
               (let ((bs (parse-typed-bindings (cdr parts) "`(name type expression)`"
                                               "`(define-rec (name type expression) …)`")))
                 (product (1 3) (2 (rec-names bs)) (3 (rec-types bs)) (4 (rec-inits bs)))))
              (else (pfail module-usage f))))))
  ;; `(load-module "path")` or, `input?`, `(load-input "path")`, at `a`..`b`:
  ;; the hidden global every load of its path is (`TODO.md` §68), the
  ;; first defining it, as the file loaded (`parse-load-file`), before the
  ;; form that loads it (`shared-pending`); a `load-input`'s, its one item.
  ;; Each expression made has a place of its own, as the compilers' facts
  ;; are found by place: the use the form's, the file's module the whole
  ;; file, and a `load-input`'s `input` its keyword, `head`.
  (parse-loaded (subr (maxeff parses spin) (string bool syn int int) exp)
    (lambda (path input? head a b)
      (let ((f (loaded-next-at a)))
        (if (null? f)
            (e-module (loaded-error (str3 "cannot read `" path "`: it was not read")) a b)
            (let* ((key (string-append (if input? "input:" "") (extract (car f) 7)))
                   (name (string->symbol (string-append "%shared:" key))))
              (begin
                (if (shared-key? key (get shared-keys))
                    #u
                    (let ((x (parse-load-file (car f) path input? a b)))
                      (begin (set shared-keys (cons key (get shared-keys)))
                             (set shared-pending
                                  (cons (t-define name (the syns-a nil) x a b)
                                        (get shared-pending))))))
                (if input?
                    (e-with name (e-var 'input (syn-start head) (syn-end head)) a b)
                    (e-var name a b))))))))
  ;; File `f`, loaded at `a`..`b` as `path`: the module, its items after its
  ;; mark (`loaded-made` of it, for a file of parameters; for a
  ;; `load-input`, `input?`, its one form, the item `input`); or why it
  ;; could not be read.
  (parse-load-file (subr (maxeff parses spin) (loaded-file string bool int int) exp)
    (lambda (f path input? a b)
      (if (= (extract f 2) 0)
          (e-module (loaded-error (extract f 3)) a b)
          (let* ((base (extract f 2))
                 (forms (extract f 5))
                 ;; The whole file, where no other expression is.
                 (end (+ base (string-length (extract f 6))))
                 ;; Its parameters and items, as a form's, out of the
                 ;; prompt that catches what is wrong in them.
                 (made (lambda ()
                         (if input?
                             (t-exp (e-module (cons (loaded-mark base path nil)
                                                    (parse-module-items (input-items forms a b)))
                                              base end))
                             (let* ((ps (loaded-params forms))
                                    (items (parse-module-items (if (null? ps) forms (cdr forms))))
                                    (m (e-module (cons (loaded-mark base path ps) items) base end)))
                               (t-exp (loaded-made ps m base end))))))
                 (r (prompt parse-tag (p-ok (cons (made) nil)) (lambda (r) r))))
            (tagcase r
              (p-err (m x y)
                (if (>= x base)
                    (e-module (loaded-error (in-loaded (get loaded) base m x)) a b)
                    (pfail-at m x y)))
              (p-ok (ts) (tagcase (car ts) (t-exp (x) x) (else y (e-module nil a b))))))))))
;; A `define-rec`'s bindings, as a `letrec`'s are.
(define parse-rec-bindings (subr (maxeff parses spin) (syns-a) letrec-list)
  (lambda (bs)
    (let ((usage "a define-rec binding is `(name type lambda)`"))
      (parse-typed-bindings bs "a define-rec binding" usage))))
;; `(define name type expression)` or `(define name expression)`; for a
;; `define*` (`star?`), the type's list holds the head too.
(define parse-define (subr (maxeff parses spin) (syn bool) top)
  (lambda (s star?)
    (let* ((items (syn-items s "a definition")) (n (len items)) (a (syn-start s)) (b (syn-end s)))
      (case n ((4)
               (let* ((name (syn-symbol (nth items 1)))
                      (heads (if star? (the syns-a (cons (car items) nil)) (the syns-a nil)))
                      (ty (the syns-a (cons (nth items 2) heads))))
                 (t-define name ty (parse-exp (nth items 3)) a b)))
              ((3)
               (let ((name (syn-symbol (nth items 1))))
                 (t-define name (the syns-a nil) (parse-exp (nth items 2)) a b)))
              (else (pfail "`(define name type expression)` or `(define name expression)`" s))))))
