;;; The signature of `regcode-places.fx`, its `regcode-places-module`,
;;; as its clients use it (`TODO.md` §68): a module file of no state.

;;; ------------------------------------------------------------ signatures

;; What its clients use of it (`regcode-core.fx`, `regcode-helpers.fx`).
;; The types it names, from the files that define them.
(define regcode-types (load-module "fx26:regcode-types.fx"))
(define-type bools (select regcode-types bools))
(define compile-types (load-module "fx26:compile-types.fx"))
(define-type cenv (select compile-types cenv))
(define parser-types ((proj (load-module "fx26:parser-types.fx") @s @e @m @c @p)))
(define-type exp (select parser-types exp))
(define check-resolve-types (load-module "fx26:check-resolve-types.fx"))
(define-type exp-let-bs (select check-resolve-types exp-let-bs))
(define-type exp-letrec-bs (select check-resolve-types exp-letrec-bs))
(define-type exps (select compile-types exps))
(define-type names (select parser-types names))
(define-type patches (select compile-types patches))
(define-type rarg (select regcode-types rarg))
(define regcode-exps-types (load-module "fx26:regcode-exps-types.fx"))
(define-type rarg-patches (select regcode-exps-types rarg-patches))
(define-type rargs (select regcode-types rargs))
(define-type renv (select regcode-types renv))
(define-type rgen (select regcode-types rgen))
(define-type rloc (select regcode-types rloc))
(define-type rplaces (select regcode-exps-types rplaces))
(define-type rscope (select regcode-exps-types rscope))
(define-type syms (select compile-types syms))
(define-type regcode-places-sig
  (moduleof (val r-in-regs
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen exps int cenv bool)
                       bools))
            (val r-place-value
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k))
                       (rgen)
                       rloc))
            (val r-get
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k))
                       (rgen rloc)
                       unit))
            (val r-reverse-env
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (renv renv)
                       renv))
            (val r-members
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen rloc names int renv)
                       renv))
            (val r-local-all
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (renv cenv)
                       cenv))
            (val r-bind-all
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (renv renv)
                       renv))
            (val r-spec-free
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen rloc syms int renv cenv bools)
                       rscope))
            (val r-loop-move
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen (listof int @k) int)
                       unit))
            (val r-field-args
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (exp-let-bs)
                       rargs))
            (val r-sibling-env
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (exp-letrec-bs (listof int @k) int int exp int renv cenv)
                       rscope))
            (val r-append-arg
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rargs rarg)
                       rargs))
            (val r-free-args
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (syms renv int)
                       rarg-patches))
            (val r-free-regs
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen syms renv int)
                       patches))
            (val r-join-places
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen exp-letrec-bs bools cenv)
                       rplaces))
            (val r-letrec-te-j
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (exp-letrec-bs bools cenv)
                       cenv))
            (val r-letrec-patch
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (rgen (listof patches @k) (listof int @k))
                       unit))
            (val r-letrec-env-j
                 (subr (maxeff (alloc @k)
                               (goto @y)
                               (read @globals)
                               (read @k)
                               (read @t)
                               (write @k)
                               spin)
                       (exp-letrec-bs (listof int @k) rplaces renv)
                       renv))))
