;;; Generated by `fixpt_fx26::lower::standard_fx26_module` from the lowering's
;;; table of standard names; `FIXPT_BLESS=1 cargo test -p fixpt-fx26 --test layout`
;;; rewrites it.

;; The runtime primitive a standard operation runs as, `%fx26-identity`
;; if it is the identity, or the empty string if neither.
(define standard-primitive (subr pure (string) string)
  (lambda (n)
    (cond
