(define-effect kstate (maxeff (read @t) (write @t)))
(define-type kcell (ref int @t))
(define-type (kbox (t type)) (pairof t t finite))
(define-generative (kid (t type +)) (pairof t int finite))
(define kval int 3)
